### ISSUE TITLE
ModelContainer grouping needs to work with a single input model

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#1291]
If a single input FITS file is sent to `resample_step`, it is stuffed into a `ModelContainer` and processed by the step.  But the container attribute `group_names` does not get defined, and so it fails.
```
ERROR RUNNING STEP 'ResampleStep':
    No attribute 'group_names'
Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/datamodels/properties.py", line 210, in __getattr__
    val = self._instance[attr]
KeyError: 'group_names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/stpipe/cmdline.py", line 320, in step_from_cmdline
    step.run(*positional)
  File "/Users/jdavies/dev/jwst/jwst/stpipe/step.py", line 370, in run
    result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_step.py", line 50, in process
    blendheaders=self.blendheaders)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 69, in __init__
    self.get_drizpars()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 85, in get_drizpars
    num_groups = len(self.input_models.group_names)
  File "/Users/jdavies/dev/jwst/jwst/datamodels/properties.py", line 213, in __getattr__
    raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'group_names'
```
The attribute `group_names` must be defined always.

**Comment by nden** [comment]
@jdavies-st Is this still an issue?

**Comment by jdavies-st** [comment]
This is no longer an issue, though I'm not sure how it was resolved.  I just tested it with NIRCam and MIRI imaging data from our regression tests.  No issues.  Closing.
