### ISSUE TITLE
make_header crashed

### ISSUE THREAD

**Issue by cracraft** [spacetelescope/jwst#2279]
I decided to run make_header and see if the keyword issues I had previously reported had been fixed, and ran into an error in attempting to run it.

I am in my jwstdev environment (updated this morning), and here's what I encountered:

$ make_header MIRI image 1 example_MIRIM_level1.fits
2018-07-23 16:37:07,217 - stpipe - WARNING - /Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/photutils/background/core.py:78: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-07-23 16:37:07,217 - stpipe - WARNING - /Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/photutils/background/core.py:120: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-07-23 16:37:07,219 - stpipe - WARNING - /Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/photutils/background/background_2d.py:287: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  sigma_clip=SigmaClip(sigma=3., iters=10),

Traceback (most recent call last):
  File "/Users/cracraft/anaconda3/envs/jwstdev/bin/make_header", line 4, in <module>
    __import__('pkg_resources').run_script('jwst==0.9.8a0.dev78+g5f970856', 'make_header')
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/jwst-0.9.8a0.dev78+g5f970856-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/make_header", line 760, in <module>
    im = main(args.instrument, args.mode, args.level)
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/jwst-0.9.8a0.dev78+g5f970856-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/make_header", line 78, in main
    defaults = set_default_values(im, instrument, mode, level)
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/jwst-0.9.8a0.dev78+g5f970856-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/make_header", line 468, in set_default_values
    set_standard_defaults(im, defaults, instrument, mode, level)
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/jwst-0.9.8a0.dev78+g5f970856-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/make_header", line 581, in set_standard_defaults
    if validate_value(im, 'meta.instrument.name', instrument):
  File "/Users/cracraft/anaconda3/envs/jwstdev/lib/python3.5/site-packages/jwst-0.9.8a0.dev78+g5f970856-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/make_header", line 746, in validate_value
    util._validate_value(value, schema)
AttributeError: module 'jwst.datamodels.util' has no attribute '_validate_value'

**Comment by jdavies-st** [comment]
Looks like the `_validate_value` method was removed back in May.

https://github.com/spacetelescope/jwst/pull/2093

**Comment by stscicrawford** [comment]
@bernie-simon when you fix this, can you add a regression test for this script so we can catch this in the future?

**Comment by bernie-simon** [comment]
The fix for this bug is on github and it should be included in the next point release.
