### ISSUE TITLE
NIRSpec FSS source id handling

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2311]
# Issue
For NIRSpec Fixed-slit, conversion from exposure to source raises the following:
```
2018-07-31 15:41:18,296 - stpipe.Spec3Pipeline - INFO - Convert from exposure-based to source-based data.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':
    invalid literal for int() with base 10: 'S400A1'
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 106, in process
    output_file, source_id=int(source_id)
ValueError: invalid literal for int() with base 10: 'S400A1'

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0-py3.6-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 106, in process
    output_file, source_id=int(source_id)
ValueError: invalid literal for int() with base 10: 'S400A1'
```

# Resources
- #159 
- Example data set `/grp/jwst/ssb/eisenhamer/testing_jscott/20180731/level3_sourceid`

**Comment by stscieisenhamer** [comment]
# Implementation

- [ ] documentation
- [ ] tests
- [ ] code
- [ ] tests
- [ ] documentation
