### ISSUE TITLE
NIRSpec IFU modeling error in outlier_detection while blotting

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2312]
# Issue
`calwebb_spec3`, running on NIRSpec IFU, fails with the following.

**Special Note** According to the log, this occurred after ~11 hours of processing.

```
2018-07-25 19:49:56,594 - stpipe.Spec3Pipeline.outlier_detection - INFO - ROI size (spatial and wave) 0.300000 0.000800
2018-07-25 19:49:56,594 - stpipe.Spec3Pipeline.outlier_detection - INFO - Number of input models 24
2018-07-25 19:49:59,336 - stpipe.Spec3Pipeline.outlier_detection - INFO - Blotting back jw93135022001_02103_00001_nrs2_cal.fits
Traceback (most recent call last):
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdl
ine
    step.run(*positional)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 398, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 120, in proces
s
    result = self.outlier_detection(result)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/stpipe/step.py", line 398, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_step.py", l
ine 164, in process
    step.do_detection()
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_ifu.py", li
ne 141, in do_detection
    self.blot_median(median_model)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_ifu.py", li
ne 190, in blot_median
    blot_models = cubeblot.blot_images()
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/jwst-0.9.6-py3.5-linux-x86_64.egg/jwst/cube_build/blot_cube_build.py", line 143, in bl
ot_images
    ra_det,dec_det,wave_det = model.meta.wcs(xdet,ydet)
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/gwcs/wcs.py", line 232, in __call__
    transform = self.forward_transform
  File "/ifs/int/jwstb/pipeline/pkgs/miniconda3/envs/jwstdp-0.9.6-py35/lib/python3.5/site-packages/gwcs/wcs.py", line 159, in forward_transform
```

# Resources
- Example data set `/grp/jwst/ssb/eisenhamer/testing_jscott/20180731/level3_modeling`
- Example command: `strun calwebb_spec3.cfg jw93135-o022_20180724t222511_spec3_001_asn.json`

**Comment by nden** [comment]
Looks like a `cube_build.blot_images` bug.  [This line](https://github.com/spacetelescope/jwst/blob/master/jwst/cube_build/blot_cube_build.py#L142) will not work for nirspec IFU because the WCSs are defined per slice. It works for MRS because the MRS uses a pixel map to define the slices.
