### ISSUE TITLE
No IFU slices fall on detector NRS2

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2336]
# Issue
From SDP data jw84700,  a run of `calwebb_spec2` reports the following:
<details><summary>Error Log</summary>
<p>

```
$ strun cfgs/calwebb_spec2.cfg /ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level2/jw84700-o006_20180806t170209_spec2_003_asn.json --output_dir level2b
2018-08-08 02:13:56,219 - stpipe - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/photutils/background/core.py:71: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-08 02:13:56,220 - stpipe - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/photutils/background/core.py:114: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-08 02:13:56,224 - stpipe - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/photutils/background/background_2d.py:285: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  sigma_clip=SigmaClip(sigma=3., iters=10),

2018-08-08 02:13:56,922 - stpipe.Spec2Pipeline - INFO - Spec2Pipeline instance created.
2018-08-08 02:13:56,924 - stpipe.Spec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2018-08-08 02:13:56,926 - stpipe.Spec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2018-08-08 02:13:56,927 - stpipe.Spec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2018-08-08 02:13:56,929 - stpipe.Spec2Pipeline.msa_flagging - INFO - MSAFlagOpenStep instance created.
2018-08-08 02:13:56,930 - stpipe.Spec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2018-08-08 02:13:56,932 - stpipe.Spec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2018-08-08 02:13:56,933 - stpipe.Spec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2018-08-08 02:13:56,935 - stpipe.Spec2Pipeline.straylight - INFO - StraylightStep instance created.
2018-08-08 02:13:56,936 - stpipe.Spec2Pipeline.fringe - INFO - FringeStep instance created.
2018-08-08 02:13:56,938 - stpipe.Spec2Pipeline.pathloss - INFO - PathLossStep instance created.
2018-08-08 02:13:56,939 - stpipe.Spec2Pipeline.barshadow - INFO - BarShadowStep instance created.
2018-08-08 02:13:56,940 - stpipe.Spec2Pipeline.photom - INFO - PhotomStep instance created.
2018-08-08 02:13:56,942 - stpipe.Spec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2018-08-08 02:13:56,945 - stpipe.Spec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2018-08-08 02:13:56,947 - stpipe.Spec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
2018-08-08 02:13:56,951 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-08-08 02:13:56,951 - stpipe - INFO - OS: Linux
2018-08-08 02:13:57,053 - stpipe.Spec2Pipeline - INFO - Step Spec2Pipeline running with args ('/ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level2/jw84700-o006_20180806t170209_spec2_003_asn.json',).
2018-08-08 02:13:58,229 - stpipe.Spec2Pipeline - INFO - Prefetching reference files for dataset: 'jw84700006001_02101_00001_nrs2_rate.fits' reftypes = ['area', 'barshadow', 'camera', 'collimator', 'cubepar', 'dflat', 'disperser', 'distortion', 'drizpars', 'extract1d', 'fflat', 'filteroffset', 'flat', 'fore', 'fpa', 'fringe', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'msaoper', 'ote', 'pathloss', 'photom', 'regions', 'resol', 'sflat', 'specwcs', 'straymask', 'wavecorr', 'wavelengthrange', 'wfssbkg']
2018-08-08 02:13:58,715 - stpipe.Spec2Pipeline - INFO - Prefetch for AREA reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_area_0008.fits'.
2018-08-08 02:13:58,716 - stpipe.Spec2Pipeline - INFO - Prefetch for BARSHADOW reference file is 'N/A'.
2018-08-08 02:13:58,716 - stpipe.Spec2Pipeline - INFO - Prefetch for CAMERA reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_camera_0004.asdf'.
2018-08-08 02:13:58,717 - stpipe.Spec2Pipeline - INFO - Prefetch for COLLIMATOR reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_collimator_0004.asdf'.
2018-08-08 02:13:58,718 - stpipe.Spec2Pipeline - INFO - Prefetch for CUBEPAR reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_cubepar_0002.fits'.
2018-08-08 02:13:58,719 - stpipe.Spec2Pipeline - INFO - Prefetch for DFLAT reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_dflat_0002.fits'.
2018-08-08 02:13:58,720 - stpipe.Spec2Pipeline - INFO - Prefetch for DISPERSER reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_disperser_0037.asdf'.
2018-08-08 02:13:58,721 - stpipe.Spec2Pipeline - INFO - Prefetch for DISTORTION reference file is 'N/A'.
2018-08-08 02:13:58,721 - stpipe.Spec2Pipeline - INFO - Prefetch for DRIZPARS reference file is 'N/A'.
2018-08-08 02:13:58,721 - stpipe.Spec2Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_extract1d_0005.json'.
2018-08-08 02:13:58,722 - stpipe.Spec2Pipeline - INFO - Prefetch for FFLAT reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_fflat_0013.fits'.
2018-08-08 02:13:58,722 - stpipe.Spec2Pipeline - INFO - Prefetch for FILTEROFFSET reference file is 'N/A'.
2018-08-08 02:13:58,723 - stpipe.Spec2Pipeline - INFO - Prefetch for FLAT reference file is 'N/A'.
2018-08-08 02:13:58,723 - stpipe.Spec2Pipeline - INFO - Prefetch for FORE reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_fore_0027.asdf'.
2018-08-08 02:13:58,724 - stpipe.Spec2Pipeline - INFO - Prefetch for FPA reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_fpa_0005.asdf'.
2018-08-08 02:13:58,724 - stpipe.Spec2Pipeline - INFO - Prefetch for FRINGE reference file is 'N/A'.
2018-08-08 02:13:58,724 - stpipe.Spec2Pipeline - INFO - Prefetch for IFUFORE reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_ifufore_0003.asdf'.
2018-08-08 02:13:58,725 - stpipe.Spec2Pipeline - INFO - Prefetch for IFUPOST reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_ifupost_0004.asdf'.
2018-08-08 02:13:58,726 - stpipe.Spec2Pipeline - INFO - Prefetch for IFUSLICER reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_ifuslicer_0003.asdf'.
2018-08-08 02:13:58,727 - stpipe.Spec2Pipeline - INFO - Prefetch for MSA reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_msa_0005.asdf'.
2018-08-08 02:13:58,728 - stpipe.Spec2Pipeline - INFO - Prefetch for MSAOPER reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_msaoper_0001.json'.
2018-08-08 02:13:58,729 - stpipe.Spec2Pipeline - INFO - Prefetch for OTE reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_ote_0005.asdf'.
2018-08-08 02:13:58,729 - stpipe.Spec2Pipeline - INFO - Prefetch for PATHLOSS reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_pathloss_0003.fits'.
2018-08-08 02:13:58,730 - stpipe.Spec2Pipeline - INFO - Prefetch for PHOTOM reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_photom_0013.fits'.
2018-08-08 02:13:58,731 - stpipe.Spec2Pipeline - INFO - Prefetch for REGIONS reference file is 'N/A'.
2018-08-08 02:13:58,731 - stpipe.Spec2Pipeline - INFO - Prefetch for RESOL reference file is 'N/A'.
2018-08-08 02:13:58,731 - stpipe.Spec2Pipeline - INFO - Prefetch for SFLAT reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_sflat_0031.fits'.
2018-08-08 02:13:58,732 - stpipe.Spec2Pipeline - INFO - Prefetch for SPECWCS reference file is 'N/A'.
2018-08-08 02:13:58,732 - stpipe.Spec2Pipeline - INFO - Prefetch for STRAYMASK reference file is 'N/A'.
2018-08-08 02:13:58,732 - stpipe.Spec2Pipeline - INFO - Prefetch for WAVECORR reference file is 'N/A'.
2018-08-08 02:13:58,732 - stpipe.Spec2Pipeline - INFO - Prefetch for WAVELENGTHRANGE reference file is '/grp/crds/cache/references/jwst/jwst_nirspec_wavelengthrange_0004.asdf'.
2018-08-08 02:13:58,733 - stpipe.Spec2Pipeline - INFO - Prefetch for WFSSBKG reference file is 'N/A'.
2018-08-08 02:13:58,733 - stpipe.Spec2Pipeline - INFO - Starting calwebb_spec2 ...
2018-08-08 02:13:58,747 - stpipe.Spec2Pipeline - INFO - Processing product jw84700006001_02101_00001_nrs2
2018-08-08 02:13:58,747 - stpipe.Spec2Pipeline - INFO - Working on input /ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level2/jw84700006001_02101_00001_nrs2_rate.fits ...
2018-08-08 02:13:59,036 - stpipe.Spec2Pipeline.assign_wcs - INFO - Step assign_wcs running with args (<IFUImageModel(2048, 2048) from jw84700006001_02101_00001_nrs2_rate.fits>,).
2018-08-08 02:13:59,123 - stpipe.Spec2Pipeline.assign_wcs - CRITICAL - No IFU slices fall on detector NRS2
2018-08-08 02:13:59,123 - stpipe.Spec2Pipeline.assign_wcs - WARNING - assign_wcs: SKIPPED
2018-08-08 02:13:59,127 - stpipe.Spec2Pipeline.assign_wcs - INFO - Step assign_wcs done
2018-08-08 02:13:59,127 - stpipe.Spec2Pipeline - ERROR - Assign_wcs processing was skipped.
Aborting remaining processing for this exposure.
No output product will be created.
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 90, in process
    asn.filename
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 193, in process_exposure_product
    raise RuntimeError('Cannot determine WCS.')
RuntimeError: Cannot determine WCS.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    One or more products failed to process. Failing calibration.
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 102, in process
    'One or more products failed to process. Failing calibration.'
RuntimeError: One or more products failed to process. Failing calibration.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_spec2.py", line 102, in process
    'One or more products failed to process. Failing calibration.'
RuntimeError: One or more products failed to process. Failing calibration.
```

</p>
</details>

**Comment by nden** [comment]
There are certain gratings which don't project on NRS2 and assign_wcs is skipped.
It'd be useful to see the data (what the gratng is) but because of the message I'm pretty sure this is the case here. So the question is should we ever get exposures like this and what is the correct way to fail ?

**Comment by stscieisenhamer** [comment]
If the only criterion for "no NRS2 slices" is grating, or other purely-keyword-based criteria, then the generator would be able to determine when and when not to create an NRS2 level2 association. All that would be needed are the forbidden values.

If the criteria is more complicated than just keyword values, then some type of modification would need to be made to `calwebb_spec2`.

**Comment by jemorrison** [comment]
I think that the only NIRSPEC IFU data that is on NRS2 when the Grating is one of the high resolution ones. So these combinations:
F100LP/G140H, F290LP/G395H, F170LP/G235H

**Comment by nden** [comment]
There are several ways one can get no data projected on a detector.
There are two cases when we never get slices projected on NRS2.

- NRS IFU on NRS2 and grating ends with "M" (i.e. all mid-resolution gratings)
- NRS IFU on NRS2 and G140H + F070LP

If not one of those cases, the instrument model is run on each slit to see if it projects on the detector.
It's possible, especially with the MSA, that none of the open shutters project on the detector.

In all of those cases assign_wcs is skipped.

So, again, the question is, what should the pipeline do in this case? Perhaps it should crash because what else could be done if there's no data?

This specific failure is for `G235M`.

**Comment by stscieisenhamer** [comment]
Reviewing the last issue that dealt with this, #2151, and seeing that @nden actually provided a list of "known failures" (my bad for missing that), the case still stands that an exception is what is required, at least by ground system. Note that in resolving the aforementioned issue, through #2168, a new config option was added, `fail_on_exception`, which allows a user to decide how they want to handle the situation.

So, the state is:

1. Baseline is status quo: Throw an exception when no WCS can be determined.
2. Add to the generator the requirement that for IFU, only allow NRS2 when the following grating/filters are specified:
    - F100LP/G140H
    - F290LP/G395H
    - F170LP/G235H

Do all concerned concur?

**Comment by nden** [comment]
Is there a way to make the requirement negative, i.e. do not allow certain configurations?
If not, configurations with lamps may need to be listed, as well as F110W_G395H, F100LP_PRISM, CLEAR_PRISM.

**Comment by stscieisenhamer** [comment]
That probably makes more sense, since we have the baseline case anyways. If there is any "grayness", leave it to the pipeline to figure out. I would like to make sure that all the known situations, that can be determined by grating/filter/instrument alone are weeded out ahead of time.

So, the reverse then, is the cases we know that will not have NRS2 as listed in #2151. Note that this discussion is specific to actual science; all the calibration-type exposures are already handled in their own ways, for example see #1188.

**Comment by stscieisenhamer** [comment]
# Solution

For the grey situations, where only by running the pipeline can one know whether there is any data on NRS2, @stscieisenhamer talked with SDP and agreed to the following: Currently, if a pipeline fails, that process is considered a fail. Similarly, if some downstream process, such as archive digest, is expecting files because all previous steps succeeded, then those processes will raise failure flags.  Since the grey situations are ones where the pipeline did not fail, but also did not produce output, some way of returning this "succeed but expect no more data" state will be developed. When the workflow encounters this state, it will ensure that no other downstream processes, that would otherwise expect output, are gracefully terminated, without raising failure notices.

**Comment by stscieisenhamer** [comment]
# Implementation
- [ ] documentation
- [ ] tests
- [ ] code
    - [ ] Update association rules such that known cases, as listed in #2151, will not produce NRS2-based associations
    - [ ] When `assign_wcs` returns with the exception `CRITICAL - No IFU slices fall on detector NRS2`, return a specific flag, TBD, back to the workflow to indicate that no data is to be expected from the current association.
- [ ] tests
- [ ] documentation
