### ISSUE TITLE
gwcs_drizzle produces TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2337]
From SDP data, the following occurs when running `calwebb_spec3`:
```
strun /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/pipeline//calwebb_spec3.cfg /ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level3/jw80600-o013_20180806t154319_spec3_001_asn.json
2018-08-06 23:23:32,584 - stpipe - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/photutils/background/core.py:78: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-06 23:23:32,586 - stpipe - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/photutils/background/core.py:120: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-06 23:23:32,623 - stpipe - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/photutils/background/background_2d.py:287: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  sigma_clip=SigmaClip(sigma=3., iters=10),

2018-08-06 23:23:34,621 - stpipe.Spec3Pipeline - INFO - Spec3Pipeline instance created.
2018-08-06 23:23:34,622 - stpipe.Spec3Pipeline.mrs_imatch - INFO - MRSIMatchStep instance created.
2018-08-06 23:23:34,625 - stpipe.Spec3Pipeline.outlier_detection - INFO - OutlierDetectionStep instance created.
2018-08-06 23:23:34,628 - stpipe.Spec3Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2018-08-06 23:23:34,633 - stpipe.Spec3Pipeline.cube_build - INFO - CubeBuildStep instance created.
2018-08-06 23:23:34,639 - stpipe.Spec3Pipeline.extract_1d - INFO - Extract1dStep instance created.
2018-08-06 23:23:34,640 - stpipe - INFO - Hostname: iljwdmscdp2.stsci.edu
2018-08-06 23:23:34,641 - stpipe - INFO - OS: Linux
2018-08-06 23:23:34,774 - stpipe.Spec3Pipeline - INFO - Step Spec3Pipeline running with args ('/ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level3/jw80600-o013_20180806t154319_spec3_001_asn.json',).
2018-08-06 23:23:35,610 - stpipe.Spec3Pipeline - INFO - Prefetching reference files for dataset: 'jw80600013001_02101_00001_mirimage_cal.fits' reftypes = ['cubepar', 'drizpars', 'extract1d', 'resol']
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, 7.2.5, 7f6becb
CRDS - DEBUG -  getreferences() server: https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('cubepar', 'drizpars', 'extract1d', 'resol')
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /ifs/int/jwstc/ref/crds/cache
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  Using CACHED CRDS reference assignment rules last updated on '2018-07-31 12:00:03.504080'
CRDS - DEBUG -  Using reference file selection rules 'jwst_0477.pmap' defined by cache.
CRDS - DEBUG -  Final effective context is 'jwst_0477.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'FASTGRPAVG',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
 'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
 'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
 'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
 'META.OBSERVATION.DATE [DATE-OBS]': '2016-01-17',
 'META.OBSERVATION.TIME [TIME-OBS]': '08:56:14.234',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  READONLY CACHE skipping config update.
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_miri_drizpars_0001.fits'
CRDS - DEBUG -  Reference type 'extract1d' defined as 'jwst_miri_extract1d_0004.json'
2018-08-06 23:23:36,235 - stpipe.Spec3Pipeline - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2018-08-06 23:23:36,236 - stpipe.Spec3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2018-08-06 23:23:36,238 - stpipe.Spec3Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_extract1d_0004.json'.
2018-08-06 23:23:36,239 - stpipe.Spec3Pipeline - INFO - Prefetch for RESOL reference file is 'N/A'.
2018-08-06 23:23:36,240 - stpipe.Spec3Pipeline - INFO - Starting calwebb_spec3 ...
2018-08-06 23:23:36,811 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<ModelContainer>,).
2018-08-06 23:23:36,815 - stpipe.Spec3Pipeline.outlier_detection - WARNING - Input only contains 1 exposures.
2018-08-06 23:23:36,816 - stpipe.Spec3Pipeline.outlier_detection - WARNING - Outlier detection step will be skipped.
2018-08-06 23:23:36,816 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection done
2018-08-06 23:23:36,958 - stpipe.Spec3Pipeline.resample_spec - INFO - Step resample_spec running with args (<ModelContainer>,).
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, 7.2.5, 7f6becb
CRDS - DEBUG -  getreferences() server: https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('drizpars',)
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /ifs/int/jwstc/ref/crds/cache
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  Final effective context is 'jwst_0477.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'FASTGRPAVG',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
 'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
 'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
 'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
 'META.OBSERVATION.DATE [DATE-OBS]': '2016-01-17',
 'META.OBSERVATION.TIME [TIME-OBS]': '08:56:14.234',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_miri_drizpars_0001.fits'
2018-08-06 23:23:36,970 - stpipe.Spec3Pipeline.resample_spec - INFO - Drizpars reference file: /ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_drizpars_0001.fits
2018-08-06 23:23:37,156 - stpipe.Spec3Pipeline.resample_spec - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:642: RuntimeWarning: invalid value encountered in less
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):

2018-08-06 23:23:37,157 - stpipe.Spec3Pipeline.resample_spec - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:642: RuntimeWarning: invalid value encountered in greater_equal
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):

2018-08-06 23:23:37,158 - stpipe.Spec3Pipeline.resample_spec - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:529: RuntimeWarning: invalid value encountered in less
  if np.any(angles.value < lower) or np.any(angles.value > upper):

2018-08-06 23:23:37,158 - stpipe.Spec3Pipeline.resample_spec - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:529: RuntimeWarning: invalid value encountered in greater
  if np.any(angles.value < lower) or np.any(angles.value > upper):

2018-08-06 23:23:37,490 - stpipe.Spec3Pipeline.resample_spec - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/modeling/rotations.py:186: RuntimeWarning: invalid value encountered in less
  mask = alpha < 0

2018-08-06 23:23:37,858 - stpipe.Spec3Pipeline.resample_spec - INFO - Resampling slit (387, 43)
2018-08-06 23:23:39,535 - stpipe.Spec3Pipeline.resample_spec - INFO - Drizzling (1024, 1032) --> (387, 43)
Traceback (most recent call last):
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 132, in process
    result = self.resample_spec(result)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/resample/resample_spec_step.py", line 76, in process
    resamp.do_drizzle()
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/resample/resample_spec.py", line 318, in do_drizzle
    pscale_ratio=self.pscale_ratio)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/resample/gwcs_drizzle.py", line 206, in add_image
    fillval=self.fillval)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/resample/gwcs_drizzle.py", line 457, in dodrizzle
    fillstr=str(fillval)
TypeError: must be real number, not NoneType
```

**Comment by stscieisenhamer** [comment]
# Resources
Data can be found in
```
/grp/jwst/ssb/eisenhamer/jwst_issues/issue2337
```
