### ISSUE TITLE
model given to make_output_path

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2338]
From SDP run, running `calwebb_spec3`, the following occurs:
```
strun /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/pipeline//calwebb_spec3.cfg /ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level3/jw98010-o001_20180806t184118_spec3_001_asn.json
2018-08-07 00:28:58,896 - stpipe - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/photutils/background/core.py:78: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-07 00:28:58,898 - stpipe - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/photutils/background/core.py:120: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-07 00:28:58,900 - stpipe - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/photutils/background/background_2d.py:287: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  sigma_clip=SigmaClip(sigma=3., iters=10),

2018-08-07 00:28:59,570 - stpipe.Spec3Pipeline - INFO - Spec3Pipeline instance created.
2018-08-07 00:28:59,571 - stpipe.Spec3Pipeline.mrs_imatch - INFO - MRSIMatchStep instance created.
2018-08-07 00:28:59,573 - stpipe.Spec3Pipeline.outlier_detection - INFO - OutlierDetectionStep instance created.
2018-08-07 00:28:59,574 - stpipe.Spec3Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2018-08-07 00:28:59,576 - stpipe.Spec3Pipeline.cube_build - INFO - CubeBuildStep instance created.
2018-08-07 00:28:59,577 - stpipe.Spec3Pipeline.extract_1d - INFO - Extract1dStep instance created.
2018-08-07 00:28:59,578 - stpipe - INFO - Hostname: iljwdmscdp3.stsci.edu
2018-08-07 00:28:59,578 - stpipe - INFO - OS: Linux
2018-08-07 00:28:59,646 - stpipe.Spec3Pipeline - INFO - Step Spec3Pipeline running with args ('/ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/asn_creation/cal/level3/jw98010-o001_20180806t184118_spec3_001_asn.json',).
2018-08-07 00:29:00,062 - stpipe.Spec3Pipeline - INFO - Prefetching reference files for dataset: 'jw98010001001_02104_00001_mirimage_cal.fits' reftypes = ['cubepar', 'drizpars', 'extract1d', 'resol']
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, 7.2.5, 7f6becb
CRDS - DEBUG -  getreferences() server: https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('cubepar', 'drizpars', 'extract1d', 'resol')
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /ifs/int/jwstc/ref/crds/cache
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  Using CACHED CRDS reference assignment rules last updated on '2018-07-31 12:00:03.504080'
CRDS - DEBUG -  Using reference file selection rules 'jwst_0477.pmap' defined by cache.
CRDS - DEBUG -  Final effective context is 'jwst_0477.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'SLOW',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
 'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
 'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
 'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
 'META.OBSERVATION.DATE [DATE-OBS]': '2016-01-24',
 'META.OBSERVATION.TIME [TIME-OBS]': '05:41:56.301',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  READONLY CACHE skipping config update.
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_miri_drizpars_0001.fits'
CRDS - DEBUG -  Reference type 'extract1d' defined as 'jwst_miri_extract1d_0004.json'
2018-08-07 00:29:00,280 - stpipe.Spec3Pipeline - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2018-08-07 00:29:00,281 - stpipe.Spec3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2018-08-07 00:29:00,281 - stpipe.Spec3Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_extract1d_0004.json'.
2018-08-07 00:29:00,282 - stpipe.Spec3Pipeline - INFO - Prefetch for RESOL reference file is 'N/A'.
2018-08-07 00:29:00,528 - stpipe.Spec3Pipeline - INFO - Prefetching reference files for dataset: 'jw98010001001_02103_00001_mirimage_cal.fits' reftypes = ['cubepar', 'drizpars', 'extract1d', 'resol']
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, 7.2.5, 7f6becb
CRDS - DEBUG -  getreferences() server: https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('cubepar', 'drizpars', 'extract1d', 'resol')
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /ifs/int/jwstc/ref/crds/cache
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  Final effective context is 'jwst_0477.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'SLOW',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
 'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
 'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
 'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
 'META.OBSERVATION.DATE [DATE-OBS]': '2016-01-24',
 'META.OBSERVATION.TIME [TIME-OBS]': '05:39:09.069',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_miri_drizpars_0001.fits'
CRDS - DEBUG -  Reference type 'extract1d' defined as 'jwst_miri_extract1d_0004.json'
2018-08-07 00:29:00,533 - stpipe.Spec3Pipeline - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2018-08-07 00:29:00,533 - stpipe.Spec3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2018-08-07 00:29:00,538 - stpipe.Spec3Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_extract1d_0004.json'.
2018-08-07 00:29:00,542 - stpipe.Spec3Pipeline - INFO - Prefetch for RESOL reference file is 'N/A'.
2018-08-07 00:29:00,768 - stpipe.Spec3Pipeline - INFO - Prefetching reference files for dataset: 'jw98010001001_02101_00001_mirimage_cal.fits' reftypes = ['cubepar', 'drizpars', 'extract1d', 'resol']
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, 7.2.5, 7f6becb
CRDS - DEBUG -  getreferences() server: https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('cubepar', 'drizpars', 'extract1d', 'resol')
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /ifs/int/jwstc/ref/crds/cache
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  Final effective context is 'jwst_0477.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'SLOW',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
 'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
 'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
 'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
 'META.OBSERVATION.DATE [DATE-OBS]': '2016-01-24',
 'META.OBSERVATION.TIME [TIME-OBS]': '05:33:34.605',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_miri_drizpars_0001.fits'
CRDS - DEBUG -  Reference type 'extract1d' defined as 'jwst_miri_extract1d_0004.json'
2018-08-07 00:29:00,776 - stpipe.Spec3Pipeline - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2018-08-07 00:29:00,776 - stpipe.Spec3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2018-08-07 00:29:00,776 - stpipe.Spec3Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_extract1d_0004.json'.
2018-08-07 00:29:00,777 - stpipe.Spec3Pipeline - INFO - Prefetch for RESOL reference file is 'N/A'.
2018-08-07 00:29:01,022 - stpipe.Spec3Pipeline - INFO - Prefetching reference files for dataset: 'jw98010001001_02102_00001_mirimage_cal.fits' reftypes = ['cubepar', 'drizpars', 'extract1d', 'resol']
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, 7.2.5, 7f6becb
CRDS - DEBUG -  getreferences() server: https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('cubepar', 'drizpars', 'extract1d', 'resol')
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /ifs/int/jwstc/ref/crds/cache
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
CRDS - DEBUG -  Final effective context is 'jwst_0477.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'SLOW',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
 'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
 'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
 'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
 'META.OBSERVATION.DATE [DATE-OBS]': '2016-01-24',
 'META.OBSERVATION.TIME [TIME-OBS]': '05:36:21.837',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_miri_drizpars_0001.fits'
CRDS - DEBUG -  Reference type 'extract1d' defined as 'jwst_miri_extract1d_0004.json'
2018-08-07 00:29:01,026 - stpipe.Spec3Pipeline - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2018-08-07 00:29:01,026 - stpipe.Spec3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_drizpars_0001.fits'.
2018-08-07 00:29:01,027 - stpipe.Spec3Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/ifs/int/jwstc/ref/crds/cache/references/jwst/miri/jwst_miri_extract1d_0004.json'.
2018-08-07 00:29:01,028 - stpipe.Spec3Pipeline - INFO - Prefetch for RESOL reference file is 'N/A'.
2018-08-07 00:29:01,028 - stpipe.Spec3Pipeline - INFO - Starting calwebb_spec3 ...
2018-08-07 00:29:01,310 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<ModelContainer>,).
2018-08-07 00:29:01,313 - stpipe.Spec3Pipeline.outlier_detection - INFO - Performing outlier detection on 4 inputs
2018-08-07 00:29:01,388 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:642: RuntimeWarning: invalid value encountered in less
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):

2018-08-07 00:29:01,388 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:642: RuntimeWarning: invalid value encountered in greater_equal
  if np.any(self_angle < wrap_angle_floor) or np.any(self_angle >= wrap_angle):

2018-08-07 00:29:01,389 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:529: RuntimeWarning: invalid value encountered in less
  if np.any(angles.value < lower) or np.any(angles.value > upper):

2018-08-07 00:29:01,389 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/coordinates/angles.py:529: RuntimeWarning: invalid value encountered in greater
  if np.any(angles.value < lower) or np.any(angles.value > upper):

2018-08-07 00:29:01,566 - stpipe.Spec3Pipeline.outlier_detection - WARNING - /ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/astropy/modeling/rotations.py:186: RuntimeWarning: invalid value encountered in less
  mask = alpha < 0

2018-08-07 00:29:02,272 - stpipe.Spec3Pipeline.outlier_detection - INFO - Resampling slit (387, 43)
2018-08-07 00:29:03,267 - stpipe.Spec3Pipeline.outlier_detection - INFO - Drizzling (1024, 1032) --> (387, 43)
2018-08-07 00:29:03,340 - stpipe.Spec3Pipeline.outlier_detection - INFO - Resampling slit (387, 43)
2018-08-07 00:29:04,294 - stpipe.Spec3Pipeline.outlier_detection - INFO - Drizzling (1024, 1032) --> (387, 43)
2018-08-07 00:29:04,359 - stpipe.Spec3Pipeline.outlier_detection - INFO - Resampling slit (387, 43)
2018-08-07 00:29:05,269 - stpipe.Spec3Pipeline.outlier_detection - INFO - Drizzling (1024, 1032) --> (387, 43)
2018-08-07 00:29:05,339 - stpipe.Spec3Pipeline.outlier_detection - INFO - Resampling slit (387, 43)
2018-08-07 00:29:06,384 - stpipe.Spec3Pipeline.outlier_detection - INFO - Drizzling (1024, 1032) --> (387, 43)
Traceback (most recent call last):
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_spec3.py", line 120, in process
    result = self.outlier_detection(result)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_step.py", line 166, in process
    step.do_detection()
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/outlier_detection/outlier_detection_spec.py", line 78, in do_detection
    model, suffix=self.resample_suffix
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/site-packages/jwst-0.10.0-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 855, in _make_output_path
    basename, basepath_ext = splitext(split(basepath)[1])
  File "/ifs/int/jwstc/pipeline/pkgs/miniconda3/envs/jwstdp-0.10.0-py36/lib/python3.6/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not DrizProductModel
```

**Comment by stscieisenhamer** [comment]
# Implementation
- [x] documentation
- [ ] tests
    - setup new regression.
- [ ] code
- [ ] tests
- [ ] documentation
