### ISSUE TITLE
memory error: refpix attempting to allocate 1.3 terabytes

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2339]
# Issue,
In SDP, while processing a `detector1` NIRCam NRC_IMAGE exposure, a memory error is hit (log below). However, the error occurs at
```
model_copy.data = np.zeros(full_shape, dtype=input_model.data.dtype)
```
Running this statement with the actual values, on a Mac, gives:
```
In [3]: arr = np.zeros((128, 640, 2048, 2048), dtype=np.dtype('float32'))

In [5]: arr.size
Out[5]: 343597383680

In [12]: sys.getsizeof(arr)
Out[12]: 1374389534864
```
Basically 1.3TB is being allocated. MAC OS seems ok with this, but RedHat is not.

Full log:
```
$ strun cfgs/calwebb_detector1.cfg /ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/fits/jw10009001001_02102_00001_nrca3_uncal.fits --output_dir level2a --debug
2018-08-08 14:04:51,650 - stpipe - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/photutils/background/core.py:71: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-08 14:04:51,651 - stpipe - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/photutils/background/core.py:114: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-08-08 14:04:51,653 - stpipe - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/photutils/background/background_2d.py:285: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  sigma_clip=SigmaClip(sigma=3., iters=10),

2018-08-08 14:04:51,817 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2018-08-08 14:04:51,818 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2018-08-08 14:04:51,819 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2018-08-08 14:04:51,820 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2018-08-08 14:04:51,821 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2018-08-08 14:04:51,822 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2018-08-08 14:04:51,823 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2018-08-08 14:04:51,824 - stpipe.Detector1Pipeline.rscd - INFO - RSCD_Step instance created.
2018-08-08 14:04:51,825 - stpipe.Detector1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2018-08-08 14:04:51,826 - stpipe.Detector1Pipeline.lastframe - INFO - LastFrameStep instance created.
2018-08-08 14:04:51,827 - stpipe.Detector1Pipeline.linearity - INFO - LinearityStep instance created.
2018-08-08 14:04:51,828 - stpipe.Detector1Pipeline.dark_current - INFO - DarkCurrentStep instance created.
2018-08-08 14:04:51,829 - stpipe.Detector1Pipeline.persistence - INFO - PersistenceStep instance created.
2018-08-08 14:04:51,830 - stpipe.Detector1Pipeline.jump - INFO - JumpStep instance created.
2018-08-08 14:04:51,831 - stpipe.Detector1Pipeline.ramp_fit - INFO - RampFitStep instance created.
2018-08-08 14:04:51,832 - stpipe.Detector1Pipeline.gain_scale - INFO - GainScaleStep instance created.
2018-08-08 14:04:51,833 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-08-08 14:04:51,833 - stpipe - INFO - OS: Linux
2018-08-08 14:04:51,867 - stpipe.Detector1Pipeline - INFO - Step Detector1Pipeline running with args ('/ifs/int/jwstc/store/doggett/tests/WholeWorks/cstring/JWSTDP-2018_2-180802/2018-08-06-153204/sdp/fits/jw10009001001_02102_00001_nrca3_uncal.fits',).
2018-08-08 14:04:52,082 - stpipe.Detector1Pipeline - INFO - Prefetching reference files for dataset: 'jw10009001001_02102_00001_nrca3_uncal.fits' reftypes = ['dark', 'gain', 'linearity', 'mask', 'persat', 'readnoise', 'refpix', 'rscd', 'saturation', 'superbias', 'trapdensity', 'trappars']
2018-08-08 14:04:52,283 - stpipe.Detector1Pipeline - INFO - Prefetch for DARK reference file is '/grp/crds/cache/references/jwst/jwst_nircam_dark_0074.fits'.
2018-08-08 14:04:52,283 - stpipe.Detector1Pipeline - INFO - Prefetch for GAIN reference file is '/grp/crds/cache/references/jwst/jwst_nircam_gain_0048.fits'.
2018-08-08 14:04:52,284 - stpipe.Detector1Pipeline - INFO - Prefetch for LINEARITY reference file is '/grp/crds/cache/references/jwst/jwst_nircam_linearity_0053.fits'.
2018-08-08 14:04:52,284 - stpipe.Detector1Pipeline - INFO - Prefetch for MASK reference file is '/grp/crds/cache/references/jwst/jwst_nircam_mask_0030.fits'.
2018-08-08 14:04:52,285 - stpipe.Detector1Pipeline - INFO - Prefetch for PERSAT reference file is '/grp/crds/cache/references/jwst/jwst_nircam_persat_0020.fits'.
2018-08-08 14:04:52,285 - stpipe.Detector1Pipeline - INFO - Prefetch for READNOISE reference file is '/grp/crds/cache/references/jwst/jwst_nircam_readnoise_0026.fits'.
2018-08-08 14:04:52,285 - stpipe.Detector1Pipeline - INFO - Prefetch for REFPIX reference file is 'N/A'.
2018-08-08 14:04:52,286 - stpipe.Detector1Pipeline - INFO - Prefetch for RSCD reference file is 'N/A'.
2018-08-08 14:04:52,286 - stpipe.Detector1Pipeline - INFO - Prefetch for SATURATION reference file is '/grp/crds/cache/references/jwst/jwst_nircam_saturation_0067.fits'.
2018-08-08 14:04:52,286 - stpipe.Detector1Pipeline - INFO - Prefetch for SUPERBIAS reference file is '/grp/crds/cache/references/jwst/jwst_nircam_superbias_0027.fits'.
2018-08-08 14:04:52,286 - stpipe.Detector1Pipeline - INFO - Prefetch for TRAPDENSITY reference file is '/grp/crds/cache/references/jwst/jwst_nircam_trapdensity_0008.fits'.
2018-08-08 14:04:52,287 - stpipe.Detector1Pipeline - INFO - Prefetch for TRAPPARS reference file is '/grp/crds/cache/references/jwst/jwst_nircam_trappars_0008.fits'.
2018-08-08 14:04:52,288 - stpipe.Detector1Pipeline - INFO - Starting calwebb_detector1 ...
2018-08-08 14:04:52,485 - stpipe.Detector1Pipeline.group_scale - INFO - Step group_scale running with args (<RampModel(128, 640, 8, 8) from jw10009001001_02102_00001_nrca3_uncal.fits>,).
2018-08-08 14:04:52,503 - stpipe.Detector1Pipeline.group_scale - INFO - NFRAMES and FRMDIVSR are equal; correction not needed
2018-08-08 14:04:52,503 - stpipe.Detector1Pipeline.group_scale - INFO - Step will be skipped
2018-08-08 14:04:52,503 - stpipe.Detector1Pipeline.group_scale - INFO - Step group_scale done
2018-08-08 14:04:52,533 - stpipe.Detector1Pipeline.dq_init - INFO - Step dq_init running with args (<RampModel(128, 640, 8, 8) from jw10009001001_02102_00001_nrca3_uncal.fits>,).
2018-08-08 14:04:52,554 - stpipe.Detector1Pipeline.dq_init - INFO - Using MASK reference file /grp/crds/cache/references/jwst/jwst_nircam_mask_0030.fits
2018-08-08 14:04:52,765 - stpipe.Detector1Pipeline.dq_init - WARNING - Keyword NOISY does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:52,909 - stpipe.Detector1Pipeline.dq_init - WARNING - Keyword WEIRD does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:52,957 - stpipe.Detector1Pipeline.dq_init - INFO - Extracting mask subarray to match science data
2018-08-08 14:04:52,967 - stpipe.Detector1Pipeline.dq_init - INFO - Step dq_init done
2018-08-08 14:04:53,009 - stpipe.Detector1Pipeline.saturation - INFO - Step saturation running with args (<RampModel(128, 640, 8, 8) from jw10009001001_02102_00001_nrca3_uncal.fits>,).
2018-08-08 14:04:53,029 - stpipe.Detector1Pipeline.saturation - INFO - Using SATURATION reference file /grp/crds/cache/references/jwst/jwst_nircam_saturation_0067.fits
2018-08-08 14:04:53,155 - stpipe.Detector1Pipeline.saturation - WARNING - Keyword NO_SATURATION does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:53,155 - stpipe.Detector1Pipeline.saturation - WARNING - Keyword FEW_SAMPLES does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:53,155 - stpipe.Detector1Pipeline.saturation - WARNING - Keyword AD_SATURATION does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:53,155 - stpipe.Detector1Pipeline.saturation - WARNING - Keyword WEIRD_PIXEL does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:53,155 - stpipe.Detector1Pipeline.saturation - WARNING - Keyword DEAD_PIXEL does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:53,195 - stpipe.Detector1Pipeline.saturation - INFO - Extracting reference file subarray to match science data
2018-08-08 14:04:54,238 - stpipe.Detector1Pipeline.saturation - INFO - Step saturation done
2018-08-08 14:04:54,282 - stpipe.Detector1Pipeline.ipc - INFO - Step ipc running with args (<RampModel(128, 640, 8, 8) from jw10009001001_02102_00001_nrca3_uncal.fits>,).
2018-08-08 14:04:54,282 - stpipe.Detector1Pipeline.ipc - INFO - Step skipped.
2018-08-08 14:04:54,282 - stpipe.Detector1Pipeline.ipc - INFO - Step ipc done
2018-08-08 14:04:54,311 - stpipe.Detector1Pipeline.superbias - INFO - Step superbias running with args (<RampModel(128, 640, 8, 8) from jw10009001001_02102_00001_nrca3_uncal.fits>,).
2018-08-08 14:04:54,337 - stpipe.Detector1Pipeline.superbias - INFO - Using SUPERBIAS reference file /grp/crds/cache/references/jwst/jwst_nircam_superbias_0027.fits
2018-08-08 14:04:54,530 - stpipe.Detector1Pipeline.superbias - WARNING - Keyword NOISY does not correspond to an existing DQ mnemonic, so will be ignored
2018-08-08 14:04:54,594 - stpipe.Detector1Pipeline.superbias - INFO - Step superbias done
2018-08-08 14:04:54,638 - stpipe.Detector1Pipeline.refpix - INFO - Step refpix running with args (<RampModel(128, 640, 8, 8) from jw10009001001_02102_00001_nrca3_uncal.fits>,).
2018-08-08 14:04:54,654 - stpipe.Detector1Pipeline.refpix - INFO - use_side_ref_pixels = True
2018-08-08 14:04:54,655 - stpipe.Detector1Pipeline.refpix - INFO - odd_even_columns = True
2018-08-08 14:04:54,655 - stpipe.Detector1Pipeline.refpix - INFO - side_smoothing_length = 11
2018-08-08 14:04:54,655 - stpipe.Detector1Pipeline.refpix - INFO - side_gain = 1.000000
2018-08-08 14:04:54,655 - stpipe.Detector1Pipeline.refpix - INFO - odd_even_rows = True
----------------------------------------------------------------------
ERROR RUNNING STEP 'Detector1Pipeline':

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_detector1.py", line 107, in process
    input = self.refpix(input)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/refpix/refpix_step.py", line 69, in process
    self.odd_even_rows)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/refpix/reference_pixels.py", line 1648, in correct_model
    odd_even_rows)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/refpix/reference_pixels.py", line 1481, in create_dataset
    model_copy.data = np.zeros(full_shape, dtype=input_model.data.dtype)
MemoryError

----------------------------------------------------------------------
> /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.10.1a0.dev33+gbbc6708d-py3.6-linux-x86_64.egg/jwst/refpix/reference_pixels.py(1481)create_dataset()
-> model_copy.data = np.zeros(full_shape, dtype=input_model.data.dtype)
(Pdb) p full_shape, input_model.data.dtype
((128, 640, 2048, 2048), dtype('float32'))
```

**Comment by stscirij** [comment]
Warren's work on fixing memory issues in the refpix step fixes this problem - I haven't tested his pull request (#2315) yet but I'm pretty sure it will make this problem go away.  And this dataset is a perfect example of why my original method was running into problems occasionally... :)

**Comment by stscieisenhamer** [comment]
# Resources
Data can be found in
```
/grp/jwst/ssb/eisenhamer/jwst_issues/issue2339
```

**Comment by stscicrawford** [comment]
Closing with merging #2315
