### ISSUE TITLE
NIRcam no flat reference

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2470]
# Issue
From EMTB DGA#3, for NIRCam with `exptype == "nrc_image"`, the following occurs from `calwebb_image2`:

<details><summary>Show log</summary>
<p>

```
$ strun cfgs/calwebb_image2.cfg jw00609001001_02101_00001_nrca1_rate.fits
2018-09-06 14:01:43,817 - stpipe.Image2Pipeline - INFO - Image2Pipeline instance created.
2018-09-06 14:01:43,819 - stpipe.Image2Pipeline.photom - INFO - PhotomStep instance created.
2018-09-06 14:01:43,820 - stpipe.Image2Pipeline.resample - INFO - ResampleStep instance created.
2018-09-06 14:01:43,822 - stpipe.Image2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2018-09-06 14:01:43,823 - stpipe.Image2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2018-09-06 14:01:43,824 - stpipe.Image2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2018-09-06 14:01:43,824 - stpipe - INFO - Hostname: inanna2.stsci.edu
2018-09-06 14:01:43,824 - stpipe - INFO - OS: Darwin
2018-09-06 14:01:43,858 - stpipe.Image2Pipeline - INFO - Step Image2Pipeline running with args ('jw00609001001_02101_00001_nrca1_rate.fits',).
2018-09-06 14:01:43,992 - stpipe.Image2Pipeline - WARNING - /Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/asdf/asdf.py:181: UserWarning: File was created with extension 'asdf.extension.BuiltinExtension' from package asdf-2.1.0.dev1436, but older version asdf-2.1.0.dev1406 is installed
  warnings.warn(fmt_msg)

2018-09-06 14:01:44,099 - stpipe.Image2Pipeline - INFO - Prefetching reference files for dataset: 'jw00609001001_02101_00001_nrca1_rate.fits' reftypes = ['area', 'camera', 'collimator', 'dflat', 'disperser', 'distortion', 'drizpars', 'fflat', 'filteroffset', 'flat', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'photom', 'regions', 'sflat', 'specwcs', 'wavelengthrange', 'wfssbkg']
CRDS - ERROR -  Error determining best reference for 'flat'  =   No match found.
2018-09-06 14:01:44,435 - stpipe.Image2Pipeline - ERROR -  Error determining best reference for 'flat'  =   No match found.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
    Error determining best reference for 'flat'  =   No match found.
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/crds/core/heavy_client.py", line 132, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/crds/client/api.py", line 758, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/crds/client/api.py", line 796, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/step.py", line 370, in run
    self._precache_references(args[0])
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/crds/core/heavy_client.py", line 132, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/crds/client/api.py", line 758, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/crds/client/api.py", line 796, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/EGG-INFO/scripts/strun", line 14, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/step.py", line 370, in run
    self._precache_references(args[0])
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/Users/eisenham/anaconda3/envs/jwst_0.9.6/lib/python3.5/site-packages/jwst-0.9.6-py3.5-macosx-10.6-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.
```

</p>
</summary>

**Comment by stscieisenhamer** [comment]
# Resources
- Data can be found in `/grp/jwst/ssb/eisenhamer/jwst_issues/issue2470`

**Comment by jaytmiller** [comment]
Running like this shows that the FLAT is for NRCA1, F070W, CLEAR.

Fishing around on the CRDS website, an odd thing about NRCA1 coverage is that unlike the other detectors,  there is no NRCA1,N/A,N/A fallback reference to handle missing F070W coverage.

So this is likely either (a) an invalid parameter set or (b) missing reference file(s).

```
$ export CRDS_VERBOSITY=50
$ strun cfgs/calwebb_image2.cfg jw00609001001_02101_00001_nrca1_rate.fits
2018-09-07 09:45:32,476 - stpipe - WARNING - /Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/photutils/background/core.py:71: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-09-07 09:45:32,476 - stpipe - WARNING - /Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/photutils/background/core.py:114: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  def __init__(self, sigma_clip=SigmaClip(sigma=3., iters=5)):

2018-09-07 09:45:32,477 - stpipe - WARNING - /Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/photutils/background/background_2d.py:285: AstropyDeprecationWarning: "iters" was deprecated in version 3.1 and will be removed in a future version. Use argument "maxiters" instead.
  sigma_clip=SigmaClip(sigma=3., iters=10),

2018-09-07 09:45:32,556 - stpipe.Image2Pipeline - INFO - Image2Pipeline instance created.
2018-09-07 09:45:32,557 - stpipe.Image2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2018-09-07 09:45:32,558 - stpipe.Image2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2018-09-07 09:45:32,558 - stpipe.Image2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2018-09-07 09:45:32,559 - stpipe.Image2Pipeline.photom - INFO - PhotomStep instance created.
2018-09-07 09:45:32,560 - stpipe.Image2Pipeline.resample - INFO - ResampleStep instance created.
2018-09-07 09:45:32,560 - stpipe - INFO - Hostname: rocket.home.stsci.edu
2018-09-07 09:45:32,560 - stpipe - INFO - OS: Darwin
2018-09-07 09:45:32,593 - stpipe.Image2Pipeline - INFO - Step Image2Pipeline running with args ('jw00609001001_02101_00001_nrca1_rate.fits',).
2018-09-07 09:45:32,840 - stpipe.Image2Pipeline - INFO - Prefetching reference files for dataset: 'jw00609001001_02101_00001_nrca1_rate.fits' reftypes = ['area', 'camera', 'collimator', 'dflat', 'disperser', 'distortion', 'drizpars', 'fflat', 'filteroffset', 'flat', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'photom', 'regions', 'sflat', 'specwcs', 'wavelengthrange', 'wfssbkg']
CRDS - DEBUG -  Acquiring lock CrdsMultiprocessingLock('crds.cache')
CRDS - DEBUG -  Lock acquired CrdsMultiprocessingLock('crds.cache')
CRDS - DEBUG -  ========================================================================================================================
CRDS - DEBUG -  getreferences() CRDS version:  7.2.6, add-cube-building-checks, e7b0193
CRDS - DEBUG -  getreferences() server: https://jwst-crds.stsci.edu
CRDS - DEBUG -  getreferences() observatory: jwst
CRDS - DEBUG -  getreferences() reftypes: ('area', 'camera', 'collimator', 'dflat', 'disperser', 'distortion', 'drizpars', 'fflat', 'filteroffset', 'flat', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'photom', 'regions', 'sflat', 'specwcs', 'wavelengthrange', 'wfssbkg')
CRDS - DEBUG -  getreferences() context: None
CRDS - DEBUG -  getreferences() ignore_cache: False
CRDS - DEBUG -  CRDS_PATH = /Users/jmiller/crds_cache_ops
CRDS - DEBUG -  CRDS_SERVER_URL = https://jwst-crds.stsci.edu
CRDS - DEBUG -  CRDS JSON RPC get_server_info () -->
CRDS - DEBUG -  RPC OK 
CRDS - DEBUG -  Connected to server at 'https://jwst-crds.stsci.edu'
CRDS - DEBUG -  Using reference file selection rules 'jwst_0482.pmap' defined by server.
CRDS - DEBUG -  Final effective context is 'jwst_0482.pmap'
CRDS - DEBUG -  Computing best references locally.
CRDS - DEBUG -  Bestrefs header:
 {'META.EXPOSURE.READPATT [READPATT]': 'RAPID',
 'META.EXPOSURE.TYPE [EXP_TYPE]': 'NRC_IMAGE',
 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'SHORT',
 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NRCA1',
 'META.INSTRUMENT.FILTER [FILTER]': 'F070W',
 'META.INSTRUMENT.MODULE [MODULE]': 'A',
 'META.INSTRUMENT.NAME [INSTRUME]': 'NIRCAM',
 'META.INSTRUMENT.PUPIL [PUPIL]': 'CLEAR',
 'META.OBSERVATION.DATE [DATE-OBS]': '2018-08-08',
 'META.OBSERVATION.TIME [TIME-OBS]': '09:48:38.433',
 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
 'REFTYPE': 'UNDEFINED'}
CRDS - DEBUG -  Connected to server and computing locally, updating CRDS cache config and operational context.
CRDS - DEBUG -  CACHE updating: '/Users/jmiller/crds_cache_ops/config/jwst/server_config'
CRDS - DEBUG -  CACHE updating: '/Users/jmiller/crds_cache_ops/config/jwst/bad_files.txt'
CRDS - DEBUG -  Reference type 'area' defined as 'jwst_nircam_area_0017.fits'
CRDS - DEBUG -  Reference type 'distortion' defined as 'jwst_nircam_distortion_0061.asdf'
CRDS - DEBUG -  Reference type 'drizpars' defined as 'jwst_nircam_drizpars_0001.fits'
CRDS - ERROR -  Error determining best reference for 'flat'  =   No match found.
2018-09-07 09:45:33,257 - stpipe.Image2Pipeline - ERROR -  Error determining best reference for 'flat'  =   No match found.
CRDS - DEBUG -  Reference type 'photom' defined as 'jwst_nircam_photom_0048.fits'
CRDS - DEBUG -  Releasing lock CrdsMultiprocessingLock('crds.cache')
CRDS - DEBUG -  Lock released CrdsMultiprocessingLock('crds.cache')
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
    Error determining best reference for 'flat'  =   No match found.
Traceback (most recent call last):
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/crds/core/heavy_client.py", line 132, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/crds/client/api.py", line 779, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/crds/client/api.py", line 819, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 372, in run
    self._precache_references(args[0])
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/crds/core/heavy_client.py", line 132, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/crds/client/api.py", line 779, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/crds/client/api.py", line 819, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 372, in run
    self._precache_references(args[0])
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/Users/jmiller/anaconda3/envs/dev/lib/python3.6/site-packages/jwst-0.10.1a0.dev231-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

```

**Comment by hbushouse** [comment]
This doesn't seem like a CAL issue to me, but rather CRDS (either missing rmap coverage or missing ref file coverage). Should it be transferred to a CRDS ticket?

**Comment by jaytmiller** [comment]
I think the "coordination" agreement was that this sort of stuff needs to be filtered through Howard or mswam@stsci.edu.    An important question is whether or not anything is wrong with the parameters shown in the debug output above.  A more important question is whether or not this is still a real issue in testing.

**Comment by hbushouse** [comment]
Someone from the NIRCam team would need to answer the question of whether the combination of parameters used in the exposure (Detector+Filter+Pupil) is allowed.

**Comment by nden** [comment]
The above file runs successfully through `calwebb_image2`, so this was fixed along the way. Closing.
