### ISSUE TITLE
Open functions that allow association files should also allow association objects

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2670]
# Issue
Methods/functions that open association files should also take association objects. When passed an object, the return should just be that object.

**Comment by bernie-simon** [comment]
There are several issues here. First, if you pass an association object to datamodels.open, it must return a datamodel, specifically a ModelContainer, just as it would if you passed it an association filename. Second, the association object returned from load_asn is a plain dict. The only way to know it's an association is to check for certain fields, like asn_id and asn_pool. Third, the filenames contained in association objects do not contain a directory. When passed a filename, the directory is copied from the directory of the filename. If there is no filename, there is nothing I can do except assume the files are in the current directory.

**Comment by ccossou** [comment]
About your third comment, I think relative path works in the association. I remember trying and I think it worked. 

For me the solution is for load_asn or another function to return a ModelContainer directly. This way, when the pipeline does 
`datamodels.open(input)` it will simply return input, since it's already the correct format. 

One of the problems for me is that association formats are not a datamodel structure, and are currently not compatible with ModelContainer.

**Comment by jdavies-st** [comment]
Associations should not have absolute or relative paths.  Only the filename.  If there are paths, then it is not portable.  I.e. it it tied to the directory structure of where it is generated.

Running:
```
container = datamodels.open('my_association_asn.json')
```
will return a `ModelContainer` with all the files in the association as iterables.

**Comment by jdavies-st** [comment]
I think it would be fairly straightforward to modify `ModelContainer` to open the datamodels within an association object rather than an association file as it currently does, if that is what is desired.

Though it seems the main issue is an easy way to write out a generated association.  This should be a one-liner `.write()` or `save()` method.

Finally, if one just wants to load a bunch of files in a `ModelContainer`, one can do:
```
from jwst import datamodels
from glob import glob
```
container = datamodels.ModelContainer(glob('*.fits'))
```
This will only give you the list of files though, and won't populate information about the association pool or product name, things which are only available from the association JSON file.

**Comment by ccossou** [comment]
About relative path, since files can be in sub-folders because they are different exposures, this did not shock me, but you might be right. 

The issue here is not really about writing an association. It's about using an association object as input for the pipeline. Right now I MUST create a .json file to read the association from it.

For instance I'd like to do:
`from jwst.associations.asn_from_list import asn_from_list
from jwst.associations.lib.rules_level3_base import DMS_Level3_Base
data = [("LRS-SLIT_demo_data_pipeline/det_image_2_MIRIMAGE_P750Lexp1_rate.fits", "science"), ("LRS-SLIT_demo_data_pipeline/det_image_1_MIRIMAGE_P750Lexp1_rate.fits", "background")]
asn3 = asn_from_list(data, rule=DMS_Level3_Base, product_name="toto", with_exptype=True)

### Some additional line to convert asn3 into a ModelContainer? ###

Image3Pipeline.call(asn_3)`

**Comment by stscieisenhamer** [comment]
About the relative paths: We should open a separate issue for that aspect. However, he current usage, within JWST calibrations, is to not allow relative paths. The path to the "data set" is determined by the path to the initial input file. This is necessary because there are other files defined within the headers, the MSA configuration file, that must also be found.

About the opening: JWST associations have a validating schema. `load_asn`, or a higher-level utility open, would check a dict-like object against the schema to decide if its an association or not. If the input is a string, the check would be either if the string is a file or a serialization. Any other utilities would just call said function, either `load_asn` or the higher level one. This would allow `Step`'s and `Pipeline`'s  to take either a file, serialization, or an association-like object.  This would be one approach.

**Comment by ccossou** [comment]
I just tried to run level3 with what @jdavies-st adviced. 

It works up to the point when Imager3Pipeline tries to write the output, then I get:
`2018-11-28 14:33:16,389 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection done
2018-11-28 14:33:16,389 - stpipe.Image3Pipeline - INFO - Writing Level 2c images with updated DQ arrays...
Traceback (most recent call last):
  File "/media/shared/miricle/jwst/jwst/datamodels/properties.py", line 232, in __getattr__
    val = self._instance[attr]
KeyError: 'asn_table'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/shared/miricle/pipeline/tmp/run_pipeline.py", line 147, in <module>
    main()
  File "/media/shared/miricle/pipeline/tmp/run_pipeline.py", line 144, in main
    run_ima_level3(lvl2s)
  File "/media/shared/miricle/pipeline/tmp/run_pipeline.py", line 103, in run_ima_level3
    Image3Pipeline.call(input, save_results=True)
  File "/media/shared/miricle/jwst/jwst/stpipe/step.py", line 531, in call
    return instance.run(*args)
  File "/media/shared/miricle/jwst/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/media/shared/miricle/jwst/jwst/pipeline/calwebb_image3.py", line 81, in process
    asn_id = input_models.meta.asn_table.asn_id
  File "/media/shared/miricle/jwst/jwst/datamodels/properties.py", line 235, in __getattr__
    raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'asn_table'`

Funny thing is, all the other steps works well, but it crash once Pipeline3 has completed, but before it writes the files. 

My code is:
`input_lvl2_pattern = "test/det_images/*_cal.fits"
lvl2s = datamodels.ModelContainer(glob.glob(input_lvl2_pattern))
Image3Pipeline.call(lvl2s, save_results=True)`

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2161](https://jira.stsci.edu/browse/JP-2161)._

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2161](https://jira.stsci.edu/browse/JP-2161)._

**Comment by stscijirahub** [comment]
_Comment by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) on [JIRA](https://jira.stsci.edu/browse/JP-2161?focusedCommentId=1034016#comment-1034016):_

<https://jira.stsci.edu/browse/JP-3960> looks pretty closely related.

**Comment by stscijirahub** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-2161?focusedCommentId=1034335#comment-1034335):_

JP-439 also looks related, maybe duplicate?

**Comment by pllim** [comment]
xref #2666

**Comment by stscijirahub** [comment]
_Comment by [Pey-Lian Lim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lim) on [JIRA](https://jira.stsci.edu/browse/JP-2161?focusedCommentId=1034491#comment-1034491):_

#10678

**Comment by braingram** [comment]
To check I'm following, is the plan to support users passing:
https://github.com/spacetelescope/jwst/blob/d626e4cad00ab7d8eef44910b7219d7acfa96450/jwst/associations/association.py#L27
to steps/containers/open functions?

Can we instead just make that class private? It seems like an implementation detail as part of the association construction code and not something we want users interacting with directly.

FWIW roman recently made `Association` private: https://github.com/spacetelescope/romancal/pull/2355 so it would be good to confine changes related to this work to jwst (since there are no plans for a public `Association` class for roman).

**Comment by jdavies-st** [comment]
It's not clear there's a need to have an association object useable by users.  The basic interface for users is:

1. I have some JWST data files, and I need to build an association for them so that I can get level 2 or level 3 products.  This use case is for when the MAST-provided associations are not complete (i.e. data spans more than one visit of a prop id, or multiple prop ids.)  But all the logic for figuring out like filters with like filters/pupils, etc is not always clear, and usually people hack it together.  The association rules exist in the Association class, but this is likely too heavy for the simple task of having a pile of _cal.fits files in a directory and figuring out the 4 associations that need to be made in order to get like filters or spectral modes together.
2. I have an association and I need to figure out what dataset this is associated with.  Since the default file naming does not include filter/pupil or spectral grating/pass info in the association filename itself, often only the output product of the association gives a clue to what the anodynely-named association JSON actually produces.  So one needs to parse.  And for spectra, this is a bit of a pain, as there are level 2 and level 3, and for MSA, lots of them.

Beyond that @braingram I agree, not much use for this functionality needing to use the Association class.

But the two use cases above are very common, and cumbersome in the current framework.

**Comment by pllim** [comment]
High level pipeline steps for level 2 and 3 should take Association object now after merge of https://github.com/spacetelescope/jwst/pull/10716 . If I missed anything, please open new follow-up issue(s). Thanks!

**Comment by stscijirahub** [comment]
_Comment by [Pey-Lian Lim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lim) on [JIRA](https://jira.stsci.edu/browse/JP-2161?focusedCommentId=1042631#comment-1042631):_

Addressed in #10716
