### ISSUE TITLE
Bad subarray corners

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2743]
From WFR2-OTB-20181004 processing run doggett/tests/wfr2/cstring/JWSTDP-2018_2-181017, running `calwebb_detector1` on NIS_EXTCAL results in the following:

<details><summary>Show log...</summary>
<p>

```
$ strun cfgs/calwebb_detector1.cfg jw00778006001_02101_00001_nis_uncal.fits
2018-10-22 15:26:46,811 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2018-10-22 15:26:46,812 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2018-10-22 15:26:46,813 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2018-10-22 15:26:46,814 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2018-10-22 15:26:46,815 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2018-10-22 15:26:46,816 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2018-10-22 15:26:46,817 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2018-10-22 15:26:46,818 - stpipe.Detector1Pipeline.rscd - INFO - RSCD_Step instance created.
2018-10-22 15:26:46,819 - stpipe.Detector1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2018-10-22 15:26:46,819 - stpipe.Detector1Pipeline.lastframe - INFO - LastFrameStep instance created.
2018-10-22 15:26:46,820 - stpipe.Detector1Pipeline.linearity - INFO - LinearityStep instance created.
2018-10-22 15:26:46,822 - stpipe.Detector1Pipeline.dark_current - INFO - DarkCurrentStep instance created.
2018-10-22 15:26:46,823 - stpipe.Detector1Pipeline.persistence - INFO - PersistenceStep instance created.
2018-10-22 15:26:46,824 - stpipe.Detector1Pipeline.jump - INFO - JumpStep instance created.
2018-10-22 15:26:46,825 - stpipe.Detector1Pipeline.ramp_fit - INFO - RampFitStep instance created.
2018-10-22 15:26:46,826 - stpipe.Detector1Pipeline.gain_scale - INFO - GainScaleStep instance created.
2018-10-22 15:26:46,826 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-10-22 15:26:46,826 - stpipe - INFO - OS: Linux
2018-10-22 15:26:46,859 - stpipe.Detector1Pipeline - INFO - Step Detector1Pipeline running with args ('jw00778006001_02101_00001_nis_uncal.fits',).
2018-10-22 15:26:47,682 - stpipe.Detector1Pipeline - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/util.py:167: NoTypeWarning: model_type not found. Opening jw00778006001_02101_00001_nis_uncal.fits as a RampModel
  warnings.warn(errmsg, NoTypeWarning)

2018-10-22 15:26:47,683 - stpipe.Detector1Pipeline - INFO - Prefetching reference files for dataset: 'jw00778006001_02101_00001_nis_uncal.fits' reftypes = ['dark', 'gain', 'linearity', 'mask', 'persat', 'readnoise', 'refpix', 'rscd', 'saturation', 'superbias', 'trapdensity', 'trappars']
2018-10-22 15:26:47,962 - stpipe.Detector1Pipeline - INFO - Prefetch for DARK reference file is '/grp/crds/cache/references/jwst/jwst_niriss_dark_0111.fits'.
2018-10-22 15:26:47,964 - stpipe.Detector1Pipeline - INFO - Prefetch for GAIN reference file is '/grp/crds/cache/references/jwst/jwst_niriss_gain_0005.fits'.
2018-10-22 15:26:47,969 - stpipe.Detector1Pipeline - INFO - Prefetch for LINEARITY reference file is '/grp/crds/cache/references/jwst/jwst_niriss_linearity_0011.fits'.
2018-10-22 15:26:47,972 - stpipe.Detector1Pipeline - INFO - Prefetch for MASK reference file is '/grp/crds/cache/references/jwst/jwst_niriss_mask_0010.fits'.
2018-10-22 15:26:47,976 - stpipe.Detector1Pipeline - INFO - Prefetch for PERSAT reference file is '/grp/crds/cache/references/jwst/jwst_niriss_persat_0003.fits'.
2018-10-22 15:26:47,978 - stpipe.Detector1Pipeline - INFO - Prefetch for READNOISE reference file is '/grp/crds/cache/references/jwst/jwst_niriss_readnoise_0004.fits'.
2018-10-22 15:26:47,981 - stpipe.Detector1Pipeline - INFO - Prefetch for REFPIX reference file is 'N/A'.
2018-10-22 15:26:47,981 - stpipe.Detector1Pipeline - INFO - Prefetch for RSCD reference file is 'N/A'.
2018-10-22 15:26:47,981 - stpipe.Detector1Pipeline - INFO - Prefetch for SATURATION reference file is '/grp/crds/cache/references/jwst/jwst_niriss_saturation_0010.fits'.
2018-10-22 15:26:47,983 - stpipe.Detector1Pipeline - INFO - Prefetch for SUPERBIAS reference file is '/grp/crds/cache/references/jwst/jwst_niriss_superbias_0111.fits'.
2018-10-22 15:26:47,985 - stpipe.Detector1Pipeline - INFO - Prefetch for TRAPDENSITY reference file is '/grp/crds/cache/references/jwst/jwst_niriss_trapdensity_0002.fits'.
2018-10-22 15:26:47,989 - stpipe.Detector1Pipeline - INFO - Prefetch for TRAPPARS reference file is '/grp/crds/cache/references/jwst/jwst_niriss_trappars_0002.fits'.
2018-10-22 15:26:47,997 - stpipe.Detector1Pipeline - INFO - Starting calwebb_detector1 ...
2018-10-22 15:26:48,530 - stpipe.Detector1Pipeline.group_scale - INFO - Step group_scale running with args (<RampModel(3, 20, 96, 2048) from jw00778006001_02101_00001_nis_uncal.fits>,).
2018-10-22 15:26:48,546 - stpipe.Detector1Pipeline.group_scale - INFO - NFRAMES and FRMDIVSR are equal; correction not needed
2018-10-22 15:26:48,546 - stpipe.Detector1Pipeline.group_scale - INFO - Step will be skipped
2018-10-22 15:26:48,547 - stpipe.Detector1Pipeline.group_scale - INFO - Step group_scale done
2018-10-22 15:26:48,576 - stpipe.Detector1Pipeline.dq_init - INFO - Step dq_init running with args (<RampModel(3, 20, 96, 2048) from jw00778006001_02101_00001_nis_uncal.fits>,).
2018-10-22 15:26:48,597 - stpipe.Detector1Pipeline.dq_init - INFO - Using MASK reference file /grp/crds/cache/references/jwst/jwst_niriss_mask_0010.fits
2018-10-22 15:26:48,882 - stpipe.Detector1Pipeline.dq_init - WARNING - Keyword CDP_WARM does not correspond to an existing DQ mnemonic, so will be ignored
2018-10-22 15:26:48,882 - stpipe.Detector1Pipeline.dq_init - WARNING - Keyword CDP_NOISY does not correspond to an existing DQ mnemonic, so will be ignored
2018-10-22 15:26:49,170 - stpipe.Detector1Pipeline.dq_init - ERROR - Science file subarray corners are invalid
----------------------------------------------------------------------
ERROR RUNNING STEP 'Detector1Pipeline':
    Bad subarray corners
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_detector1.py", line 99, in process
    input = self.dq_init(input)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/dq_init/dq_init_step.py", line 79, in process
    result = dq_initialization.correct_model(input_model, mask_model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/dq_init/dq_initialization.py", line 34, in correct_model
    output_model = do_dqinit(input_model, mask_model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/dq_init/dq_initialization.py", line 63, in do_dqinit
    if reffile_utils.ref_matches_sci(output_model, mask_model):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/lib/reffile_utils.py", line 168, in ref_matches_sci
    raise ValueError("Bad subarray corners")
ValueError: Bad subarray corners

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_detector1.py", line 99, in process
    input = self.dq_init(input)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/dq_init/dq_init_step.py", line 79, in process
    result = dq_initialization.correct_model(input_model, mask_model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/dq_init/dq_initialization.py", line 34, in correct_model
    output_model = do_dqinit(input_model, mask_model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/dq_init/dq_initialization.py", line 63, in do_dqinit
    if reffile_utils.ref_matches_sci(output_model, mask_model):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/lib/reffile_utils.py", line 168, in ref_matches_sci
    raise ValueError("Bad subarray corners")
ValueError: Bad subarray corners
```

</p>
</details>

**Comment by stscieisenhamer** [comment]
# Resources

Data is located in `/grp/jwst/ssb/eisenhamer/jwst_issues/issue2743`.

**Comment by philhodge** [comment]
jw00778006001_02101_00001_nis_uncal.fits has:

SUBARRAY= 'SUBSTRIP96'         / Subarray used
SUBSTRT1=                 -126 / Starting pixel in axis 1 direction
SUBSTRT2=                 1953 / Starting pixel in axis 2 direction
SUBSIZE1=                 2048 / Number of pixels in axis 1 direction
SUBSIZE2=                   96 / Number of pixels in axis 2 direction

**Comment by hbushouse** [comment]
This is a problem with SDP population of SUBSTRT1/2 keyword values. Nothing for CAL to fix. Closing.
