### ISSUE TITLE
Error determining best reference for 'dark'

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2748]
# Issue

For whole works run JWSTDP-2018_2-181017/2018-10-20-015602 by rspencer, running `calwebb_detector1` on NRS_FIXEDSLIT, gives the following:

<details><summary>Show log...</summary>
<p>

```
$ strun cfgs/calwebb_detector1.cfg jw84600002001_02101_00001_nrs2_uncal.fits
2018-10-22 21:21:27,804 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2018-10-22 21:21:27,805 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2018-10-22 21:21:27,806 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2018-10-22 21:21:27,807 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2018-10-22 21:21:27,808 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2018-10-22 21:21:27,809 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2018-10-22 21:21:27,810 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2018-10-22 21:21:27,811 - stpipe.Detector1Pipeline.rscd - INFO - RSCD_Step instance created.
2018-10-22 21:21:27,812 - stpipe.Detector1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2018-10-22 21:21:27,812 - stpipe.Detector1Pipeline.lastframe - INFO - LastFrameStep instance created.
2018-10-22 21:21:27,813 - stpipe.Detector1Pipeline.linearity - INFO - LinearityStep instance created.
2018-10-22 21:21:27,815 - stpipe.Detector1Pipeline.dark_current - INFO - DarkCurrentStep instance created.
2018-10-22 21:21:27,816 - stpipe.Detector1Pipeline.persistence - INFO - PersistenceStep instance created.
2018-10-22 21:21:27,817 - stpipe.Detector1Pipeline.jump - INFO - JumpStep instance created.
2018-10-22 21:21:27,818 - stpipe.Detector1Pipeline.ramp_fit - INFO - RampFitStep instance created.
2018-10-22 21:21:27,819 - stpipe.Detector1Pipeline.gain_scale - INFO - GainScaleStep instance created.
2018-10-22 21:21:27,821 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-10-22 21:21:27,821 - stpipe - INFO - OS: Linux
2018-10-22 21:21:27,873 - stpipe.Detector1Pipeline - INFO - Step Detector1Pipeline running with args ('jw84600002001_02101_00001_nrs2_uncal.fits',).
2018-10-22 21:21:28,369 - stpipe.Detector1Pipeline - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/util.py:167: NoTypeWarning: model_type not found. Opening jw84600002001_02101_00001_nrs2_uncal.fits as a RampModel
  warnings.warn(errmsg, NoTypeWarning)

2018-10-22 21:21:28,370 - stpipe.Detector1Pipeline - INFO - Prefetching reference files for dataset: 'jw84600002001_02101_00001_nrs2_uncal.fits' reftypes = ['dark', 'gain', 'linearity', 'mask', 'persat', 'readnoise', 'refpix', 'rscd', 'saturation', 'superbias', 'trapdensity', 'trappars']
CRDS - ERROR -  Error determining best reference for 'dark'  =    parameter='META.SUBARRAY.YSTART [SUBSTRT2]' value='899.0' is not in ['1.0', '1005.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1056.0', '1072.0', '1083.0', '513.0', '897.0', '903.0', '905.0', '918.0', '945.0', '946.0', '957.0', '963.0', '965.0', '967.0', '975.0', '978.0', '980.0', '981.0']
2018-10-22 21:21:28,859 - stpipe.Detector1Pipeline - ERROR -  Error determining best reference for 'dark'  =    parameter='META.SUBARRAY.YSTART [SUBSTRT2]' value='899.0' is not in ['1.0', '1005.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1056.0', '1072.0', '1083.0', '513.0', '897.0', '903.0', '905.0', '918.0', '945.0', '946.0', '957.0', '963.0', '965.0', '967.0', '975.0', '978.0', '980.0', '981.0']
CRDS - ERROR -  Error determining best reference for 'superbias'  =    parameter='META.SUBARRAY.YSTART [SUBSTRT2]' value='899.0' is not in ['1.0', '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0', '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0', '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0', '967.0', '975.0', '978.0', '980.0', '981.0']
2018-10-22 21:21:28,859 - stpipe.Detector1Pipeline - ERROR -  Error determining best reference for 'superbias'  =    parameter='META.SUBARRAY.YSTART [SUBSTRT2]' value='899.0' is not in ['1.0', '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0', '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0', '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0', '967.0', '975.0', '978.0', '980.0', '981.0']
----------------------------------------------------------------------
ERROR RUNNING STEP 'Detector1Pipeline':
    Error determining best reference for 'superbias'  =
    parameter='META.SUBARRAY.YSTART' value='899.0' is not in ['1.0',
    '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0',
    '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0',
    '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0',
    '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0',
    '967.0', '975.0', '978.0', '980.0', '981.0']
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/core/heavy_client.py", line 127, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 774, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 814, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'superbias'  =    parameter='META.SUBARRAY.YSTART' value='899.0' is not in ['1.0', '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0', '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0', '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0', '967.0', '975.0', '978.0', '980.0', '981.0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 372, in run
    self._precache_references(args[0])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'superbias'  =    parameter='META.SUBARRAY.YSTART' value='899.0' is not in ['1.0', '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0', '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0', '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0', '967.0', '975.0', '978.0', '980.0', '981.0']

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/core/heavy_client.py", line 127, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 774, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 814, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'superbias'  =    parameter='META.SUBARRAY.YSTART' value='899.0' is not in ['1.0', '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0', '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0', '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0', '967.0', '975.0', '978.0', '980.0', '981.0']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 372, in run
    self._precache_references(args[0])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'superbias'  =    parameter='META.SUBARRAY.YSTART' value='899.0' is not in ['1.0', '1005.0', '1006.0', '1018.0', '1020.0', '1021.0', '1041.0', '1051.0', '1054.0', '1055.0', '1056.0', '1068.0', '1072.0', '1083.0', '513.0', '895.0', '897.0', '903.0', '905.0', '918.0', '930.0', '945.0', '946.0', '957.0', '963.0', '965.0', '966.0', '967.0', '975.0', '978.0', '980.0', '981.0']
```

</p>
</details>

**Comment by hbushouse** [comment]
This appears to be the previously known case of NIRSpec subarray exposures having SUBSTRT1/2 values that are just slightly off from the available CRDS reference files, due to poor EngDB data.
This is not an issue for Cal, but rather SDP (or CRDS). Closing.
