### ISSUE TITLE
Error determining best reference for 'flat'

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2749]
# Issue

For whole works run JWSTDP-2018_2-181017/2018-10-20-015602 by rspencer, running `calwebb_image2` on NRC_IMAGE gives the following:

<details><summary>Show log...</summary>
<p>

```
$ strun cfgs/calwebb_image2.cfg jw00322-o002_20181020t031906_image2_009_asn.json
2018-10-22 21:28:08,636 - stpipe.Image2Pipeline - INFO - Image2Pipeline instance created.
2018-10-22 21:28:08,637 - stpipe.Image2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2018-10-22 21:28:08,638 - stpipe.Image2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2018-10-22 21:28:08,639 - stpipe.Image2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2018-10-22 21:28:08,640 - stpipe.Image2Pipeline.photom - INFO - PhotomStep instance created.
2018-10-22 21:28:08,641 - stpipe.Image2Pipeline.resample - INFO - ResampleStep instance created.
2018-10-22 21:28:08,641 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-10-22 21:28:08,641 - stpipe - INFO - OS: Linux
2018-10-22 21:28:08,674 - stpipe.Image2Pipeline - INFO - Step Image2Pipeline running with args ('jw00322-o002_20181020t031906_image2_009_asn.json',).
2018-10-22 21:28:09,956 - stpipe.Image2Pipeline - INFO - Prefetching reference files for dataset: 'jw00322002008_02101_00001_nrca1_rate.fits' reftypes = ['area', 'camera', 'collimator', 'dflat', 'disperser', 'distortion', 'drizpars', 'fflat', 'filteroffset', 'flat', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'photom', 'regions', 'sflat', 'specwcs', 'wavelengthrange', 'wfssbkg']
CRDS - ERROR -  Error determining best reference for 'flat'  =   No match found.
2018-10-22 21:28:10,447 - stpipe.Image2Pipeline - ERROR -  Error determining best reference for 'flat'  =   No match found.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
    Error determining best reference for 'flat'  =   No match found.
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/core/heavy_client.py", line 127, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 774, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 814, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 372, in run
    self._precache_references(args[0])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 188, in _precache_references_opened
    self._precache_references_opened(contained_model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 101, in _get_refpaths
    bestrefs = crds.getreferences(data_dict, reftypes=reference_file_types, observatory="jwst")
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/core/heavy_client.py", line 127, in getreferences
    final_context, bestrefs, ignore_cache=ignore_cache)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 774, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/crds/client/api.py", line 814, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 372, in run
    self._precache_references(args[0])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 168, in _precache_references
    self._precache_references_opened(model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 188, in _precache_references_opened
    self._precache_references_opened(contained_model)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 191, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/pipeline.py", line 211, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 71, in get_multiple_reference_paths
    refpaths = _get_refpaths(data_dict, tuple(reference_file_types))
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/crds_client.py", line 107, in _get_refpaths
    raise crds.CrdsLookupError(str(exc))
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'flat'  =   No match found.
```

</p>
</details>

**Comment by stscieisenhamer** [comment]
# Resources

Data can be found in `grp/jwst/ssb/eisenhamer/jwst_issues/issue2749`.

**Comment by hbushouse** [comment]
This exposure uses:
EXP_TYPE = 'NRC_IMAGE'
READPATT = 'RAPID'
DETECTOR = 'NRCA1'
FILTER = 'F070W'
PUPIL = 'CLEAR'

Looking at NIRCam FLATs in CRDS I see that there's no coverage for the F070W filter, for any detector. So this is a CRDS issue, not CAL.

**Comment by hbushouse** [comment]
This is being tracked for CRDS in https://jira.stsci.edu/browse/CRDS-220.  Closing for CAL.
