### ISSUE TITLE
Array has wrong number of dimensions

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2750]
# Issue

For whole works run JWSTDP-2018_2-181017/2018-10-20-015602 by rspencer, running `calwebb_coron3` with NRC_CORON gives the following:

<details><summary>Show log...</summary>
<p>

```
$ strun cfgs/calwebb_coron3.cfg jw10005-c1000_20181020t033546_coron3_001_asn.json
2018-10-22 21:59:15,425 - stpipe.Coron3Pipeline - INFO - Coron3Pipeline instance created.
2018-10-22 21:59:15,426 - stpipe.Coron3Pipeline.stack_refs - INFO - StackRefsStep instance created.
2018-10-22 21:59:15,427 - stpipe.Coron3Pipeline.align_refs - INFO - AlignRefsStep instance created.
2018-10-22 21:59:15,428 - stpipe.Coron3Pipeline.klip - INFO - KlipStep instance created.
2018-10-22 21:59:15,430 - stpipe.Coron3Pipeline.outlier_detection - INFO - OutlierDetectionStep instance created.
2018-10-22 21:59:15,431 - stpipe.Coron3Pipeline.resample - INFO - ResampleStep instance created.
2018-10-22 21:59:15,433 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-10-22 21:59:15,433 - stpipe - INFO - OS: Linux
2018-10-22 21:59:15,498 - stpipe.Coron3Pipeline - INFO - Step Coron3Pipeline running with args ('jw10005-c1000_20181020t033546_coron3_001_asn.json',).
2018-10-22 21:59:16,611 - stpipe.Coron3Pipeline - INFO - Prefetching reference files for dataset: 'jw10005001001_02102_00001_nrca2_cal.fits' reftypes = ['drizpars', 'psfmask']
2018-10-22 21:59:17,170 - stpipe.Coron3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/grp/crds/cache/references/jwst/jwst_nircam_drizpars_0001.fits'.
2018-10-22 21:59:17,177 - stpipe.Coron3Pipeline - INFO - Prefetch for PSFMASK reference file is '/grp/crds/cache/references/jwst/jwst_nircam_psfmask_0049.fits'.
2018-10-22 21:59:17,616 - stpipe.Coron3Pipeline - INFO - Prefetching reference files for dataset: 'jw10005007001_02102_00001_nrca2_cal.fits' reftypes = ['drizpars', 'psfmask']
2018-10-22 21:59:17,620 - stpipe.Coron3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/grp/crds/cache/references/jwst/jwst_nircam_drizpars_0001.fits'.
2018-10-22 21:59:17,621 - stpipe.Coron3Pipeline - INFO - Prefetch for PSFMASK reference file is '/grp/crds/cache/references/jwst/jwst_nircam_psfmask_0049.fits'.
2018-10-22 21:59:18,132 - stpipe.Coron3Pipeline - INFO - Prefetching reference files for dataset: 'jw10005004001_02102_00001_nrca2_cal.fits' reftypes = ['drizpars', 'psfmask']
2018-10-22 21:59:18,136 - stpipe.Coron3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/grp/crds/cache/references/jwst/jwst_nircam_drizpars_0001.fits'.
2018-10-22 21:59:18,137 - stpipe.Coron3Pipeline - INFO - Prefetch for PSFMASK reference file is '/grp/crds/cache/references/jwst/jwst_nircam_psfmask_0049.fits'.
2018-10-22 21:59:18,140 - stpipe.Coron3Pipeline - INFO - Starting calwebb_coron3 ...
----------------------------------------------------------------------
ERROR RUNNING STEP 'Coron3Pipeline':
    Array has wrong number of dimensions.  Expected 3, got 2
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_coron3.py", line 79, in process
    psf_input = datamodels.CubeModel(psf_files[i])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/cube.py", line 50, in __init__
    super(CubeModel, self).__init__(init=init, **kwargs)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/model_base.py", line 162, in __init__
    self._extensions, self._ctx)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 541, in from_fits
    ff.tree, context)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 488, in _load_from_schema
    mschema.walk_schema(schema, callback)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/schema.py", line 211, in walk_schema
    recurse(schema, [], None, ctx)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/schema.py", line 201, in recurse
    recurse(val, path + [key], combiner, ctx)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/schema.py", line 188, in recurse
    if callback(schema, path, combiner, ctx, recurse):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 466, in callback
    hdulist, schema, ctx.get('hdu_index'), known_datas)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 428, in _fits_array_loader
    return from_fits_hdu(hdu, schema)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 560, in from_fits_hdu
    data = properties._cast(data, schema)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/properties.py", line 38, in _cast
    schema['ndim'], len(val.shape)))
ValueError: Array has wrong number of dimensions.  Expected 3, got 2

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_coron3.py", line 79, in process
    psf_input = datamodels.CubeModel(psf_files[i])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/cube.py", line 50, in __init__
    super(CubeModel, self).__init__(init=init, **kwargs)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/model_base.py", line 162, in __init__
    self._extensions, self._ctx)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 541, in from_fits
    ff.tree, context)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 488, in _load_from_schema
    mschema.walk_schema(schema, callback)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/schema.py", line 211, in walk_schema
    recurse(schema, [], None, ctx)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/schema.py", line 201, in recurse
    recurse(val, path + [key], combiner, ctx)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/schema.py", line 188, in recurse
    if callback(schema, path, combiner, ctx, recurse):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 466, in callback
    hdulist, schema, ctx.get('hdu_index'), known_datas)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 428, in _fits_array_loader
    return from_fits_hdu(hdu, schema)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/fits_support.py", line 560, in from_fits_hdu
    data = properties._cast(data, schema)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/datamodels/properties.py", line 38, in _cast
    schema['ndim'], len(val.shape)))
ValueError: Array has wrong number of dimensions.  Expected 3, got 2
```

</p>
</details>

**Comment by stscieisenhamer** [comment]
# Resources

Data is located in `/grp/jwst/ssb/eisenhamer/jwst_issues/issue2750`.

**Comment by stscieisenhamer** [comment]
# Implementation
Fix associations so all coronographic work happens in integration space.

- [ ] documentation
- [ ] tests
- [ ] code
- [ ] tests
- [ ] documentation
- [ ] changelog

**Comment by stscieisenhamer** [comment]
@hbushouse 
After fixing the associations, I ran that jw10005 set through 2b and 3 processing for confirmation. All seemed to work. If you wish to confirm, see 
```
/grp/jwst/ssb/eisenhamer/jwst_issues/issue2750/analysis
```

**Comment by stscieisenhamer** [comment]
# Questions
NRC_CORON is to be handled at the integration level. Is this also true for the MIRI coronagraphs?

**Comment by hbushouse** [comment]
Yes, all coronagraphic modes for NIRCam and MIRI.
