### ISSUE TITLE
No module named 'mpl_toolkits.basemap'

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2764]
# Issue

For whole works run JWSTDP-2018_2-181017/2018-10-20-015602 by rspencer, running `calwebb_image3` on NIS_IMAGE gives the following:

<details><summary>Show log...</summary>
<p>

```
$ strun cfgs/calwebb_image3.cfg jw87600-o006_20181020t023522_image3_001_asn.json
2018-10-24 15:16:35,187 - stpipe.Image3Pipeline - INFO - Image3Pipeline instance created.
2018-10-24 15:16:35,189 - stpipe.Image3Pipeline.tweakreg - INFO - TweakRegStep instance created.
2018-10-24 15:16:35,190 - stpipe.Image3Pipeline.skymatch - INFO - SkyMatchStep instance created.
2018-10-24 15:16:35,193 - stpipe.Image3Pipeline.outlier_detection - INFO - OutlierDetectionStep instance created.
2018-10-24 15:16:35,194 - stpipe.Image3Pipeline.resample - INFO - ResampleStep instance created.
2018-10-24 15:16:35,195 - stpipe.Image3Pipeline.source_catalog - INFO - SourceCatalogStep instance created.
2018-10-24 15:16:35,195 - stpipe - INFO - Hostname: iljwdmscdp1.stsci.edu
2018-10-24 15:16:35,195 - stpipe - INFO - OS: Linux
2018-10-24 15:16:35,228 - stpipe.Image3Pipeline - INFO - Step Image3Pipeline running with args ('jw87600-o006_20181020t023522_image3_001_asn.json',).
2018-10-24 15:16:36,096 - stpipe.Image3Pipeline - INFO - Prefetching reference files for dataset: 'jw87600006001_02101_00001_nis_cal.fits' reftypes = ['drizpars']
2018-10-24 15:16:36,366 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/grp/crds/cache/references/jwst/jwst_niriss_drizpars_0002.fits'.
2018-10-24 15:16:36,895 - stpipe.Image3Pipeline - INFO - Prefetching reference files for dataset: 'jw87600006001_02103_00001_nis_cal.fits' reftypes = ['drizpars']
2018-10-24 15:16:36,898 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/grp/crds/cache/references/jwst/jwst_niriss_drizpars_0002.fits'.
2018-10-24 15:16:37,398 - stpipe.Image3Pipeline - INFO - Prefetching reference files for dataset: 'jw87600006001_02102_00001_nis_cal.fits' reftypes = ['drizpars']
2018-10-24 15:16:37,402 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/grp/crds/cache/references/jwst/jwst_niriss_drizpars_0002.fits'.
2018-10-24 15:16:37,403 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2018-10-24 15:16:38,566 - stpipe.Image3Pipeline - INFO - Aligning input images...
2018-10-24 15:16:38,608 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg running with args (<ModelContainer>,).
2018-10-24 15:16:38,699 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 1 sources in jw87600006001_02101_00001_nis_cal.fits.
2018-10-24 15:16:38,910 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 7 sources in jw87600006001_02103_00001_nis_cal.fits.
2018-10-24 15:16:39,022 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 2 sources in jw87600006001_02102_00001_nis_cal.fits.
ERROR (qd_real::acos): Argument out of domain.
2018-10-24 15:16:39,365 - stpipe.Image3Pipeline.tweakreg - WARNING - /ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/great_circle_arc.py:320: RuntimeWarning: invalid value encountered in angle
  angle = math_util.angle(A, B, C)

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 391, in _sanity_check
    assert len(node._edges) >= 2
AssertionError
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    No module named 'mpl_toolkits.basemap'
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 391, in _sanity_check
    assert len(node._edges) >= 2
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_image3.py", line 70, in process
    input_models = self.tweakreg(input_models)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/tweakreg/tweakreg_step.py", line 115, in process
    wgroup = WCSGroupCatalog(wcsimlist, name=wcsimlist[0].name)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/tweakreg/wcsimage.py", line 756, in __init__
    self.update_bounding_polygon()
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/tweakreg/wcsimage.py", line 827, in update_bounding_polygon
    self._polygon = SphericalPolygon.multi_union(polygons)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/polygon.py", line 1161, in multi_union
    return g.union()
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 481, in union
    self._sanity_check("union - find all intersections")
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 398, in _sanity_check
    self._dump_graph(title=title)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 404, in _dump_graph
    from mpl_toolkits.basemap import Basemap
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 391, in _sanity_check
    assert len(node._edges) >= 2
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/pipeline/calwebb_image3.py", line 70, in process
    input_models = self.tweakreg(input_models)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/tweakreg/tweakreg_step.py", line 115, in process
    wgroup = WCSGroupCatalog(wcsimlist, name=wcsimlist[0].name)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/tweakreg/wcsimage.py", line 756, in __init__
    self.update_bounding_polygon()
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev67+gf56c3fd4-py3.6-linux-x86_64.egg/jwst/tweakreg/wcsimage.py", line 827, in update_bounding_polygon
    self._polygon = SphericalPolygon.multi_union(polygons)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/polygon.py", line 1161, in multi_union
    return g.union()
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 481, in union
    self._sanity_check("union - find all intersections")
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 398, in _sanity_check
    self._dump_graph(title=title)
  File "/ifs/int/jwstc/info/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/spherical_geometry/graph.py", line 404, in _dump_graph
    from mpl_toolkits.basemap import Basemap
ModuleNotFoundError: No module named 'mpl_toolkits.basemap'
```

</p>
</details>

**Comment by stscieisenhamer** [comment]
# Resources

Data can be found in `/grp/jwst/ssb/eisenhamer/jwst_issues/issue2764`.

**Comment by mcara** [comment]
This actually seems to be in the field of expertise of @bernie-simon as the underlying issue is a problem in the `spherical_geometry` package.

**Comment by bernie-simon** [comment]
There's debugging code in the spherical geometry package that uses this library and can (will) be deleted. The library is only imported when there's an error in the graph structure used to support intersections and unions. The problem that needs to be addressed is the error in the graph structure, a node with three edges. I need to see a test case and understand the operation being performed to solve that problem.

**Comment by stscieisenhamer** [comment]
The error case is given in original issue details. In short, under condadev, do the following:

```
(condadev) $ cd /grp/jwst/ssb/eisenhamer/jwst_issues/issue2764
(condadev) $ strun cfgs/calwebb_image3.cfg jw87600-o006_20181020t023522_image3_001_asn.json
```

**Comment by stscicrawford** [comment]
The PR https://github.com/spacetelescope/spherical_geometry/pull/149 fixes this.

@rendinam will a new version of spherical_geometry have to be released or is the build using the development version?

**Comment by mcara** [comment]
@stscicrawford Probably with https://github.com/spacetelescope/jwst/pull/2797 `stsci_sphere` will not crash anyway.

**Comment by stscicrawford** [comment]
Closing issue as the dev version is being delivered to SDP
