### ISSUE TITLE
calwebb_guider failing because of blank VISITYPE keyword

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#2811]
The DMS B7.2 tests are encountering errors when processing many FGS guide star datasets through the `calwebb_guider` pipeline, which is due to problems associated with the fact that the VISITYPE keyword in the input _uncal file has a blank string value, i.e. "". This causes data model schema validation to issue a warning when the file is loaded, but then stops with an error when the calibrated data model is written back to disk at the end of processing.

An example processing log:
```
2018-10-30 16:32:45,499 - stpipe.GuiderPipeline - INFO - GuiderPipeline instance created.
2018-10-30 16:32:45,500 - stpipe.GuiderPipeline.dq_init - INFO - DQInitStep instance created.
2018-10-30 16:32:45,501 - stpipe.GuiderPipeline.guider_cds - INFO - GuiderCdsStep instance created.
2018-10-30 16:32:45,502 - stpipe.GuiderPipeline.flat_field - INFO - FlatFieldStep instance created.
2018-10-30 16:32:45,502 - stpipe - INFO - Hostname: macviper.stsci.edu
2018-10-30 16:32:45,502 - stpipe - INFO - OS: Darwin
2018-10-30 16:32:45,534 - stpipe.GuiderPipeline - INFO - Step GuiderPipeline running with args ('jw86600030001_gs-acq2_2016018142142_uncal.fits',).
2018-10-30 16:32:45,657 - stpipe.GuiderPipeline - WARNING - /Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/validate.py:35: ValidationWarning: While validating meta.visit.type the following error occurred:
'' is not one of ['GENERIC', 'PARALLEL_DARK_CALIBRATION', 'PARALLEL_EXTERNAL_CALIBRATION', 'PARALLEL_PURE', 'PARALLEL_SLEW_CALIBRATION', 'PRIME_STATION_KEEPING', 'PRIME_TARGETED_FIXED', 'PRIME_TARGETED_MOVING', 'PRIME_UNTARGETED', 'PRIME_WFSC_ROUTINE', 'PRIME_WFSC_SENSING_CONTROL', 'PRIME_WFSC_SENSING_ONLY', 'PRIOR_MOMENTUM_UNLOAD']

Failed validating 'enum' in schema:
    {'$schema': 'http://stsci.edu/schemas/asdf-schema/0.1.0/asdf-schema',
     'blend_table': True,
     'enum': ['GENERIC',
              'PARALLEL_DARK_CALIBRATION',
              'PARALLEL_EXTERNAL_CALIBRATION',
              'PARALLEL_PURE',
              'PARALLEL_SLEW_CALIBRATION',
              'PRIME_STATION_KEEPING',
              'PRIME_TARGETED_FIXED',
              'PRIME_TARGETED_MOVING',
              'PRIME_UNTARGETED',
              'PRIME_WFSC_ROUTINE',
              'PRIME_WFSC_SENSING_CONTROL',
              'PRIME_WFSC_SENSING_ONLY',
              'PRIOR_MOMENTUM_UNLOAD'],
     'fits_keyword': 'VISITYPE',
     'title': 'Visit type',
     'type': 'string'}

On instance:
    ''
  warnings.warn(errmsg, ValidationWarning)

2018-10-30 16:32:45,660 - stpipe.GuiderPipeline - WARNING - /Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/validate.py:35: ValidationWarning: While validating meta.visit.tsovisit the following error occurred:
'' is not of type 'boolean'

Failed validating 'type' in schema:
    {'$schema': 'http://stsci.edu/schemas/asdf-schema/0.1.0/asdf-schema',
     'blend_table': True,
     'fits_keyword': 'TSOVISIT',
     'title': 'Time Series Observation visit indicator',
     'type': 'boolean'}

On instance:
    ''
  warnings.warn(errmsg, ValidationWarning)

2018-10-30 16:32:45,700 - stpipe.GuiderPipeline - WARNING - /Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/util.py:167: NoTypeWarning: model_type not found. Opening jw86600030001_gs-acq2_2016018142142_uncal.fits as a RampModel
  warnings.warn(errmsg, NoTypeWarning)

2018-10-30 16:32:45,701 - stpipe.GuiderPipeline - INFO - Prefetching reference files for dataset: 'jw86600030001_gs-acq2_2016018142142_uncal.fits' reftypes = ['dflat', 'fflat', 'flat', 'mask', 'sflat']
2018-10-30 16:32:45,885 - stpipe.GuiderPipeline - INFO - Prefetch for DFLAT reference file is 'N/A'.
2018-10-30 16:32:45,885 - stpipe.GuiderPipeline - INFO - Prefetch for FFLAT reference file is 'N/A'.
2018-10-30 16:32:45,885 - stpipe.GuiderPipeline - INFO - Prefetch for FLAT reference file is '/grp/crds/cache/references/jwst/jwst_fgs_flat_0010.fits'.
2018-10-30 16:32:45,887 - stpipe.GuiderPipeline - INFO - Prefetch for MASK reference file is '/grp/crds/cache/references/jwst/jwst_fgs_mask_0025.fits'.
2018-10-30 16:32:45,890 - stpipe.GuiderPipeline - INFO - Prefetch for SFLAT reference file is 'N/A'.
2018-10-30 16:32:45,890 - stpipe.GuiderPipeline - INFO - Starting calwebb_guider ...
2018-10-30 16:32:46,007 - stpipe.GuiderPipeline.dq_init - INFO - Step dq_init running with args (<GuiderRawModel(5, 2, 32, 32) from jw86600030001_gs-acq2_2016018142142_uncal.fits>,).
2018-10-30 16:32:46,023 - stpipe.GuiderPipeline.dq_init - WARNING - /Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/validate.py:35: ValidationWarning: While validating <RampModel(5, 2, 32, 32) from jw86600030001_gs-acq2_2016018142142_uncal.fits> the following error occurred:
'' is not one of ['GENERIC', 'PARALLEL_DARK_CALIBRATION', 'PARALLEL_EXTERNAL_CALIBRATION', 'PARALLEL_PURE', 'PARALLEL_SLEW_CALIBRATION', 'PRIME_STATION_KEEPING', 'PRIME_TARGETED_FIXED', 'PRIME_TARGETED_MOVING', 'PRIME_UNTARGETED', 'PRIME_WFSC_ROUTINE', 'PRIME_WFSC_SENSING_CONTROL', 'PRIME_WFSC_SENSING_ONLY', 'PRIOR_MOMENTUM_UNLOAD']

Failed validating 'enum' in schema['properties']['meta']['properties']['visit']['properties']['type']:
    OrderedDict([('title', 'Visit type'),
                 ('type', 'string'),
                 ('enum',
                  ['GENERIC',
                   'PARALLEL_DARK_CALIBRATION',
                   'PARALLEL_EXTERNAL_CALIBRATION',
                   'PARALLEL_PURE',
                   'PARALLEL_SLEW_CALIBRATION',
                   'PRIME_STATION_KEEPING',
                   'PRIME_TARGETED_FIXED',
                   'PRIME_TARGETED_MOVING',
                   'PRIME_UNTARGETED',
                   'PRIME_WFSC_ROUTINE',
                   'PRIME_WFSC_SENSING_CONTROL',
                   'PRIME_WFSC_SENSING_ONLY',
                   'PRIOR_MOMENTUM_UNLOAD']),
                 ('fits_keyword', 'VISITYPE'),
                 ('blend_table', True)])

On instance['meta']['visit']['type']:
    ''
  warnings.warn(errmsg, ValidationWarning)

2018-10-30 16:32:46,036 - stpipe.GuiderPipeline.dq_init - INFO - Input opened as GuiderRawModel
2018-10-30 16:32:46,038 - stpipe.GuiderPipeline.dq_init - INFO - Using MASK reference file /grp/crds/cache/references/jwst/jwst_fgs_mask_0025.fits
2018-10-30 16:32:46,280 - stpipe.GuiderPipeline.dq_init - WARNING - Keyword FGS_WARM does not correspond to an existing DQ mnemonic, so will be ignored
2018-10-30 16:32:46,280 - stpipe.GuiderPipeline.dq_init - WARNING - Keyword FGS_NOISY does not correspond to an existing DQ mnemonic, so will be ignored
2018-10-30 16:32:46,338 - stpipe.GuiderPipeline.dq_init - INFO - Extracting mask subarray to match science data
2018-10-30 16:32:46,346 - stpipe.GuiderPipeline.dq_init - INFO - Step dq_init done
2018-10-30 16:32:46,379 - stpipe.GuiderPipeline.guider_cds - INFO - Step guider_cds running with args (<GuiderRawModel(5, 2, 32, 32) from jw86600030001_gs-acq2_2016018142142_uncal.fits>,).
2018-10-30 16:32:46,396 - stpipe.GuiderPipeline.guider_cds - INFO - Instrument: FGS
2018-10-30 16:32:46,396 - stpipe.GuiderPipeline.guider_cds - INFO - Exposure type: FGS_ACQ2
2018-10-30 16:32:46,396 - stpipe.GuiderPipeline.guider_cds - INFO - Number of integrations: 5
2018-10-30 16:32:46,396 - stpipe.GuiderPipeline.guider_cds - INFO - Number of groups per integration: 2
2018-10-30 16:32:46,396 - stpipe.GuiderPipeline.guider_cds - INFO - Group time: 0.05016
2018-10-30 16:32:46,396 - stpipe.GuiderPipeline.guider_cds - INFO - Frame time:    0.01254
2018-10-30 16:32:46,422 - stpipe.GuiderPipeline.guider_cds - INFO - Step guider_cds done
2018-10-30 16:32:46,454 - stpipe.GuiderPipeline.flat_field - INFO - Step flat_field running with args (<GuiderCalModel(5, 32, 32) from jw86600030001_gs-acq2_2016018142142_uncal.fits>,).
2018-10-30 16:32:46,660 - stpipe.GuiderPipeline.flat_field - INFO - Extracting matching subarray from flat
2018-10-30 16:32:46,672 - stpipe.GuiderPipeline.flat_field - INFO - Step flat_field done
2018-10-30 16:32:46,672 - stpipe.GuiderPipeline - INFO - ... ending calwebb_guider
----------------------------------------------------------------------
ERROR RUNNING STEP 'GuiderPipeline':
    '' is not one of ['GENERIC', 'PARALLEL_DARK_CALIBRATION',
    'PARALLEL_EXTERNAL_CALIBRATION', 'PARALLEL_PURE',
    'PARALLEL_SLEW_CALIBRATION', 'PRIME_STATION_KEEPING',
    'PRIME_TARGETED_FIXED', 'PRIME_TARGETED_MOVING',
    'PRIME_UNTARGETED', 'PRIME_WFSC_ROUTINE',
    'PRIME_WFSC_SENSING_CONTROL', 'PRIME_WFSC_SENSING_ONLY',
    'PRIOR_MOMENTUM_UNLOAD']  Failed validating 'enum' in schema['prop
    erties']['meta']['properties']['visit']['properties']['type']:
    OrderedDict([('title', 'Visit type'),                  ('type',
    'string'),                  ('enum',                   ['GENERIC',
    'PARALLEL_DARK_CALIBRATION',
    'PARALLEL_EXTERNAL_CALIBRATION',
    'PARALLEL_PURE',                    'PARALLEL_SLEW_CALIBRATION',
    'PRIME_STATION_KEEPING',
    'PRIME_TARGETED_FIXED',
    'PRIME_TARGETED_MOVING',                    'PRIME_UNTARGETED',
    'PRIME_WFSC_ROUTINE',
    'PRIME_WFSC_SENSING_CONTROL',
    'PRIME_WFSC_SENSING_ONLY',
    'PRIOR_MOMENTUM_UNLOAD']),                  ('fits_keyword',
    'VISITYPE'),                  ('blend_table', True)])  On
    instance['meta']['visit']['type']:     ''
Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 454, in run
    self.save_model(result, idx=idx)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 782, in save_model
    **components
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/model_base.py", line 504, in save
    self.to_fits(output_path, *args, **kwargs)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/model_base.py", line 589, in to_fits
    extensions=self._extensions) as ff:
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/fits_support.py", line 386, in to_fits
    _save_from_schema(hdulist, tree, schema)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.0a0.dev148-py3.6-macosx-10.7-x86_64.egg/jwst/datamodels/fits_support.py", line 340, in _save_from_schema
    validator.validate(tree, _schema=schema)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: '' is not one of ['GENERIC', 'PARALLEL_DARK_CALIBRATION', 'PARALLEL_EXTERNAL_CALIBRATION', 'PARALLEL_PURE', 'PARALLEL_SLEW_CALIBRATION', 'PRIME_STATION_KEEPING', 'PRIME_TARGETED_FIXED', 'PRIME_TARGETED_MOVING', 'PRIME_UNTARGETED', 'PRIME_WFSC_ROUTINE', 'PRIME_WFSC_SENSING_CONTROL', 'PRIME_WFSC_SENSING_ONLY', 'PRIOR_MOMENTUM_UNLOAD']

Failed validating 'enum' in schema['properties']['meta']['properties']['visit']['properties']['type']:
    OrderedDict([('title', 'Visit type'),
                 ('type', 'string'),
                 ('enum',
                  ['GENERIC',
                   'PARALLEL_DARK_CALIBRATION',
                   'PARALLEL_EXTERNAL_CALIBRATION',
                   'PARALLEL_PURE',
                   'PARALLEL_SLEW_CALIBRATION',
                   'PRIME_STATION_KEEPING',
                   'PRIME_TARGETED_FIXED',
                   'PRIME_TARGETED_MOVING',
                   'PRIME_UNTARGETED',
                   'PRIME_WFSC_ROUTINE',
                   'PRIME_WFSC_SENSING_CONTROL',
                   'PRIME_WFSC_SENSING_ONLY',
                   'PRIOR_MOMENTUM_UNLOAD']),
                 ('fits_keyword', 'VISITYPE'),
                 ('blend_table', True)])

On instance['meta']['visit']['type']:
    ''
```

What surprises me about this is the fact that the VISITYPE keyword/attribute is still there in the output data model, in order to cause the error when trying to write it to a file. I would've thought that the schema validation error on input would've cause the data model attribute for that keyword to be set to None, such that the keyword would essentially be gone. So why is it still giving a schema validation on the output model?

Note that the output model is created in the `guider_cds` step (the 2nd step of the `calwebb_guider` pipeline) by first creating an empty model and then using `model.update(input)` to copy the keywords from the input model.

Example files can be found in /grp/jwst/ssb/bushouse/jwst_data/FGS/Guiding/. To run:
```
$ strun calwebb_guider.cfg jw86600030001_gs-acq2_2016018142142_uncal.fits
```

**Comment by hbushouse** [comment]
Mike Swam indicates that relatively few guide star datasets are being affected by this problem and there are plenty of successful cases that can be used to satisfy the DMS requirement for calibrating guide star data. So this is no longer high priority for B7.2 and can be fixed later.

**Comment by hbushouse** [comment]
VISITYPE is set to "VALUE_REQUIRED" in the keyword dictionary, with an enum list of:
```
GENERIC, PARALLEL_DARK_CALIBRATION, PARALLEL_EXTERNAL_CALIBRATION, PARALLEL_PURE, PARALLEL_SLEW_CALIBRATION, PRIME_STATION_KEEPING, PRIME_TARGETED_FIXED, PRIME_TARGETED_MOVING, PRIME_UNTARGETED, PRIME_WFSC_ROUTINE, PRIME_WFSC_SENSING_CONTROL, PRIME_WFSC_SENSING_ONLY, PRIOR_MOMENTUM_UNLOAD
```
which is consistent with our datamodel schema and does not allow for a blank value. Hence this error was due to bad data and does not require fixing in Cal.
