### ISSUE TITLE
IndexError: Compound model CompoundModel56 does not have a component named crval

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2817]
# Issue
Running on WFR2 data on a fine phasing proposal, jw00711, using `wfs_combine` on a pair, gives the following:

<details><summary>Show log...</summary>
<p>

```
$ strun cfgs/wfs_combine.cfg jw00711_20181027T043250_pool-o002_wfs-image3_001_asn.json
2018-10-31 11:51:28,011 - stpipe.WfsCombine - INFO - WfsCombineStep instance created.
2018-10-31 11:51:28,038 - stpipe.WfsCombine - INFO - Step WfsCombine running with args ('jw00711_20181027T043250_pool-o002_wfs-image3_001_asn.json',).
2018-10-31 11:51:28,060 - stpipe.WfsCombine - INFO - Using input table: jw00711_20181027T043250_pool-o002_wfs-image3_001_asn.json
2018-10-31 11:51:28,061 - stpipe.WfsCombine - INFO - The number of pairs of input files: 1
2018-10-31 11:51:40,669 - stpipe.WfsCombine - INFO - File 1 to combine: jw00711002001_02105_00002_nrca4_cal.fits
2018-10-31 11:51:40,669 - stpipe.WfsCombine - INFO - File 2 to combine: jw00711002001_02105_00001_nrca4_cal.fits
2018-10-31 11:51:40,669 - stpipe.WfsCombine - INFO - Output file: jw00711-o002_t001_nircam_wlp4-nrca4_{suffix}-05
2018-10-31 11:51:40,669 - stpipe.WfsCombine - INFO - do_refine: False
----------------------------------------------------------------------
ERROR RUNNING STEP 'WfsCombineStep':
    Compound model CompoundModel56 does not have a component named
    crval
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2705, in get_index_from_name
    return cls.submodel_names.index(name)
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine_step.py", line 37, in process
    output_model = wfs.do_all()
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine.py", line 88, in do_all
    im_2_a = self.create_aligned_2()  # Aligned image #2
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine.py", line 135, in create_aligned_2
    self.off_x, self.off_y = self.get_wcs_offsets()
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine.py", line 261, in get_wcs_offsets
    crval1_model = self.input_1.meta.wcs.forward_transform['crval']
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2891, in __getitem__
    index = self.__class__._normalize_index(index)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2724, in _normalize_index
    return get_index_from_name(index)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2709, in get_index_from_name
    '{1}'.format(cls.name, name))
IndexError: Compound model CompoundModel56 does not have a component named crval

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2705, in get_index_from_name
    return cls.submodel_names.index(name)
ValueError: tuple.index(x): x not in tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine_step.py", line 37, in process
    output_model = wfs.do_all()
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine.py", line 88, in do_all
    im_2_a = self.create_aligned_2()  # Aligned image #2
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine.py", line 135, in create_aligned_2
    self.off_x, self.off_y = self.get_wcs_offsets()
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/jwst-0.13.0a0.dev146+g4abefa32-py3.6-macosx-10.7-x86_64.egg/jwst/wfs_combine/wfs_combine.py", line 261, in get_wcs_offsets
    crval1_model = self.input_1.meta.wcs.forward_transform['crval']
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2891, in __getitem__
    index = self.__class__._normalize_index(index)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2724, in _normalize_index
    return get_index_from_name(index)
  File "/Users/eisenham/anaconda3/envs/condadev/lib/python3.6/site-packages/astropy-3.2.dev23179-py3.6-macosx-10.7-x86_64.egg/astropy/modeling/core.py", line 2709, in get_index_from_name
    '{1}'.format(cls.name, name))
IndexError: Compound model CompoundModel56 does not have a component named crval
```

</p>
</details>

**Comment by stscieisenhamer** [comment]
# Resources

Data can be found in `/grp/jwst/ssb/eisenhamer/jwst_issues/issue2817`.

**Comment by stscicrawford** [comment]
@dmggh Can you take a look at this as a high priority item?

**Comment by nden** [comment]
I've been asked to look at this. I think `get_wcs_offsets` makes assumptions about the WCS which may have been correct several builds ago (either build3 or build 5) but not any more. If I understand correctly the algorithm, then something like this needs to happen

1. get CRVAL and CRPIX for input1 and input2 from model.meta.wcsinfo
2. use input1.meta.wcs.inverse(*input2.crval) to get the location of input2's CRVAL in the frame of input1, i.e. new values for CRPIX
3. Subtract input1's CRPIX from the values computed in 2. above to get the offset

@dmggh Is this a correct description of the algorithm?

**Comment by nden** [comment]
Oh, I thought we have a regression test for this step. How come it didn't pick up the problem?

**Comment by dmggh** [comment]
That description is basically correct.

**Comment by stscieisenhamer** [comment]
There is a regression, but the data is old and hand-constructed. The data should be replaced with this "real" data.

**Comment by philhodge** [comment]
I don't see why you need to rely on crval and crpix.  Crpix doesn't even need to be within the image.  Why not take some pixel (any pixel) near the middle of the image, use the WCS for the first image to compute the corresponding right ascension and declination at that pixel, then use the WCS for the second image to compute the pixel numbers in the second image from those values of ra and dec?  If the images are the same size, that should work.  If they're not the same size, then this still gives you pixel coordinates in both images for the same point in the sky.

**Comment by dmggh** [comment]
I have a plausible fix based on Phil's comment just above, but I will wait until Jonathan's PR #2831 ("Update WFS&C associations and rename wfs_combine to match workflow convention") has been merged before I commit my updates.

**Comment by dmggh** [comment]
This was handled by PR #2834.
