### ISSUE TITLE
Data model problem when referencing url's in schemas

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#3224]
Steven Beard (MIRI IDT software team) reports:

> The MIRI software team would like to update the version of the JWST library installed by MIRICLE from 0.9.6 (B7.1.3) to 0.12.3 (B7.2.1) but there seems to have been a change to the schema software which is affecting the MIRI data models. The MIRI schemas use the syntax
```
- $ref: http://jwst.stsci.edu/schemas/core.schema.yaml
```
> to import data models from the jwst package, but this syntax no longer works. When the MIRI software attempts to use this syntax with the B7.1.3 data model software it fails with the following error message.
```
$ python miri_model_base.py
Testing the MiriDataModel module.
Empty MIRI data model
Traceback (most recent call last):
  File "miri_model_base.py", line 3361, in <module>
    with MiriDataModel() as testdata:
  File "miri_model_base.py", line 454, in __init__
    **kwargs)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/jwst-0.12.3-py3.5-linux-x86_64.egg/jwst/datamodels/model_base.py", line 104, in __init__
    resolve_references=True)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/schema.py", line 355, in load_schema
    schema = treeutil.walk_and_modify(schema, resolve_refs)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/treeutil.py", line 182, in walk_and_modify
    return recurse_with_json_ids(top, None)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/treeutil.py", line 161, in recurse_with_json_ids
    val = recurse_with_json_ids(val, json_id)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/treeutil.py", line 170, in recurse_with_json_ids
    [recurse_with_json_ids(val, json_id) for val in tree])
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/treeutil.py", line 170, in <listcomp>
    [recurse_with_json_ids(val, json_id) for val in tree])
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/treeutil.py", line 177, in recurse_with_json_ids
    result = callback(result, json_id)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/schema.py", line 350, in resolve_refs
    subschema = load_schema(suburl_path, resolver, True)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/schema.py", line 332, in load_schema
    schema, url = loader(url)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/schema.py", line 273, in load_schema
    return _load_schema(url)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/schema.py", line 261, in _load_schema
    with generic_io.get_file(url) as fd:
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/generic_io.py", line 1172, in get_file
    return _make_http_connection(init, mode, uri=uri)
  File "/sw4/smb/anaconda3/envs/testLatestJwstSoftware/lib/python3.5/site-packages/asdf/generic_io.py", line 1063, in _make_http_connection
    response.status, response.reason))
OSError: HTTP failed: 301 Moved Permanently
```
> It looks like there has been some work done on the reference syntax because I notice the schema names no longer need to include the “.yaml” extension. For example:
 ```
         - $ref: http://stsci.edu/schemas/asdf/time/time-1.0.0
 ```
> The “stsci.edu” syntax still works but the “jwst.stsci.edu” syntax is no longer recognised. Has this syntax been removed, or is there a problem that we are only seeing now because MIRI is the only software making use of the syntax?

**Comment by hbushouse** [comment]
Additional info from Steven:
```
Did you find out whether the syntax
 
                http://jwst.stsci.edu/schemas/<filename>.schema
 
has been removed from the Build 7.2 JWST library. The MIRI software uses this syntax to reference the JWST data model schemas.
For example, we use
 
allOf:
- $ref: http://jwst.stsci.edu/schemas/core.schema.yaml
- $ref: http://jwst.stsci.edu/schemas/referencefile.schema.yaml
- etc…
 
To inherit all of your core definitions and reference file definitions. The syntax
 
                http://stsci.edu/schemas/<filename>.schema
 
for referencing schemas from the ADSF package still works, however. I would be grateful for any advice on the best way to incorporate the JWST schema definitions from Build 7.2.
The only other way I can think of doing this would be to copy your data models into our folder and reference them directly, but this would make version control harder and complicate the MIRICLE installation scripts. Any advice appreciated.
```

**Comment by hbushouse** [comment]
@jdavies-st reports:
```
So chatting with Dan, we were able to pinpoint the issue.  This is what broke the functionality:

https://github.com/spacetelescope/jwst/pull/2430/files

Basically, we just need to revert that PR, add a test, and fix up the call to the asdf.resolver to actually use the URI instead of a hard-coded path.  That last piece is not necessary, but will make the code more robust and use the resolver as it was meant to be used.
```

**Comment by jdavies-st** [comment]
FWIW this functionality was added in #261.  And removed in #2430.

Fix coming shortly.

**Comment by jdavies-st** [comment]
So fix PR is submitted.

One little wrinkle is that we have 2 entry points for ASDF extensions in this package:

- `JWSTExtension` which makes the `astropy.modeling` transforms defined in this package available to `gwcs`, `asdf` and other packages
- `BaseExtension` which makes the datamodel schemas available in the same way

But the URLs for these 2 ASDF extensions are fundamentally different in format:

`JWSTExtension` maps `http://stsci.edu/schemas/jwst_pipeline/` to transform schemas
`BaseExtension` maps `http://jwst.stsci.edu/schemas/` to datamodel schemas

Further, whether the `.yaml` ending is included varies as well.  It must be included on `BaseExtension`, but it cannot be included on `JWSTExtension`.

And neither of these extension names indicate that they are for transforms schemas or datamodel schemas, something a name should probably do.

It would be nice to resolve these for consistency sake, though not necessarily in #3227.  Thoughts on the best way to resolve this?  Can we get input from Steven Beard as well on this issue?  I don't want to break backwards compatibility with the MIRI IDT code.  But since we already have, perhaps there's scope to get these resolved.
