### ISSUE TITLE
Error in tweakreg when processing MIRI images

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#3287]
Recent DMS testing has resulted in the following error during `tweakreg` processing of a set of MIRI images, which I suspect is due to the fact that the detected sources are all bogus, because the input images contain nothing but noise.
```
2019-03-25 14:24:02,721 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2019-03-25 14:24:04,052 - stpipe.Image3Pipeline - INFO - Aligning input images...
2019-03-25 14:24:04,099 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg running with args (<ModelContainer>,).
2019-03-25 14:24:04,556 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 5 sources in jw80600006001_02101_00001_mirimage_cal.fits.
2019-03-25 14:24:05,179 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 48 sources in jw80600006001_02102_00001_mirimage_cal.fits.
2019-03-25 14:24:05,625 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 13 sources in jw80600006001_02103_00001_mirimage_cal.fits.
2019-03-25 14:24:06,245 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 39 sources in jw80600006001_02104_00001_mirimage_cal.fits.
2019-03-25 14:24:06,516 - stpipe.Image3Pipeline.tweakreg - WARNING - /Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/spherical_geometry/polygon.py:594: RuntimeWarning: invalid value encountered in triple_product
  orient = great_circle_arc.triple_product(A-B, C-B, B)

2019-03-25 14:24:06,517 - stpipe.Image3Pipeline.tweakreg - WARNING - /Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/spherical_geometry/polygon.py:133: RuntimeWarning: invalid value encountered in triple_product
  orient = great_circle_arc.triple_product(A-B, C-B, B)

----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    Out of domain for acos
Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/pipeline/calwebb_image3.py", line 70, in process
    input_models = self.tweakreg(input_models)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/tweakreg/tweakreg_step.py", line 126, in process
    wcsimlist = list(map(self._imodel2wcsim, g))
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/tweakreg/tweakreg_step.py", line 179, in _imodel2wcsim
    meta={'image_model': image_model}
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/tweakreg/wcsimage.py", line 361, in __init__
    self.catalog = catalog
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/tweakreg/wcsimage.py", line 463, in catalog
    self.calc_bounding_polygon()
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/tweakreg/wcsimage.py", line 692, in calc_bounding_polygon
    self._calc_cat_convex_hull()
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/jwst-0.13.2a0.dev75-py3.6-macosx-10.7-x86_64.egg/jwst/tweakreg/wcsimage.py", line 679, in _calc_cat_convex_hull
    self._poly_area = np.fabs(self._polygon.area())
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/spherical_geometry/polygon.py", line 1100, in area
    area += subpoly.area()
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/spherical_geometry/polygon.py", line 547, in area
    points[2:], degrees=False)
  File "/Users/bushouse/anaconda3/envs/myjwst/lib/python3.6/site-packages/spherical_geometry/great_circle_arc.py", line 320, in angle
    angle = math_util.angle(A, B, C)
ValueError: Out of domain for acos
```
The input data files and ASN file can be found in
```
/grp/jwst/ssb/bushouse/jwst_data/MIRI/Image/
```
The ASN file for use as input to `calwebb_image3` is `jw80600-o006_20190313t134653_image3_001_asn.json`, which lists the input data sets:
```
jw80600006001_0210[1234]_00001_mirimage_cal.fits.
```

**Comment by hbushouse** [comment]
A smaller set of test data that still produces the same error has been created using only 2 of the input files. Copy over the files "test_asn.json", "jw80600006001_02101_00001_mirimage_cal.fits", and "jw80600006001_02102_00001_mirimage_cal.fits" from /grp/jwst/ssb/bushouse/jwst_data/MIRI/Image/ and run the command:
```
strun jwst.pipeline.Image3Pipeline test_asn.json
```

**Comment by mcara** [comment]
@hbushouse

My investigation into this issue shows that one of the sources detected by the source finding algorithm lies outside the WCS's bounding box.

Specifically, `(x, y) = (1027.7276754433412, 498.7667003905598)` is outside the bounding box defined by the WCS which is `((3.5, 1027.5), (-0.5, 1023.5))`.

There are two approaches to fixing this: either we filter the catalogs in the `tweakreg` step or `photutils` (@larrybradley) could have an option to not return (filter out) sources with the centers outside an image or on masked pixels.

Which approach would be preferable? @hbushouse @larrybradley

**Comment by mcara** [comment]
NOTE: the traceback of this error is similar to the one in https://github.com/spacetelescope/jwst/issues/2746

**Comment by mcara** [comment]
https://github.com/spacetelescope/jwst/pull/3292 should fix this issue. However, IMO it would also be useful to add some filtering code to the source finding algorithm in `photutils`, @larrybradley 
The reason for this is that parameters such as `nbright` may pick let's say 15 sources but I may have to throw away 3 of them. Then `tweakreg` would be effectively using only 12 sources. By having filtering performed before top `nbright` are selected, we guaranty to return `nbright` _valid_ sources.

I know source finding does not need a WCS, but maybe it could accept a "bounding box" (or similar).

Just a thought...

**Comment by hbushouse** [comment]
I'm surprised that whatever routine is being used to find sources is able to find and document one that lies outside the WCS bounding box to begin with. If it's outside the box, I assume there's no way to compute sky coords for it, so what kind of entry ends up in the catalog? Or does the tweakreg catalog only use positions in pixel space, as opposed to sky? If the source finding function is not currently using the WCS object of the exposure for anything, then having it check whether a source lies within the WCS bounding box would be some additional work (i.e. it would obviously have to load and query the WCS object in order to compare source positions against the bounding box).

**Comment by hbushouse** [comment]
This particular failure may be related to the fact that we're dealing with MIRI imaging data, where the imager field-of-view fills only about 2/3 of the detector (the rest of the space is occupied by the coronagraphic masks and LRS spectroscopy slit). So for an imaging-mode exposure the WCS bounding box will encompass only about 2/3 of the detector space. I wonder if the tweakreg catalog routine is searching the entire detector/image area? If so, that's wasted effort and a strong argument for having that routine only search within the WCS bounding box to begin with.

**Comment by mcara** [comment]
Source finding in `tweakreg`/`photutils` is working in pixel coordinates - it has no knowledge of the WCS (and probably shouldn't). But it would be great if it could accept some sort of a bounding box specification and/or mask.

**Comment by sosey** [comment]
There are plans to have photutils work with the GWCS, but it hasn't been added yet...right @larrybradley ?

**Comment by larrybradley** [comment]
Yes, I'm going to implement the astropy unified WCS APE in photutils.  It's not there yet.

**Comment by larrybradley** [comment]
Is the MIRI WCS bounding box defined only for the imaging area (i.e. ~2/3 part of the detector)?

**Comment by hbushouse** [comment]
I believe that's the case for an exposure with EXP_TYPE='MIR_IMAGE'. Similarly, for EXP_TYPE='MIR_LRS-FIXEDSLIT' or 'MIR_CORON' the WCS bounding box is confined to the region occupied by those data. But @nden should confirm.

**Comment by mcara** [comment]
Was this fixed?

**Comment by larrybradley** [comment]
The non-imaging regions are now masked in the tweakreg source finding (https://github.com/spacetelescope/jwst/pull/3461).
