### ISSUE TITLE
extract_1d fails on WFSS data

### ISSUE THREAD

**Issue by hbushouse** [spacetelescope/jwst#3413]
The ``extract_1d`` step is failing when processing a NIRISS WFSS exposure:
```
2019-04-26 18:32:31,444 - stpipe.Spec2Pipeline.photom - INFO - Step photom done
2019-04-26 18:32:31,528 - stpipe.Spec2Pipeline.extract_1d - INFO - Step extract_1d running with args (<MultiSlitModel from jw87600017001_02101_00002_nis_cal.fits>,).
2019-04-26 18:32:31,543 - stpipe.Spec2Pipeline.extract_1d - INFO - No EXTRACT1D reference file will be used
2019-04-26 18:32:31,580 - stpipe.Spec2Pipeline.extract_1d - INFO - Working on slit Object 10
Traceback (most recent call last):
  File "/data1/jenkins/workspace/RT/JWST/jwst/pipeline/calwebb_spec2.py", line 91, in process
    asn.filename
  File "/data1/jenkins/workspace/RT/JWST/jwst/pipeline/calwebb_spec2.py", line 302, in process_exposure_product
    x1d_result = self.extract_1d(result_extra)
  File "/data1/jenkins/workspace/RT/JWST/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/data1/jenkins/workspace/RT/JWST/jwst/extract_1d/extract_1d_step.py", line 189, in process
    self.apply_nod_offset)
  File "/data1/jenkins/workspace/RT/JWST/jwst/extract_1d/extract.py", line 2736, in run_extract1d
    apply_nod_offset)
  File "/data1/jenkins/workspace/RT/JWST/jwst/extract_1d/extract.py", line 2892, in do_extract1d
    prev_offset, True, extract_params)
  File "/data1/jenkins/workspace/RT/JWST/jwst/extract_1d/extract.py", line 3546, in extract_one_slit
    input_model, slit, local_verbose)
  File "/data1/jenkins/workspace/RT/JWST/jwst/extract_1d/extract.py", line 1192, in offset_from_offset
    verbose)
  File "/data1/jenkins/workspace/RT/JWST/jwst/extract_1d/extract.py", line 1297, in locn_from_wcs
    stuff = self.wcs(x, y)
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/gwcs/wcs.py", line 255, in __call__
    result = transform(*args, **kwargs)
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 382, in __call__
    ('equivalencies', None)])
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 363, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 797, in __call__
    valid_result = self.evaluate(*chain(args, parameters))
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2921, in evaluate
    return self.__class__.evaluate(*args)
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2362, in evaluate
    result = cls._evaluate(inputs, params)
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2194, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2194, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2194, in <lambda>
    return (lambda inputs, params: g[0](f[0](inputs, params), params),
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2802, in f
    return evaluate_wrapper(model, inputs, param_values)
  File "/data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.6/site-packages/astropy/modeling/core.py", line 2794, in evaluate_wrapper
    outputs = model.evaluate(*inputs, *param_values)
  File "/data1/jenkins/workspace/RT/JWST/jwst/transforms/models.py", line 1442, in evaluate
    iorder = self._order_mapping[int(order)]
TypeError: only size-1 arrays can be converted to Python scalars
```
Looks like it might be an error involving computing the wavelengths similar to the problem we were having in ``get_wavelengths`` before the fix in #3408. Is the fix possibly already included in #3412?

**Comment by hbushouse** [comment]
Fixed in B7.3
