### ISSUE TITLE
Problem installing with setup.py install command

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#3952]
When attempting to install `master` from source, I get this obscure traceback. At first, it claims to come from `stsci.image`. But then I could install `stsci.image` from its `master` with no problem. After that, trying this again now give me the same error but from `drizzle`. Do you run your tests against Numpy 1.17 yet? Did you see something like this?
```
Running drizzle-1.13.1/setup.py -q bdist_egg --dist-dir .../drizzle-1.13.1/egg-dist-tmp-hjnkz91m
Traceback (most recent call last):
  File ".../setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File ".../setuptools/sandbox.py", line 195, in setup_context
    yield
  File ".../setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File ".../setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File ".../drizzle-1.13.1/setup.py", line 12, in <module>
    Beginning with JWST 0.9, Python 3.5 and above is required.
  File ".../numpy/__init__.py", line 142, in <module>
    from . import core
  File ".../numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File ".../numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File ".../numpy/core/overrides.py", line 47, in <module>
 
RuntimeError: implement_array_function method already has a docstring

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 216, in <module>
    entry_points=entry_points,
  File ".../setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File ".../distutils/core.py", line 148, in setup
    dist.run_commands()
  File ".../distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File ".../distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File ".../setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File ".../setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File ".../setuptools/command/easy_install.py", line 418, in run
    self.easy_install(spec, not self.no_deps)
  File ".../setuptools/command/easy_install.py", line 660, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File ".../setuptools/command/easy_install.py", line 707, in install_item
    self.process_distribution(spec, dist, deps)
  File ".../setuptools/command/easy_install.py", line 752, in process_distribution
    [requirement], self.local_index, self.easy_install
  File ".../pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File ".../pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File ".../pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File ".../setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File ".../setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File ".../setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File ".../setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File ".../setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File ".../setuptools/sandbox.py", line 253, in run_setup
    raise
  File ".../contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File ".../setuptools/sandbox.py", line 195, in setup_context
    yield
  File ".../contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File ".../setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File ".../setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File ".../setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File ".../setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File ".../setuptools/sandbox.py", line 195, in setup_context
    yield
  File ".../setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File ".../setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File ".../drizzle-1.13.1/setup.py", line 12, in <module>
    Beginning with JWST 0.9, Python 3.5 and above is required.
  File ".../numpy/__init__.py", line 142, in <module>
    from . import core
  File ".../numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File ".../numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File ".../numpy/core/overrides.py", line 47, in <module>

RuntimeError: implement_array_function method already has a docstring
```

**Comment by jhunkeler** [comment]
@jdavies-st reported this issue around the time we started looking at `pip` as an alternative to `conda` (`-dev`). At that time downgrading `numpy` to 1.15.[something?] fixed it (maybe even 1.14.[something]). The `numpy` devs introduced a C macro to aid generating their documentation, but as a consequence (somehow) any package that used `cython` would trigger the failure @pllim posted.

Last I remember... the `numpy` folks were wondering when the `cython` people were going to fix the problem. On the `cython` side I think they were wondering when the `numpy` people were going to fix it as well.

The problem still exists, so I think it is fair to say both parties are still wondering to this day.
