### ISSUE TITLE
Asdf error on pipeline run

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/jwst#4014]
I recently installed the calibration pipeline v0.13.7 for testing and am unable to run due to an asdf package error. Any advice? The same error occurred when trying to run MIRISim (separate ticket raised there). It looks like it's looking for a file (version_map-1.3.0.yaml) in the wrong location? this file is present in /anaconda3/envs/..../asdf/, but not in /envs/..../asdf/.

```
(jwst_env) Sarahs-MacBook-Pro-3:LRS-slit-simulations kendrew$ strun jwst.pipeline.Detector1Pipeline lmc81_slit_nodither_uncal.fits
2019-09-12 14:06:01,001 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2019-09-12 14:06:01,002 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2019-09-12 14:06:01,003 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2019-09-12 14:06:01,003 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2019-09-12 14:06:01,004 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2019-09-12 14:06:01,005 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2019-09-12 14:06:01,006 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2019-09-12 14:06:01,006 - stpipe.Detector1Pipeline.rscd - INFO - RSCD_Step instance created.
2019-09-12 14:06:01,007 - stpipe.Detector1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2019-09-12 14:06:01,008 - stpipe.Detector1Pipeline.lastframe - INFO - LastFrameStep instance created.
2019-09-12 14:06:01,009 - stpipe.Detector1Pipeline.linearity - INFO - LinearityStep instance created.
2019-09-12 14:06:01,010 - stpipe.Detector1Pipeline.dark_current - INFO - DarkCurrentStep instance created.
2019-09-12 14:06:01,011 - stpipe.Detector1Pipeline.persistence - INFO - PersistenceStep instance created.
2019-09-12 14:06:01,012 - stpipe.Detector1Pipeline.jump - INFO - JumpStep instance created.
2019-09-12 14:06:01,012 - stpipe.Detector1Pipeline.ramp_fit - INFO - RampFitStep instance created.
2019-09-12 14:06:01,013 - stpipe.Detector1Pipeline.gain_scale - INFO - GainScaleStep instance created.
2019-09-12 14:06:01,013 - stpipe - INFO - Hostname: Sarahs-MacBook-Pro-3.local
2019-09-12 14:06:01,013 - stpipe - INFO - OS: Darwin
2019-09-12 14:06:01,047 - stpipe.Detector1Pipeline - INFO - Step Detector1Pipeline running with args ('lmc81_slit_nodither_uncal.fits',).
2019-09-12 14:06:01,233 - stpipe.Detector1Pipeline - INFO - First argument lmc81_slit_nodither_uncal.fits does not appear to be a model
2019-09-12 14:06:01,233 - stpipe.Detector1Pipeline - INFO - Starting calwebb_detector1 ...
----------------------------------------------------------------------
ERROR RUNNING STEP 'Detector1Pipeline':
    Don't know how to write out ASDF version 1.3.0
Traceback (most recent call last):
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/versioning.py", line 52, in get_version_map
    with generic_io.get_file(version_map_path, 'r') as fd:
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/generic_io.py", line 1198, in get_file
    fd = open(realpath, realmode)
FileNotFoundError: [Errno 2] No such file or directory: '/envs/jwst_env/lib/python3.6/site-packages/asdf/schemas/stsci.edu/asdf/version_map-1.3.0.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/type_index.py", line 57, in __init__
    version_map = get_version_map(self._version)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/versioning.py", line 57, in get_version_map
    "Could not load version map for version {0}".format(version))
ValueError: Could not load version map for version 1.3.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/stpipe/step.py", line 394, in run
    step_result = self.process(*args)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/pipeline/calwebb_detector1.py", line 67, in process
    input = datamodels.RampModel(input)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/datamodels/ramp.py", line 38, in __init__
    super(RampModel, self).__init__(init=init, **kwargs)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/datamodels/model_base.py", line 91, in __init__
    asdf_file = AsdfFile()
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/asdf.py", line 137, in __init__
    self.tree = {}
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/asdf.py", line 395, in tree
    self._validate(asdf_object, custom=bool(tree))
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/asdf.py", line 419, in _validate
    tree, self)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/yamlutil.py", line 229, in walker
    tag = ctx.type_index.from_custom_type(type(node), ctx.version_string)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/type_index.py", line 255, in from_custom_type
    write_type_index = _AsdfWriteTypeIndex(version, self)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/type_index.py", line 63, in __init__
    self._version))
ValueError: Don't know how to write out ASDF version 1.3.0

----------------------------------------------------------------------
Traceback (most recent call last):
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/versioning.py", line 52, in get_version_map
    with generic_io.get_file(version_map_path, 'r') as fd:
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/generic_io.py", line 1198, in get_file
    fd = open(realpath, realmode)
FileNotFoundError: [Errno 2] No such file or directory: '/envs/jwst_env/lib/python3.6/site-packages/asdf/schemas/stsci.edu/asdf/version_map-1.3.0.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/type_index.py", line 57, in __init__
    version_map = get_version_map(self._version)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/versioning.py", line 57, in get_version_map
    "Could not load version map for version {0}".format(version))
ValueError: Could not load version map for version 1.3.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/EGG-INFO/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/stpipe/cmdline.py", line 297, in step_from_cmdline
    step.run(*positional)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/stpipe/step.py", line 394, in run
    step_result = self.process(*args)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/pipeline/calwebb_detector1.py", line 67, in process
    input = datamodels.RampModel(input)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/datamodels/ramp.py", line 38, in __init__
    super(RampModel, self).__init__(init=init, **kwargs)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/jwst-0.13.7-py3.6.egg/jwst/datamodels/model_base.py", line 91, in __init__
    asdf_file = AsdfFile()
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/asdf.py", line 137, in __init__
    self.tree = {}
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/asdf.py", line 395, in tree
    self._validate(asdf_object, custom=bool(tree))
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/asdf.py", line 419, in _validate
    tree, self)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/yamlutil.py", line 234, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(tree, walker)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/treeutil.py", line 206, in walk_and_modify
    return recurse(top)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/treeutil.py", line 158, in recurse
    result = callback(result)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/yamlutil.py", line 229, in walker
    tag = ctx.type_index.from_custom_type(type(node), ctx.version_string)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/type_index.py", line 255, in from_custom_type
    write_type_index = _AsdfWriteTypeIndex(version, self)
  File "//anaconda3/envs/jwst_env/lib/python3.6/site-packages/asdf/type_index.py", line 63, in __init__
    self._version))
ValueError: Don't know how to write out ASDF version 1.3.0

```

**Comment by skendrew** [comment]
Asdf version:
```
(jwst_env) Sarahs-MacBook-Pro-3:miri-lrs-notebooks kendrew$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import asdf
>>> asdf.__version__
'2.4.0.dev58+g96f5e34'
>>> 

```
Output of conda list:

```
(jwst_env) Sarahs-MacBook-Pro-3:miri-lrs-notebooks kendrew$ conda list
# packages in environment at //anaconda3/envs/jwst_env:
#
# Name                    Version                   Build  Channel
alembic                   1.1.0                    pypi_0    pypi
appnope                   0.1.0            py36hf537a9a_0  
asdf                      2.4.0.dev.dev58+g96f5e34          py36_3    http://ssb.stsci.edu/astroconda-dev
asn1crypto                0.24.0                   py36_0  
astropy                   4.0.0.dev13236+g15ce42165          py36_0    http://ssb.stsci.edu/astroconda-dev
async-generator           1.10                     pypi_0    pypi
atomicwrites              1.3.0                    py36_1  
attrs                     19.1.0                   py36_1  
backcall                  0.1.0                    py36_0  
beautifulsoup4            4.7.1                    py36_1  
blas                      1.0                         mkl  
bleach                    3.1.0                    pypi_0    pypi
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_0  
certipy                   0.1.3                    pypi_0    pypi
cffi                      1.12.3           py36hb5b8e2f_0  
cfitsio                   3.440                         5    http://ssb.stsci.edu/astroconda-dev
chardet                   3.0.4                    py36_1  
cloudpickle               1.1.1                      py_0  
crds                      7.3.3.dev18+g750e8f44          py36_4    http://ssb.stsci.edu/astroconda-dev
cryptography              2.7              py36ha12b0ac_0  
cycler                    0.10.0           py36hfc81398_0  
cython                    0.29.10          py36h0a44026_0  
cytoolz                   0.9.0.1          py36h1de35cc_1  
dask-core                 1.2.2                      py_0  
decorator                 4.4.0                    py36_1  
defusedxml                0.6.0                    pypi_0    pypi
drizzle                   1.13.dev0+ge4c567a          py36_2    http://ssb.stsci.edu/astroconda-dev
entrypoints               0.3                      pypi_0    pypi
filelock                  3.0.12                     py_0  
fitsverify                4.18                          6    http://ssb.stsci.edu/astroconda-dev
freetds                   1.00.9                        0    http://ssb.stsci.edu/astroconda-dev
freetype                  2.9.1                hb4e5f40_0  
gwcs                      0.10.1a.dev37+ge1e33fb          py36_2    http://ssb.stsci.edu/astroconda-dev
h5py                      2.9.0            py36h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py36_0  
imageio                   2.5.0                    py36_0  
importlib_metadata        0.17                     py36_1  
intel-openmp              2019.4                      233  
ipykernel                 5.1.2                    pypi_0    pypi
ipython                   7.5.0            py36h39e3cac_0  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.13.3                   py36_0  
jinja2                    2.10.1                   py36_0  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   he5867d9_2  
jplephem                  2.9.dev1+g48c99ce          py36_2    http://ssb.stsci.edu/astroconda-dev
json5                     0.8.5                    pypi_0    pypi
jsonschema                2.6.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            5.3.1                    pypi_0    pypi
jupyter-console           6.0.0                    pypi_0    pypi
jupyter-core              4.5.0                    pypi_0    pypi
jwst                      0.13.7                   pypi_0    pypi
kiwisolver                1.1.0            py36h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libtiff                   4.0.10               hcb84e12_2  
libxml2                   2.9.9                hab757c2_0  
libxslt                   1.1.33               h33a18ac_0  
llvm-openmp               4.0.1                hcfea43d_1  
lockfile                  0.12.2                   py36_0  
lxml                      4.3.3            py36hef8c89e_0  
mako                      1.1.0                    pypi_0    pypi
markupsafe                1.1.1            py36h1de35cc_0  
matplotlib                3.1.0            py36h54f8f79_0  
mistune                   0.8.4                    pypi_0    pypi
mkl                       2019.4                      233  
mkl-service               2.0.2            py36h1de35cc_0  
mkl_fft                   1.0.12           py36h5e564d8_0  
mkl_random                1.0.2            py36h27c97d8_0  
more-itertools            7.0.0                    py36_0  
mpmath                    1.1.0                    py36_0  
nbconvert                 5.6.0                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1  
networkx                  2.3                        py_0  
notebook                  6.0.1                    pypi_0    pypi
numpy                     1.16.4           py36hacdab7b_0  
numpy-base                1.16.4           py36h6575580_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py36_0  
openssl                   1.1.1c               h1de35cc_1  
packaging                 19.0                     py36_0  
pamela                    1.0.0                    pypi_0    pypi
pandas                    0.24.2           py36h0a44026_0  
pandocfilters             1.4.2                    pypi_0    pypi
parsley                   1.3                      py36_1    http://ssb.stsci.edu/astroconda-dev
parso                     0.4.0                      py_0  
pexpect                   4.7.0                    py36_0  
photutils                 0.6.dev339+g24732069          py36_0    http://ssb.stsci.edu/astroconda-dev
pickleshare               0.7.5                    py36_0  
pillow                    6.0.0            py36hb68e598_0  
pip                       19.1.1                   py36_0  
pluggy                    0.12.0                     py_0  
prometheus-client         0.7.1                    pypi_0    pypi
prompt_toolkit            2.0.9                    py36_0  
psutil                    5.6.2            py36h1de35cc_0  
ptyprocess                0.6.0                    py36_0  
py                        1.8.0                    py36_0  
pycparser                 2.19                     py36_0  
pygments                  2.4.2                      py_0  
pymssql                   2.1.3                    py36_1    http://ssb.stsci.edu/astroconda-dev
pyopenssl                 19.0.0                   py36_0  
pyparsing                 2.4.0                      py_0  
pyrsistent                0.15.4                   pypi_0    pypi
pysocks                   1.7.0                    py36_0  
pytest                    4.6.2                    py36_0  
pytest-arraydiff          0.3              py36h39e3cac_0  
pytest-astropy            0.5.0                    py36_0  
pytest-doctestplus        0.3.0                    py36_0  
pytest-openfiles          0.3.2                    py36_0  
pytest-remotedata         0.3.1                    py36_0  
python                    3.6.8                haf84260_0  
python-dateutil           2.8.0                    py36_0  
python-editor             1.0.4                    pypi_0    pypi
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py36h1d22016_1  
pyyaml                    5.1              py36h1de35cc_0  
pyzmq                     18.1.0                   pypi_0    pypi
qtconsole                 4.5.5                    pypi_0    pypi
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py36_0  
scikit-image              0.15.0           py36h0a44026_0  
scikit-learn              0.21.2           py36h27c97d8_0  
scipy                     1.2.1            py36h1410ff5_0  
semantic_version          2.6.0                    py36_0  
send2trash                1.5.0                    pypi_0    pypi
setuptools                41.0.1                   py36_0  
six                       1.12.0                   py36_0  
soupsieve                 1.8                      py36_0  
spherical-geometry        1.2.10.dev5+gf3c016b          py36_1    http://ssb.stsci.edu/astroconda-dev
sqlalchemy                1.3.8                    pypi_0    pypi
sqlite                    3.28.0               ha441bb4_0  
stsci.image               2.3.1.dev0+g642799f          py36_3    http://ssb.stsci.edu/astroconda-dev
stsci.imagestats          1.6.2.dev0+gd7fc9fe          py36_1    http://ssb.stsci.edu/astroconda-dev
stsci.stimage             0.2.2.dev0+g7049ddca          py36_1    http://ssb.stsci.edu/astroconda-dev
stsci.tools               3.5.2rc1.dev6+gb926e11          py36_1    http://ssb.stsci.edu/astroconda-dev
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0  
toolz                     0.9.0                    py36_0  
tornado                   6.0.3                    pypi_0    pypi
traitlets                 4.3.2            py36h65bd3ce_0  
unixodbc                  2.3.7                h1de35cc_0  
urllib3                   1.24.2                   py36_0  
verhawk                   0.0.3.dev0+g4f4a60c          py36_1    http://ssb.stsci.edu/astroconda-dev
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.4                   py36_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zipp                      0.5.1                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  

```

Conda version is 4.7.10. It's installed in /anaconda3, I did nothing during the installation (just last week) other than accept the defaults, as this had always worked well in the past.
