### ISSUE TITLE
BUG: strun --version is broken

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#4467]
Would be convenient to have a `strun --version` command to quickly tell what `jwst` version that command is tied to.

**Comment by jdavies-st** [comment]
There is one currently, but it is broken.
```
$ strun --version
Traceback (most recent call last):
  File "/Users/jdavies/miniconda3/envs/jwst/bin/strun", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/jdavies/dev/jwst/scripts/strun", line 22, in <module>
    sys.stdout.write("%s\n" % stpipe.__version__)
AttributeError: module 'jwst.stpipe' has no attribute '__version__'
```
This will be an easy fix.
