### ISSUE TITLE
Error when using asdf file to run the stage 1 pipeline.

### ISSUE THREAD

**Issue by talensgj** [spacetelescope/jwst#4472]
I've recently installed the pipeline and am trying to run Stage 1 on simulated NIRISS SOSS data. Some of these simulations do not have noise in them, and so I need to disable some of the steps. In order to do this I created an .asdf file as described in the documentation by running:

`strun jwst.pipeline.Detector1Pipeline myfile.fits --save-parameters mystage1.asdf`

However when I try to use this file (unedited) to run the stage 1 pipeline by running:

`strun mystage1.asdf myfile.fits`

It produces the following error message:

```Traceback (most recent call last):
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/lib/python3.6/site-packages/jwst/stpipe/cmdline.py", line 275, in just_the_step_from_cmdline
    config, name=name, config_file=config_file)
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/lib/python3.6/site-packages/jwst/stpipe/step.py", line 232, in from_config_section
    config, spec, root_dir=dirname(config_file or ''))
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/lib/python3.6/site-packages/jwst/stpipe/config_parser.py", line 390, in validate
    raise ValidationError('\n'.join(messages))
jwst.stpipe.config_parser.ValidationError: Extra value 'dark_current' in root

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/lib/python3.6/site-packages/jwst/stpipe/step.py", line 155, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/lib/python3.6/site-packages/jwst/stpipe/cmdline.py", line 330, in step_from_cmdline
    just_the_step_from_cmdline(args, cls)
  File "/lustre03/project/6046302/software/2017/Core/miniconda3/4.3.27/envs/jwstpipe/lib/python3.6/site-packages/jwst/stpipe/cmdline.py", line 280, in just_the_step_from_cmdline
    raise ValueError(str(e))
ValueError: Extra value 'dark_current' in root
```

I'm running version 14.2 of the pipeline and have verified that this issue occurs on 3 different systems. I've attached the relevant .asdf file (renamed as .txt because github refused .asdf).

[mystage1.txt](https://github.com/spacetelescope/jwst/files/4099610/mystage1.txt)

**Comment by hbushouse** [comment]
Duplicated by #4477

**Comment by stscieisenhamer** [comment]
This issue has been resolved and is available from the master branch. See the README for instructions on installing. If there are any further questions/issues, you can add commentary here or open up a new issue.
