### ISSUE TITLE
Tweakreg error when input is association

### ISSUE THREAD

**Issue by smarandeshmukh** [spacetelescope/jwst#4601]
I am getting the following error when running tweakreg. I input an association file which has 4 dithered images. Essentially the problem seems to arise because of the ModelContainer expects a list of lists while it recieves an ordered dictionary instead. The problem persists from running the same command from within python.

Pipeline version 14.2

> strun jwst.tweakreg.TweakRegStep ../associations/l2_asn_dit.json --output_dir=../stage3/
2020-02-21 15:12:00,725 - stpipe.TweakRegStep - INFO - TweakRegStep instance created.
2020-02-21 15:12:00,776 - stpipe.TweakRegStep - INFO - Step TweakRegStep running with args ('../associations/l2_asn_dit.json',).
2020-02-21 15:12:00,777 - stpipe.TweakRegStep - INFO - Step TweakRegStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '../stage3/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '../associations', 'save_catalogs': False, 'catalog_format': 'ecsv', 'kernel_fwhm': 2.5, 'snr_threshold': 10.0, 'brightest': 100, 'peakmax': None, 'enforce_user_order': False, 'expand_refcat': False, 'minobj': 15, 'searchrad': 1.0, 'use2dhist': True, 'separation': 0.5, 'tolerance': 1.0, 'xoffset': 0.0, 'yoffset': 0.0, 'fitgeometry': 'general', 'nclip': 3, 'sigma': 3.0}
2020-02-21 15:12:02,350 - stpipe.TweakRegStep - INFO - Detected 28 sources in det_image_seq1_MIRIMAGE_F560Wexp01_cal.fits.
2020-02-21 15:12:03,857 - stpipe.TweakRegStep - INFO - Detected 32 sources in det_image_seq1_MIRIMAGE_F560Wexp02_cal.fits.
2020-02-21 15:12:04,822 - stpipe.TweakRegStep - INFO - Detected 43 sources in det_image_seq1_MIRIMAGE_F560Wexp03_cal.fits.
2020-02-21 15:12:05,823 - stpipe.TweakRegStep - INFO - Detected 35 sources in det_image_seq1_MIRIMAGE_F560Wexp04_cal.fits.
2020-02-21 15:12:05,825 - stpipe.TweakRegStep - INFO - 
2020-02-21 15:12:05,825 - stpipe.TweakRegStep - INFO - Number of image groups to be aligned: 1.
2020-02-21 15:12:05,825 - stpipe.TweakRegStep - INFO - Image groups:
2020-02-21 15:12:05,825 - stpipe.TweakRegStep - INFO - * Images in GROUP 1:
ERROR RUNNING STEP 'TweakRegStep':
    'odict_values' object does not support indexing

> Traceback (most recent call last):
  File "/net/texel/data/users/deshmukh/jwst142/jwst/stpipe/cmdline.py", line 338, in step_from_cmdline
    step.run(*positional)
  File "/net/texel/data/users/deshmukh/jwst142/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/net/texel/data/users/deshmukh/jwst142/jwst/tweakreg/tweakreg_step.py", line 134, in process
    for im in grp_img[0]:
TypeError: 'odict_values' object does not support indexing

> Traceback (most recent call last):
  File "/net/texel/data/users/deshmukh/jwst142/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/net/texel/data/users/deshmukh/jwst142/jwst/stpipe/step.py", line 155, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/net/texel/data/users/deshmukh/jwst142/jwst/stpipe/cmdline.py", line 338, in step_from_cmdline
    step.run(*positional)
  File "/net/texel/data/users/deshmukh/jwst142/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/net/texel/data/users/deshmukh/jwst142/jwst/tweakreg/tweakreg_step.py", line 134, in process
    for im in grp_img[0]:
TypeError: 'odict_values' object does not support indexing

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2079](https://jira.stsci.edu/browse/JP-2079)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2079?focusedCommentId=527002#comment-527002):_

Fixed by #6022
