### ISSUE TITLE
Outlier detection fails when grow=0

### ISSUE THREAD

**Issue by chriswillott** [spacetelescope/jwst#4628]
The outlier detection step fails with the following error when the grow parameter is set to zero:
```
ERROR RUNNING STEP 'Image3Pipeline':
    filter weights array has incorrect shape.
Traceback (most recent call last):
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 338, in step_from_cmdline
    step.run(*positional)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.py", line 76, in process
    input_models = self.outlier_detection(input_models)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
    step_result = self.process(*args)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/outlier_detection/outlier_detection_step.py", line 166, in process
    step.do_detection()
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/outlier_detection/outlier_detection.py", line 247, in do_detection
    self.detect_outliers(blot_models)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/outlier_detection/outlier_detection.py", line 349, in detect_outliers
    flag_cr(image, blot, **self.outlierpars)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/jwst/outlier_detection/outlier_detection.py", line 457, in flag_cr
    ndimage.convolve(cr_mask, cr_grow_kernel, output=cr_grow_kernel_conv)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/scipy/ndimage/filters.py", line 755, in convolve
    origin, True)
  File "/home/cjw/miniconda3/envs/jwstdp0p14p2/lib/python3.7/site-packages/scipy/ndimage/filters.py", line 605, in _correlate_or_convolve
    raise RuntimeError('filter weights array has incorrect shape.')
RuntimeError: filter weights array has incorrect shape.
```
The error occurs because in line 457 an attempt is made to convolve with the cr_grow_kernel but for grow=0 this is a zero shape array.
ndimage.convolve(cr_mask, cr_grow_kernel, output=cr_grow_kernel_conv)

The user should be free to set the grow parameter to zero if they don't need to exclude neighbouring pixels of outliers. The revised jumpstep by Mike Regan will flag cosmic ray neighbours as bad so one does not need to grow the outlier mask as well. This should be  configurable.

**Comment by hbushouse** [comment]
@mcara @stsci-hack I see that the outlier_detection step code still includes "grow" as a step param, but I can't find anywhere that it's actually used anymore in the lower-level functions. The only place that `ndimage.convolve()` is called anymore is here: https://github.com/spacetelescope/jwst/blob/master/jwst/outlier_detection/outlier_detection.py#L447 , which uses a hardwired 3x3 kernel to smooth a boolean mask array.  Has the use of "grow" in the way that caused the error reported here no longer there? Has it been removed?  If so, it should also be removed as a step param.

**Comment by hbushouse** [comment]
It appears that the code changes included in https://github.com/spacetelescope/jwst/pull/5822 (by @karllark ) removed the use of the grow parameter and by default just creates a 3x3 kernel to apply to the mask. However, the grow parameter was not removed from the list of step params or the documentation. We'll need to file a separate ticket to make those updates. But in the meantime I'm closing this ticket, because this error can't occur anymore.
