### ISSUE TITLE
NIRISS WFSS spec2 ASN's need to match direct image filters

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4841]
_Issue [JP-1411](https://jira.stsci.edu/browse/JP-1411) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

Test program jw00625 observation 30 is a NIRISS WFSS observation that obtains direct images in 3 different filters (F090W, F150W, F200W) and grism images (using both GR150C and GR150R grisms) also in each of those 3 filters. image2 and image3 ASN's are created correctly, resulting in combined i2d images and source catalogs (cat.ecsv) for each of the 3 filters used for the direct images. spec2 ASN's for the grism exposures, however, all list the F090W i2d product as the "direct_image" member and the F090W source catalog as the "sourcecat" member. This results in grism exposures that used the F150W and F200W filter using the F090W direct image information during calwebb_spec2 processing.

This may be due to the fact that the current ASN rules for WFSS observations are setup to always reference the first set of direct images contained in the observation (in this case the F090W images), rather than trying to match up the filters used in a given grism exposure with a direct image using the same filter. It would be best to match up filters for the grism and direct images, when a match is available.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=460126#comment-460126):_

Updated info from [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey):

"The grism exposures don't really care what filter the direct image or source catalog were taken in. The grism exposure WCS is setup to apply the distortion from the filter that was used in the grism exposure itself (not the direct image), so the WCS for the grism exposures is OK."

So technically having the F090W image and source catalog listed in all of the spec2 ASN files will not cause any processing issues. The only downside is that a more optimal set of sources may be available once we're able to create and use "uber" images and their catalog.

So I think the only remaining issue for this observation right now is to investigate why none of the spec3 products were created. The spec2 products have been copied into the test data directory mentioned above, so that spec3 processing can be tested.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=460131#comment-460131):_

As [Megan Sosey](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sosey) says, the ideal case is the uber image. Since that is not available yet, the current choice is to pick the "first" images found by the generator, where "first" is more "random" depending on order of observations, etc.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=460143#comment-460143):_

The lack of grism level-3 products has been traced to an error that occurs during calwebb_spec3 processing for all 3 grism ASN's in this observation, which is a schema validation problem. The input cal files included in the spec3 ASN's all have a SCATFILE keyword value of something like "/ifs/archive/test/jwst/store/rspencer/tests/nOPS6/dtest1/JWSTDP-2019.3.0-50~c909c7b1/2019-11-22-035812/sdp/asn_creation/cal/level2/jw00625-o030_t006_niriss_clear-f090w_cat.ecsv", all of which result in a schema validation error when the exp_to_source function tries to save the reorganized cal files that it creates:
```java
Traceback (most recent call last):
  File "/Users/bushouse/JWST/softw/jwst/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 156, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_spec3.py", line 167, in process
    self.save_model(result, 'cal')
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 862, in save_model
    output_path = model.save(
  File "/Users/bushouse/JWST/softw/jwst/jwst/datamodels/source_container.py", line 60, in save
    save_model_func(self._multiexposure, output_file=path)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 874, in save_model
    output_path = model.save(
  File "/Users/bushouse/JWST/softw/jwst/jwst/datamodels/model_base.py", line 520, in save
    self.to_fits(output_path, *args, **kwargs)
  File "/Users/bushouse/JWST/softw/jwst/jwst/datamodels/model_base.py", line 631, in to_fits
    with fits_support.to_fits(self._instance, self._schema) as ff:
  File "/Users/bushouse/JWST/softw/jwst/jwst/datamodels/fits_support.py", line 386, in to_fits
    _save_from_schema(hdulist, tree, schema)
  File "/Users/bushouse/JWST/softw/jwst/jwst/datamodels/fits_support.py", line 340, in _save_from_schema
    validator.validate(tree, _schema=schema)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.8/site-packages/jsonschema/validators.py", line 353, in validate
    raise error
jsonschema.exceptions.ValidationError: {'filename': '/ifs/archive/test/jwst/store/rspencer/tests/nOPS6/dtest1/JWSTDP-2019.3.0-50~c909c7b1/2019-11-22-035812/sdp/asn_creation/cal/level2/jw00625-o030_t006_niriss_clear-f090w_cat.ecsv'} is not of type 'string'


Failed validating 'type' in schema['properties']['meta']['properties']['source_catalog']:
    OrderedDict([('title', 'Source catalog filename'),
                 ('type', 'string'),
                 ('fits_keyword', 'SCATFILE')])


On instance['meta']['source_catalog']:
    {'filename': '/ifs/archive/test/jwst/store/rspencer/tests/nOPS6/dtest1/JWSTDP-2019.3.0-50~c909c7b1/2019-11-22-035812/sdp/asn_creation/cal/level2/jw00625-o030_t006_niriss_clear-f090w_cat.ecsv'}
```
The keyword is defined as type "string", which is the case for these values, so my only guess is that the path is so ridiculously long that it fails (for some reason) to validate as type string.

Example data files are in the ██████████████████████████████████████████████ directory. Test can be performed using the command:
```java
strun calwebb_spec3.cfg jw00625-o030_20200304t043757_spec3_002_asn.json```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=460149#comment-460149):_

Keep in mind that these example data files came from B7.4 processing (not B7.4.2), so we may have already implemented something that trims the path from the SCATFILE value before serializing our products.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=460174#comment-460174):_

Possibly related PR 4597 and 4627

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=461560#comment-461560):_

#4597 included a fix that trims the directory path from the catalog file name loaded from the ASN before saving in the SCATFILE keyword. That PR was included in B7.4.2. The issue above happened when running B7.4. Hence this should now be fixed and ready for retest.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=461561#comment-461561):_

Previously fixed by #4597

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=463043#comment-463043):_

I am looking at the processed data we got from Build 7.4.2 run and still don't see the level 3 spec product. This data is in ████████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=463265#comment-463265):_

You're right [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz). PR #&#x2060;4597 updated the source_catalog step used for imaging data to trim the path from the source catalog file name before storing it in a keyword. But this particular problem is the source catalog file name used for calspec2 processing of grism exposures, the storing of which did not yet get fixed. JP-1444 has been filed to get this fixed in our next release candidate for B7.5.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1411?focusedCommentId=463267#comment-463267):_

The issue related to direct image filters has been resolved (wasn't a problem to begin with). So closing this ticket again. The separate issue that's preventing level 3 products from being created is now tracked in JP-1444.
