### ISSUE TITLE
source_catalog crashing on MIRI image

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4947]
_Issue [JP-1454](https://jira.stsci.edu/browse/JP-1454) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The calwebb_image3 source_catalog step is crashing on MIRI imaging data in the DMS mt1-OTB test suite with:
```java
2020-05-13 02:15:11,783 - stpipe.Image3Pipeline.source_catalog - INFO - Using ABVEGAOFFSET reference file /ifs/archive/test/jwst/ref/tmp_crds/cache/references/jwst/miri/jwst_miri_abvegaoffset_0001.asdf
2020-05-13 02:15:11,784 - stpipe.Image3Pipeline.source_catalog - INFO - Instrument: MIRI
2020-05-13 02:15:11,784 - stpipe.Image3Pipeline.source_catalog - INFO - Detector: MIRIMAGE
2020-05-13 02:15:11,784 - stpipe.Image3Pipeline.source_catalog - INFO - Filter: F1130W
2020-05-13 02:15:11,784 - stpipe.Image3Pipeline.source_catalog - INFO - Subarray: BRIGHTSKY
2020-05-13 02:15:12,061 - stpipe.Image3Pipeline.source_catalog - INFO - Detected 8 sources
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.py", line 111, in process
    self.source_catalog(result)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/source_catalog/source_catalog_step.py", line 97, in process
    aperture_params=refdata.aperture_params,
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/astropy/utils/decorators.py", line 758, in __get__
    val = self.fget(obj)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/source_catalog/source_catalog.py", line 184, in aperture_params
    row = self._get_ee_table_row(aper_ee)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/source_catalog/source_catalog.py", line 153, in _get_ee_table_row
    self.apcorr_filename))
RuntimeError: Aperture encircled energy value of 30 appears to be invalid. No matching row was found in the APCORR reference file /ifs/archive/test/jwst/ref/tmp_crds/cache/references/jwst/miri/jwst_miri_apcorr_0001.fits
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    Aperture encircled energy value of 30 appears to be invalid. No
    matching row was found in the APCORR reference file /ifs/archive/t
    est/jwst/ref/tmp_crds/cache/references/jwst/miri/jwst_miri_apcorr_
    0001.fits
----------------------------------------------------------------------
```
Might be related to garbage input data?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463965#comment-463965):_

The image3 ASN consists of a single BRIGHTOBJ subarray exposure. Data have been copied to the location listed above.

**Comment by stscijgbot-jp** [comment]
_Comment by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463977#comment-463977):_

I started poking around with this, and one thing that jumps out is that for the APCORR file used in this case, "jwst_miri_apcorr_0001", there doesn't appear to be a corresponding row for the BRIGHTSKY subarray name

**Comment by stscijgbot-jp** [comment]
_Comment by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463978#comment-463978):_

available subarrays in the reference file: ['BRIGHT' 'FULL' 'SUB128' 'SUB256' 'SUB64']

**Comment by stscijgbot-jp** [comment]
_Comment by [James White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jwhite) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463985#comment-463985):_

The reason that you're seeing an error about the encircled energy value is that there's no check on the length of the table (or rows) until the code attempts to select a particular row based on the encircled energy value, and in this case it was dealing with an empty table from the start

**Comment by stscijgbot-jp** [comment]
_Comment by [Larry Bradley](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lbradley) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463988#comment-463988):_

Sounds like the MIRI APCORR reference files need to be fixed.  Do you want to also add a workaround/fallback to source_catalog for the case where the APCORR table is empty (because of invalid selectors, etc.)?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463992#comment-463992):_

There is no BRIGHT subarray currently for MIRI.  I assume BRIGHT == BRIGHTSKY?  Can we use that row?

<https://jwst-docs.stsci.edu/mid-infrared-instrument/miri-instrumentation/miri-detector-overview/miri-detector-subarrays#MIRIDetectorSubarrays-Imaging>

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463994#comment-463994):_

[Larry Bradley](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lbradley) a workaround for the "no matching row" case would be good, but I feel that instead of it going ahead and doing photometry without any aperture correction applied, it should instead just shutdown (cleanly) with an informative error message. Unless you think there's any useful photometry that can be done without the aperture correction.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=463996#comment-463996):_

[Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) we've run into an error in the DMS test suites for B7.5 when trying to run a MIRI SUBARRAY='BRIGHTSKY' observation through the calwebb_image3 source_catalog step. It appears that the problem is due to the fact that there's no row in the APCORR ref file with a matching subarray name. The closest match has "BRIGHT". We're assuming this is just an error in the ref file creation? Can the MIRI team fix and redeliver?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464047#comment-464047):_

Here's another source_catalog error, which does not appear to be in any way connected to the MIRI ref file problem, but I don't feel like creating yet another ticket for source_catalog! ;)

Processing NIRCam data led to the following traceback in one case:
```java
2020-05-14 11:31:33,516 - stpipe.Image3Pipeline.source_catalog - INFO - Detected 1 sources
2020-05-14 11:31:33,597 - stpipe.Image3Pipeline.source_catalog - INFO - AB to Vega magnitude offset 2.49018
2020-05-14 11:31:33,649 - stpipe.Image3Pipeline.source_catalog - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jsonschema/validators.py:320: ResourceWarning: unclosed file <_io.BufferedReader name='/ifs/archive/test/jwst/ref/tmp_crds/cache/references/jwst/nircam/jwst_nircam_abvegaoffset_0001.asdf'>
  validators = iteritems(_schema)


2020-05-14 11:31:33,677 - stpipe.Image3Pipeline.source_catalog - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/astropy/io/fits/card.py:1003: VerifyWarning: Card is too long, comment will be truncated.
  VerifyWarning)


2020-05-14 11:31:33,680 - stpipe.Image3Pipeline.source_catalog - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/astropy/wcs/wcs.py:687: FITSFixedWarning: 'datfix' made the change 'Set DATE-BEG to '2017-09-20T19:10:52.416' from MJD-BEG.
Set DATE-AVG to '2017-09-20T19:11:13.889' from MJD-AVG.
Set DATE-END to '2017-09-20T19:11:35.363' from MJD-END'.
  FITSFixedWarning)


Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.py", line 111, in process
    self.source_catalog(result)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/source_catalog/source_catalog_step.py", line 99, in process
    catalog = catobj.catalog
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/astropy/utils/decorators.py", line 758, in __get__
    val = self.fget(obj)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/source_catalog/source_catalog.py", line 1297, in catalog
    catalog[colname] = getattr(self, column)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/astropy/utils/decorators.py", line 758, in __get__
    val = self.fget(obj)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/source_catalog/source_catalog.py", line 1147, in nn_abmag
    nn_abmag = self.aper_total_abmag[self._ckdtree_query[1]]
IndexError: index 1 is out of bounds for axis 0 with size 1
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    index 1 is out of bounds for axis 0 with size 1
----------------------------------------------------------------------
```
I'll copy example data to the same directory. The image3 ASN consists of a single NIRCam NRCBLONG image.

**Comment by stscijgbot-jp** [comment]
_Comment by [Larry Bradley](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lbradley) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464048#comment-464048):_

Howard, the error above looks like the nearest-neighbor issue with only one detected source, which was fixed.  Was the above run after that fix was merged?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464054#comment-464054):_

No, all of these runs are still using our 0.16.0 delivery from May 4, so they don't yet include any fixes done in the past week or so. We're hoping to make a 0.16.1 delivery around the beginning of next week (5/18) that will include all of these fixes. Then we'll restart all the testing again.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464056#comment-464056):_

In the meantime it would be good for someone to rerun calwebb_image3 on this dataset using our latest master and see if in fact it has been fixed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Larry Bradley](https://jira.stsci.edu/secure/ViewProfile.jspa?name=lbradley) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464059#comment-464059):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) :  Indeed, the last bug you reported is already fixed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464061#comment-464061):_

(y)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464062#comment-464062):_

Thanks [Tea Temim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ttemim) for the updated ref file. Is that also being delivered to CRDS?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tea Temim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ttemim) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464066#comment-464066):_

Hi [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse), Yes, the file will be delivered to CRDS. Thanks.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464075#comment-464075):_

Fixed in #4948 by adding a check and warning for missing ref file data. Ultimate solution is of course the updated MIRI ref file with correct subarray names (but that's a CRDS issue).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464076#comment-464076):_

I've confirmed that the pipeline now works properly with the updated ref file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tea Temim](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ttemim) on [JIRA](https://jira.stsci.edu/browse/JP-1454?focusedCommentId=464079#comment-464079):_

Great! Thank you [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse)!
