### ISSUE TITLE
wfs_combine error "list index out of range"

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#4962]
_Issue [JP-1463](https://jira.stsci.edu/browse/JP-1463) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The wfs_combine step is failing when processing a wfs-image3 ASN containing 2 NIRCam science exposures and 2 targ-acqs. Traceback is:
```java
2020-05-17 01:47:54,251 - stpipe.WfsCombine - INFO - Using input table: /ifs/archive/test/jwst/store/doggett/tests/complete_long_05/dtest2/JWSTDP-2020.2.0-60~9e61bebe/2020-05-16-212724/sdp/asn_creation/cal/level3/jw00632-o003_20200516t214154_wfs-image3_004_asn.json
2020-05-17 01:47:54,251 - stpipe.WfsCombine - INFO - The number of pairs of input files: 1
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.0.20200507-py37/lib/python3.7/site-packages/jwst/wfs_combine/wfs_combine_step.py", line 39, in process
    infile_2 = science_members[1]['expname']
IndexError: list index out of range
----------------------------------------------------------------------
ERROR RUNNING STEP 'WfsCombineStep':
    list index out of range
----------------------------------------------------------------------
```
Error sounds familiar from previous instances, which could not be reproduced using manual test runs.

**Comment by dmggh** [comment]
I can't access the input table :
/ifs/archive/test/jwst/store/doggett/tests/complete_long_05/dtest2/JWSTDP-2020.2.0-60~9e61bebe/2020-05-16-212724/sdp/asn_creation/cal/level3/jw00632-o003_20200516t214154_wfs-image3_004_asn.json

Yes, we've seen this before, back in November 2019 for jw00632-o003_20191102t153056_wfs-image3_005_asn.json, and at the time I could not get that case to fail.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1463?focusedCommentId=464684#comment-464684):_

The data have been copied to ███████████████████████████████████████████ as noted in the "Data Location" field above. There are notes associated with this processing run indicating that there were some configuration problems that allowed test instances from the D-1 string to show up on the D-2 string, where D-1 is still running B7.4. So this may be a red herring, in that it's an old error due to old code. Can't hurt to at least run it once manually using B7.5 to verify whether it runs for us or not.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1463?focusedCommentId=464716#comment-464716):_

[Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) reports:

"There was a missing OSF entry (wfscFile) for that program/obs that messes up our association counting, and we end up sending the association on for Level2b/3 processing MULTIPLE times in the same test run, and they can clobber each other and cause odd results.  If the failure you are talking about is for that specific program/obs (632:3), I would ignore it for now, and since we have the OSF patch in place on Dstring2, we should see that effect clear up in the rc1 re-run."

So we can ignore this, at least for now.
