### ISSUE TITLE
Error in calwebb_spec3 extract_1d step for NIRISS WFSS data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5004]
_Issue [JP-1481](https://jira.stsci.edu/browse/JP-1481) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The calwebb_spec3 pipeline is crashing at the start of the next iteration of the extract_1d step after successfully processing 279 slits/sources in a NIRISS WFSS observation. Traceback is:
```java
2020-05-29 12:41:33,377 - stpipe.Spec3Pipeline.combine_1d - INFO - Saved model in jw00650-o002_s00279_niriss_f150w-gr150c-gr150r_c1d.fits
2020-05-29 12:41:33,378 - stpipe.Spec3Pipeline.combine_1d - INFO - Step combine_1d done
2020-05-29 12:41:41,297 - stpipe.Spec3Pipeline - INFO - Saved model in jw00650-o002_s00001_niriss_f150w-gr150c-gr150r_cal.fits
2020-05-29 12:41:48,782 - stpipe.Spec3Pipeline.extract_1d - INFO - Step extract_1d running with args (<SourceModelContainer>,).
2020-05-29 12:41:48,783 - stpipe.Spec3Pipeline.extract_1d - INFO - Step extract_1d parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': 'x1d', 'search_output_file': True, 'input_dir': '/ifs/archive/test/jwst/store/rspencer/tests/sk21d/dtest2/JWSTDP-2020.2.0-70~42b495de/2020-05-29-074408/sdp/asn_creation/cal/level3', 'smoothing_length': None, 'bkg_order': None, 'log_increment': 50, 'subtract_background': None, 'apply_nod_offset': None}
2020-05-29 12:41:48,786 - stpipe.Spec3Pipeline.extract_1d - INFO - No EXTRACT1D reference file will be used
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_spec3.py", line 213, in process
    result = self.extract_1d(result)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/extract_1d/extract_1d_step.py", line 190, in process
    was_source_model=was_source_model)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/extract_1d/extract.py", line 2584, in run_extract1d
    apply_nod_offset, was_source_model)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/extract_1d/extract.py", line 2696, in do_extract1d
    input_temp = input_model[0]
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/model_base.py", line 771, in __getitem__
    assert isinstance(key, str)
AssertionError
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':


----------------------------------------------------------------------
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1481?focusedCommentId=469862#comment-469862):_

Fixed by #5076
