### ISSUE TITLE
extract_2d crash when no grism spectra to extract

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5039]
_Issue [JP-1507](https://jira.stsci.edu/browse/JP-1507) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The calwebb_spec2 pipeline crashed in the extract_2d step when processing a NIRISS WFSS exposure with the following traceback:
```java
2020-06-11 19:15:04,784 - stpipe.Spec2Pipeline.extract_2d - INFO - EXP_TYPE is NIS_WFSS
2020-06-11 19:15:04,784 - stpipe.Spec2Pipeline.extract_2d - INFO - Extracting objects < abmag = 99.0
2020-06-11 19:15:04,784 - stpipe.Spec2Pipeline.extract_2d - INFO - Getting objects from /ifs/int/jwst/info/jwowlmgr/build7.4/paths/sdp/asn_creation/cal/level2/jw99512-o005_t001_niriss_clear-f150w_cat.ecsv
2020-06-11 19:15:04,860 - stpipe.Spec2Pipeline.extract_2d - INFO - Using default order extraction from reference file
2020-06-11 19:15:04,875 - stpipe.Spec2Pipeline.extract_2d - INFO - Excluding off-image object: 1, order 1
2020-06-11 19:15:04,888 - stpipe.Spec2Pipeline.extract_2d - INFO - Partial order on detector for obj: 2 order: 1
2020-06-11 19:15:04,889 - stpipe.Spec2Pipeline.extract_2d - INFO - Grism object list created from source catalog: /ifs/int/jwst/info/jwowlmgr/build7.4/paths/sdp/asn_creation/cal/level2/jw99512-o005_t001_niriss_clear-f150w_cat.ecsv
2020-06-11 19:15:04,889 - stpipe.Spec2Pipeline.extract_2d - INFO - Extracting grism objects into MultiSlitModel
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_spec2.py", line 95, in process
asn.filename
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_spec2.py", line 237, in process_exposure_product
input = self.extract_2d(input)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/extract_2d/extract_2d_step.py", line 38, in process
extract_height=self.extract_height)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/extract_2d/extract_2d.py", line 78, in extract2d
mmag_extract=99.)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/extract_2d/grisms.py", line 488, in extract_grism_objects
del subwcs
UnboundLocalError: local variable 'subwcs' referenced before assignment
```
A quick look suggest that the object "subwcs" is created within a loop over spectra to extract, but is deleted outside the end of the loop. Hence if there aren't any spectra to extract, it never gets created in the first place and then the delete fails.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1507?focusedCommentId=470212#comment-470212):_

Fixed by #5093
