### ISSUE TITLE
Crash in skymatch step for MIRI images

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5077]
_Issue [JP-1538](https://jira.stsci.edu/browse/JP-1538) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The calwebb_spec3 pipeline crashed in the skymatch step when processing an association of MIRI images:
```java
2020-06-11 21:12:25,769 - stpipe.Image3Pipeline.skymatch - INFO - * Image ID=jw00212001001_03106_00001_mirimage_cal.fits. Sky background: 1.24523
2020-06-11 21:12:25,769 - stpipe.Image3Pipeline.skymatch - WARNING - * Image ID=jw00212001001_02101_00001_mirimage_cal.fits: Unable to compute sky value
2020-06-11 21:12:25,769 - stpipe.Image3Pipeline.skymatch - INFO - * Image ID=jw00212001001_02101_00001_mirimage_cal.fits. Sky background: 0
2020-06-11 21:12:25,769 - stpipe.Image3Pipeline.skymatch - INFO -
2020-06-11 21:12:25,769 - stpipe.Image3Pipeline.skymatch - INFO - ---- Computing "global" sky - smallest sky value across *all* input images.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
'>' not supported between instances of 'float' and 'NoneType'
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 338, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.py", line 73, in process
input_models = self.skymatch(input_models)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/skymatch/skymatch_step.py", line 97, in process
subtract=self.subtract)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/skymatch/skymatch.py", line 358, in match
if do_global and (minsky is None or sky < minsky):
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
Highly likely to be the result (as usual) of garbage data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-1538?focusedCommentId=474123#comment-474123):_

Although not MIRI, we saw the same kind of failure for an FGS association of images at the PROPOSAL level for fileset [w00621-a3001_20200617t123508_image3_001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw00621-a3001_20200617t123508_image3_001_1594764145.464342) during the GSEG3 Run for Record.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1538?focusedCommentId=477354#comment-477354):_

Using the B7.6 development version of the Cal pipeline the failure no longer occurs for jw00212-o001_20200611t170030_image3_001_asn.json, which contains 2 MIRI images.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1538?focusedCommentId=477355#comment-477355):_

The original traceback provided in <https://jtar.stsci.edu/browse/JWSTDMSDR-5687> suggests that the real problem may have been caused by the fact that a target_acq image listed in the input image3 ASN file was incorrectly included in the processing. The issue of only loading science members from the ASN has also been fixed, so now only the 2 science images are processed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1538?focusedCommentId=477567#comment-477567):_

JP-1541 will take care of issues due to images with large range of coord values.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1538?focusedCommentId=479295#comment-479295):_

Closing this ticket, because the problem in `skymatch` has been fixed. The remaining problem with processing the FGS association is not due to `skymatch`, it's due to bad coords in the input files. That issue will be addressed by JP-1541.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1538?focusedCommentId=480935#comment-480935):_

Closing this issue, based on comments above.
