### ISSUE TITLE
Investigate resample step crash on NIRISS image

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5078]
_Issue [JP-1539](https://jira.stsci.edu/browse/JP-1539) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The resample step crashed in the calwebb_image2 pipeline when working on a NIRISS image:
```java
2020-06-11 20:09:49,450 - CRDS - DEBUG - Reference type 'drizpars' defined as 'jwst_niriss_drizpars_0002.fits'
2020-06-11 20:09:49,451 - stpipe.Image2Pipeline.resample - INFO - Drizpars reference file: /ifs/int/jwstc/ref/crds/cache/references/jwst/niriss/jwst_niriss_drizpars_0002.fits
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
Invalid output frame shape: (0, 0)
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 338, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image2.py", line 67, in process
op.basename(asn.filename)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image2.py", line 158, in process_exposure_product
self.resample(input)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 391, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/resample/resample_step.py", line 70, in process
resamp = resample.ResampleData(input_models, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/resample/resample.py", line 55, in __init__
self.output_wcs = resample_utils.make_output_wcs(self.input_models)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.15.1.20200311-py37/lib/python3.7/site-packages/jwst/resample/resample_utils.py", line 53, in make_output_wcs
"{}".format(output_wcs.data_size))
ValueError: Invalid output frame shape: (0, 0)

```
Could be lack of appropriate pointing or other WCS-related meta data? Check the WCS meta info in the input rate product (and perhaps original uncal as well).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473238#comment-473238):_

The uncal and rate products have:

APERNAME='NRCALL_FULL'

PPS_APER='NRCALL_FULL'

The SIAF does not have detector reference pixel or pixel scale information for this aperture, so various WCS keywords like CRPIXn and CDELTn were set to default values of 0 and 1 by the level-1b set_telescope_pointing routine. This leads to the bad computation of output frames in the resample step.

I believe an original aperture value like 'NRCALL_FULL' is supposed to get translated by SDP during level-1b processing to set APERNAME to a detector-specific value, however this is a NIRISS exposure, so I'm sure the translation failed. There's no obvious indication in the uncal meta data that this is a parallel exposure, in fact EXPRIPAR='PRIME' and VISITYPE='PRIME_TARGETED_FIXED'. There is an indication from the proposer label in the APT: OBSLABEL='WFSS parallel NIRCAM obs SOR6_nOPS8-OTB-20200420' that suggests NIRCam may have been used in parallel (or vice versa) and hence may be the cause of the NIRCam aperture showing up in a NIRISS exposure.

This is obviously a problem somewhere in one of the front-end systems (or bad OSF content?) or something that level-1b processing has to figure out how to handle before the data get to the set_telescope_pointing stage (and the cal pipeline).

Alerting [Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) for his input on this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473278#comment-473278):_

The PPS_DB does show parallel NIRISS and NIRCAM pointings within this visit, e.g.,

POINT_SEQ EXPOSURE VISIT_FILE_SEQ POINTING_TYPE NUM_SCAS IMPLICIT
 TARGET_ORDER MOSAIC_TILE_ORDER EXP_SPEC_ORDER DITHER_POINT_IDX APERNAME
 APT_LABEL READOUT_PATT DMS_NOTE DURATION(secs)


1 1 1 SCIENCE 1 N
 1 1 1 1 NIS_CEN
 DIRECT_IMAGE NIS None 164
1 1 2 SCIENCE 10 N
 1 1 1 1 NRCALL_FULL
 SCIENCE SHALLOW2 None 145

2 1 1 SCIENCE 1 N
 1 1 2 1 NIS_CEN
 SCIENCE NIS None 164
2 1 2 SCIENCE 10 N
 1 1 2 1 NRCALL_FULL
 SCIENCE SHALLOW2 None 145

3 2 1 SCIENCE 1 N
 1 1 2 2 NIS_CEN
 SCIENCE NIS None 164
3 2 2 SCIENCE 10 N
 1 1 2 2 NRCALL_FULL
 SCIENCE SHALLOW2 None 114

4 3 1 SCIENCE 1 N
 1 1 2 3 NIS_CEN
 SCIENCE NIS None 164
4 3 2 SCIENCE 10 N
 1 1 2 3 NRCALL_FULL
 SCIENCE SHALLOW2 None 114

5 4 1 SCIENCE 1 N
 1 1 2 4 NIS_CEN
 SCIENCE NIS None 164
5 4 2 SCIENCE 10 N
 1 1 2 4 NRCALL_FULL
 SCIENCE SHALLOW2 None 114

6 1 1 SCIENCE 1 N
 1 1 3 1 NIS_CEN
 DIRECT_IMAGE NIS None 164
6 1 2 SCIENCE 10 N
 1 1 3 1 NRCALL_FULL
 SCIENCE SHALLOW2 None 145

7 2 1 SCIENCE 1 N
 1 1 3 2 NIS_CEN
 DIRECT_IMAGE NIS None 164
7 2 2 SCIENCE 10 N
 1 1 3 2 NRCALL_FULL
 SCIENCE SHALLOW2 None 114

8 1 1 SCIENCE 1 N
 1 1 4 1 NIS_CEN
 SCIENCE NIS None 164
8 1 2 SCIENCE 10 N
 1 1 4 1 NRCALL_FULL
 SCIENCE SHALLOW2 None 145

<snip>   48 total pointing pairs in the visit !!

 

SDP code should recognize when a NIRCam dataset is assigned APERNAME = NRCALL_FULL and substitute a detector-specific aperture.   We are in the process of trying to run this data now on Dstring2, so we will figure out if APERNAME mis-assignments are occurring during that run.  I suspect the parallelism is involved in the issue, but we will check it out once the Dstring2 run is available for analysis.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473291#comment-473291):_

Yes, I suspect that in the case of parallels all exposures get the aperture of the prime instrument, since that's where the telescope is pointed. So those will need changing in SDP to be instrument and detector-specific.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473345#comment-473345):_

[Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) How do you want to handle this ticket? Shall we transfer it to the JSDP project, close it and let you create a fresh JSDP ticket, or what?

**Comment by stscijgbot-jp** [comment]
_Comment by [Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473346#comment-473346):_

If you don't need any record of it, yes, moving it to the JSDP project would work for me.  If you want to keep it, I can file a new JSDP ticket for it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473355#comment-473355):_

Well, this ticket is currently on our sprint board, so perhaps we should just close it and let you open a JSDP ticket. Closing now. Feel free to clone if you like.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473356#comment-473356):_

Must be fixed within SDP, not CAL.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) on [JIRA](https://jira.stsci.edu/browse/JP-1539?focusedCommentId=473681#comment-473681):_

This problem appears fixed in b7.5.  The SOCVALTEST1 suite was run on Dstring2 using b7.5 on 2020-07-12 and no LEVEL_2B errors occurred for 00213070, with > 1000 Level2b FITS files produced.
