### ISSUE TITLE
NIRSpec: spec2 crashing with FS ALLSLITS NRS2 file

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5146]
_Issue [JP-1583](https://jira.stsci.edu/browse/JP-1583) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

The spec2 pipeline is crashing with the following trace back:

(jwst162) scully:G140H_opaque pena$ strun jwst.pipeline.Spec2Pipeline final_output_caldet1_NRS2.fits
2020-07-16 11:52:38,658 - CRDS - ERROR - Error determining best reference for 'pars-backgroundstep' = Unknown reference type 'pars-backgroundstep'
2020-07-16 11:52:38,663 - CRDS - ERROR - Error determining best reference for 'pars-assignwcsstep' = Unknown reference type 'pars-assignwcsstep'
2020-07-16 11:52:38,667 - CRDS - ERROR - Error determining best reference for 'pars-imprintstep' = Unknown reference type 'pars-imprintstep'
2020-07-16 11:52:38,671 - CRDS - ERROR - Error determining best reference for 'pars-msaflagopenstep' = Unknown reference type 'pars-msaflagopenstep'
2020-07-16 11:52:38,676 - CRDS - ERROR - Error determining best reference for 'pars-extract2dstep' = Unknown reference type 'pars-extract2dstep'
2020-07-16 11:52:38,680 - CRDS - ERROR - Error determining best reference for 'pars-flatfieldstep' = Unknown reference type 'pars-flatfieldstep'
2020-07-16 11:52:38,684 - CRDS - ERROR - Error determining best reference for 'pars-sourcetypestep' = Unknown reference type 'pars-sourcetypestep'
2020-07-16 11:52:38,689 - CRDS - ERROR - Error determining best reference for 'pars-straylightstep' = Unknown reference type 'pars-straylightstep'
2020-07-16 11:52:38,693 - CRDS - ERROR - Error determining best reference for 'pars-fringestep' = Unknown reference type 'pars-fringestep'
2020-07-16 11:52:38,697 - CRDS - ERROR - Error determining best reference for 'pars-pathlossstep' = Unknown reference type 'pars-pathlossstep'
2020-07-16 11:52:38,702 - CRDS - ERROR - Error determining best reference for 'pars-barshadowstep' = Unknown reference type 'pars-barshadowstep'
2020-07-16 11:52:38,707 - CRDS - ERROR - Error determining best reference for 'pars-photomstep' = Unknown reference type 'pars-photomstep'
2020-07-16 11:52:38,712 - CRDS - ERROR - Error determining best reference for 'pars-resamplespecstep' = Unknown reference type 'pars-resamplespecstep'
2020-07-16 11:52:38,716 - CRDS - ERROR - Error determining best reference for 'pars-cubebuildstep' = Unknown reference type 'pars-cubebuildstep'
2020-07-16 11:52:38,721 - CRDS - ERROR - Error determining best reference for 'pars-extract1dstep' = Unknown reference type 'pars-extract1dstep'
2020-07-16 11:52:38,722 - CRDS - ERROR - Error determining best reference for 'pars-spec2pipeline' = Unknown reference type 'pars-spec2pipeline'
2020-07-16 11:52:38,949 - CRDS - ERROR - Error determining best reference for 'area' = No match found.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
Error determining best reference for 'area' = No match found.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/pena/anaconda3/envs/jwst162/bin/strun", line 26, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
return cmdline.step_from_cmdline(args)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
step.run(*positional)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/step.py", line 390, in run
self.prefetch(*args)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/step.py", line 484, in prefetch
self._precache_references(args[0])
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/pipeline.py", line 269, in _precache_references
self._precache_references_opened(model)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/pipeline.py", line 292, in _precache_references_opened
self._precache_references_impl(model_or_container)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/pipeline.py", line 316, in _precache_references_impl
crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/crds_client.py", line 89, in get_multiple_reference_paths
refpaths = _get_refpaths(data_dict, tuple(reference_file_types), observatory)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/crds_client.py", line 118, in _get_refpaths
data_dict, reftypes=reference_file_types, observatory=observatory)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/crds/core/heavy_client.py", line 128, in getreferences
final_context, bestrefs, ignore_cache=ignore_cache)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/crds/client/api.py", line 851, in cache_references
wanted = _get_cache_filelist_and_report_errors(bestrefs)
File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/crds/client/api.py", line 894, in _get_cache_filelist_and_report_errors
raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'area' = No match found.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=474473#comment-474473):_

<https://jwst-crds.stsci.edu/> shows that NIRSpec AREA ref files are selected based on EXP_TYPE, DETECTOR, FILTER, GRATING, and USEAFTER. Based on the description and file name given above, I assume that EXP_TYPE='NRS_FIXEDSLIT' and DETECTOR='NRS2'. Need to determine the rest of the relevant params of the input data file.

But keep in mind that failures to find an appropriate reference file are almost never a problem in the cal pipeline software, but rather a problem with keywords or keyword values in either the input data or the reference files.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=474476#comment-474476):_

The traceback above shows that the input file used with calwebb_spec2 was "final_output_caldet1_NRS2.fits", but the only files contained in the data directory are "G140H_opaque_NRS[12]_rate.fits". Assuming that the actual input file was G140H_opaque_NRS2_rate.fits, the ref file selector values are EXP_TYPE='NRS_FIXEDSLIT', DETECTOR='NRS2', FILTER='OPAQUE', GRATING='G140H', and DATE-OBS='2015-12-11'.

So the problem here is obviously the fact that FILTER='OPAQUE' (an internal lamp observation?) and there are no AREA ref files in CRDS for that FILTER value.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=479641#comment-479641):_

Is this still a problem or has the issue been resolved? I tried looking at the input data files again, but the original data directory listed above in the ticket description no longer exists. I did find what appears to be a similar input file /ALLSLITS_G140H_opaque/final_output_caldet1_NRS2_F100LP.fits, but in this file FILTER='F100LP', as opposed to 'OPAQUE'. Changing FILTER to the name of an actual filter will enable selection of an AREA ref file from CRDS, making the previous problem go away.

One other thing I noticed about this file, however, is that SUBARRAY='ALLSLITS' (which means data from all fixed slits is available), but FXD_SLIT='NONE'. In the case of data containing multiple fixed slits, the Cal pipeline needs to know which one to treat as the primary slit (i.e. the one in which the target is placed), which it gets from the FXD_SLIT keyword. With that keyword set to 'NONE', the pipeline won't know which slit to treat as primary, which affects decisions like what source type to assign to each slit and whether or not to apply the wavelength zero-point correction.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=480957#comment-480957):_

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) can you comment whether or not the problem still exists? I think I've seen similar tickets but I'm going through and reviewing them now.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=483749#comment-483749):_

[Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe), yes the problem exists when FILTER=OPAQUE.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=483754#comment-483754):_

What kind of exposure uses FILTER='OPAQUE'? Does that result in a dark exposure? Or is that used for internal lamp observations? If it's a lamp exposure, then it should be processed using one of the new spec2 parameter files recently installed in CRDS to properly handle lamp exposures. They have various steps set to skip, if they can't be applied to a particular kind of lamp exposure, which then also skips any CRDS prefetch for reference files needed by the skipped steps (thus avoiding the missing ref file errors). The way to do this is to execute from the command line using:

 strun jwst.pipeline.Spec2Pipeline <your_rate.fits>

which will cause CRDS to search for an appropriate pars-spec2pipeline ref file. But those parameter ref files only exist for EXP_TYPE's NRS_AUTOFLAT, NRS_AUTOWAVE, and NRS_LAMP. Any other EXP_TYPE's are considered to be science and use the regular processing configuration.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=483771#comment-483771):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse), [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) I just chatted with James and he noted that this particular configuration should not be processed further than cal_detector1 because there is no trace to be extracted. The lamp keyword for this data is set to NO_LAMP so processing with internal lamps will not work. Maybe the pipeline should exit gracefully saying that for this combination spec2 is not to be run since there is no trace to extract?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=484647#comment-484647):_

JP-1699 has been created to make updates to the ASN rules to exclude LAMP='NOLAMP' exposures from level-2b processing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=485908#comment-485908):_

[Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) as mentioned in the previous comment we can modify the ASN rules to avoid level-2b processing when LAMP='NOLAMP', since there's no spectral data to work with, but what about the case where FILTER='OPAQUE'? Is that a valid setting for some kinds of lamp exposures (we're seeing quite a few of them in DMS test suites)? If so, what kind of data does it produce (I don't recall off-hand where the filter wheel lies in the NIRSpec optical path and hence what the effect would be of having it opaque)?

I note that there are several old Jira tickets that talk about processing FILTER='OPAQUE' exposures in one way or another (e.g. JP-248, JP-282, JP-667, JP-806, JP-1684), but there's no specific mention of how to handle this case in any of the specs given for lamp processing (JP-473). Are they lamp exposures at all or are they darks or what?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=485938#comment-485938):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) The filter is always set to 'OPAQUE' when an internal lamp is being used (including "NOLAMP").  I think we already set up the rules to deal with that (i.e., using the lamp name in place of the filter name to select the appropriate reference file)?  The only other time OPAQUE should appear is the dark template.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=485972#comment-485972):_

Thanks [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol), that makes sense (especially after I looked at the instrument optical path layout again and saw that the filter is upstream of pretty much everything else). It looks like the only ref file that's filter-dependent (at least for lamp processing) already has an entry for opaque and it's set to N/A, which means no SFLAT will be used (only the DFLAT). So the issues we're currently having with getting lamp exposures of different flavors to process in level-2b is not due to the filter opaque setting, but other issues.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=499154#comment-499154):_

Update as of 7-Dec-2020, once JP-1699 has been implemented, no level-2b ASN's will be created for NRS lamp exposures that have LAMP='NOLAMP' and hence processing will stop after calwebb_detector1 (level 2a), which should resolve this issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1583?focusedCommentId=504671#comment-504671):_

All fixes in SDP, Cal, and ASN generator for handling LAMP='NOLAMP' exposures have been incorporated into B7.7, which means level-2b processing will not be attempted for these exposures anymore.
