### ISSUE TITLE
NIRSpec: calwebb_detector1 crashing with dark fits processing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5192]
_Issue [JP-1617](https://jira.stsci.edu/browse/JP-1617) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

The detector1 pipeline is crashing with subarray dark data processing. The following traceback is with the ALLSLITS data, but we get the same with other subarray data:

Traceback (most recent call last):
 File "/Users/pena/anaconda3/envs/jwst162/bin/nptt_run_PTT", line 11, in <module>
 load_entry_point('nirspec-pipe-testing-tool', 'console_scripts', 'nptt_run_PTT')()
 File "/Users/pena/Documents/NIRSpec_projects/nirspec_pipe_testing_tool/nirspec_pipe_testing_tool/utils/run_PTT.py", line 215, in main
 run_PTT(report_name=report_name, config_path=config, run_detector1=run_detector1, verbose=quiet)
 File "/Users/pena/Documents/NIRSpec_projects/nirspec_pipe_testing_tool/nirspec_pipe_testing_tool/utils/run_PTT.py", line 121, in run_PTT
 run_cal_detector1.run_caldet1(run_detector1, step_by_step=False)
 File "/Users/pena/Documents/NIRSpec_projects/nirspec_pipe_testing_tool/nirspec_pipe_testing_tool/utils/run_cal_detector1.py", line 230, in run_caldet1
 result = Detector1Pipeline.call(fits_input_uncal_file, config_file=cfg_file)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/step.py", line 552, in call
 return instance.run(*args)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/step.py", line 390, in run
 self.prefetch(*args)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/step.py", line 484, in prefetch
 self._precache_references(args[0])
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/pipeline.py", line 269, in _precache_references
 self._precache_references_opened(model)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/pipeline.py", line 292, in _precache_references_opened
 self._precache_references_impl(model_or_container)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/pipeline.py", line 316, in _precache_references_impl
 crds_refs = crds_client.get_multiple_reference_paths(model, fetch_types)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/crds_client.py", line 89, in get_multiple_reference_paths
 refpaths = _get_refpaths(data_dict, tuple(reference_file_types), observatory)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/jwst/stpipe/crds_client.py", line 118, in _get_refpaths
 data_dict, reftypes=reference_file_types, observatory=observatory)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/crds/core/heavy_client.py", line 128, in getreferences
 final_context, bestrefs, ignore_cache=ignore_cache)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/crds/client/api.py", line 851, in cache_references
 wanted = _get_cache_filelist_and_report_errors(bestrefs)
 File "/Users/pena/anaconda3/envs/jwst162/lib/python3.7/site-packages/crds/client/api.py", line 894, in _get_cache_filelist_and_report_errors
 raise last_error
 crds.core.exceptions.CrdsLookupError: Error determining best reference for 'superbias' = No match found.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1617?focusedCommentId=476055#comment-476055):_

The superbias reference file is selected on

DETECTOR
READPATT
SUBARRAY
XSTART
YSTART
XSIZE
YSIZE
USEAFTER

See <https://jwst-crds.stsci.edu> under NIRSpec > superbias

Is your dataset covered by the rmap?  The error message is telling us it is not.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-1617?focusedCommentId=476362#comment-476362):_

I think it does, unless I am not understanding something?

**SUBARRAY= 'GENERIC '                                                                                                                                        READPAT= 'NRSRAPID'                                                                                                                                        DATE-OBS= '2015-12-11'   -> this is the value checked against USEAFTER, correct?                        SUBSTRT1= 1  -> this is XSTART, correct?
SUBSIZE1= 2048   -> this is XSIZE, correct?
SUBSTRT2= 897   -> this is YSTART, correct?
SUBSIZE2= 256   -> this is YSIZE, correct?

If I understand correctly one of these should have been picked up [jwst_nirspec_superbias_0002.fits](https://jwst-crds.stsci.edu/browse/jwst_nirspec_superbias_0002.fits) or [jwst_nirspec_superbias_0002.fits](https://jwst-crds.stsci.edu/browse/jwst_nirspec_superbias_0002.fits)?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1617?focusedCommentId=476547#comment-476547):_

So this is clearly a CRDS issue related to selection rules and is unrelated to `jwst` cal software.  I would recommend moving this to the CRDS project.  `MORE > MOVE` in menu above.

**Comment by hbushouse** [comment]
Closing. Issue was resolved outside of Cal code.
