### ISSUE TITLE
ami_average does not work from the command line

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5197]
_Issue [JP-1618](https://jira.stsci.edu/browse/JP-1618) was created on JIRA by [Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte):_

(jwstb75rc2_0.16.1) bash-3.2$ strun ami_average.cfg jw00042003001_01101_00008_nis_a3001_ami.fits jw00042003001_01101_00008_copy_nis_a3001_ami.fits 
2020-07-27 09:43:02,419 - CRDS - ERROR -  Error determining best reference for 'pars-amiaveragestep'  =   Unknown reference type 'pars-amiaveragestep'
2020-07-27 09:43:02,421 - stpipe.ami_average - INFO - AmiAverageStep instance created.
2020-07-27 09:43:02,458 - stpipe.ami_average - INFO - Step ami_average running with args ('jw00042003001_01101_00008_nis_a3001_ami.fits', 'jw00042003001_01101_00008_copy_nis_a3001_ami.fits').
2020-07-27 09:43:02,459 - stpipe.ami_average - INFO - Step ami_average parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}
----------------------------------------------------------------------
ERROR RUNNING STEP 'AmiAverageStep':
    process() takes 2 positional arguments but 3 were given
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/thatte/anaconda3/envs/jwstb75rc2_0.16.1/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/thatte/anaconda3/envs/jwstb75rc2_0.16.1/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/thatte/anaconda3/envs/jwstb75rc2_0.16.1/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/Users/thatte/anaconda3/envs/jwstb75rc2_0.16.1/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
TypeError: process() takes 2 positional arguments but 3 were given

Running this step from Python works. 
>>> from jwst.ami import ami_average 
>>> result=ami_average.average_LG(['jw00042003001_01101_00008_nis_a3001_ami.fits','jw00042003001_01101_00008_copy_nis_a3001_ami.fits']) 
>>> result.save('amiavg.fits') 'amiavg.fits'

It also works when all AMI calibration steps are called with calwebb_ami3.cfg. 
$strun calwebb_ami3.cfg ami_asn.json (This works)

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1618?focusedCommentId=492832#comment-492832):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Just trying to pinpoint what kind of issue this is. Is it a documentation issue? I'm assuming the strun method wasn't designed to allow AMI3 steps to be run individually, unlike with the imaging and spec pipelines? Although if you can run a single step in python, seems like you should be able to in the command line...

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1618?focusedCommentId=492840#comment-492840):_

Correct that `strun` cannot be used on any old function. However, there is an `AmiAverageStep`, so the above usage is correct. This is a bug in how that step is defined. The step has a parameter, `input_list`, that is intended to be a list of input models. However, to get this to work properly from the command line, where one would like to pass a number of files to the step as shown here, the declaration of the step needs to be

`def process(self, *input_list)`

 Of course, other changes will be needed, but this is the essence of the problem.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1618?focusedCommentId=582257#comment-582257):_

Fixed by #6797

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1618?focusedCommentId=492832#comment-492832):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Just trying to pinpoint what kind of issue this is. Is it a documentation issue? I'm assuming the strun method wasn't designed to allow AMI3 steps to be run individually, unlike with the imaging and spec pipelines? Although if you can run a single step in python, seems like you should be able to in the command line...

**Comment by stscijgbot-jp** [comment]
_Comment by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) on [JIRA](https://jira.stsci.edu/browse/JP-1618?focusedCommentId=492840#comment-492840):_

Correct that `strun` cannot be used on any old function. However, there is an `AmiAverageStep`, so the above usage is correct. This is a bug in how that step is defined. The step has a parameter, `input_list`, that is intended to be a list of input models. However, to get this to work properly from the command line, where one would like to pass a number of files to the step as shown here, the declaration of the step needs to be

`def process(self, *input_list)`

 Of course, other changes will be needed, but this is the essence of the problem.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1618?focusedCommentId=582257#comment-582257):_

Fixed by #6797
