### ISSUE TITLE
Failure on Level 3 processing for 00634039, MinAsn-8,  NIRCam MT, dither/mosaic

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5199]
_Issue [JP-1619](https://jira.stsci.edu/browse/JP-1619) was created on JIRA by [Mark Kyprianou](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kyp):_

Level 3 processing error:
  File “/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/assign_mtwcs/moving_target_wcs.py”, line 25, in assig
n_moving_target_wcs
    mt_avra = mt_ra.mean()
  File “/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/numpy/core/_methods.py”, line 151, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: ‘NoneType’ and ‘NoneType’

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=478095#comment-478095):_

We see this error in reprocessing of nops8.1 data on A-string using B7.5. The error occurs in the step that assigns WCS to moving targets and affects both image3 and spec3, as seen in the following datasets:
```
1158-UnsupportedOperandTypes.list:jw00634-o039_20200803t013618_image3_001 LEVEL_3 none
1158-UnsupportedOperandTypes.list:jw00634-o039_20200803t013618_image3_002 LEVEL_3 none
1158-UnsupportedOperandTypes.list:jw00634-o040_20200803t013618_image3_001 LEVEL_3 none
1158-UnsupportedOperandTypes.list:jw00634-o040_20200803t013618_image3_002 LEVEL_3 none
1158-UnsupportedOperandTypes.list:jw00637-o015_20200803t013440_image3_001 LEVEL_3 none
1158-UnsupportedOperandTypes.list:jw00637-o015_20200803t013440_image3_002 LEVEL_3 none
unknown--2144143668.list:jw00637-o016_20200803t013440_spec3_001 LEVEL_3 none ```
Trace back from an example ALOG*.out:
```
2020-08-03 01:47:37,816 - CRDS - DEBUG - Final effective context is 'jwst_0619.pmap'
2020-08-03 01:47:37,816 - CRDS - DEBUG - Computing best references locally.
2020-08-03 01:47:37,817 - CRDS - DEBUG - Bestrefs header:
2020-08-03 01:47:37,818 - CRDS - DEBUG - {'META.EXPOSURE.READPATT [READPATT]': 'RAPID',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.EXPOSURE.TYPE [EXP_TYPE]': 'NRC_IMAGE',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'LONG',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.CORONAGRAPH [CORONMSK]': 'UNDEFINED',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NRCBLONG',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.FILTER [FILTER]': 'F250M',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.MODULE [MODULE]': 'B',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.NAME [INSTRUME]': 'NIRCAM',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.INSTRUMENT.PUPIL [PUPIL]': 'CLEAR',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.OBSERVATION.DATE [DATE-OBS]': '2020-06-03',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.OBSERVATION.TIME [TIME-OBS]': '00:23:05.511',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
2020-08-03 01:47:37,818 - CRDS - DEBUG - 'REFTYPE': 'UNDEFINED'}
2020-08-03 01:47:37,819 - CRDS - DEBUG - Reference type 'abvegaoffset' defined as 'jwst_nircam_abvegaoffset_0001.asdf'
2020-08-03 01:47:37,819 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_nircam_apcorr_0002.fits'
2020-08-03 01:47:37,819 - CRDS - DEBUG - Reference type 'drizpars' defined as 'jwst_nircam_drizpars_0001.fits'
2020-08-03 01:47:37,820 - stpipe.Image3Pipeline - INFO - Prefetch for ABVEGAOFFSET reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_abvegaoffset_0001.asdf'.
2020-08-03 01:47:37,821 - stpipe.Image3Pipeline - INFO - Prefetch for APCORR reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_apcorr_0002.fits'.
2020-08-03 01:47:37,824 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_drizpars_0001.fits'.
2020-08-03 01:47:37,827 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2020-08-03 01:47:38,569 - stpipe.Image3Pipeline - INFO - Assigning WCS to a Moving Target exposure.
2020-08-03 01:47:38,632 - stpipe.Image3Pipeline.assign_mtwcs - INFO - Step assign_mtwcs running with args (<ModelContainer>,).
2020-08-03 01:47:38,633 - stpipe.Image3Pipeline.assign_mtwcs - INFO - Step assign_mtwcs parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': 'assign_mtwcs', 'search_output_file': True, 'input_dir': '/ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3'}
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/bin/strun", line 26, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
return cmdline.step_from_cmdline(args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.py", line 75, in process
input_models = self.assign_mtwcs(input_models)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/assign_mtwcs/assign_mtwcs_step.py", line 37, in process
result = assign_moving_target_wcs(input)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/assign_mtwcs/moving_target_wcs.py", line 25, in assign_moving_target_wcs
mt_avra = mt_ra.mean()
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/numpy/core/_methods.py", line 151, in _mean
ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
unsupported operand type(s) for +: 'NoneType' and 'NoneType'
----------------------------------------------------------------------
2020216014739-E-ERROR-/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.cfg FAILED (exit=1) on jw00634-o040_20200803t013618_image3_002_asn.json.
2020216014739-I-INFO-restoring SDP python env...
SSB python deactivated; OWL python ready for interactive use.
2020216014739-E-ERROR-exit status=1
2020216014739-E-ERROR-calibration_wrapper.csh FAILED. Archiving will NOT be attempted. ```
The curious thing is that these MT datasets [appeared to have made level_3 just fine during the run](https://innerspace.stsci.edu/display/JDOT/2020-06-19T20%3A06%3A13.545896+Program+00634040), which used B7.4.2, so something must have changed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=478806#comment-478806):_

Yes, things did change between B7.4.2 and B7.5. There was absolutely no MT-specific code at all in B7.4.2 and hence they were processed like ordinary (non-moving target) images, successfully producing scientifically incorrect results. B7.5 included partial implementation of MT processing, which is the parts necessary in the Cal pipeline. But those parts of the Cal pipeline rely on input from level-1b processing that was not yet available in B7.5, so the Cal pipeline crashes. Full MT support will be available in B7.6.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=478807#comment-478807):_

In the meantime (post-B7.5) a change was made to the Cal pipeline step that showed the failure above to make it more robust and to shutdown cleanly when the necessary inputs from level-1b MT processing are not available.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=478831#comment-478831):_

Technically this problem is being resolved by SDP, as documented in JSDP-626, which is scheduled to be included in B7.6. I guess we can leave this ticket open for now and verify that the problem goes away once B7.6 is available, even though there isn't any further Cal work needed to resolve it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Catherine Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=488741#comment-488741):_

We see L3 products for 00636018 in the latest run (run 1588) of nOps9 on D2 with B7.6, but not for the latest run (run 1653) of 00634039 from nOps8.1 on D2 with B7.6.  Needs further investigation.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=488768#comment-488768):_

When I look in the run1588 (which is nOPS8.1) and run1653 (which is nOPS9) directories on D2, I see nothing but empty directories everywhere. Have all the results already been wiped out?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=488778#comment-488778):_

In /ifs/archive/test/jwst/store/rspencer/tests/nOPS9/dtest2/JWSTDP-2020.3.0-56~560789b3/2020-09-25-004831/sdp/fits/ there are level-1b and level-2a products for jw00636018. No level-2b, let alone level-3. Where did you ([Catherine Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida)) find level-3 products for this observation?

Can't find any files under the run1588 directory for nOPS8.1.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=488792#comment-488792):_

I see level-3 product headers in █████████████████████████████████████████████████████████████████████
```
-rw-r--r--  1 rspencer  STSCI\dms   33349 Sep 24 11:13 jw00636-o018_t011_nirspec_g235m-f170lp_x1d.lis
-rw-r--r--  1 rspencer  STSCI\dms  102907 Sep 24 11:13 jw00636-o018_t011_nirspec_g235m-f170lp_s3d.lis
-rw-r--r--  1 rspencer  STSCI\dms  102907 Sep 24 11:13 jw00636-o018_t011_nirspec_g140m-f100lp_s3d.lis
-rw-r--r--  1 rspencer  STSCI\dms   33349 Sep 24 11:13 jw00636-o018_t011_nirspec_g140m-f100lp_x1d.lis```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1619?focusedCommentId=495979#comment-495979):_

Reprocessing using B7.6.2 on the A string shows that the spec3 pipeline now succeeds, albeit by skipping the assign_mtwcs step, because of the lack of necessary target coordinate info from level-1b processing. But it does at least prove that the intent of this ticket, which was to simply trap the error and proceed with normal processing, has succeeded.
