### ISSUE TITLE
extract_1d error in spec3 MOS processing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5228]
_Issue [JP-1635](https://jira.stsci.edu/browse/JP-1635) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

I’ve encountered an error in the spec3 pipeline using the latest dev version (0.16.3.dev90+gd38b706d) - when trying to process a set of 3 MOS nodded exposures, it crashes at the extract_1d step with an attribute error “‘NoneType’ object has no attribute ‘upper’“ (relevant traceback below).  These data have been previously processed successfully using 0.16.1, so this bug seems to be a result of some recent change.

 

2020-08-05 18:47:13,921 - stpipe.Spec3Pipeline.extract_1d - INFO - Using EXTRACT1D reference file ████████████████████████████████████████████████████████████████

2020-08-05 18:47:14,001 - stpipe.Spec3Pipeline.extract_1d - INFO - Using APCORR file █████████████████████████████████████████████████████████████

2020-08-05 18:47:14,177 - stpipe.Spec3Pipeline.extract_1d - INFO - Turning on source position correction for exp_type = NRS_MSASPEC

2020-08-05 18:47:14,177 - stpipe.Spec3Pipeline.extract_1d - INFO - Setting use_source_posn to False for source type None

2020-08-05 18:47:14,177 - stpipe.Spec3Pipeline.extract_1d - INFO - Beginning loop, just 1 integration ...

----------------------------------------------------------------------

ERROR RUNNING STEP 'Spec3Pipeline':

    'NoneType' object has no attribute 'upper'

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/muzerol/anaconda3/envs/jwst_dev/bin/strun", line 26, in <module>

    step = Step.from_cmdline(sys.argv[1:])

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline

    return cmdline.step_from_cmdline(args)

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline

    step.run(*positional)

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/stpipe/step.py", line 392, in run

    step_result = self.process(*args)

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/pipeline/calwebb_spec3.py", line 223, in process

    result = self.extract_1d(result)

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/stpipe/step.py", line 392, in run

    step_result = self.process(*args)

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/extract_1d/extract_1d_step.py", line 254, in process

    result = extract.run_extract1d(

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/extract_1d/extract.py", line 2485, in run_extract1d

    output_model = do_extract1d(

  File "/Users/muzerol/anaconda3/envs/jwst_dev/lib/python3.8/site-packages/jwst/extract_1d/extract.py", line 3136, in do_extract1d

    if source_type.upper() == 'POINT' and apcorr_ref_model is not None:

AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1635?focusedCommentId=478257#comment-478257):_

It's crashing while trying to work on the "source_type" object (it's set to None), so first thing to check is to see if there's a SRCTYPE keyword in the SCI extension header of all slit instances in the input cal files. This should've been added by the calwebb_spec2 srctype step, when going through level-2b processing. This error may have not shown up before because the apcorr correction is relatively new to extract_1d and it needs to know the source type to do its' work.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1635?focusedCommentId=478258#comment-478258):_

If SRCTYPE is not in the SCI extension headers, the easiest solution may be to rerun all the rate files through calwebb_spec2, to generate new cal files,.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1635?focusedCommentId=478264#comment-478264):_

I did a spot-check of a few extension headers, and SRCTYPE was correctly populated with "POINT".  I'll check all of them just to make sure there aren't a few black sheep.  The inputs to spec3 were generated from calwebb_spec2 using the same pipeline version.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1635?focusedCommentId=478279#comment-478279):_

So if the input files had in fact been reprocessed recently with the latest calwebb_spec2, then we may in fact have a bug somewhere. We'll run your dataset(s) in calwebb_spec3 to try to track it down.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-1635?focusedCommentId=478286#comment-478286):_

Ok, and I confirm SRCTYPE was set to POINT for all sources in all exposures.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1635?focusedCommentId=479693#comment-479693):_

Fixed in #5250
