### ISSUE TITLE
Support B7.6 Integration

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5294]
_Issue [JP-1664](https://jira.stsci.edu/browse/JP-1664) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Support Build 7.6 integration. Includes reviewing run results, filing issues as required, and assign as necessary.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=484183#comment-484183):_

**EvaluationSuite05**: ███████████████████████████████████████████████████

1116-ErrDeterminingBestRef - calwebb_image2 error for NIRCam WFS images using SUBARRAY='SUB8FP1A' due to more than one match for FLAT and DISTORTION ref files.

1143-Shapes - calwebb_detector1 error for NIRCam TA images using SUBARRAY='SUB320A335R', due to mismatch in science array size (2048,2048) and DARK data size (320,320). Science exposure claims to be subarray, but data are full-frame.

unknown-1249667338 - calwebb_nrslamp-spec2 errors for NRS_AUTOWAVE exposures with OPMODE='NONE'. Failure to select proper pars-spec2pipeline and other ref files, due to OPMODE='NONE'.

1140-AttributeError - calwebb_image3 error in "skymatch" step for NIRCam subarray imaging: "SkyGroup object has no attribute 'is_sky_valid'" (skymatch.py line 390). Likely due to garbage data.

*1171-ValueError - calwebb_tso3 error in tso_photometry step due to empty INT_TIMES table. Fixed by JP-1680 and JP-1681, included in B7.6rc2.*

*1240-AssertionError - calwebb_spec3 error for NRC_WFSS data in extract_1d step when beginning to work on next slit/source instance after having successfully processed several slits already. Not clear what causes the error. Error is reproducible using latest dev version of CAL. JP-1693 has been created to debug.*

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=484189#comment-484189):_

**complete_long_05**: ███████████████████████████████████████████████████

1108-UnsupportedOperandTypes - calwebb_image2 error in resample step for NIRCam images using SUB400P subarray when trying to create output wcs:
```java
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/assign_wcs/pointing.py", line 116, in wcsinfo_from_model
    for ax in range(1, wcsaxes + 1):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'```
1116-ErrDeterminingBestRef - calwebb_image2 error for NIRCam WFS images determining FLAT and DISTORTION ref files. Too many matches.

1137-Shapes - calwebb_detector1 error for NIS_SOSS with SUBARRAY='FULL' due to mismatch between science array and dark array sizes. Science claims to be full-frame, but is actually (256, 2048).

1143-Shapes - calwebb_detector1 error for NIRCam TA images using SUBARRAY='SUB320A335R', due to mismatch in science array size (2048,2048) and DARK data size (320,320). Science exposure claims to be subarray, but data are full-frame.

1170-MemoryError - calwebb_detector1 memory error in jump step for MIR_MRS exposure with NINTS=1 and NGROUPS=200:
```java
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/jump/jump.py", line 117, in detect_jumps
    gdq, row_below_dq, row_above_dq = twopt.find_crs(data, gdq, readnoise_2d, rejection_threshold,
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/jump/twopoint_difference.py", line 79, in find_crs
    number_sat_groups = (sat_groups * 1).sum(axis=2)
MemoryError: Unable to allocate 1.57 GiB for an array with shape (1024, 1032, 199) and data type int64```
1268-MemoryError - same calwebb_detector1 memory error in jump step for MIR_MRS

unknown-1036868130 - calwebb_spec2 error in resample step for MIR_LRS-FIXEDSLIT, due to the fact that it's actually MIR_LRS-SLITLESS. Error in up-stream meta data.

unknown-1249667338 - calwebb_nrslamp-spec2 error for NRS_LAMP exposures with LAMP='NOLAMP'.

unknown–1507291412 - calwebb_nrslamp-spec2 error for NRS_LAMP exposures with OPMODE='MSASPEC', but no msa meta file specified.

unknown-1604991944 - calwebb_spec2 error for NIS_WFSS exposures due to no useable objects retrieved from source catalog (blank images).

unknown-919307998 - Memory error in calwebb_detector1 jump step for MIR_MRS with NINTS=1, NGROUPS=200:
```java
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/jump/twopoint_difference.py", line 45, in find_crs
    saturated_pixels = np.where(np.bitwise_and(gdq, dqflags.group['SATURATED']))
  File "<__array_function__ internals>", line 5, in where
MemoryError: Unable to allocate 5.18 GiB for an array with shape (173952268, 4) and data type int64
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=484634#comment-484634):_

**GSEG3RR**: ███████████████████████████████████████████████████

**1178-ValueError** *- calwebb_image3 error in resample step for NRC_IMAGE exposures: "I/O operation on closed file". Fixed in JP-1665 and included in B7.6rc2.*

**unknown-1249667338** - Same calwebb_nrslamp-spec2 errors as above for exposures with LAMP='NOLAMP'.

**unknown-1507291412** - Sames calwebb_nrslamp-spec2 errors as above for OPMOE='MSASPEC' exposures with no msa meta file.

**unknown-530653517** - calwebb_tso-spec2 errors for NRC_TSGRISM exposure with SUBARRAY='SUBGRISM256' due to no matching SPECWCS ref file in CRDS. This is due to the fact that PUPIL='CLEAR' in the science exposure, instead of the expected 'GRISMC' or 'GRISMR'.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=484637#comment-484637):_

**nOPS8.1**: ███████████████████████████████████████████████████

**1116-ErrDeterminingBestRef** - calwebb_image2 error for NIRCam WFS images using SUBARRAY='SUB8FP1A' due to more than one match for FLAT and DISTORTION ref files.

**1178-ValueError** *- calwebb_image3 error in resample step for NRC_IMAGE exposures: "I/O operation on closed file". Fixed in JP-1665 and included in B7.6rc2.*

**unknown-61143725** - calwebb_spec3 error allocating memory (2.6 GB) in mrs_imatch step for a MIRI MRS association.

**unknown-1249667338** - Same calwebb_nrslamp-spec2 errors as above for exposures with LAMP='NOLAMP'.

**unknown-1604991944** - calwebb_spec2 error for NIS_WFSS exposures due to no useable objects in source catalog (image data are blank).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=484939#comment-484939):_

**SOCVALTEST2**: ███████████████████████████████████████████████████

**unknown-1094865378** - calwebb_spec2 error in cube_build step for several NRS_IFU exposures with signatures such as:
```java
2020-09-16 00:11:44,336 - stpipe.Spec2Pipeline.cube_build - INFO - Time to find Cube Flux = 0.2 s
2020-09-16 00:11:44,391 - stpipe.Spec2Pipeline.cube_build - INFO - Number of wavelength planes removed with no data: 3735
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_spec2.py", line 108, in process
    result = self.process_exposure_product(
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_spec2.py", line 263, in process_exposure_product
    result_extra = self.cube_build(result)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/stpipe/step.py", line 392, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/cube_build/cube_build_step.py", line 343, in process
    result = thiscube.build_ifucube()
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/cube_build/ifu_cube.py", line 783, in build_ifucube
    ifucube_model = self.setup_final_ifucube_model(0)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.0.20200830-py38/lib/python3.8/site-packages/jwst/cube_build/ifu_cube.py", line 2101, in setup_final_ifucube_model
    self.crval3 = self.zcoord[remove_start]
IndexError: index 1868 is out of bounds for axis 0 with size 1868
```
**unknown-1249667338** - calwebb_nrslamp-spec2 error for NRS lamp exposures with OPMODE='NONE'.

**unknown-1604991944** - calwebb_spec2 error for NIS_WFSS exposures with no useable objects in source catalog (blank images).

**unknown-1828310953** - calwebb_spec2 error for NIRSpec fixed-slit exposure on NRS2, due to no open slits on NRS2 detector.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485077#comment-485077):_

The SOCVALTEST2 dataset listed above is confirmed to have succeeded in Level2b using the 0.17.1 release under DMS b7.6 deployment  JWSTDP-2020.3.0-53~8ee2a48f/2020-09-17-000130/sdp/archive

 

level2b/jw00214054001_04108_00001_nrs1*
../../../../archive/level2b/jw00214054001_04108_00001_nrs1_cal.fits*
../../../../archive/level2b/jw00214054001_04108_00001_nrs1_cal.jpg*
../../../../archive/level2b/jw00214054001_04108_00001_nrs1_cal_thumb.jpg*

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485194#comment-485194):_

**QnGV5**: ███████████████████████████████████████████████████ with b7.6rc2

No errors!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485197#comment-485197):_

**GSEG3RR**: ███████████████████████████████████████████████████

**unknown-1249667338**: All NRS_LAMP errors in calwebb_nrslamp-spec2 due to issue with pars-spec2pipeline ref file missing an entry for skipping the master_background step, which allows a prefetch to be attempted for a pathloss ref file and there's no match. Needs updated pars-spec2pipeline ref files.

**unknown-530653517**: calwebb_tso-spec2 error for NRC_TSGRISM exposures using SUBGRISM256 due to no specwcs ref file found, because PUPIL='CLEAR' in science data, instead of 'GRISMR' or 'GRISMC'. Is it possible that these are some kind of targ-acq or ta-confirm exposures that don't have the expected EXP_TYPE?

**1178-ValueError**: calwebb_image3 error in source_catalog step for FGS_IMAGE exposure(s):
```java
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/jwst/source_catalog/source_catalog_step.py", line 113, in process
    catalog = catobj.catalog
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/astropy/utils/decorators.py", line 758, in __get__
    val = self.fget(obj)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/jwst/source_catalog/source_catalog.py", line 1341, in catalog
    self.set_aperture_properties()
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/jwst/source_catalog/source_catalog.py", line 928, in set_aperture_properties
    apertures = [CircularAperture(self.xypos, radius) for radius in
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/jwst/source_catalog/source_catalog.py", line 928, in <listcomp>
    apertures = [CircularAperture(self.xypos, radius) for radius in
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/photutils/aperture/circle.py", line 148, in __init__
    self.positions = positions
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/photutils/aperture/attributes.py", line 65, in __set__
    self._validate(value)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.17.1.20200915-py38/lib/python3.8/site-packages/photutils/aperture/attributes.py", line 85, in _validate
    raise ValueError('{} must not contain any non-finite (e.g. NaN '
ValueError: positions must not contain any non-finite (e.g. NaN or inf) positions
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485201#comment-485201):_

**complete_short_04a**: ███████████████████████████████████████████████████ with b7.6rc2

**1108-UnsupportedOperandTypes**: calwebb_image2 error in resample step for NRC_IMAGE exposures using F150W, CLEAR (pupil), and SUB400P when calling assign_wcs.util.wcs_from_footprints. WCS-related keywords look bogus: V2_REF=V3_REF=-999, RA_REF=DEC_REF=0, no V1 pointing keywords, all of which suggests set_telescope_pointing failed, which is due to APERNAME='UNKNOWN'. It's a NRCB3 exposure with PPS_APER='NRCB1_SUB400P' (i.e. the PPS aper is for a different detector).

**unknown-1249667338**: calwebb_nrslamp-spec2 error for NRS lamp exposures with OPMODE='NONE'.

**unknown-528175539**: calwebb_detector1 error in ramp_fit step for MIR_IMAGE using FASTGRPAVG, due incorrect NGROUPS=4 value (should be 1).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485254#comment-485254):_

**complete_medium_03**: ███████████████████████████████████████████████████ with b7.6rc2

**1108-UnsupportedOperandTypes**: same calwebb_image2 error as above, due to APERNAME='UNKNOWN'

**1143-Shapes**: same calwebb_detector1 error as above for NIRCam TA images using SUBARRAY='SUB320A335R', due to mismatch in science array size (2048,2048) and DARK data size (320,320). Science exposure claims to be subarray, but data are full-frame.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485256#comment-485256):_

**L2A_large_03**: ███████████████████████████████████████████████████

**1108-UnsupportedOperandTypes**: same as above

**1137-Shapes**: same as above

**1143-Shapes**: same as above

**1236-ErrDeterminingBestRef**: calwebb_detector1 errors determining DARK and READNOISE ref files for a mixture of MIRI and NIRCam images.

**unknown-530653517**: same calwebb_tso-spec2 error as above, failing to find SPECWCS ref file for NRC_TSGRISM with PUPIL='CLEAR'

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485429#comment-485429):_

**remoteOTB1_trimmed_01**: ███████████████████████████████████████████████████

**1116-ErrDeterminingBestRef**: 

**1143-Shapes**:

**1140-AttributeError**: calwebb_image3 error skymatch step ("no attribute 'is_sky_valid'")

**1170-MemoryError**: calwebb_detector1 error in jump step for MIR_4QPM subarray MASK1550 exposure with NGROUPS=250 and NINTS=60 at end of processing last integration (presumably trying to create an output array).

**1235-KeyError**: calwebb_image2 error in photom step for MIR_CORONCAL subarray MASK1140 when using jwst_miri_photom_0042.fits ref file, which is an obsolete ref file with old (incorrect) format.

**1236-ErrDeterminingBestRef**: 

**1238-MemoryError**: calwebb_dark error in refpix step for NRS_DARK exposure using READPATT='NRSIRS2RAPID', NGROUPS=200, NINTS=1.

**1239-MemoryError**: same as 1238-MemoryError

**1240-AssertionError**: calwebb_spec3 error in extract_1d step for NRC_WFSS after having run extract_1d and combine_1d for several slits/sources.

**unknown-522647501**: calwebb_spec2 error "no grism objects created from source catalog" (blank data)

**unknown-919307998**: calwebb_detector1 memory allocation error in jump step for MIR_4QPM subarray MASK1550 with NGROUPS=250, NINTS=60 at the end of processing integration 60 (same as 1170 above).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485447#comment-485447):_

**complete_long_05a**: ███████████████████████████████████████████████████ with b7.6r2

**1108-UnsupportedOperandTypes**: same calwebb_image2 error as above, due to APERNAME='UNKNOWN'

1116-ErrDeterminingBestRef: 

**1130-MemoryError**: calwebb_detector1 error for MIRI LRS fixed-slit exposure mislabeled as MIR_LRS-SLITLESS.

1137-Shapes:

1143-Shapes: 

**1170-MemoryError**: calwebb_detector1 error in jump step for MIR_MRS when trying to allocate only 802MB of memory.

**1202-TypeError**: calwebb_image3 error in skymatch step for MIR_IMAGE exposures.

**1268-MemoryError**: calwebb_detector1 error in dq_init step for MIR_IMAGE full-frame TSO exposure with NGROUPS=5 and NINTS=72 when trying to allocate only 1.4GB

unknown-1249667338: calwebb_nrslamp2 error

**unknown-60161723**: calwebb_spec2 error for MIRI LRS slitless exposure incorrectly labeled as MIR_LRS-FIXEDSLIT.

**unknown-919307998**: calwebb_detector1 memory error for MIR_MRS exposure when trying to allocate only 403MB.

**unknown-820026101**: calwebb_spec3 error in cube_build step for MIR_MRS when using np.amin() "zero-size array to reduction operation minimum which has no idendity". On the surface it looks like garbage data. Should be fixed by JP-1690 (not in B7.6).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485633#comment-485633):_

Run 1642 (remote OTB1): ███████████████████████████████████████████████████

jw00623055 investigation - MIRI LRS Slitless TSO observation (1 exposure) with NINTS=200, NGROUPS=60. Target acq (image) using FASTGRPAVG and F560W. APT pointing file suggests that we should expect a total of 4 exposures: TARG_ACQ (image) at TABLOCK, TARG_ACQ (image) at TASLITLESSPRISM, Verification at SLITLESSPRISM (image), and MIR_LRS-SLITLESS (science spectrum).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485688#comment-485688):_

**EvaluationSuite05**: ███████████████████████████████████████████████████ with b7.6rc2

1143-Shapes: 

226-CalMissingInputFile: Various calwebb_image2, calwebb_spec2, and calwebb_wfs-image3 errors due to failure to find/open the requested input ASN file.

unknown–1387175414: calwebb_detector1 error due to mismatch in shapes between science and ref files.

unknown-522647501: calwebb_spec2 error "no grism objects create from source catalog" (blank images)

unknown-737157582: calwebb_wfs-image2 error determining distortion and flat ref files for NRC_IMAGE with SUB8FP1A subarray. FILTER and PUPIL both = 'N/A'.

unknown-769406701: calwebb_nrslamp-spec2 errors due to OPMODE='NONE'

unknown-918632693: calwebb_image3 error in skymatch step (garbage data).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485695#comment-485695):_

**nOPS7**: ███████████████████████████████████████████████████ with b7.6rc2

No Cal errors. Also no products at all beyond level-2a.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485697#comment-485697):_

**EvaluationSuite03**: ███████████████████████████████████████████████████ with b7.6rc2

No analysis results yet.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1664?focusedCommentId=485760#comment-485760):_

**SOCVALTEST1**: ███████████████████████████████████████████████████ with b7.6rc2

1240-AssertionError: calwebb_spec3 error in extract_1d step for NRC_WFSS after having processed several slits successfully.

unknown-1433615236: calwebb_image3 error in skymatch step for MIR_IMAGE (garbage data?)

unknown-1249667338: calwebb_nrslamp-spec2 errors due to OPMODE='NONE'

unknown-1850301014: calwebb_spec2 errors in background step for NRC_WFSS with GRISMR "cannot convert float NaN to integer"
