### ISSUE TITLE
Level_3 (image3) NRC_IMAGE failure in writing level_2c fits file

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5303]
_Issue [JP-1669](https://jira.stsci.edu/browse/JP-1669) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

Failure observed during SI-MIni rehearsal 2020-Aug-18 for fileset [jw00759-o118_20200818t202034_image3_001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw00759-o118_20200818t202034_image3_001_1597784439.518763) after the outlier_detection step when it tried to write the level_2c fits file but had the error "Floating point nan values are not allowed in FITS headers."

Traceback:
```
2020-08-18 21:01:09,595 - CRDS - DEBUG - getreferences() CRDS version: 7.4.1.3, b7.4.1.3, b38c37e3437101250cbf746e1acc2fbfb34a8005
2020-08-18 21:01:09,595 - CRDS - DEBUG - getreferences() server: https://jwst-serverless-mode.stsci.edu
2020-08-18 21:01:09,595 - CRDS - DEBUG - getreferences() observatory: jwst
2020-08-18 21:01:09,595 - CRDS - DEBUG - getreferences() reftypes: ('abvegaoffset', 'apcorr', 'drizpars')
2020-08-18 21:01:09,595 - CRDS - DEBUG - getreferences() context: None
2020-08-18 21:01:09,595 - CRDS - DEBUG - getreferences() ignore_cache: False
2020-08-18 21:01:09,595 - CRDS - DEBUG - CRDS_PATH = /ifs/archive/ops/jwst/ref/tmp_crds/crds/cache
2020-08-18 21:01:09,595 - CRDS - DEBUG - CRDS_SERVER_URL = https://jwst-serverless-mode.stsci.edu
2020-08-18 21:01:09,596 - CRDS - DEBUG - Final effective context is 'jwst_0619.pmap'
2020-08-18 21:01:09,596 - CRDS - DEBUG - Computing best references locally.
2020-08-18 21:01:09,597 - CRDS - DEBUG - Bestrefs header:
2020-08-18 21:01:09,597 - CRDS - DEBUG - {'META.EXPOSURE.READPATT [READPATT]': 'RAPID',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.EXPOSURE.TYPE [EXP_TYPE]': 'NRC_IMAGE',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.CHANNEL [CHANNEL]': 'SHORT',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.CORONAGRAPH [CORONMSK]': 'UNDEFINED',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NRCB1',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.FILTER [FILTER]': 'F182M',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.MODULE [MODULE]': 'B',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.NAME [INSTRUME]': 'NIRCAM',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.INSTRUMENT.PUPIL [PUPIL]': 'CLEAR',
2020-08-18 21:01:09,597 - CRDS - DEBUG - 'META.OBSERVATION.DATE [DATE-OBS]': '2020-08-18',
2020-08-18 21:01:09,598 - CRDS - DEBUG - 'META.OBSERVATION.TIME [TIME-OBS]': '20:18:16.559',
2020-08-18 21:01:09,598 - CRDS - DEBUG - 'META.SUBARRAY.NAME [SUBARRAY]': 'SUB640',
2020-08-18 21:01:09,598 - CRDS - DEBUG - 'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
2020-08-18 21:01:09,598 - CRDS - DEBUG - 'REFTYPE': 'UNDEFINED'}
2020-08-18 21:01:09,598 - CRDS - DEBUG - Reference type 'abvegaoffset' defined as 'jwst_nircam_abvegaoffset_0001.asdf'
2020-08-18 21:01:09,598 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_nircam_apcorr_0002.fits'
2020-08-18 21:01:09,598 - CRDS - DEBUG - Reference type 'drizpars' defined as 'jwst_nircam_drizpars_0001.fits'
2020-08-18 21:01:09,599 - stpipe.Image3Pipeline - INFO - Prefetch for ABVEGAOFFSET reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_abvegaoffset_0001.asdf'.
2020-08-18 21:01:09,599 - stpipe.Image3Pipeline - INFO - Prefetch for APCORR reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_apcorr_0002.fits'.
2020-08-18 21:01:09,600 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nircam/jwst_nircam_drizpars_0001.fits'.
2020-08-18 21:01:09,604 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2020-08-18 21:01:18,080 - stpipe.Image3Pipeline - INFO - Aligning input images...
2020-08-18 21:01:18,168 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg running with args (<ModelContainer>,).
2020-08-18 21:01:18,170 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3', 'save_catalogs': False, 'catalog_format': 'ecsv', 'kernel_fwhm': 2.5, 'snr_threshold': 10.0, 'brightest': 100, 'peakmax': None, 'enforce_user_order': False, 'expand_refcat': False, 'minobj': 15, 'searchrad': 1.0, 'use2dhist': True, 'separation': 0.5, 'tolerance': 1.0, 'xoffset': 0.0, 'yoffset': 0.0, 'fitgeometry': 'general', 'nclip': 3, 'sigma': 3.0, 'align_to_gaia': False, 'gaia_catalog': 'GAIADR2', 'min_gaia': 5, 'save_gaia_catalog': False}
2020-08-18 21:01:18,332 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/photutils/detection/findstars.py:972: NoDetectionsWarning: Sources were found, but none pass the sharpness and roundness criteria.
'and roundness criteria.', NoDetectionsWarning)

2020-08-18 21:01:18,333 - stpipe.Image3Pipeline.tweakreg - WARNING - No sources found in jw00759118001_02104_00001_nrcb2_cal.fits.
2020-08-18 21:01:18,682 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/photutils/detection/findstars.py:972: NoDetectionsWarning: Sources were found, but none pass the sharpness and roundness criteria.
'and roundness criteria.', NoDetectionsWarning)

2020-08-18 21:01:18,683 - stpipe.Image3Pipeline.tweakreg - WARNING - No sources found in jw00759118001_02104_00001_nrcb4_cal.fits.
2020-08-18 21:01:18,996 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/photutils/detection/findstars.py:972: NoDetectionsWarning: Sources were found, but none pass the sharpness and roundness criteria.
'and roundness criteria.', NoDetectionsWarning)

2020-08-18 21:01:18,997 - stpipe.Image3Pipeline.tweakreg - WARNING - No sources found in jw00759118001_02106_00001_nrcb4_cal.fits.
2020-08-18 21:01:19,144 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/photutils/detection/findstars.py:940: NoDetectionsWarning: No sources were found.
warnings.warn('No sources were found.', NoDetectionsWarning)

<snip>

2020-08-18 21:01:25,241 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch done
2020-08-18 21:01:25,336 - stpipe.Image3Pipeline - INFO - Performing outlier detection on input images...
2020-08-18 21:01:25,412 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<ModelContainer>,).
2020-08-18 21:01:25,413 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': False, 'input_dir': '/ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3', 'weight_type': 'exptime', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'nlow': 0, 'nhigh': 0, 'maskpt': 0.7, 'grow': 1, 'snr': '4.0 3.0', 'scale': '0.5 0.4', 'backg': 0.0, 'save_intermediate_results': False, 'resample_data': True, 'good_bits': '~DO_NOT_USE', 'scale_detection': False}
2020-08-18 21:01:25,418 - stpipe.Image3Pipeline.outlier_detection - INFO - Performing outlier detection on 16 inputs
2020-08-18 21:01:26,419 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:27,352 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:28,039 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:28,657 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:29,348 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:30,372 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:31,069 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:31,715 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:32,373 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:32,947 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:33,513 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:34,087 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:35,086 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:35,971 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:36,646 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:37,238 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (640, 640) --> (2357, 2323)
2020-08-18 21:01:39,220 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting median...
2020-08-18 21:01:39,642 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:40,089 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:40,535 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:40,969 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:41,416 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:41,851 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:42,289 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:42,723 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:43,178 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:44,081 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:44,786 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:45,301 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:45,778 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:46,220 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:47,168 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:47,705 - stpipe.Image3Pipeline.outlier_detection - INFO - Blotting (640, 640) <-- (2357, 2323)
2020-08-18 21:01:47,794 - stpipe.Image3Pipeline.outlier_detection - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/outlier_detection/outlier_detection.py:423: RuntimeWarning: invalid value encountered in greater
tmp1 = np.logical_not(np.greater(diff_noise, t2))

2020-08-18 21:01:47,808 - stpipe.Image3Pipeline.outlier_detection - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/outlier_detection/outlier_detection.py:438: RuntimeWarning: invalid value encountered in greater
np.logical_not(np.greater(diff_noise, xt2) & np.less(tmp2, 9), cr_mask)

2020-08-18 21:01:48,455 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection done
2020-08-18 21:01:48,684 - stpipe.Image3Pipeline - INFO - Writing Level 2c images with updated DQ arrays...
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/bin/strun", line 26, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 156, in from_cmdline
return cmdline.step_from_cmdline(args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 392, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/pipeline/calwebb_image3.py", line 95, in process
suffix=suffix_2c
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/stpipe/step.py", line 880, in save_model
**components
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/model_base.py", line 544, in save
self.to_fits(output_path, *args, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/model_base.py", line 655, in to_fits
with fits_support.to_fits(self._instance, self._schema) as ff:
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/fits_support.py", line 398, in to_fits
_save_from_schema(hdulist, tree, schema)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/fits_support.py", line 351, in _save_from_schema
validator.validate(tree, _schema=schema)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 352, in validate
for error in self.iter_errors(*args, **kwargs):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/asdf/schema.py", line 278, in iter_errors
for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 328, in iter_errors
for error in errors:
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/fits_support.py", line 217, in _fits_comment_section_handler
schema_path=property,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 344, in descend
for error in self.iter_errors(instance, schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/asdf/schema.py", line 278, in iter_errors
for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 328, in iter_errors
for error in errors:
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/fits_support.py", line 217, in _fits_comment_section_handler
schema_path=property,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 344, in descend
for error in self.iter_errors(instance, schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/asdf/schema.py", line 278, in iter_errors
for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 328, in iter_errors
for error in errors:
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/fits_support.py", line 217, in _fits_comment_section_handler
schema_path=property,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 344, in descend
for error in self.iter_errors(instance, schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/asdf/schema.py", line 278, in iter_errors
for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jsonschema/validators.py", line 327, in iter_errors
errors = validator(self, v, instance, _schema) or ()
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/jwst/datamodels/fits_support.py", line 248, in _fits_element_writer
hdu.header.append((fits_keyword, instance, comment), end=True)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/astropy/io/fits/header.py", line 1195, in append
card = Card(*card)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/astropy/io/fits/card.py", line 193, in __init__
self.value = value
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-0.16.1.20200520-py37/lib/python3.7/site-packages/astropy/io/fits/card.py", line 325, in value
"in FITS headers.".format(value))
ValueError: Floating point nan values are not allowed in FITS headers.
! WARNING: Clipped data falls within 1 histogram bin
! WARNING: Clipped data falls within 1 histogram bin
! WARNING: Clipped data falls within 1 histogram bin
! WARNING: Clipped data falls within 1 histogram bin
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
Floating point nan values are not allowed in FITS headers. ```

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-1669?focusedCommentId=480238#comment-480238):_

Data packaged up in ████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-1669?focusedCommentId=480238#comment-480238):_

Data packaged up in ████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1669?focusedCommentId=590497#comment-590497):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) 

With so many pipeline updates since this issue was reported, I'm guessing perhaps this issue is resolved or is another case where the problem was due to the SI mini rehearsal test data?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1669?focusedCommentId=590536#comment-590536):_

I'll see if I can reproduce the problem using B8.0.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1669?focusedCommentId=590545#comment-590545):_

Entire calwebb_image3 pipeline completes successfully using B8.0 (Cal 1.5.2), including the successful creation of the level-2c (crf) products from the outlier_detection step. So this does not appear to be an issue anymore and will close the ticket.
