### ISSUE TITLE
tso_photometry bug in computation of time stamps

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5316]
_Issue [JP-1680](https://jira.stsci.edu/browse/JP-1680) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The tso_photometry step is crashing when processing a set of segmented MIRI imaging TSO data. The input calints products have 0 rows populated in their INT_TIMES table extensions, so the tso_photometry step defaults to computing its own time stamps. But the time stamps are computed based on the total number of integrations in the whole exposure, as opposed to the number of integrations contained in the segment being processed. This leads to a mismatch in the number of time stamps vs. number of photometry results, causing a crash in the astropy table functions.
```java
ERROR RUNNING STEP 'TSOPhotometryStep':
    Inconsistent data column lengths
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bushouse/JWST/softw/jwst/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 162, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 398, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/tso_photometry/tso_photometry_step.py", line 67, in process
    catalog = tso_aperture_photometry(model, xcenter, ycenter,
  File "/Users/bushouse/JWST/softw/jwst/jwst/tso_photometry/tso_photometry.py", line 168, in tso_aperture_photometry
    tbl['aperture_sum'] = aperture_sum
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.8/site-packages/astropy/table/table.py", line 1635, in __setitem__
    self.add_column(value, name=item, copy=True)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.8/site-packages/astropy/table/table.py", line 1916, in add_column
    raise ValueError('Inconsistent data column lengths')
ValueError: Inconsistent data column lengths
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1680?focusedCommentId=483435#comment-483435):_

Fixed by #5318
