### ISSUE TITLE
Error in calwebb_spec3 extract_1d for NIRCam WFSS association

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5331]
_Issue [JP-1693](https://jira.stsci.edu/browse/JP-1693) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The calwebb_spec3 pipeline crashes in the extract_1d step when processing an association of NIRCam WFSS exposures. It successfully processes the data for several slit/sources instances and then crashes on the next slit with:
```java
2020-09-15 08:37:57,283 - stpipe.Spec3Pipeline.extract_1d - INFO - Step extract_1d running with args (<SourceModelContainer>,).
2020-09-15 08:37:57,285 - stpipe.Spec3Pipeline.extract_1d - INFO - Step extract_1d parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': 'x1d', 'search_output_file': True, 'input_dir': '', 'smoothing_length': None, 'bkg_order': None, 'log_increment': 50, 'subtract_background': None, 'use_source_posn': None, 'apply_apcorr': True}
2020-09-15 08:37:57,285 - stpipe.Spec3Pipeline.extract_1d - DEBUG - Environmental "STRICT_VALIDATION" cannot be found. Using default value of "False".
2020-09-15 08:37:57,288 - stpipe.Spec3Pipeline.extract_1d - DEBUG - Input is a SourceModelContainer
2020-09-15 08:37:57,288 - stpipe.Spec3Pipeline.extract_1d - INFO - No EXTRACT1D reference file will be used
2020-09-15 08:37:57,306 - stpipe.Spec3Pipeline.extract_1d - INFO - Using APCORR file ████████████████████████████████████████████████████████████
2020-09-15 08:37:57,306 - stpipe.Spec3Pipeline.extract_1d - DEBUG - Environmental "STRICT_VALIDATION" cannot be found. Using default value of "False".
2020-09-15 08:37:57,335 - stpipe.Spec3Pipeline.extract_1d - DEBUG - Environmental "SKIP_FITS_UPDATE" cannot be found. Using default value of "None".
2020-09-15 08:37:57,335 - stpipe.Spec3Pipeline.extract_1d - DEBUG - No ASDF information found. Cannot skip updating from FITS headers.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':


----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bushouse/JWST/softw/jwst/scripts/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 163, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 399, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_spec3.py", line 215, in process
    result = self.extract_1d(result)
  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 399, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/extract_1d/extract_1d_step.py", line 215, in process
    result = extract.run_extract1d(
  File "/Users/bushouse/JWST/softw/jwst/jwst/extract_1d/extract.py", line 2485, in run_extract1d
    output_model = do_extract1d(
  File "/Users/bushouse/JWST/softw/jwst/jwst/extract_1d/extract.py", line 2621, in do_extract1d
    input_temp = input_model[0]
  File "/Users/bushouse/JWST/softw/jwst/jwst/datamodels/model_base.py", line 703, in __getitem__
    assert isinstance(key, str)
AssertionError
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1693?focusedCommentId=492857#comment-492857):_

Fixed in #5439
