### ISSUE TITLE
FITS cannot write NAN value possibly because SKYMATCH GLOBAL is NAN

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5565]
_Issue [JP-1830](https://jira.stsci.edu/browse/JP-1830) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

`calwebb_image3` is failing with a `ValueError: Floating point nan values are not allowed in FITS headers.` Full traceback is below.

Examining behavior pre-0.18.0, it is noted that the `skymatch` setting of the "Global" sky value correction changed from zero to NAN.

Full traceback:
$ strun cfgs/calwebb_image3.cfg jw00617-o083_20201223t045707_image3_001_asn.json
2020-12-23 07:57:09,604 - CRDS - INFO -  Fetching  /Users/eisenham/Downloads/crds-cache/jwst_op/mappings/jwst/jwst_nircam_gain_0010.rmap    2.3 K bytes  (1 / 3 files) (0 / 7.4 K bytes)
2020-12-23 07:57:09,727 - CRDS - INFO -  Fetching  /Users/eisenham/Downloads/crds-cache/jwst_op/mappings/jwst/jwst_nircam_0145.imap    4.5 K bytes  (2 / 3 files) (2.3 K / 7.4 K bytes)
2020-12-23 07:57:09,844 - CRDS - INFO -  Fetching  /Users/eisenham/Downloads/crds-cache/jwst_op/mappings/jwst/jwst_0645.pmap      580 bytes  (3 / 3 files) (6.8 K / 7.4 K bytes)
2020-12-23 07:57:11,309 - stpipe.Image3Pipeline - INFO - Image3Pipeline instance created.
2020-12-23 07:57:11,310 - stpipe.Image3Pipeline.assign_mtwcs - INFO - AssignMTWcsStep instance created.
2020-12-23 07:57:11,312 - stpipe.Image3Pipeline.tweakreg - INFO - TweakRegStep instance created.
2020-12-23 07:57:11,313 - stpipe.Image3Pipeline.skymatch - INFO - SkyMatchStep instance created.
2020-12-23 07:57:11,314 - stpipe.Image3Pipeline.outlier_detection - INFO - OutlierDetectionStep instance created.
2020-12-23 07:57:11,315 - stpipe.Image3Pipeline.resample - INFO - ResampleStep instance created.
2020-12-23 07:57:11,315 - stpipe.Image3Pipeline.source_catalog - INFO - SourceCatalogStep instance created.
2020-12-23 07:57:11,316 - stpipe - INFO - Hostname: inanna.local.stsci.edu
2020-12-23 07:57:11,316 - stpipe - INFO - OS: Darwin
2020-12-23 07:57:11,366 - stpipe.Image3Pipeline - INFO - Step Image3Pipeline running with args ('jw00617-o083_20201223t045707_image3_001_asn.json',).
2020-12-23 07:57:11,373 - stpipe.Image3Pipeline - INFO - Step Image3Pipeline parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'steps': {'assign_mtwcs': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': 'assign_mtwcs', 'search_output_file': True, 'input_dir': ''}, 'tweakreg': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_catalogs': False, 'catalog_format': 'ecsv', 'kernel_fwhm': 2.5, 'snr_threshold': 10.0, 'brightest': 100, 'peakmax': None, 'enforce_user_order': False, 'expand_refcat': False, 'minobj': 15, 'searchrad': 1.0, 'use2dhist': True, 'separation': 0.5, 'tolerance': 1.0, 'xoffset': 0.0, 'yoffset': 0.0, 'fitgeometry': 'general', 'nclip': 3, 'sigma': 3.0, 'align_to_gaia': False, 'gaia_catalog': 'GAIADR2', 'min_gaia': 5, 'save_gaia_catalog': False}, 'skymatch': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'skymethod': 'global+match', 'match_down': True, 'subtract': False, 'stepsize': None, 'skystat': 'mode', 'dqbits': '0', 'lower': None, 'upper': None, 'nclip': 5, 'lsigma': 4.0, 'usigma': 4.0, 'binwidth': 0.1}, 'outlier_detection': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': False, 'input_dir': '', 'weight_type': 'exptime', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'nlow': 0, 'nhigh': 0, 'maskpt': 0.7, 'grow': 1, 'snr': '4.0 3.0', 'scale': '0.5 0.4', 'backg': 0.0, 'save_intermediate_results': False, 'resample_data': True, 'good_bits': '~DO_NOT_USE', 'scale_detection': False, 'allowed_memory': None}, 'resample': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'weight_type': 'exptime', 'pixel_scale_ratio': 1.0, 'single': False, 'blendheaders': True, 'allowed_memory': None}, 'source_catalog': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': 'cat', 'search_output_file': True, 'input_dir': '', 'bkg_boxsize': 100, 'kernel_fwhm': 3.0, 'snr_threshold': 3.0, 'npixels': 50, 'deblend': False, 'aperture_ee1': 30, 'aperture_ee2': 50, 'aperture_ee3': 70, 'ci1_star_threshold': 2.0, 'ci2_star_threshold': 1.8}}}
2020-12-23 07:57:11,471 - stpipe.Image3Pipeline - INFO - Prefetching reference files for dataset: 'jw00617083001_02102_00001_nrcb3_cal.fits' reftypes = ['abvegaoffset', 'apcorr', 'drizpars']
2020-12-23 07:57:11,477 - stpipe.Image3Pipeline - INFO - Prefetch for ABVEGAOFFSET reference file is '/Users/eisenham/Downloads/crds-cache/jwst_op/references/jwst/nircam/jwst_nircam_abvegaoffset_0001.asdf'.
2020-12-23 07:57:11,477 - stpipe.Image3Pipeline - INFO - Prefetch for APCORR reference file is '/Users/eisenham/Downloads/crds-cache/jwst_op/references/jwst/nircam/jwst_nircam_apcorr_0004.fits'.
2020-12-23 07:57:11,478 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/Users/eisenham/Downloads/crds-cache/jwst_op/references/jwst/nircam/jwst_nircam_drizpars_0001.fits'.
2020-12-23 07:57:11,478 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2020-12-23 07:57:11,901 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch running with args (<ModelContainer>,).
2020-12-23 07:57:11,902 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'skymethod': 'global+match', 'match_down': True, 'subtract': False, 'stepsize': None, 'skystat': 'mode', 'dqbits': '0', 'lower': None, 'upper': None, 'nclip': 5, 'lsigma': 4.0, 'usigma': 4.0, 'binwidth': 0.1}
2020-12-23 07:57:11,951 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,951 - stpipe.Image3Pipeline.skymatch - INFO - ***** jwst.skymatch.skymatch.match() started on 2020-12-23 07:57:11.951810
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO - Sky computation method: 'global+match'
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO - Sky matching direction: DOWN
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO - Sky subtraction from image data: OFF
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO - ----  Computing differences in sky values in overlapping regions.
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - WARNING -    *  Group ID=1: Unable to compute sky value
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -    *  Group ID=1. Sky background of component images:
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb3_cal.fits. Sky background: 0
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb1_cal.fits. Sky background: 0
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb2_cal.fits. Sky background: 0
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb4_cal.fits. Sky background: 0
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,952 - stpipe.Image3Pipeline.skymatch - INFO - ----  Computing "global" sky - smallest sky value across **all** input images.
! WARNING: Clipped data falls within 1 histogram bin
! WARNING: Clipped data falls within 1 histogram bin
! WARNING: Clipped data falls within 1 histogram bin
! WARNING: Clipped data falls within 1 histogram bin
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -    "Global" sky value correction: nan [not converted]
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO - ----  Final (match+global) sky for:
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -    *  Group ID=1. Sky background of component images:
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb3_cal.fits. Sky background: NAN (old=0, delta=NAN)
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb1_cal.fits. Sky background: NAN (old=0, delta=NAN)
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb2_cal.fits. Sky background: NAN (old=0, delta=NAN)
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -       - Image ID=jw00617083001_02102_00001_nrcb4_cal.fits. Sky background: NAN (old=0, delta=NAN)
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,953 - stpipe.Image3Pipeline.skymatch - INFO - ***** jwst.skymatch.skymatch.match() ended on 2020-12-23 07:57:11.953726
2020-12-23 07:57:11,954 - stpipe.Image3Pipeline.skymatch - INFO - ***** jwst.skymatch.skymatch.match() TOTAL RUN TIME: 0:00:00.001916
2020-12-23 07:57:11,954 - stpipe.Image3Pipeline.skymatch - INFO -
2020-12-23 07:57:11,957 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch done
2020-12-23 07:57:12,008 - stpipe.Image3Pipeline.resample - INFO - Step resample running with args (<ModelContainer>,).
2020-12-23 07:57:12,009 - stpipe.Image3Pipeline.resample - INFO - Step resample parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': 'i2d', 'search_output_file': True, 'input_dir': '', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'weight_type': 'exptime', 'pixel_scale_ratio': 1.0, 'single': False, 'blendheaders': True, 'allowed_memory': None}
2020-12-23 07:57:12,014 - stpipe.Image3Pipeline.resample - INFO - Drizpars reference file: /Users/eisenham/Downloads/crds-cache/jwst_op/references/jwst/nircam/jwst_nircam_drizpars_0001.fits
2020-12-23 07:57:12,149 - stpipe.Image3Pipeline.resample - INFO - Blending metadata for jw00617-o083_t001_nircam_clear-f090w-sub160
2020-12-23 07:57:12,913 - stpipe.Image3Pipeline.resample - INFO - Drizzling (160, 160) --> (458, 477)
2020-12-23 07:57:13,085 - stpipe.Image3Pipeline.resample - INFO - Drizzling (160, 160) --> (458, 477)
2020-12-23 07:57:13,213 - stpipe.Image3Pipeline.resample - INFO - Drizzling (160, 160) --> (458, 477)
2020-12-23 07:57:13,353 - stpipe.Image3Pipeline.resample - INFO - Drizzling (160, 160) --> (458, 477)
2020-12-23 07:57:13,372 - stpipe.Image3Pipeline.resample - INFO - Update S_REGION to POLYGON ICRS  177.430791938 50.175148708 177.434425793 50.171963607 177.439605397 50.174387314 177.435971703 50.177572578
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    Floating point nan values are not allowed in FITS headers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jwst/stpipe/step.py", line 164, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline
    step.run(*positional)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jwst/stpipe/step.py", line 400, in run
    step_result = self.process(*args)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jwst/pipeline/calwebb_image3.py", line 95, in process
    result = self.resample(input_models)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jwst/stpipe/step.py", line 455, in run
    self.save_model(result, idx=idx)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jwst/stpipe/step.py", line 888, in save_model
    output_path = model.save(
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/model_base.py", line 510, in save
    self.to_fits(output_path, *args, **kwargs)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/model_base.py", line 622, in to_fits
    with fits_support.to_fits(self._instance, self._schema) as ff:
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 396, in to_fits
    _save_from_schema(hdulist, tree, schema)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 353, in _save_from_schema
    validator.validate(tree, _schema=schema)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 352, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/asdf/schema.py", line 319, in iter_errors
    for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 215, in _fits_comment_section_handler
    for error in validator.descend(
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/asdf/schema.py", line 319, in iter_errors
    for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 215, in _fits_comment_section_handler
    for error in validator.descend(
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/asdf/schema.py", line 319, in iter_errors
    for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 215, in _fits_comment_section_handler
    for error in validator.descend(
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/asdf/schema.py", line 319, in iter_errors
    for x in super(ASDFValidator, self).iter_errors(instance, _schema=schema):
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/jsonschema/validators.py", line 327, in iter_errors
    errors = validator(self, v, instance, _schema) or ()
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 250, in _fits_element_writer
    hdu.header.append((fits_keyword, instance, comment), end=True)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/astropy/io/fits/header.py", line 1203, in append
    card = Card(*card)
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/astropy/io/fits/card.py", line 193, in *_init_*
    self.value = value
  File "/Users/eisenham/miniconda3/envs/jwst-0.18.0/lib/python3.9/site-packages/astropy/io/fits/card.py", line 324, in value
    raise ValueError("Floating point {!r} values are not allowed "
ValueError: Floating point nan values are not allowed in FITS headers.

**Comment by jdavies-st** [comment]
Well, it's definitely being produced by `skymatch`.  And the only change since 0.17.1 was

https://github.com/spacetelescope/jwst/pull/5440

I wonder if @mcara could have a look?

**Comment by jdavies-st** [comment]
I'll add that the dataset here is complete garbage in the data arrays.  Not even close to being physical.  Huge negative values.

**Comment by mcara** [comment]
I have a couple of questions: Why is this detected only today and not, let's say a week ago? Is this test not run daily? If so, how can I get the test data to run just the `skymach` step?

Thanks!

**Comment by jdavies-st** [comment]
This is DMS data.  We don't run it as part of our regression tests.

Data location is listed in the JIRA ticket under "data location"

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1830?focusedCommentId=501732#comment-501732):_

Fixed by #5567
