### ISSUE TITLE
source_catalog step crashing for some FGS images

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5572]
_Issue [JP-1834](https://jira.stsci.edu/browse/JP-1834) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

[Mike Swam](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mswam) reports a handful of the calwebb_image3 failures all involving FGS imaging, due to the source_catalog step crashing with a traceback of:

```

2020-12-30 14:28:54,198 - stpipe.source_catalog - INFO - Instrument: FGS

2020-12-30 14:28:54,199 - stpipe.source_catalog - INFO - Detector: GUIDER2

2020-12-30 14:28:54,199 - stpipe.source_catalog - INFO - Subarray: FULL

2020-12-30 14:28:54,257 - stpipe.source_catalog - DEBUG - No ASDF information found. Cannot skip updating from FITS headers.

2020-12-30 14:28:54,330 - stpipe.source_catalog - INFO - AB to Vega magnitude offset 1.22852

2020-12-30 14:29:00,181 - stpipe.source_catalog - INFO - Detected 2036 sources

----------------------------------------------------------------------

ERROR RUNNING STEP 'SourceCatalogStep':

    positions must not contain any non-finite (e.g., NaN or inf)

    positions

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/bushouse/JWST/softw/jwst/scripts/strun", line 26, in <module>

    step = Step.from_cmdline(sys.argv[1:])

  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 164, in from_cmdline

    return cmdline.step_from_cmdline(args)

  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/cmdline.py", line 346, in step_from_cmdline

    step.run(*positional)

  File "/Users/bushouse/JWST/softw/jwst/jwst/stpipe/step.py", line 400, in run

    step_result = self.process(*args)

  File "/Users/bushouse/JWST/softw/jwst/jwst/source_catalog/source_catalog_step.py", line 113, in process

    catalog = catobj.catalog

  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/astropy/utils/decorators.py", line 758, in *_get_*

    val = self.fget(obj)

  File "/Users/bushouse/JWST/softw/jwst/jwst/source_catalog/source_catalog.py", line 1341, in catalog

    self.set_aperture_properties()

  File "/Users/bushouse/JWST/softw/jwst/jwst/source_catalog/source_catalog.py", line 928, in set_aperture_properties

    apertures = [CircularAperture(self.xypos, radius) for radius in

  File "/Users/bushouse/JWST/softw/jwst/jwst/source_catalog/source_catalog.py", line 928, in <listcomp>

    apertures = [CircularAperture(self.xypos, radius) for radius in

  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/photutils/aperture/circle.py", line 148, in *_init_*

    self.positions = positions

  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/photutils/aperture/attributes.py", line 62, in *_set_*

    self._validate(value)

  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/photutils/aperture/attributes.py", line 80, in _validate

    raise ValueError('{} must not contain any non-finite (e.g., NaN '

ValueError: positions must not contain any non-finite (e.g., NaN or inf) positions

```

**Comment by nden** [comment]
@hbushouse Close?

**Comment by hbushouse** [comment]
Yes, somehow we got duplicate issues created (#5572 and #5573). I blame the gitbot.
