### ISSUE TITLE
Ramp fit fails with multiprocessing

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5756]
_Issue [JP-1926](https://jira.stsci.edu/browse/JP-1926) was created on JIRA by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert):_

The ramp-fitting step crashes for me when I try to use multiprocessing (e.g. when I set ramp_fit.maximum_cores = 'quarter'). When I run the same script with multiprocessing turned off, ramp-fitting completes successfully. The traceback is below. My data are full frame NIRCam exposures. The strange array size mentioned in the traceback makes me think it must have something to do with the way multiprocessing is dividing the data. Note that I also have ramp_fit.save_opt set to True.

Here is my pipeline call:

 

from jwst.pipeline import Detector1Pipeline

cal = Detector1Pipeline()
 cal.dark_current.skip = True
 cal.persistence.skip = True

cal.jump.rejection_threshold = 9
 cal.jump.maximum_cores = 'quarter'
 cal.jump.save_results = True

cal.ramp_fit.save_opt = True
 #cal.ramp_fit.maximum_cores = 'quarter'

cal.output_dir = os.path.dirname(filename)
 cal.save_results = True
 cal.run(filename)

 

 

`2021-02-16 16:25:58,683 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:25:58,683 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:25:59,060 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:25:59,060 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:25:59,393 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:25:59,393 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:25:59,854 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:25:59,854 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:26:00,511 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:26:00,511 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:26:27,069 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:26:27,069 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:26:27,280 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108`

`2021-02-16 16:26:27,280 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`2021-02-16 16:26:29,603 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of groups per integration: 108``2`

`021-02-16 16:26:29,603 - stpipe.Detector1Pipeline.ramp_fit - INFO - Number of integrations: 1`

`Traceback (most recent call last):``  File "█████████████████████████████████████████████████████████████████████████████████████████████ line 63, in <module>``    cal.run(filename)``  `

`File "/user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/stpipe/step.py", line 400, in run``    step_result = self.process(*args)``  `

`File "/user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_detector1.py", line 132, in process``    result, ints_model = self.ramp_fit(result)``  `

`File "/user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/stpipe/step.py", line 400, in run``    step_result = self.process(*args)``  `

`File "/user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit_step.py", line 70, in process``    out_model, int_model, opt_model, gls_opt_model = ramp_fit.ramp_fit(``  `

`File "/user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py", line 109, in ramp_fit``    ols_ramp_fit_multi(model, buffsize, save_opt, readnoise_2d,``  `

`File "/user/hilbert/anaconda2/envs/jwst-py3.9/lib/python3.9/site-packages/jwst/ramp_fitting/ramp_fit.py", line 341, in ols_ramp_fit_multi``    opt_model.slope[:, :, start_row: (k + 1) *rows_per_slice, :] = resultslice[11]`

`ValueError: could not broadcast input array from shape (1,3,171,2048) into shape (1,2,171,2048)`

**Comment by stscijgbot-jp** [comment]
_Comment by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald) on [JIRA](https://jira.stsci.edu/browse/JP-1926?focusedCommentId=541248#comment-541248):_

The implementation for multiprocessing has been changed and properly account for the variable nature of the dimensions for the optional results value.  This previously caused problems with multiprocessing since the dimensions of the optional results depend on the properties of the sliced data.  Upon reassembly of the resultant outputs from each process into a single data product, the software now properly accounts for this variability.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald) on [JIRA](https://jira.stsci.edu/browse/JP-1926?focusedCommentId=541249#comment-541249):_

Multiprocessing for ramp fitting has been refactored and now properly reassembles results from each process to account for the variability that can occur in each "slice" of the data during reassembly of the "sliced" return results.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kenneth MacDonald](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kmacdonald) on [JIRA](https://jira.stsci.edu/browse/JP-1926?focusedCommentId=541791#comment-541791):_

This issue is resolved with PR: spacetelescope/stcal#30

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-1926?focusedCommentId=564214#comment-564214):_

I think this issue is resolved now, [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) let me know if you disagree. I'll go ahead and close it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1926?focusedCommentId=564252#comment-564252):_

Fixed by <https://github.com/spacetelescope/stcal/pull/30,> which will be included in B7.9.
