### ISSUE TITLE
flat-field failing for imaging mode NRS lamp exposures

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5793]
_Issue [JP-1942](https://jira.stsci.edu/browse/JP-1942) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

A recent change to ASN rules ([https://github.com/spacetelescope/jwst/pull/5740)] directs all NRS lamp exposures with OPMODE='IMAGE' and GRATING='MIRROR' to the calwebb_image2 pipeline for level-2b processing, rather than the calwebb_spec2 pipeline. Unfortunately it appears that the flat-field step is not setup to correctly recognize such exposures as being imaging cases and hence attempts to process as spectroscopic, which naturally fails. The traceback is:
```java
2021-02-26 09:15:56,247 - stpipe.Image2Pipeline.flat_field - INFO - Step flat_field running with args (<ImageModel(2048, 2048) from jw00620029001_02106_00001_nrs2_rate.fits>,).
2021-02-26 09:15:56,248 - stpipe.Image2Pipeline.flat_field - INFO - Step flat_field parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_interpolated_flat': False, 'user_supplied_flat': None, 'inverse': False}
2021-02-26 09:17:32,662 - stpipe.Image2Pipeline.flat_field - WARNING - Can't determine dispaxis, assuming horizontal.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image2Pipeline':
    No flat field algorithm exists for handling data <ImageModel(2048,
    2048) from jw00620029001_02106_00001_nrs2_rate.fits>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/jwstdev/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_image2.py", line 66, in process
    result = self.process_exposure_product(
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_image2.py", line 152, in process_exposure_product
    input = self.flat_field(input)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field_step.py", line 122, in process
    output_model, flat_applied = flat_field.do_correction(
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 78, in do_correction
    flat_applied = do_nirspec_flat_field(output_model, fflat, sflat, dflat,
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 299, in do_nirspec_flat_field
    raise RuntimeError(f'No flat field algorithm exists for handling data {output_model}')
RuntimeError: No flat field algorithm exists for handling data <ImageModel(2048, 2048) from jw00620029001_02106_00001_nrs2_rate.fits>
```
This appears to be due to the fact that the flat-field step is currently setup to treat any exposure with EXP_TYPE='NRS_LAMP' as a spectroscopic mode. An additional check based on either OPMODE='IMAGE' or GRATING='MIRROR' should be added, so that exposures with those values go through the imaging branch of flat-fielding.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-1942?focusedCommentId=524489#comment-524489):_

After discussion with the NIRSpec team, it's been decided that these exposures should probably skip the flat_field step during processing. This ticket has been sent to the INS team to create an rmap in CRDS for this exposure setting, skipping the flat_field step there.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1942?focusedCommentId=531714#comment-531714):_

Given that this is to be resolved by a CRDS rmap update, can this JP ticket be closed?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1942?focusedCommentId=538886#comment-538886):_

Fixed via CRDS rmap update. No Cal pipeline work needed.
