### ISSUE TITLE
pars-sourcecatalogstep reffile defining output_ext produces ValueError

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5831]
_Issue [JP-1958](https://jira.stsci.edu/browse/JP-1958) was created on JIRA by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies):_

When using a pars reffile for `SourceCatalogStep` that has `output_ext` defined, we get the following error in our regression tests:

<https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/1112/testReport/junit/jwst.regtest/test_miri_image/_stable_deps__test_miri_image3_catalog/>

```
Traceback (most recent call last):
  File "/Users/jdavies/miniconda3/envs/jwst/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/source_catalog/source_catalog_step.py", line 124, in process
    self.save_model(segm_model, suffix='segm')
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 918, in save_model
    output_path = model.save(
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stdatamodels/model_base.py", line 515, in save
    raise ValueError("unknown filetype {0}".format(ext))
ValueError: unknown filetype .ecsv
```

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-1958?focusedCommentId=525370#comment-525370):_

This was resolved by delivering a new reffile.  See

<https://jira.stsci.edu/browse/CRDS-411>
