### ISSUE TITLE
Test suite error in assign_mtwcs

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5842]
_Issue [JP-1964](https://jira.stsci.edu/browse/JP-1964) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

During run of the SOR7/nOPS10 test suite, a error was encountered while running assign_mtwcs on the association jw00634-o044_20210307t130334_image3_001_asn.json.

Error trace below:

```python
2021-03-07 14:29:58,389 - stpipe.Image3Pipeline.assign_mtwcs - INFO - Step assign_mtwcs parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': 'assign_mtwcs', 'search_output_file': True, 'input_dir': '/ifs/archive/test/jwst/store/rspencer/tests/SOR7-nOPS10-OTB/dtest2/JWSTDP-2021.1.0-44~ca4af842/2021-03-07-122635/sdp/asn_creation/cal/level3'}
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    cannot reshape array of size 0 into shape (400,400)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_image3.py", line 83, in process
    input_models = self.assign_mtwcs(input_models)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/jwst/assign_mtwcs/assign_mtwcs_step.py", line 40, in process
    result = assign_moving_target_wcs(input)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/jwst/assign_mtwcs/moving_target_wcs.py", line 59, in assign_moving_target_wcs
    model.meta.wcs = new_wcs
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stdatamodels/properties.py", line 319, in __setattr__
    if node._validate():
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stdatamodels/properties.py", line 262, in _validate
    return validate.value_change(self._name, self._instance, self._schema, self._ctx)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stdatamodels/validate.py", line 23, in value_change
    _check_value(value, schema, ctx)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/stdatamodels/validate.py", line 49, in _check_value
    value = yamlutil.custom_tree_to_tagged_tree(value, ctx._asdf)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/asdf/yamlutil.py", line 230, in custom_tree_to_tagged_tree
    return treeutil.walk_and_modify(
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.1.0.20210226-py38/lib/python3.8/site-packages/asdf/treeutil.py", line 406, in walk_and_modify
    return _recurse(top)
```

This is followed by many lines of recursive calls.

EDIT: After moving the relevant files to a public location and trying a quick run, it seems to have passed successfully. Unclear to me what this means for the test suite error.

**Comment by hbushouse** [comment]
Error no longer appears in B7.8 processing runs.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-1964?focusedCommentId=534344#comment-534344):_

D2 string run2280, processed on 10-Jun-2021 using Cal v1.2.3 and the latest B7.8 SDP succeeded in creating all 4 expected level-3 products for jw00634-o044:

```
-rwxrwxr-x. 3 mswam dms 10373760 Jun 10 14:11 ../level3/jw00634-o044_t020_nircam_clear-f090w-sub400p_i2d.fits
-rwxrwxr-x. 3 mswam dms 10414080 Jun 10 14:11 ../level3/jw00634-o044_t020_nircam_clear-f200w-sub400p_i2d.fits
-rwxrwxr-x. 3 mswam dms  7208640 Jun 10 14:11 ../level3/jw00634-o044_t020_nircam_clear-f277w-sub400p_i2d.fits
-rwxrwxr-x. 3 mswam dms  7228800 Jun 10 14:12 ../level3/jw00634-o044_t020_nircam_clear-f335m-sub400p_i2d.fits
```

so I'm declaring this issue to be closed.
