### ISSUE TITLE
NIRSpec MOS slitlet with only 1 pixel on detector crashes flat-field step

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5921]
_Issue [JP-2022](https://jira.stsci.edu/browse/JP-2022) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The NIRSpec MOS dataset jw00643036001_03101_00002_nrs1_rate.fits crashes in the calwebb_spec2 flat-field step with the error:
```java
2021-03-30 08:30:38,268 - stpipe.Spec2Pipeline.flat_field - INFO - Working on slit 80
Traceback (most recent call last):
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_spec2.py", line 112, in process
    result = self.process_exposure_product(
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_spec2.py", line 241, in process_exposure_product
    calibrated = self._process_nirspec_slits(calibrated)
  File "/Users/bushouse/JWST/softw/jwst/jwst/pipeline/calwebb_spec2.py", line 391, in _process_nirspec_slits
    calibrated = self.flat_field(calibrated)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field_step.py", line 122, in process
    output_model, flat_applied = flat_field.do_correction(
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 78, in do_correction
    flat_applied = do_nirspec_flat_field(output_model, fflat, sflat, dflat,
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 304, in do_nirspec_flat_field
    return nirspec_fs_msa(output_model, f_flat_model, s_flat_model, d_flat_model, dispaxis,
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 399, in nirspec_fs_msa
    slit_flat = flat_for_nirspec_slit(
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 1999, in flat_for_nirspec_slit
    flat_2d, flat_dq_2d, flat_err_2d = create_flat_field(wl,
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 635, in create_flat_field
    f_flat, f_flat_dq, f_flat_err = fore_optics_flat(
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 764, in fore_optics_flat
    f_flat, f_flat_dq = combine_fast_slow(wl, flat_2d, f_flat_dq,
  File "/Users/bushouse/JWST/softw/jwst/jwst/flatfield/flat_field.py", line 1299, in combine_fast_slow
    dwl[:, -1] = dwl[:, -2]
IndexError: index -2 is out of bounds for axis 1 with size 1
```
which is due to the fact that slitlet 80 was extracted with only 1 pixel along the wavelength axis:
```java
2021-03-30 08:25:10,412 - stpipe.Spec2Pipeline.extract_2d - INFO - Name of subarray extracted: 80
2021-03-30 08:25:10,412 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray x-extents are: 2047 2048
2021-03-30 08:25:10,412 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray y-extents are: 1335 1357
```
Note that the values listed in the log messages are actual python array slice indexes, hence a range of [2047:2048] results in only 1 pixel being extracted in the X direction. This crashes the flat-field step when it attempts an operation that uses 2 values along the X (wavelength) direction of the slit array.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2022?focusedCommentId=518808#comment-518808):_

Triggered by <https://jtar.stsci.edu/browse/JWSTDMSDR-5704>

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2022?focusedCommentId=520705#comment-520705):_

Fixed by #5948

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2022?focusedCommentId=532318#comment-532318):_

This dataset was last processed on D2 in run2279 using CAL_VER=1.2.3 (the latest B7.8 release candidate). Level-1b and level-2a products were created, but nothing beyond that. I don't see any level-2b spec2 ASN tables for this program, so that would explain why no further processing was triggered. Investigating why no ASN tables were created. Perhaps a completeness issue at level-1?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2022?focusedCommentId=532323#comment-532323):_

When I run asn_generate manually on jw00643_20210610t030530_pool.csv I get spec2 and spec3 ASN's generated for jw00643-o036, but these ASN's don't appear in the DMS processing run.

Furthermore, when I process the jw00643036001_03101_00002_nrs1_rate.fits manually through calwebb_spec2, processing completes successfully.

So if ASN's had been created and used for processing in the DMS test environment, I believe it would've been successful. So the question is, why weren't any ASN's created?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2022?focusedCommentId=532544#comment-532544):_

Mike Swam confirms that level-1b completeness was not satisfied during regular DMS processing, so the ASN generator never got triggered for these observations. Manual processing shows that the error in obs 36 is gone and the remaining error in obs 29 is not our problem. Case closed.
