### ISSUE TITLE
NIRSpec wavecor step in spec2 crashes with ALLSLITS data

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#5940]
_Issue [JP-2034](https://jira.stsci.edu/browse/JP-2034) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

This Fixed Slit ALLSLITS data set crashes the wavecor step for detector NRS1 with the following traceback:

(pipedev) scully:G140H_F100LP pena$ strun jwst.wavecorr.WavecorrStep fs_allslits_g140h_f100lp_nrs1_sourcetypestep.fits 
----------------------------------------------------------------------
ERROR RUNNING STEP 'WavecorrStep':
 Frame v2v3 is not in the available frames
----------------------------------------------------------------------
Traceback (most recent call last):
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/gwcs/wcs.py", line 166, in get_transform
 from_ind = self._get_frame_index(from_frame)
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/gwcs/wcs.py", line 258, in _get_frame_index
 return frame_names.index(frame)
ValueError: 'v2v3' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/Users/pena/anaconda3/envs/pipedev/bin/strun", line 28, in <module>
 step = Step.from_cmdline(sys.argv[1:])
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/stpipe/step.py", line 173, in from_cmdline
 return cmdline.step_from_cmdline(args)
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
 step.run(*positional)
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
 step_result = self.process(*args)
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/jwst/wavecorr/wavecorr_step.py", line 62, in process
 output_model = wavecorr.do_correction(input_model, reffile)
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/jwst/wavecorr/wavecorr.py", line 59, in do_correction
 apply_zero_point_correction(slit, wavecorr_file)
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/jwst/wavecorr/wavecorr.py", line 91, in apply_zero_point_correction
 source_xpos = get_source_xpos(slit, slit_wcs, lam=2,
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/jwst/wavecorr/wavecorr.py", line 256, in get_source_xpos
 v2v3_to_msa_frame = slit_wcs.get_transform("v2v3", "msa_frame")
 File "/Users/pena/anaconda3/envs/pipedev/lib/python3.9/site-packages/gwcs/wcs.py", line 168, in get_transform
 raise CoordinateFrameError("Frame \{0} is not in the available "
gwcs.utils.CoordinateFrameError: Frame v2v3 is not in the available frames

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2034?focusedCommentId=520439#comment-520439):_

Same data problem as reported in another ticket. The file names claim that the F100LP filter is in use, but FILTER='OPAQUE' in the data files. There's no coverage in CRDS for an AREA ref file with FILTER='OPAQUE'. If I recall correctly, that filter setting is only ever used for darks and lamp exposures. If this is intended to be processed as a lamp exposure, then it should have the appropriate EXP_TYPE, LAMP, and OPMODE settings expected for a lamp exposure. Or the FILTER keyword value simply needs to be changed to 'F100LP'. When I change the value of the FILTER keyword it runs fine.

Also, the value of the FXD_SLIT keyword in these data files is inappropriate. It's set to 'ALLSLITS'. The purpose of the FXD_SLIT keyword is to tell the software which **one** of the 5 fixed slits is the primary slit, i.e. has the target of interest in it. So it needs to be set to the name of one of the individual slits, such as 'S200A1' or 'S1600A1'. Certain calibration steps rely on knowing which one of the slits has the target in it.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-2034?focusedCommentId=521027#comment-521027):_

Thanks Howard. With these fixes the data does run.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-2034?focusedCommentId=521028#comment-521028):_

Fixed
