### ISSUE TITLE
Error in tweakreg calculations for set of NIRISS images - bad data?

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6112]
_Issue [JP-2127](https://jira.stsci.edu/browse/JP-2127) was created on JIRA by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly):_

During a test suite run of a set of NIRISS images through calwebb_image3, an error is reported in skymatch:

```python
2021-05-29 21:14:43,413 - stpipe.Image3Pipeline.skymatch - INFO - ----  Computing differences in sky values in overlapping regions.
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
    intersection: find all intersections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_image3.py", line 87, in process
    input_models = self.skymatch(input_models)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/skymatch/skymatch_step.py", line 96, in process
    match(images, skymethod=self.skymethod, match_down=self.match_down,
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/skymatch/skymatch.py", line 305, in match
    sky_deltas = _find_optimum_sky_deltas(images, apply_sky=not subtract)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/skymatch/skymatch.py", line 500, in _find_optimum_sky_deltas
    A, W = _overlap_matrix(images, apply_sky=apply_sky)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/skymatch/skymatch.py", line 479, in _overlap_matrix
    s1, w1, area1 = images[i].calc_sky(
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/skymatch/skyimage.py", line 395, in calc_sky
    intersection = self.intersection(overlap)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/jwst/skymatch/skyimage.py", line 231, in intersection
    return self._polygon.intersection(skyimage.polygon)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/spherical_geometry/polygon.py", line 1209, in intersection
    subpolygons = polya.intersection(polyb)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/spherical_geometry/polygon.py", line 664, in intersection
    return g.intersection()
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/spherical_geometry/graph.py", line 440, in intersection
    self._sanity_check("intersection: find all intersections")
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.2.0.20210524-py38/lib/python3.8/site-packages/spherical_geometry/graph.py", line 392, in _sanity_check
    raise MalformedPolygonError(msg)
spherical_geometry.polygon.MalformedPolygonError: intersection: find all intersections
```

However, in the log above skymatch, for tweakreg, some calculation results appear strange:

```python
2021-05-29 21:14:42,441 - stpipe.Image3Pipeline.tweakreg - INFO - Selected image 'GROUP ID: jw00660020001_06101_00001_nis_cal' as reference image
2021-05-29 21:14:42,445 - stpipe.Image3Pipeline.tweakreg - INFO - Aligning image catalog 'GROUP ID: jw00660020001_04101_00002_nis_cal' to the reference catalog.
2021-05-29 21:14:42,623 - stpipe.Image3Pipeline.tweakreg - INFO - Matching sources from 'jw00660020001_04101_00002_nis_cal' catalog with sources from the reference 'jw00660020001_06101_00001_nis_cal' catalog.
2021-05-29 21:14:42,624 - stpipe.Image3Pipeline.tweakreg - INFO - Computing initial guess for X and Y shifts...
2021-05-29 21:14:42,624 - stpipe.Image3Pipeline.tweakreg - INFO - Found peak in the 2D histogram lies at the edge of the histogram. Try increasing 'searchrad' for improved results.
2021-05-29 21:14:42,624 - stpipe.Image3Pipeline.tweakreg - WARNING - Unable to estimate significance of the detection of the initial shift.
2021-05-29 21:14:42,624 - stpipe.Image3Pipeline.tweakreg - INFO - Found initial X and Y shifts of 1, -1 with 2 matches.
2021-05-29 21:14:42,625 - stpipe.Image3Pipeline.tweakreg - INFO - Found 3 matches for 'GROUP ID: jw00660020001_04101_00002_nis_cal'...
2021-05-29 21:14:42,625 - stpipe.Image3Pipeline.tweakreg - WARNING - The number of sources for the fit is smaller than the minimum number of sources necessary for the requested 'fitgeom'.
2021-05-29 21:14:42,625 - stpipe.Image3Pipeline.tweakreg - WARNING - Resetting number of clipping iterations to 0.
2021-05-29 21:14:42,625 - stpipe.Image3Pipeline.tweakreg - INFO - Performing 'general' fit
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO - Computed 'general' fit for GROUP ID: jw00660020001_04101_00002_nis_cal:
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO - XSH: -2.16192e+18  YSH: -1.72954e+19    PROPER ROT: -135
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO - <ROT>: -37.875  SKEW: 90    ROT_X: 97.125  ROT_Y: -172.875
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO - <SCALE>: 0  SCALE_X: 2.90473e+17  SCALE_Y: 7.26184e+16
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO -
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO - FIT RMSE: 7.23651e+16   FIT MAE: 6.82265e+16
2021-05-29 21:14:42,627 - stpipe.Image3Pipeline.tweakreg - INFO - Final solution based on 3 objects.
2021-05-29 21:14:42,669 - stpipe.Image3Pipeline.tweakreg - INFO - Aligning image catalog 'GROUP ID: jw00660020001_04101_00001_nis_cal' to the reference catalog.
2021-05-29 21:14:42,840 - stpipe.Image3Pipeline.tweakreg - INFO - Matching sources from 'jw00660020001_04101_00001_nis_cal' catalog with sources from the reference 'jw00660020001_06101_00001_nis_cal' catalog.
2021-05-29 21:14:42,841 - stpipe.Image3Pipeline.tweakreg - INFO - Computing initial guess for X and Y shifts...
2021-05-29 21:14:42,841 - stpipe.Image3Pipeline.tweakreg - INFO - Found peak in the 2D histogram lies at the edge of the histogram. Try increasing 'searchrad' for improved results.
2021-05-29 21:14:42,841 - stpipe.Image3Pipeline.tweakreg - WARNING - Unable to estimate significance of the detection of the initial shift.
2021-05-29 21:14:42,841 - stpipe.Image3Pipeline.tweakreg - INFO - Found initial X and Y shifts of 1, -1 with 2 matches.
2021-05-29 21:14:42,842 - stpipe.Image3Pipeline.tweakreg - INFO - Found 3 matches for 'GROUP ID: jw00660020001_04101_00001_nis_cal'...
2021-05-29 21:14:42,842 - stpipe.Image3Pipeline.tweakreg - WARNING - The number of sources for the fit is smaller than the minimum number of sources necessary for the requested 'fitgeom'.
2021-05-29 21:14:42,842 - stpipe.Image3Pipeline.tweakreg - WARNING - Resetting number of clipping iterations to 0.
2021-05-29 21:14:42,842 - stpipe.Image3Pipeline.tweakreg - INFO - Performing 'general' fit
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO - Computed 'general' fit for GROUP ID: jw00660020001_04101_00001_nis_cal:
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO - XSH: -2.16192e+18  YSH: -1.72954e+19    PROPER ROT: -135
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO - <ROT>: -37.875  SKEW: 90    ROT_X: 97.125  ROT_Y: -172.875
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO - <SCALE>: 0  SCALE_X: 2.90473e+17  SCALE_Y: 7.26184e+16
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO -
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO - FIT RMSE: 7.23651e+16   FIT MAE: 6.82265e+16
2021-05-29 21:14:42,844 - stpipe.Image3Pipeline.tweakreg - INFO - Final solution based on 3 objects.
2021-05-29 21:14:42,884 - stpipe.Image3Pipeline.tweakreg - INFO - Aligning image catalog 'GROUP ID: jw00660020001_02101_00001_nis_cal' to the reference catalog.
2021-05-29 21:14:43,052 - stpipe.Image3Pipeline.tweakreg - INFO - Matching sources from 'jw00660020001_02101_00001_nis_cal' catalog with sources from the reference 'jw00660020001_06101_00001_nis_cal' catalog.
2021-05-29 21:14:43,052 - stpipe.Image3Pipeline.tweakreg - INFO - Computing initial guess for X and Y shifts...
2021-05-29 21:14:43,053 - stpipe.Image3Pipeline.tweakreg - INFO - Found peak in the 2D histogram lies at the edge of the histogram. Try increasing 'searchrad' for improved results.
2021-05-29 21:14:43,053 - stpipe.Image3Pipeline.tweakreg - WARNING - Unable to estimate significance of the detection of the initial shift.
2021-05-29 21:14:43,053 - stpipe.Image3Pipeline.tweakreg - INFO - Found initial X and Y shifts of 1, -1 with 2 matches.
2021-05-29 21:14:43,054 - stpipe.Image3Pipeline.tweakreg - INFO - Found 3 matches for 'GROUP ID: jw00660020001_02101_00001_nis_cal'...
2021-05-29 21:14:43,054 - stpipe.Image3Pipeline.tweakreg - WARNING - The number of sources for the fit is smaller than the minimum number of sources necessary for the requested 'fitgeom'.
2021-05-29 21:14:43,054 - stpipe.Image3Pipeline.tweakreg - WARNING - Resetting number of clipping iterations to 0.
2021-05-29 21:14:43,054 - stpipe.Image3Pipeline.tweakreg - INFO - Performing 'general' fit
2021-05-29 21:14:43,055 - stpipe.Image3Pipeline.tweakreg - INFO - Computed 'general' fit for GROUP ID: jw00660020001_02101_00001_nis_cal:
2021-05-29 21:14:43,055 - stpipe.Image3Pipeline.tweakreg - INFO - XSH: -2.16192e+18  YSH: -1.72954e+19    PROPER ROT: -135
2021-05-29 21:14:43,055 - stpipe.Image3Pipeline.tweakreg - INFO - <ROT>: -37.875  SKEW: 90    ROT_X: 97.125  ROT_Y: -172.875
2021-05-29 21:14:43,055 - stpipe.Image3Pipeline.tweakreg - INFO - <SCALE>: 0  SCALE_X: 2.90473e+17  SCALE_Y: 7.26184e+16
2021-05-29 21:14:43,056 - stpipe.Image3Pipeline.tweakreg - INFO -
2021-05-29 21:14:43,056 - stpipe.Image3Pipeline.tweakreg - INFO - FIT RMSE: 7.23651e+16   FIT MAE: 6.82265e+16
2021-05-29 21:14:43,056 - stpipe.Image3Pipeline.tweakreg - INFO - Final solution based on 3 objects.
2021-05-29 21:14:43,094 - stpipe.Image3Pipeline.tweakreg - INFO -
2021-05-29 21:14:43,094 - stpipe.Image3Pipeline.tweakreg - INFO - ***** tweakwcs.imalign.align_wcs() ended on 2021-05-29 21:14:43.094299
2021-05-29 21:14:43,094 - stpipe.Image3Pipeline.tweakreg - INFO - ***** tweakwcs.imalign.align_wcs() TOTAL RUN TIME: 0:00:00.761073
2021-05-29 21:14:43,094 - stpipe.Image3Pipeline.tweakreg - INFO -
2021-05-29 21:14:43,199 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg done
2021-05-29 21:14:43,338 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch running with args (<ModelContainer>,).
```

I'm unfamiliar with tweakreg - not sure if this is a result of poor data or if there is an issue present.

**Comment by jdavies-st** [comment]
Yeah, this is probably garbage data that should not be run through tweakreg, though it would be good to the data itself.  A rotation of 37 degrees based on 3 sources (probably noise).  And that will have a knock-on effect for all steps subsequent.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2127?focusedCommentId=554412#comment-554412):_

Whoops, I needed to read the error log more closely - the poor fit by /tweakreg/ was what caused the error in skymatch. [JP-2152](https://jira.stsci.edu/browse/JP-2152) set an upper limit to tweakreg fitting parameters, and this removes the erroneous fit present in this ticket's error log. The run now shows tweakreg attempting to 'tweak' by more than 10 arcsec and so is skipped instead of being applied. This seems to be the pipeline working as intended, so I'm going to call this ticket a non-issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2127?focusedCommentId=554413#comment-554413):_

Ticket issue resolved by past work in [JP-2152,](https://jira.stsci.edu/browse/JP-2152) no additional work necessary.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2127?focusedCommentId=554404#comment-554404):_

Running these data through Image3Pipeline produces no errors. I don't see any changes to skymatch between the issuing of this ticket and now, which is quite confusing.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2127?focusedCommentId=554412#comment-554412):_

Whoops, I needed to read the error log more closely - the poor fit by /tweakreg/ was what caused the error in skymatch. [JP-2152](https://jira.stsci.edu/browse/JP-2152) set an upper limit to tweakreg fitting parameters, and this removes the erroneous fit present in this ticket's error log. The run now shows tweakreg attempting to 'tweak' by more than 10 arcsec and so is skipped instead of being applied. This seems to be the pipeline working as intended, so I'm going to call this ticket a non-issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2127?focusedCommentId=554413#comment-554413):_

Ticket issue resolved by past work in [JP-2152,](https://jira.stsci.edu/browse/JP-2152) no additional work necessary.
