### ISSUE TITLE
spec2 pipeline crashes during the resample_spec step for NIRSpec FS

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6141]
_Issue [JP-2138](https://jira.stsci.edu/browse/JP-2138) was created on JIRA by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol):_

I'm getting the following error while running calwebb_spec2 on FS simulated exposures:

2021-06-10 12:59:08,221 - stpipe.Spec2Pipeline.resample_spec - INFO - Drizzling (0, 0, 0) --> (34, 435)
Traceback (most recent call last):
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 113, in process
 result = self.process_exposure_product(
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 263, in process_exposure_product
 resampled = self.resample_spec(calibrated)
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
 step_result = self.process(*args)
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/resample/resample_spec_step.py", line 59, in process
 result = self._process_multislit(input_models)
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/resample/resample_spec_step.py", line 97, in _process_multislit
 drizzled_models = resamp.do_drizzle()
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/resample/resample.py", line 98, in do_drizzle
 return self.resample_many_to_one()
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/resample/resample.py", line 173, in resample_many_to_one
 self.resample_variance_array("var_flat", output_model)
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/resample/resample.py", line 208, in resample_variance_array
 self.drizzle_arrays(input_array, inwht, model.meta.wcs,
 File "/Users/muzerol/anaconda3/envs/jwst_1.2.0/lib/python3.9/site-packages/jwst/resample/resample.py", line 398, in drizzle_arrays
 _vers, _nmiss, _nskip = cdrizzle.tdriz(
ValueError: Invalid input array

For some reason, the fourth instance of drizzle has a zero-sized input; it should be (40, 435).  This behavior does not occur when running the resample_spec step by itself.  It also did not appear in earlier pipeline versions.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532470#comment-532470):_

These rate files do not have variance arrays, i.e. VAR_RNOISE and VAR_POISSON.  They should if they ran through detector1 and ramp fit, i.e. were produced from ramps.  The traceback is showing that it is failing when passing one of these arrays to the drizzle code.

That said, if run through the whole pipeline, those get created anyway as zeros, so it while garbage it should not cause an issue.  And in fact, this is what I see with `jwst 1.2.3`:

```
$ for file in *_rate.fits
> do
>   strun calwebb_spec2 $file
> done

```

Doing the above runs the full spec2 pipeline on all rate files and I see no errors.  Is there a different way of processing these that produces the traceback above?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532514#comment-532514):_

Thanks [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies)!  I'm running in a python notebook, executing spec2 directly with all defaults except skipping the flat field step.

Maria kindly gave me some code to add dummy variance arrays, I'll try that and see if the problem clears up.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532633#comment-532633):_

I can reproduce this via

```
$ strun calwebb_spec2 nirspec_002_CLEAR-PRISM_SLIT_fluxcal11_d01_000_491_cts_NRS1_mod_rate.fits --steps.flat_field.skip=True
...
2021-06-11 13:39:31,918 - stpipe.Spec2Pipeline.resample_spec - INFO - Drizzling (40, 435) --> (34, 435)
2021-06-11 13:39:31,925 - stpipe.Spec2Pipeline.resample_spec - INFO - Resampling var_flat
2021-06-11 13:39:31,945 - stpipe.Spec2Pipeline.resample_spec - INFO - Drizzling (0, 0, 0) --> (34, 435)
Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 113, in process
    result = self.process_exposure_product(
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 263, in process_exposure_product
    resampled = self.resample_spec(calibrated)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 67, in process
    result = self._process_multislit(input_models)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 105, in _process_multislit
    drizzled_models = resamp.do_drizzle()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 96, in do_drizzle
    return self.resample_many_to_one()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 172, in resample_many_to_one
    self.resample_variance_array("var_flat", output_model)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 208, in resample_variance_array
    self.drizzle_arrays(input_array, inwht, model.meta.wcs,
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 401, in drizzle_arrays
    _vers, _nmiss, _nskip = cdrizzle.tdriz(
ValueError: Invalid input array
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    Traceback (most recent call last):   File
    "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line
    113, in process     result = self.process_exposure_product(   File
    "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line
    263, in process_exposure_product     resampled =
    self.resample_spec(calibrated)   File
    "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-
    packages/stpipe/step.py", line 407, in run     step_result =
    self.process(*args)   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py",
    line 67, in process     result =
    self._process_multislit(input_models)   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py",
    line 105, in _process_multislit     drizzled_models =
    resamp.do_drizzle()   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 96, in
    do_drizzle     return self.resample_many_to_one()   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 172, in
    resample_many_to_one     self.resample_variance_array("var_flat",
    output_model)   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 208, in
    resample_variance_array     self.drizzle_arrays(input_array,
    inwht, model.meta.wcs,   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 401, in
    drizzle_arrays     _vers, _nmiss, _nskip = cdrizzle.tdriz(
    ValueError: Invalid input array
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jdavies/miniconda3/envs/jwst/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 131, in process
    raise RuntimeError('\n'.join(failures))
RuntimeError: Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 113, in process
    result = self.process_exposure_product(
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 263, in process_exposure_product
    resampled = self.resample_spec(calibrated)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 67, in process
    result = self._process_multislit(input_models)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 105, in _process_multislit
    drizzled_models = resamp.do_drizzle()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 96, in do_drizzle
    return self.resample_many_to_one()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 172, in resample_many_to_one
    self.resample_variance_array("var_flat", output_model)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 208, in resample_variance_array
    self.drizzle_arrays(input_array, inwht, model.meta.wcs,
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 401, in drizzle_arrays
    _vers, _nmiss, _nskip = cdrizzle.tdriz(
ValueError: Invalid input array

```

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=546000#comment-546000):_

Fix proposed in #6305

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=549738#comment-549738):_

Successfully tested on FS and MOS data.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532470#comment-532470):_

These rate files do not have variance arrays, i.e. VAR_RNOISE and VAR_POISSON.  They should if they ran through detector1 and ramp fit, i.e. were produced from ramps.  The traceback is showing that it is failing when passing one of these arrays to the drizzle code.

That said, if run through the whole pipeline, those get created anyway as zeros, so it while garbage it should not cause an issue.  And in fact, this is what I see with `jwst 1.2.3`:

```
$ for file in *_rate.fits
> do
>   strun calwebb_spec2 $file
> done

```

Doing the above runs the full spec2 pipeline on all rate files and I see no errors.  Is there a different way of processing these that produces the traceback above?

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532514#comment-532514):_

Thanks [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies)!  I'm running in a python notebook, executing spec2 directly with all defaults except skipping the flat field step.

Maria kindly gave me some code to add dummy variance arrays, I'll try that and see if the problem clears up.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532604#comment-532604):_

Ah!  I wonder if skipping the flat field step is the culprit.  That's the step that actually accesses and modfies those arrays, so if they're not in the `_cal.fits` file, they will be (but zeros) after flat field.  Also VAR_FLAT is added.

<https://github.com/spacetelescope/jwst/blob/9a4e53544079c5808afd1ae097752689bc9c88f0/jwst/flatfield/flat_field.py#L202-L213>

It might be a good idea if we accessed them in resample before using them, just to make sure they exist.

To add them to a toy model:

```
In [17]: from jwst.datamodels import SlitModel

In [18]: model = SlitModel((3, 15))

In [19]: model.data.shape
Out[19]: (3, 15)

In [20]: model.info()
root (AsdfObject)
├─data (ndarray): shape=(3, 15), dtype=float32
└─meta (dict)
  ├─model_type (str): SlitModel
  └─date (str): 2021-06-11T16:23:15.976

In [21]: model.var_rnoise
Out[21]: 
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [22]: model.var_poisson
Out[22]: 
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)

In [23]: model.info()
root (AsdfObject)
├─data (ndarray): shape=(3, 15), dtype=float32
├─meta (dict)
│ ├─model_type (str): SlitModel
│ └─date (str): 2021-06-11T16:23:15.976
├─var_rnoise (ndarray): shape=(3, 15), dtype=float32
└─var_poisson (ndarray): shape=(3, 15), dtype=float32

In [24]: model.save("myfile.fits")
Out[24]: 'myfile.fits'

In [25]: !fitsinfo myfile.fits
Filename: myfile.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       7   ()      
  1  SCI           1 ImageHDU         9   (15, 3)   float32   
  2  VAR_POISSON    1 ImageHDU         9   (15, 3)   float32   
  3  VAR_RNOISE    1 ImageHDU         9   (15, 3)   float32   
  4  ASDF          1 BinTableHDU     11   1R x 1C   [907B]   
```

**Comment by stscijgbot-jp** [comment]
_Comment by [James Davies [X]](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jdavies) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=532633#comment-532633):_

I can reproduce this via

```
$ strun calwebb_spec2 nirspec_002_CLEAR-PRISM_SLIT_fluxcal11_d01_000_491_cts_NRS1_mod_rate.fits --steps.flat_field.skip=True
...
2021-06-11 13:39:31,918 - stpipe.Spec2Pipeline.resample_spec - INFO - Drizzling (40, 435) --> (34, 435)
2021-06-11 13:39:31,925 - stpipe.Spec2Pipeline.resample_spec - INFO - Resampling var_flat
2021-06-11 13:39:31,945 - stpipe.Spec2Pipeline.resample_spec - INFO - Drizzling (0, 0, 0) --> (34, 435)
Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 113, in process
    result = self.process_exposure_product(
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 263, in process_exposure_product
    resampled = self.resample_spec(calibrated)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 67, in process
    result = self._process_multislit(input_models)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 105, in _process_multislit
    drizzled_models = resamp.do_drizzle()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 96, in do_drizzle
    return self.resample_many_to_one()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 172, in resample_many_to_one
    self.resample_variance_array("var_flat", output_model)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 208, in resample_variance_array
    self.drizzle_arrays(input_array, inwht, model.meta.wcs,
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 401, in drizzle_arrays
    _vers, _nmiss, _nskip = cdrizzle.tdriz(
ValueError: Invalid input array
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline':
    Traceback (most recent call last):   File
    "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line
    113, in process     result = self.process_exposure_product(   File
    "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line
    263, in process_exposure_product     resampled =
    self.resample_spec(calibrated)   File
    "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-
    packages/stpipe/step.py", line 407, in run     step_result =
    self.process(*args)   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py",
    line 67, in process     result =
    self._process_multislit(input_models)   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py",
    line 105, in _process_multislit     drizzled_models =
    resamp.do_drizzle()   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 96, in
    do_drizzle     return self.resample_many_to_one()   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 172, in
    resample_many_to_one     self.resample_variance_array("var_flat",
    output_model)   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 208, in
    resample_variance_array     self.drizzle_arrays(input_array,
    inwht, model.meta.wcs,   File
    "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 401, in
    drizzle_arrays     _vers, _nmiss, _nskip = cdrizzle.tdriz(
    ValueError: Invalid input array
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jdavies/miniconda3/envs/jwst/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 131, in process
    raise RuntimeError('\n'.join(failures))
RuntimeError: Traceback (most recent call last):
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 113, in process
    result = self.process_exposure_product(
  File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 263, in process_exposure_product
    resampled = self.resample_spec(calibrated)
  File "/Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 67, in process
    result = self._process_multislit(input_models)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample_spec_step.py", line 105, in _process_multislit
    drizzled_models = resamp.do_drizzle()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 96, in do_drizzle
    return self.resample_many_to_one()
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 172, in resample_many_to_one
    self.resample_variance_array("var_flat", output_model)
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 208, in resample_variance_array
    self.drizzle_arrays(input_array, inwht, model.meta.wcs,
  File "/Users/jdavies/dev/jwst/jwst/resample/resample.py", line 401, in drizzle_arrays
    _vers, _nmiss, _nskip = cdrizzle.tdriz(
ValueError: Invalid input array

```

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=546000#comment-546000):_

Fix proposed in #6305

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=546488#comment-546488):_

Fixed by #6305

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=546489#comment-546489):_

[James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) this has been fixed in the development version of the pipeline code. It will now properly skip trying to resample any of the variance arrays that aren't in the input data files, as is the case with countrate images coming out of the NIRSpec simulator. You can test at your leisure.

**Comment by stscijgbot-jp** [comment]
_Comment by [James Muzerolle](https://jira.stsci.edu/secure/ViewProfile.jspa?name=muzerol) on [JIRA](https://jira.stsci.edu/browse/JP-2138?focusedCommentId=549738#comment-549738):_

Successfully tested on FS and MOS data.
