### ISSUE TITLE
ami_analyze crashes when input image contains NaN's

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6318]
_Issue [JP-2271](https://jira.stsci.edu/browse/JP-2271) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The ami_analyze step crashes with the following traceback when given an input image that contains a few pixels that are set to NaN:

```
2021-09-01 08:28:25,520 - stpipe.AmiAnalyzeStep - INFO - Using filter throughput reference file ████████████████████████████████████████████████████████████████
2021-09-01 08:28:25,613 - stpipe.AmiAnalyzeStep - DEBUG - No ASDF information found. Cannot skip updating from FITS headers.
2021-09-01 08:28:30,988 - stpipe.AmiAnalyzeStep - WARNING - /Users/bushouse/JWST/softw/jwst/jwst/ami/utils.py:726: RuntimeWarning: Mean of empty slice.
  slopes = G[0] * tilt[0][newmaskh].mean(), G[1] * tilt[1][newmaskv].mean()

2021-09-01 08:28:30,989 - stpipe.AmiAnalyzeStep - WARNING - /Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

----------------------------------------------------------------------
ERROR RUNNING STEP 'AmiAnalyzeStep':
    Only 2D ImageModel data can be processed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/ami_analyze_step.py", line 68, in process
    result = ami_analyze.apply_LG_plus(input_model, throughput_model,
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/ami_analyze.py", line 99, in apply_LG_plus
    output_model = ff_t.fit_fringes_all(input_copy)
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/nrm_core.py", line 121, in fit_fringes_all
    nrm.make_model(fov=self.ctrd.shape[0], bandpass=nrm.bandpass,
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/lg_model.py", line 315, in make_model
    pb, ff = analyticnrm2.model_array(self.modelctrs, l, self.over,
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/analyticnrm2.py", line 356, in model_array
    asf_pb = asf_hex(pitch, fov, oversample, ctrs, d, lam, phi, psf_offset, affine2d)
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/analyticnrm2.py", line 531, in asf_hex
    return hextransformee.hextransform(s=(oversample * fov, oversample * fov),
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/hextransformee.py", line 109, in hextransform
    d0, d1 = (c[0] - int(c[0]), c[1] - int(c[1]))
ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bushouse/anaconda3/envs/jwstdev/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/Users/bushouse/anaconda3/envs/jwstdev/lib/python3.9/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/Users/bushouse/JWST/softw/jwst/jwst/ami/ami_analyze_step.py", line 81, in process
    raise RuntimeError("Only 2D ImageModel data can be processed.") from err
RuntimeError: Only 2D ImageModel data can be processed.
```

This problem had been fixed in the original version of the ami_analyze code (JP-142), but has reappeared since the new algorithm was implemented.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=547297#comment-547297):_

I can't seem to put my hands on exactly how the issue with input NaN's was handled in the old version of the code. Looking at the latest version, I don't see any place where DQ information is utilized in any of the actual fringe fitting functions, so simply flagging NaN's with something like `DO_NOT_USE` is not a viable option, at least not without reworking the lower-level functions to pay attention to the DQ flags.

Simple brute-force approaches are possible, such as replacing NaN's in the input image with some other numerical values, such as zero or mean of 3x3 box around each NaN, etc. I have verified that each of these two simple approaches avoids having the code crash, but I don't know how it affects the results.

Will need direction from the AMI working group as to the best way to implement this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=547301#comment-547301):_

[Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte) and [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) FYI

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548137#comment-548137):_

Temporarily putting status back to Open while waiting for INS input.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anand Sivaramakrishnan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=anand) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548167#comment-548167):_

 "replacing NaN's in the input image with some other numerical values, such as zero or mean of 3x3 box around each NaN" will work fine, but only if the DO_NOT_USE flag is set.  We have an iterative "outside implaneia" fix that works faster (fewer iterations) when bad pixel values are not hugely numerically different from their 'correct but undetected' values.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548176#comment-548176):_

In light of Anand's comment it would be better to replace the NaN value with the mean of the 3x3 box of surrounding pixels rather than with a value of zero, even though it is more work in the code.  The DO_NOT_USE flag or some other flag can be set at this point to alert the user that the value has been replaced.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548185#comment-548185):_

I did another check of the current code and found that there is in fact the function `img_median_replace`, which will replace pixel values flagged with DO_NOT_USE with the median of the surrounding pixels, with the size of the median box being adjustable. This was implemented and put into use in the previous version of the `ami_analyze` step, but got dropped from use when the big rewrite took place to implement the latest LG+ algorithms (the median function is still there, it just isn't being called in order to fix the input data). So this should be a simple fix to reinstate the use of that function, if you're all OK with doing a median replacement, as opposed to mean. What would be a good default filter box size: 3x3 (total of 8 pixels used), 4x4 (total of 15 pixels used), ...?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548187#comment-548187):_

I think we should use the small box 3x3 pixels excluding the central one.  The median is fine as opposed to the mean, it just needs to be in the right range compared to the adjacent pixels.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548190#comment-548190):_

Where do pixels with NaN come from in the pipeline?  Are these already flagged as DO_NOT_USE when the NaN appears?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548287#comment-548287):_

It's hard to say. Sometimes the NaN's get propagated in from reference files, although there are hooks in many of the steps to prevent this (i.e. if the ref file contains NaN, don't modify the science pixel at all), and in all of those places the DO_NOT_USE flag is also getting set. So I'm not 100% sure what the exact use case is here for AMI images, but we've now got it handled.

The function that I'm implementing will look for and replace pixels that are NaN and/or set to DO_NOT_USE, so it'll catch both cases.

As of right now the code is hardwired to use a 3x3 box for the median replacement. Would you like that to be a user-settable parameter (i.e. make it a new step parameter) with a default of 3?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548293#comment-548293):_

I do not think that there is any point in making the box size a parameter for this purpose.  The pixels that get NaNs should not be used for the detailed analysis and so small changes in the assigned value had better not affect the analysis or something is wrong.  Since using the 3x3 box is consistent with Anand's comment above I think we are OK as is.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anand Sivaramakrishnan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=anand) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548361#comment-548361):_

Kevin's right - anything close is "good enough for government use" - a hardwired 3x3 box is fine.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548473#comment-548473):_

Fixed by #6334

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=556849#comment-556849):_

I think that Deepashri tested this and it can be closed.  Right now I think Deepashri is off but I will check with her once she is back.

**Comment by stscijgbot-jp** [comment]
_Comment by [Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=584235#comment-584235):_

I introduced two NAN pixels in the data and ran ami_analyze. It does not crash when input image contains NANs.


result = AmiAnalyzeStep.call("all_effects_data_withNaN_cal.fits", config_file='../cfgfiles/ami_analyze.cfg',output_dir=odir, save_results=True)
```java
2022-04-29 12:09:05,730 - stpipe.ami_analyze - INFO - AmiAnalyzeStep instance created.
2022-04-29 12:09:05,834 - stpipe.ami_analyze - INFO - Step ami_analyze running with args ('all_effects_data_withNaN_cal.fits',).
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Step ami_analyze parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': './ami_pipeline_output_b79', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'oversample': 3, 'rotation': 0.0, 'psf_offset': '0.0 0.0', 'rotation_search': '-3 3.1 1.'}
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Oversampling factor = 3
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Initial rotation guess = 0.0 deg
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Initial values to use for psf offset = [0.0, 0.0]
2022-04-29 12:09:06,107 - stpipe.ami_analyze - INFO - Using filter throughput reference file /Users/thatte/crds_cache/references/jwst/niriss/jwst_niriss_throughput_0008.fits
2022-04-29 12:09:06,201 - stpipe.ami_analyze - INFO - Applying median filter for 2 NaN and 0 DO_NOT_USE pixels
2022-04-29 12:09:06,203 - stpipe.ami_analyze - INFO - Initial values to use for rotation search [-3. -2. -1. 0. 1. 2. 3.]
2022-04-29 12:09:17,872 - stpipe.ami_analyze - INFO - Saved model in ./ami_pipeline_output_b79/all_effects_data_withNaN_ami_analyze.fits
2022-04-29 12:09:17,872 - stpipe.ami_analyze - INFO - Step ami_analyze done```

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=547297#comment-547297):_

I can't seem to put my hands on exactly how the issue with input NaN's was handled in the old version of the code. Looking at the latest version, I don't see any place where DQ information is utilized in any of the actual fringe fitting functions, so simply flagging NaN's with something like `DO_NOT_USE` is not a viable option, at least not without reworking the lower-level functions to pay attention to the DQ flags.

Simple brute-force approaches are possible, such as replacing NaN's in the input image with some other numerical values, such as zero or mean of 3x3 box around each NaN, etc. I have verified that each of these two simple approaches avoids having the code crash, but I don't know how it affects the results.

Will need direction from the AMI working group as to the best way to implement this.

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=547301#comment-547301):_

[Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte) and [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) FYI

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548137#comment-548137):_

Temporarily putting status back to Open while waiting for INS input.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anand Sivaramakrishnan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=anand) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548167#comment-548167):_

 "replacing NaN's in the input image with some other numerical values, such as zero or mean of 3x3 box around each NaN" will work fine, but only if the DO_NOT_USE flag is set.  We have an iterative "outside implaneia" fix that works faster (fewer iterations) when bad pixel values are not hugely numerically different from their 'correct but undetected' values.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548176#comment-548176):_

In light of Anand's comment it would be better to replace the NaN value with the mean of the 3x3 box of surrounding pixels rather than with a value of zero, even though it is more work in the code.  The DO_NOT_USE flag or some other flag can be set at this point to alert the user that the value has been replaced.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548185#comment-548185):_

I did another check of the current code and found that there is in fact the function `img_median_replace`, which will replace pixel values flagged with DO_NOT_USE with the median of the surrounding pixels, with the size of the median box being adjustable. This was implemented and put into use in the previous version of the `ami_analyze` step, but got dropped from use when the big rewrite took place to implement the latest LG+ algorithms (the median function is still there, it just isn't being called in order to fix the input data). So this should be a simple fix to reinstate the use of that function, if you're all OK with doing a median replacement, as opposed to mean. What would be a good default filter box size: 3x3 (total of 8 pixels used), 4x4 (total of 15 pixels used), ...?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548187#comment-548187):_

I think we should use the small box 3x3 pixels excluding the central one.  The median is fine as opposed to the mean, it just needs to be in the right range compared to the adjacent pixels.

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548190#comment-548190):_

Where do pixels with NaN come from in the pipeline?  Are these already flagged as DO_NOT_USE when the NaN appears?

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548293#comment-548293):_

I do not think that there is any point in making the box size a parameter for this purpose.  The pixels that get NaNs should not be used for the detailed analysis and so small changes in the assigned value had better not affect the analysis or something is wrong.  Since using the 3x3 box is consistent with Anand's comment above I think we are OK as is.

**Comment by stscijgbot-jp** [comment]
_Comment by [Anand Sivaramakrishnan](https://jira.stsci.edu/secure/ViewProfile.jspa?name=anand) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548361#comment-548361):_

Kevin's right - anything close is "good enough for government use" - a hardwired 3x3 box is fine.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=548473#comment-548473):_

Fixed by #6334

**Comment by stscijgbot-jp** [comment]
_Comment by [Kevin Volk](https://jira.stsci.edu/secure/ViewProfile.jspa?name=kvolk) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=556849#comment-556849):_

I think that Deepashri tested this and it can be closed.  Right now I think Deepashri is off but I will check with her once she is back.

**Comment by stscijgbot-jp** [comment]
_Comment by [Deepashri Thatte](https://jira.stsci.edu/secure/ViewProfile.jspa?name=thatte) on [JIRA](https://jira.stsci.edu/browse/JP-2271?focusedCommentId=584235#comment-584235):_

I introduced two NAN pixels in the data and ran ami_analyze. It does not crash when input image contains NANs.


result = AmiAnalyzeStep.call("all_effects_data_withNaN_cal.fits", config_file='../cfgfiles/ami_analyze.cfg',output_dir=odir, save_results=True)
```java
2022-04-29 12:09:05,730 - stpipe.ami_analyze - INFO - AmiAnalyzeStep instance created.
2022-04-29 12:09:05,834 - stpipe.ami_analyze - INFO - Step ami_analyze running with args ('all_effects_data_withNaN_cal.fits',).
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Step ami_analyze parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': './ami_pipeline_output_b79', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'oversample': 3, 'rotation': 0.0, 'psf_offset': '0.0 0.0', 'rotation_search': '-3 3.1 1.'}
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Oversampling factor = 3
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Initial rotation guess = 0.0 deg
2022-04-29 12:09:05,835 - stpipe.ami_analyze - INFO - Initial values to use for psf offset = [0.0, 0.0]
2022-04-29 12:09:06,107 - stpipe.ami_analyze - INFO - Using filter throughput reference file /Users/thatte/crds_cache/references/jwst/niriss/jwst_niriss_throughput_0008.fits
2022-04-29 12:09:06,201 - stpipe.ami_analyze - INFO - Applying median filter for 2 NaN and 0 DO_NOT_USE pixels
2022-04-29 12:09:06,203 - stpipe.ami_analyze - INFO - Initial values to use for rotation search [-3. -2. -1. 0. 1. 2. 3.]
2022-04-29 12:09:17,872 - stpipe.ami_analyze - INFO - Saved model in ./ami_pipeline_output_b79/all_effects_data_withNaN_ami_analyze.fits
2022-04-29 12:09:17,872 - stpipe.ami_analyze - INFO - Step ami_analyze done```
