### ISSUE TITLE
Error in cube_build during B7.8.2 testing for MIRI MRS

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6343]
_Issue [JP-2281](https://jira.stsci.edu/browse/JP-2281) was created on JIRA by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse):_

The cube_build step failed during calwebb_spec3 for a MIRI MRS association with the following traceback:

```
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec3Pipeline':
    zero-size array to reduction operation minimum which has no
    identity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/bin/strun", line 28, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/stpipe/step.py", line 173, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/stpipe/cmdline.py", line 339, in step_from_cmdline
    step.run(*positional)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_spec3.py", line 195, in process
    result = self.cube_build(result)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
    step_result = self.process(*args)
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/jwst/cube_build/cube_build_step.py", line 339, in process
    cube_result = thiscube.build_ifucube()
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/jwst/cube_build/ifu_cube.py", line 576, in build_ifucube
    pixelresult = self.map_detector_to_outputframe(this_par1,
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/jwst/cube_build/ifu_cube.py", line 1435, in map_detector_to_outputframe
    log.debug(f'After removing pixels based on criteria min and max wave: {np.min(wave)}, {np.max(wave)}')
  File "<__array_function__ internals>", line 5, in amin
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2858, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
2021254131122-E-ERROR-/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.3.2.20210904-py38/lib/python3.8/site-packages/jwst/pipeline/calwebb_spec3.cfg FAILED (exit=1) on jw00684-o006_20210911t121525_spec3_001_asn.json.
```

This is a part of the cube_build code that was modified to make use of C extensions and also happens to correspond to a debug-level log message statement when attempting to compute the min/max of the "wave" array. Could be garbage data.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549081#comment-549081):_

I have not yet run the spec3 pipeline on the data. I first looked at the cal files. [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Have you seen data like this ? Is this made up data - the black values in the slices are zero. I will try and run spec3 now. I am wondering if it is a data problem or a step in calspec2 that would produced such strange looking data. 
!image-2021-09-13-10-55-16-822.png|width=796,height=569!

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549082#comment-549082):_

It's probably just the weird "ramp" data that gets injected into data coming out of the OTB, where by "ramp" they're referring to the fact that it has a repeating ramp of signal in the spatial domain, not in the traditional sense of multi-readout IR ramp data (where the ramp is in the time domain).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549083#comment-549083):_

It would likely be good to look back at the rate files, which I can dig up from the D2 string for you.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549087#comment-549087):_

I've copied all 8 rate files to the jp-2281 data directory. The SCI extensions show a very similar pattern as you saw in the cal files, so the assumption is that this is just the garbage OTB signal.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549130#comment-549130):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) I confirmed that when I ran the files on the development version calspec3 ran fine. I track down the problem to after outlier detection is run the channel 3 data is mostly flagged as an outlier. In PR #&#x2060;6326 it may not be obvious from the title on GITHUB (Nirspec improvements in blotting for outlier detection) but I also made a number of improvements in blotting for BOTH MIRI AND NIRSPEC. 

My branch on adding 3d drizzling does not include those updates from #&#x2060;6326 but it includes all the c extension improvements. Basically I made  this branch right before I worked on #&#x2060;6326. I also get the same error when I run the data in this branch. Looking at the comments in Jp2050 I see this statement :  "I tracked down 1 error for MIRI MRS outlier detection. The set of input_images needs to be consistent between outlier_detection and blot_cube. Blot_cube was redefining the list of images to be only those contained on the channel that is being blotted. This results in incorrect data arrays being added together in outlier_detection."
 I believe this error results what we are seeing.

Can we also merge 6326 to the release pipeline ?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549204#comment-549204):_

To further test this I made two asn files - one that just contained the IFUSHORT and one the just contained IFULONG. When I did this both test ran through the spec3 pipeline. This further points to the problem in #&#x2060;6326. When the full set (both IFULONG and IFUSHORT) is used outlier detection  and blotting have a mismatch of file indexes (because the blot routine pulls out files from the full list).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549205#comment-549205):_

Given that:
1) It's highly likely that this particular error only appears as a result of garbage OTB data used in DMS test suites;
2) The error does not appear for tests using other kinds of (semi-real) data;
3) The error occurs in level 3 processing, which is not officially required in Ops for commissioning; and
4) We can easily fix it in the first available patch delivered to Ops post-launch;
5) Who knows what kind of side-effects we might introduce by merging PR#&#x2060;6326 into the B7.8.2 release,
I don't think this warrants fixing via another Cal release for B7.8.2, especially at this very late date in the B7.8.2 test and release schedule.

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=549336#comment-549336):_

The research was finished on why this data results in an error. The fix for the code was already in PR 6326, but it was merged into master after 7.8.2 was released.  Outlier detection will not correctly flag outliers on MIRI data if the association contains IFLONG and IFUSHORT data.  A work around is to run outlier detection on an association file that contains only IFULONG or IFUSHORT data. After outlier detection has been  run cube build can then be run using data from both detectors

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=551690#comment-551690):_

Same error was reported during SOC validation testing of B7.8.2, but this time occurring in the calwebb_spec2 pipeline. The affected datasets were jw00413-o025_20210923t190614_spec2_00[123456].

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) do you have access to these datasets, presumably on the I&T C-string? I can't find them anywhere on the D2 string.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=551844#comment-551844):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) yes, I've packaged the data up in 

█████████████████████████████████████

**Comment by jemorrison** [comment]
@hbushouse  could you point me to where the data is so I can see what is going on

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=551897#comment-551897):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) see the previous comment by Hien, which points to the data location

**Comment by stscijgbot-jp** [comment]
_Comment by [Matthew Burger](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mburger) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=551899#comment-551899):_

jw00802-o115_20211001t024017_spec3_001 failed also on 10/1.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=551902#comment-551902):_

Yes, errors when running calwebb_spec3 using B7.8.2 are expected, because the fix for the problem that triggers the spec3 error was not included in B7.8.2. It will be in B7.9.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=551974#comment-551974):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) I put the uncal fits files here ███████████████████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-2281?focusedCommentId=552342#comment-552342):_

I have created JP-2297  to report a bug in ramp_fitting related to how the final dq value is created from the integration values. 

The final DQ reported in the *rate.fits files (what cube build uses) is created from a bitwise_or of the integration dq values. If a single integration contains DO_NOT_USE then the final DQ will contain DO_NOT_USE.  The data from this test is not scientific - but the error in the data has pointed out this bug in how the final DQ is determined. This data set contained 5 groups of 20 integrations. However this data had - for SOME integrations -  the first (or first few) groups saturating and then the remain groups jump down into the unsaturated region. This results in at least one integration in the set of 20 being flagged with the DO_USE_FLAG. See the example below of such an integration. This integration should be excluded from the final rate determination and its DQ flag not used to set the final DQ flag. Currently it is being used so all the pixels end up with a final DQ flags with DO_NOT_USE being set. Though this data are not scientific, the code should be able to handle the cases were one or more integrations are not useful and should be disregarded when determining the final value and the final rate and DQ should be based only on the good values.  !image-2021-10-05-11-34-42-959.png!
