### ISSUE TITLE
Outlier detection fails with moving target data containing >1 input file

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#6447]
_Issue [JP-2328](https://jira.stsci.edu/browse/JP-2328) was created on JIRA by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert):_

When attempting to run some NIRCam moving target data through the pipeline, outlier detection is crashing when attempting to calculate the inverse variance within resample. My initial pipeline call included my entire dataset, which is 4 detectors * 9 pointings = 36 files. However, I get the same crash anytime I input more than 1 file. When I run with a single file, the pipeline completes with no problem. Also, the pipeline completed successfully running on all 36 files last night, when I had forgotten to add the TARGTYPE keyword. So in that case, the pipeline treated the data as regular, sidereal tracking data. Only after adding TARGTYPE='MOVING' did I start seeing this error.

Here is the full traceback (in the case where I tried to run with 2 files as input):

2021-11-11 12:00:30,830 - stpipe.Image3Pipeline.skymatch - INFO - Step skymatch done
 2021-11-11 12:00:30,891 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<ModelContainer>,).
 2021-11-11 12:00:30,892 - stpipe.Image3Pipeline.outlier_detection - INFO - Step outlier_detection parameters are: \{'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': 'crf', 'search_output_file': False, 'input_dir': '', 'weight_type': 'ivm', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'nlow': 0, 'nhigh': 0, 'maskpt': 0.7, 'grow': 1, 'snr': '5.0 4.0', 'scale': '1.2 0.7', 'backg': 0.0, 'save_intermediate_results': False, 'resample_data': True, 'good_bits': '~DO_NOT_USE', 'scale_detection': False, 'allowed_memory': None}
 2021-11-11 12:00:30,894 - stpipe.Image3Pipeline.outlier_detection - INFO - Performing outlier detection on 2 inputs
 Traceback (most recent call last):
 File "run_pipeline.py", line 86, in <module>
 run_image3(level3_lw_asn, 'F360M', outdir)
 File "run_pipeline.py", line 65, in run_image3
 image3.run(asn_file)
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
 step_result = self.process(*args)
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/jwst/pipeline/calwebb_image3.py", line 88, in process
 input_models = self.outlier_detection(input_models)
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/stpipe/step.py", line 407, in run
 step_result = self.process(*args)
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/jwst/outlier_detection/outlier_detection_step.py", line 158, in process
 step.do_detection()
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/jwst/outlier_detection/outlier_detection.py", line 192, in do_detection
 drizzled_models = resamp.do_drizzle()
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/jwst/resample/resample.py", line 93, in do_drizzle
 return self.resample_many_to_many()
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/jwst/resample/resample.py", line 122, in resample_many_to_many
 inwht = resample_utils.build_driz_weight(img, weight_type=self.weight_type,
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/jwst/resample/resample_utils.py", line 153, in build_driz_weight
 inv_variance = model.var_rnoise**-1
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/asdf/tags/core/ndarray.py", line 556, in *_operation_*
 return getattr(self._make_array(), name)(*args)
 File "/user/hilbert/anaconda2/envs/mirage-py3.8/lib/python3.8/site-packages/asdf/tags/core/ndarray.py", line 264, in _make_array
 self._array = np.ndarray(
 TypeError: buffer is too small for requested array

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2328?focusedCommentId=558920#comment-558920):_

This turns out to have been a problem with the input data. I accidentally had uncal files listed in my level 3 association file. So when the level3 pipeline went back to write the updated WCS back into the input files, it ended up saving the modified datamodel instance back into the uncal files. Then when I re-ran all stages of the pipeline later, the problems snowballed because the uncal files were now in the wrong format.

I went back and re-created my simulated data from scratch and fixed the association file, and all stages of the pipeline have run successfully.

**Comment by stscijgbot-jp** [comment]
_Comment by [Bryan Hilbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hilbert) on [JIRA](https://jira.stsci.edu/browse/JP-2328?focusedCommentId=558922#comment-558922):_

User error.
