### ISSUE TITLE
Level_3 error: cannot reshape array. can be rescued without a needed repair

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7271]
_Issue [JP-2943](https://jira.stsci.edu/browse/JP-2943) was created on JIRA by [Steven Slowinski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slowinski):_

We are regularly seeing the issue where a dataset will fail level 3 processing due to the 'cannot reshape array' error.  The level_3 dataset can later be rescued and successfully complete processing without any repair being done.

2022-08-30 17:26:40,404 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 200 sources in jw01306001001_02101_00007_nrca1_cal.fits.
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/bin/strun", line 28, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 179, in from_cmdline
return cmdline.step_from_cmdline(args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/cmdline.py", line 349, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 485, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_image3.py", line 86, in process
input_models = self.tweakreg(input_models)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 485, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/tweakreg/tweakreg_step.py", line 83, in process
catalog = make_tweakreg_catalog(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/tweakreg/tweakreg_catalog.py", line 67, in make_tweakreg_catalog
threshold_img = detect_threshold(model.data, nsigma=snr_threshold)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/utils/decorators.py", line 546, in wrapper
return function(*args, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/utils/decorators.py", line 546, in wrapper
return function(*args, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/utils/decorators.py", line 546, in wrapper
return function(*args, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/photutils/segmentation/detect.py", line 138, in detect_threshold
clipped_data = sigma_clip(data, masked=False, return_bounds=False,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/stats/sigma_clipping.py", line 600, in *_call_*
data = np.asanyarray(data)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/asdf/tags/core/ndarray.py", line 355, in *_getattr_*
return getattr(self._make_array(), attr)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/asdf/tags/core/ndarray.py", line 256, in _make_array
shape = self.get_actual_shape(self._shape, self._strides, self._dtype, len(block))
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/asdf/fits_embed.py", line 32, in *_len_*
return self._hdu.data.nbytes
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/utils/decorators.py", line 777, in *_get_*
val = self.fget(obj)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/io/fits/hdu/image.py", line 235, in data
data = self._get_scaled_image_data(self._data_offset, self.shape)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/io/fits/hdu/image.py", line 779, in _get_scaled_image_data
raw_data = self._get_raw_data(shape, code, offset)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/io/fits/hdu/base.py", line 522, in _get_raw_data
return self._file.readarray(offset=offset, dtype=code, shape=shape)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/io/fits/file.py", line 330, in readarray
data.shape = shape
ValueError: cannot reshape array of size 0 into shape (2048,2048)
----------------------------------------------------------------------
ERROR RUNNING STEP 'Image3Pipeline':
cannot reshape array of size 0 into shape (2048,2048)
----------------------------------------------------------------------
2022242172642-E-ERROR-/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_image3.cfg FAILED (exit=1) on jw01306-o001_20220830t161955_image3_003_asn.json.
2022242172642-I-INFO-restoring SDP python env...
SSB python deactivated; OWL python ready for interactive use.
2022242172642-E-ERROR-exit status=1
2022242172642-E-ERROR-calibration_wrapper.csh FAILED. Archiving will NOT be attempted.

**Comment by stscijgbot-jp** [comment]
_Comment by [Steven Slowinski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slowinski) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=604498#comment-604498):_

Recent examples

jw01304-o005_20220826t151830_image3_003
jw01305-o001_20220826t152753_image3_002
jw01305-o002_20220826t152753_image3_002
jw01305-o002_20220826t152753_image3_003
jw01306-o001_20220830t161955_image3_003
jw01305-o003_20220826t152753_image3_002
jw01304-o004_20220826t151830_image3_003
jw01304-o052_20220826t151830_image3_002
jw01305-o004_20220826t152753_image3_003
jw01305-o004_20220826t152753_image3_002

**Comment by stscijgbot-jp** [comment]
_Comment by [Steven Slowinski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=slowinski) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=604499#comment-604499):_

See other examples in DMSOPS-558

**Comment by stscijgbot-jp** [comment]
_Comment by [Faith Abney](https://jira.stsci.edu/secure/ViewProfile.jspa?name=abney) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=604507#comment-604507):_

Moving from DMSOPS to JWSTDMS since we would developers to figure out why they fail and need to be rescued when they work the second time just fine.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=610849#comment-610849):_

Appears as though all examples listed above are coordinated parallel observations with NIRCam and NIRISS imaging - a possible clue as to what the issue is.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=625949#comment-625949):_

this appears to occur when there's a "truncation" problem in the data file, for whatever reason, file transfer perhaps?

**Comment by stscijgbot-jp** [comment]
_Comment by [Jesse Doggett](https://jira.stsci.edu/secure/ViewProfile.jspa?name=doggett) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=648892#comment-648892):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) Is there something concrete that points to a "truncation" problem that could be detected by software.

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Could it be the case that when doing Level 3 processing, that it would be impossible for an "array of size 0" to occur except for a corrupted input file?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=649117#comment-649117):_

a recent example of this failure is
||Fileset||Status||Rescue||Start Time||Completion Time||Process Name||State||Duration||Exit Code||
|[jw01208-o023_20230526t031845_image3_00005](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o023_20230526t031845_image3_00005_1686984882.241194&fileset_name=jw01208-o023_20230526t031845_image3_00005&dag_name=LEVEL_3) |success| |2023-06-17 20:30:06.0|2023-06-17 21:40:44.79|LEVEL_3|Exited|4238.791|0|
|[jw01208-o023_20230526t031845_image3_00005](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o023_20230526t031845_image3_00005_1686984882.241194&fileset_name=jw01208-o023_20230526t031845_image3_00005&dag_name=LEVEL_3) |error|2023-06-17 20:29:51.7|2023-06-17 17:15:06.0|2023-06-17 17:41:56.467|LEVEL_3|Exited|1610.4681|1|
|[jw01208-o023_20230526t031845_image3_00005](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o023_20230526t031845_image3_00005_1686984882.241194&fileset_name=jw01208-o023_20230526t031845_image3_00005&dag_name=LEVEL_3) |error|2023-06-17 17:14:12.45|2023-06-17 15:31:22.0|2023-06-17 15:57:56.333|LEVEL_3|Exited|1594.3342|1|
|[jw01208-o023_20230526t031845_image3_00005](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o023_20230526t031845_image3_00005_1686984882.241194&fileset_name=jw01208-o023_20230526t031845_image3_00005&dag_name=LEVEL_3) |error|2023-06-17 15:31:04.9|2023-06-17 06:58:17.0|2023-06-17 07:24:54.27|LEVEL_3|Exited|1597.2694|1|

where each row shows the status of each attempt to process the **same** fileset: there were three failures, each of which was subsequently rescued for retry, until the eventual success in the fourth attempt.   

the full alog .out file for each of the failures is attached

the logs can be found in Directory Path: /ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o023_20230526t031845_image3_00005_1686984882.241194

**Comment by stscijgbot-jp** [comment]
_Comment by [Jo Taylor](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jotaylor) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=659304#comment-659304):_

Is it possible to access statistics on how many datasets have encountered this issue? Or are all the datasets listed above the only ones affected? This will help the NIRISS team evaluate a criticality rating.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=673428#comment-673428):_

the datasets listed in this ticket are definitely **not** the only ones where this issue is encountered. we see it all the time in ops, and the cases are too numerous to list. a very recent example is [jw01476-o003_20231124t012407_image3_00002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01476-o003_20231124t012407_image3_00002_1700819434.384935&fileset_name=jw01476-o003_20231124t012407_image3_00002&dag_name=REPRO_LEVEL_3), which needed no less than 13 retries before eventually succeeding, taking 4 days and a lot of manual intervention in the process. we really need a fix for this

**Comment by stscijgbot-jp** [comment]
_Comment by [Alicia Canipe](https://jira.stsci.edu/secure/ViewProfile.jspa?name=acanipe) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=673431#comment-673431):_

Updated NRC criticality assessment based on how resource intensive this bug seems to be.

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=681280#comment-681280):_

Looking at [jw01476-o003_20231124t012407_image3_00002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01476-o003_20231124t012407_image3_00002_1700819434.384935&fileset_name=jw01476-o003_20231124t012407_image3_00002&dag_name=REPRO_LEVEL_3), it seems that the issue always appears at the same place, and always has the characteristic of being due to a file being corrupted.  The error happens in the outlier detection step after the data have been resampled and the median calculation is being performed using the output from the resampling.  These output data should have been written to a local filesystem.

Running the step locally on my macbook executes with no problems.  I also tried running using jwcalibdev accessing data on central store (a non-local filesystem), and again the task completed with no problems.  It's not obvious how to duplicate the problem, making it difficult to diagnose and even more difficult to test possible solutions.

Since the problem seems to be related to file corruption, one possible solution is to verify the files that are written by the resample step at the time they are written, so they can be re-written if there are issues.

**Comment by stscijgbot-jp** [comment]
_Comment by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=684383#comment-684383):_

Another option is to use the large amount of memory available on the Ops machines.  The outlier_detection stage allows drizzling, median creation and blotting to be done IN MEMORY (using the --in_memory=True flag).  This avoids writing out the intermediate files. but can require large mounts of memory.  I was able to run the image3 pipeline for the above case ([jw01476-o003_20231124t012407_image3_00002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01476-o003_20231124t012407_image3_00002_1700819434.384935&fileset_name=jw01476-o003_20231124t012407_image3_00002&dag_name=REPRO_LEVEL_3)) on jwcalibdev with no issues.  It has 48 nircam images, each of about 1.1Gb.  I suspect that the operations machines have significantly more memory than jwcalibdev, so would probably be able to handle most, if not all, instances of the image3 pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=689269#comment-689269):_

Fixed by #8305

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=693234#comment-693234):_

Update: Testing of 10.2 by SDP on ? string shows the same error despite the fix we have in place.

Reopening this ticket.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=693669#comment-693669):_

Fixed by #8418 which adds <asn_id> to the file name suffix of outlier_i2d.fits files, in order to avoid file name clashes when parallel processes are using the same exposures in the same working directory in the operations environment.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=719041#comment-719041):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) : Can this be closed now based on 11.0 performance in ops?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2943?focusedCommentId=944992#comment-944992):_

although we still do see this type of failures occasionally in our latest repro runs with b11.1.1, they're much less frequent and less numerous. i'm ok with closing it, and if they happen more often, we can file a new ticket.
