### ISSUE TITLE
level_3 (spec3) failure of jw01473-o016 NRS_MSASPEC

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7293]
_Issue [JP-2931](https://jira.stsci.edu/browse/JP-2931) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

Fileset jw01473-o016_20220916t051545_spec3_001 failed lev3 during the outlier_detection step with the error message "The points in dimension 0 must be strictly ascending" 
```java
2022-09-16 10:08:47,660 - CRDS - DEBUG - Final effective context is 'jwst_0977.pmap' 
2022-09-16 10:08:47,660 - CRDS - DEBUG - Computing best references locally. 
2022-09-16 10:08:47,661 - CRDS - DEBUG - Bestrefs header: 
{'META.EXPOSURE.READPATT [READPATT]': 'NRSIRS2RAPID', 
'META.EXPOSURE.TYPE [EXP_TYPE]': 'NRS_MSASPEC', 
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NRS2', 
'META.INSTRUMENT.FILTER [FILTER]': 'CLEAR', 
'META.INSTRUMENT.GRATING [GRATING]': 'PRISM', 
'META.INSTRUMENT.LAMP_MODE [OPMODE]': 'MSASPEC', 
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE', 
'META.INSTRUMENT.NAME [INSTRUME]': 'NIRSPEC', 
'META.OBSERVATION.DATE [DATE-OBS]': '2022-04-23', 
'META.OBSERVATION.TIME [TIME-OBS]': '10:50:26.893999', 
'META.SUBARRAY.NAME [SUBARRAY]': 'FULL', 
'META.SUBARRAY.XSIZE [SUBSIZE1]': '2048.0', 
'META.SUBARRAY.XSTART [SUBSTRT1]': '1.0', 
'META.SUBARRAY.YSIZE [SUBSIZE2]': '2048.0', 
'META.SUBARRAY.YSTART [SUBSTRT2]': '1.0', 
'META.VISIT.TSOVISIT [TSOVISIT]': 'F', 
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED', 
'REFTYPE': 'UNDEFINED'} 
2022-09-16 10:08:47,662 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_nirspec_apcorr_0004.fits' 
2022-09-16 10:08:47,663 - stpipe.Spec3Pipeline.extract_1d - INFO - Using APCORR file /ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/nirspec/jwst_nirspec_apcorr_0004.fits 
2022-09-16 10:08:47,733 - stpipe.Spec3Pipeline.extract_1d - INFO - Turning on source position correction for exp_type = NRS_MSASPEC 
2022-09-16 10:08:47,733 - stpipe.Spec3Pipeline.extract_1d - INFO - Processing spectral order 0 
2022-09-16 10:08:47,733 - stpipe.Spec3Pipeline.extract_1d - INFO - Setting use_source_posn to False for source type EXTENDED 
2022-09-16 10:08:47,748 - stpipe.Spec3Pipeline.extract_1d - INFO - Using extraction limits: xstart=0, xstop=420, ystart=10.0, ystop=17.0 
2022-09-16 10:08:48,081 - stpipe.Spec3Pipeline.extract_1d - INFO - Saved model in jw01473-o016_s00219_nirspec_clear-prism_x1d.fits 
2022-09-16 10:08:48,082 - stpipe.Spec3Pipeline.extract_1d - INFO - Step extract_1d done 
2022-09-16 10:08:50,368 - stpipe.Spec3Pipeline - INFO - Saved model in jw01473-o016_s00220_nirspec_clear-prism_cal.fits 
2022-09-16 10:08:57,261 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection running with args (<SourceModelContainer>,). 
2022-09-16 10:08:57,263 - stpipe.Spec3Pipeline.outlier_detection - INFO - Step outlier_detection parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': 'crf', 'search_output_file': False, 'input_dir': '/ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3', 'weight_type': 'ivm', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'nlow': 0, 'nhigh': 0, 'maskpt': 0.7, 'grow': 1, 'snr': '5.0 4.0', 'scale': '1.2 0.7', 'backg': 0.0, 'save_intermediate_results': False, 'resample_data': True, 'good_bits': '~DO_NOT_USE', 'scale_detection': False, 'allowed_memory': None} 
2022-09-16 10:08:57,270 - stpipe.Spec3Pipeline.outlier_detection - INFO - Performing outlier detection on 3 inputs 
2022-09-16 10:08:57,728 - stpipe.Spec3Pipeline.outlier_detection - INFO - Driz parameter kernal: square 
2022-09-16 10:08:57,728 - stpipe.Spec3Pipeline.outlier_detection - INFO - Driz parameter pixfrac: 1.0 
2022-09-16 10:08:57,728 - stpipe.Spec3Pipeline.outlier_detection - INFO - Driz parameter fillval: INDEF 
2022-09-16 10:08:57,728 - stpipe.Spec3Pipeline.outlier_detection - INFO - Driz parameter weight_type: ivm 
Traceback (most recent call last): 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/bin/strun", line 28, in <module> 
step = Step.from_cmdline(sys.argv[1:]) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 179, in from_cmdline 
return cmdline.step_from_cmdline(args) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/cmdline.py", line 349, in step_from_cmdline 
step.run(*positional) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 485, in run 
step_result = self.process(*args) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec3.py", line 227, in process 
result = self.outlier_detection(result) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/stpipe/step.py", line 485, in run 
step_result = self.process(*args) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/outlier_detection/outlier_detection_step.py", line 159, in process 
step.do_detection() 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/outlier_detection/outlier_detection_spec.py", line 74, in do_detection 
drizzled_models = resamp.do_drizzle() 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/resample/resample.py", line 118, in do_drizzle 
return self.resample_many_to_many() 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/resample/resample.py", line 156, in resample_many_to_many 
driz.add_image(data, img.meta.wcs, inwht=inwht) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/resample/gwcs_drizzle.py", line 184, in add_image 
dodrizzle(insci, inwcs, inwht, self.outwcs, self.outsci, self.outwht, 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/resample/gwcs_drizzle.py", line 365, in dodrizzle 
pixmap = resample_utils.calc_gwcs_pixmap(input_wcs, output_wcs, insci.shape) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/resample/resample_utils.py", line 109, in calc_gwcs_pixmap 
pixmap = np.dstack(reproject(in_wcs, out_wcs)(grid[0], grid[1])) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/jwst/resample/resample_utils.py", line 160, in _reproject 
det = backward_transform(*tuple(flat_sky)) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__ 
outputs = self._generic_evaluate(evaluate, inputs, 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate 
outputs = evaluate(_inputs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate 
return self._evaluate(*_inputs, **kwargs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3232, in _evaluate 
return self.right(*leftval, **kw) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__ 
outputs = self._generic_evaluate(evaluate, inputs, 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate 
outputs = evaluate(_inputs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate 
return self._evaluate(*_inputs, **kwargs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3217, in _evaluate 
leftval = self.left(*args, **kw) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__ 
outputs = self._generic_evaluate(evaluate, inputs, 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate 
outputs = evaluate(_inputs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate 
return self._evaluate(*_inputs, **kwargs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3225, in _evaluate 
rightval = self.right(*(args[self.left.n_inputs:]), **kw) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 395, in __call__ 
new_call = make_function_with_signature( 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 374, in __call__ 
return super(cls, self).__call__(*inputs, **kwargs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__ 
outputs = self._generic_evaluate(evaluate, inputs, 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate 
outputs = evaluate(_inputs) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 936, in evaluate 
return self.evaluate(*chain(_inputs, parameters)) 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/astropy/modeling/tabular.py", line 225, in evaluate 
result = interpn(self.points, self.lookup_table, inputs, 
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.6.2.20220719-py39/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 2688, in interpn 
raise ValueError("The points in dimension %d must be strictly " 
ValueError: The points in dimension 0 must be strictly ascending 
---------------------------------------------------------------------- 
ERROR RUNNING STEP 'Spec3Pipeline': 
The points in dimension 0 must be strictly ascending 
----------------------------------------------------------------------  ```
this is very similar to JWSTDMS-696 with the same error message (issue resolved in B8.0.1).

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=607345#comment-607345):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) Could you attach the ASN file jw01473-o016_20220916t051545_spec3_001 to the ticket, in order for us to triage the problem.

new logs attached

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=607351#comment-607351):_

spec3 asn file attached

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=607499#comment-607499):_

I just successfully processed this with the latest Cal, so now I'm wondering which source it died on during Ops processing. [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) can you track down the processing log file and attach to the ticket?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=607504#comment-607504):_

i've attached the two ALOG* files

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=607892#comment-607892):_

I just successfully processed this using Cal 1.6.2, which was the version in use in Ops when the failure occurred. I also checked and confirmed that both run used the same reference files. So I can't reproduce the error using either B8.1.1 or B8.1.2. Hence I'm suggesting that you just go ahead and try processing it again with B8.1.2 and see what happens.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=607979#comment-607979):_

i've rescued the failed job with b8.1.2 installed in ops, and got the same failure with the same error message. so unfortunately, no change.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=608002#comment-608002):_

OK, thanks for trying. Now I'm stumped. Back to the drawing board.

**Comment by stscijgbot-jp** [comment]
_Comment by [Catherine Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=609234#comment-609234):_

Moving from JWSTDMS-755 to JP project, this is a CAL-only issue.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=609346#comment-609346):_

This error shows the same characteristics as another bug, in that it runs fine in a B8.1.2 environment on Mac OS, but fails under B8.1.2 on Linux. The failure occurs when trying to process slit 220 in the outlier_detection step.

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=610008#comment-610008):_

jw02640-o001_20221001t082455_spec3_002 looks similar, seen in repro 10/1 build 8.1.2

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=615119#comment-615119):_

seen for another nrs_msa case [jw01117-o006_20221103t194926_spec3_001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01117-o006_20221103t194926_spec3_001_1667509042.627619&fileset_name=jw01117-o006_20221103t194926_spec3_001&dag_name=LEVEL_3) during repro with b8.1.3
```
The points in dimension 0 must be strictly ascending or descending ```

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=616749#comment-616749):_

Also seen for jw02609-o006_20221019t153819_spec3_001

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=622664#comment-622664):_

This was seen again for [jw01473-o016_20221222t050339_spec3_00001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01473-o016_20221222t050339_spec3_00001_1671694212.898010&fileset_name=jw01473-o016_20221222t050339_spec3_00001&dag_name=REPRO_LEVEL_3) during repro with B9.0.2

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=626821#comment-626821):_

seen for [jw01448-o010_20230127t002543_spec3_00001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01448-o010_20230127t002543_spec3_00001_1675105631.899070&fileset_name=jw01448-o010_20230127t002543_spec3_00001&dag_name=REPRO_LEVEL_3) during jan26 repro with b9.0.2

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=629894#comment-629894):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) Do you want to leave this ticket in its RTT status until Ops can test the fix when they get B9.1.x?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=630516#comment-630516):_

yes, we'd like to test it with b9.1 in ops. jw01345-o061_20230108t085135_spec3_00002 (for f290lp-g395m) also failed to this error, leading to the "funny" effect of previews being ingested seen in JWSTDMS-812

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2931?focusedCommentId=635621#comment-635621):_

not all programs in this ticket have been reprocessed with b9.1.2 before repro was paused due to snowball issues, but for those that had (1117, 1473, 2640), this error was no longer seen. this ticket can be considered passed, and closed.
