### ISSUE TITLE
nrc_wfss extract_2d crashing in l2b with "index 0 is out of bounds for axis 0 with size 0"

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7314]
_Issue [JP-2982](https://jira.stsci.edu/browse/JP-2982) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

error seen during repro of datasets for jw01309, obs 23,24,25,26 with b8.1.2
```
jw01309-o023_20220930t102114_spec2_010	LEVEL_2B	Sep 30 2022 02:02:41:000PM	1
jw01309-o023_20220930t102114_spec2_018	LEVEL_2B	Sep 30 2022 02:02:43:000PM	1
jw01309-o023_20220930t102114_spec2_027	LEVEL_2B	Sep 30 2022 02:02:46:000PM	1
jw01309-o023_20220930t102114_spec2_028	LEVEL_2B	Sep 30 2022 02:02:45:000PM	1
jw01309-o023_20220930t102114_spec2_043	LEVEL_2B	Sep 30 2022 02:02:46:000PM	1
jw01309-o024_20220930t102114_spec2_016	LEVEL_2B	Sep 30 2022 02:24:44:000PM	1
jw01309-o025_20220930t102114_spec2_009	LEVEL_2B	Sep 30 2022 01:17:51:000PM	1
jw01309-o026_20220930t102114_spec2_008	LEVEL_2B	Sep 30 2022 12:31:06:000PM	1
jw01309-o026_20220930t102114_spec2_034	LEVEL_2B	Sep 30 2022 12:39:39:000PM	1 ```
with traceback like 
```
2022-09-30 14:25:07,543 - CRDS - DEBUG - Final effective context is 'jwst_0988.pmap'
2022-09-30 14:25:07,543 - CRDS - DEBUG - Computing best references locally.
2022-09-30 14:25:07,544 - CRDS - DEBUG - Bestrefs header:
{'META.EXPOSURE.NOUTPUTS [NOUTPUTS]': '4.0',
'META.EXPOSURE.READPATT [READPATT]': 'SHALLOW4',
'META.EXPOSURE.TYPE [EXP_TYPE]': 'NRC_WFSS',
'META.INSTRUMENT.CHANNEL [CHANNEL]': 'LONG',
'META.INSTRUMENT.CORONAGRAPH [CORONMSK]': 'UNDEFINED',
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NRCALONG',
'META.INSTRUMENT.FILTER [FILTER]': 'F322W2',
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'UNDEFINED',
'META.INSTRUMENT.MODULE [MODULE]': 'A',
'META.INSTRUMENT.NAME [INSTRUME]': 'NIRCAM',
'META.INSTRUMENT.PUPIL [PUPIL]': 'GRISMC',
'META.OBSERVATION.DATE [DATE-OBS]': '2022-07-03',
'META.OBSERVATION.TIME [TIME-OBS]': '09:43:51.093',
'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
'META.VISIT.CROWDED_FIELD [CROWDFLD]': 'F',
'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED',
'REFTYPE': 'UNDEFINED'}
2022-09-30 14:25:07,544 - CRDS - DEBUG - Reference type 'wavelengthrange' defined as 'jwst_nircam_wavelengthrange_0003.asdf'
2022-09-30 14:25:07,551 - stpipe.Spec2Pipeline.extract_2d - INFO - EXP_TYPE is NRC_WFSS
2022-09-30 14:25:07,565 - stpipe.Spec2Pipeline.extract_2d - INFO - Getting objects from jw01309-o024_t005_nircam_clear-f410m_cat.ecsv
2022-09-30 14:25:07,898 - stpipe.Spec2Pipeline.extract_2d - INFO - Partial order on detector for obj: 1 order: 1
2022-09-30 14:25:07,910 - stpipe.Spec2Pipeline.extract_2d - INFO - Partial order on detector for obj: 1 order: 2
2022-09-30 14:25:08,029 - stpipe.Spec2Pipeline.extract_2d - INFO - Partial order on detector for obj: 2 order: 1
2022-09-30 14:25:08,036 - stpipe.Spec2Pipeline.extract_2d - INFO - Partial order on detector for obj: 2 order: 2
2022-09-30 14:25:08,051 - stpipe.Spec2Pipeline.extract_2d - INFO - Partial order on detector for obj: 3 order: 1
<snip>
...

2022-09-30 14:25:43,376 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extracted for obj: 74 order: 1:
2022-09-30 14:25:43,376 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:0, xmax:3.2075220091078194), (ymin:0, ymax:485)
2022-09-30 14:25:43,584 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extracted for obj: 74 order: 2:
2022-09-30 14:25:43,585 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:0, xmax:0.056528326115440564), (ymin:1250, ymax:2048)
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 117, in process
result = self.process_exposure_product(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 247, in process_exposure_product
calibrated = self._process_grism(calibrated)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 443, in _process_grism
calibrated = self.extract_2d(calibrated)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/stpipe/step.py", line 483, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/extract_2d/extract_2d_step.py", line 37, in process
output_model = extract_2d.extract2d(dm, self.slit_name,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/extract_2d/extract_2d.py", line 79, in extract2d
output_model = extract_grism_objects(input_model,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/extract_2d/grisms.py", line 485, in extract_grism_objects
new_slit.wavelength = compute_wavelength_array(new_slit)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/extract_2d/grisms.py", line 576, in compute_wavelength_array
wavelength = transform(x, y)[2]
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate
return self._evaluate(*_inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3217, in _evaluate
leftval = self.left(*args, **kw)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate
return self._evaluate(*_inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3217, in _evaluate
leftval = self.left(*args, **kw)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate
return self._evaluate(*_inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3217, in _evaluate
leftval = self.left(*args, **kw)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate
return self._evaluate(*_inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3232, in _evaluate
return self.right(*leftval, **kw)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate
return self._evaluate(*_inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3217, in _evaluate
leftval = self.left(*args, **kw)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3191, in evaluate
return self._evaluate(*_inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 3217, in _evaluate
leftval = self.left(*args, **kw)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 395, in __call__
new_call = make_function_with_signature(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 374, in __call__
return super(cls, self).__call__(*inputs, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1076, in __call__
outputs = self._generic_evaluate(evaluate, inputs,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 1040, in _generic_evaluate
outputs = evaluate(_inputs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/astropy/modeling/core.py", line 936, in evaluate
return self.evaluate(*chain(_inputs, parameters))
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.7.2.20220912-py39/lib/python3.9/site-packages/jwst/transforms/models.py", line 730, in evaluate
iorder = self._order_mapping[int(order.flatten()[0])]
IndexError: index 0 is out of bounds for axis 0 with size 0
----------------------------------------------------------------------
ERROR RUNNING STEP 'Spec2Pipeline': ```
jshih noted:
```
Looking at a few more of these errors, they are all preceded by either xmax-xmin < 1 or ymax-ymin < 1, for example
 2022-09-30 14:25:43,585 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:0, xmax:0.056528326115440564), (ymin:1250, ymax:2048) and
2022-09-30 14:03:52,902 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:0, xmax:1359), (ymin:0, ymax:0.04441537685625008)  ```
these errors were not encountered during reprocessing of the same datasets with previous builds. possibly a result of changes in crds reference files?

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Ridgaway](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ridgaway) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=610004#comment-610004):_

A similar error was seen for [jw01538-o067_20221004t132953_tso-spec2_002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01538-o067_20221004t132953_tso-spec2_002_1664912875.544509&fileset_name=jw01538-o067_20221004t132953_tso-spec2_002&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [Catherine Kaleida](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ckaleida) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=610339#comment-610339):_

[Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham) to assess if reference file changes are the root cause of this error.  If so, then we can move this JWSTDMS ticket to the CRDS project to get the reference file issue remedied.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=612790#comment-612790):_

While the syntax of the error messages for the jw01309 and jw01538-o067 failures are the same, they are inherently different problems. The first is an error that occurs in the extract_2d step when attempting to extract a 2D cutout that has 0 length in one axis. The second is an error in the extract_1d step (for NIRISS SOSS data, not NIRCam WFSS) when trying to extract a 1D spectrum.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=612791#comment-612791):_

Can someone attach to this ticket an example of one of the spec2 asn files for jw01309 that had a failure, such as jw01309-o024_20220930t102114_spec2_016?  Because they failed, we of course can't get access to any of the files through MAST. Without the contents of the asn file we don't know what dataset was being processed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=612800#comment-612800):_

the jw01309-o024_20220930t102114_spec2_016_asn.json is attached

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=612937#comment-612937):_

Regardless of whether or not the appearance of this error was triggered by new CRDS reference files, the calibration code itself is to blame for trying to extract source/spectrum regions that have zero extent in one or more dimensions and needs to be updated to be more robust against such failures. So I'm removing the CRDS component from this ticket and transferring it over to the JP project, where an update to the Cal pipeline will be implemented.

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=613720#comment-613720):_

Problem is also seen with jw01187-o073_20221026t142607_spec2_003

I'll attach the asn

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=613727#comment-613727):_

also seen for 

jw01309-o024_20221024t211419_spec2_026	
jw01309-o024_20221024t211419_spec2_015
jw01309-o023_20221024t211419_spec2_048	
jw01309-o023_20221024t211419_spec2_041
jw01309-o023_20221024t211419_spec2_021
jw01309-o025_20221024t211419_spec2_008
jw01309-o026_20221024t211419_spec2_028
jw01309-o026_20221024t211419_spec2_002

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=613777#comment-613777):_

Fixed by #7312

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=613786#comment-613786):_

The example 1309 dataset, as well as jw01187-o073_20221026t142607_spec2_003, now succeed processing using the implemented fix.

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Ridgaway](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ridgaway) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=613801#comment-613801):_

Additional instances of the error were seen in:

[jw01243-o001_20221027t181043_spec2_115](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01243-o001_20221027t181043_spec2_115_1666912769.779402&fileset_name=jw01243-o001_20221027t181043_spec2_115&dag_name=LEVEL_2B)

[jw01243-o001_20221027t181043_spec2_091](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01243-o001_20221027t181043_spec2_091_1666912747.315544&fileset_name=jw01243-o001_20221027t181043_spec2_091&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [Michael Ridgaway](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ridgaway) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=614075#comment-614075):_

More instances seen in [jw02078-o002_20221028t234108_spec2_002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw02078-o002_20221028t234108_spec2_002_1667018187.887513&fileset_name=jw02078-o002_20221028t234108_spec2_002&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=614836#comment-614836):_

two more cases during repro of 1208 (nis_wfss)

[jw01208-o026_20221102t115305_spec2_017](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o026_20221102t115305_spec2_017_1667406951.405786&fileset_name=jw01208-o026_20221102t115305_spec2_017&dag_name=LEVEL_2B)

[jw01208-o026_20221102t115305_spec2_018](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01208-o026_20221102t115305_spec2_018_1667406974.837121&fileset_name=jw01208-o026_20221102t115305_spec2_018&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=616704#comment-616704):_

Also seen for jw02078-o002_20221028t234108_spec2_002

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=617549#comment-617549):_

Also seen for 

jw01895-o001_20221117t154544_spec2_00071
jw01895-o001_20221117t154544_spec2_00065
jw01895-o001_20221117t154544_spec2_00047
jw01895-o001_20221117t154544_spec2_00026

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=618190#comment-618190):_

Also seen for jw02078-o002_20221122t230554_spec2_00010 in reprocessing using B9.0

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=618211#comment-618211):_

Also seen for [jw02738-o003_20221126t221703_spec2_00002](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw02738-o003_20221126t221703_spec2_00002_1669601950.992428&fileset_name=jw02738-o003_20221126t221703_spec2_00002&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=623818#comment-623818):_

I believe this was also seen for these new cases:

[jw01933-o001_20230107t005123_spec2_00144](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01933-o001_20230107t005123_spec2_00144_1673116172.314531&fileset_name=jw01933-o001_20230107t005123_spec2_00144&dag_name=LEVEL_2B)
[jw01933-o001_20230107t005123_spec2_00130](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01933-o001_20230107t005123_spec2_00130_1673116149.753685&fileset_name=jw01933-o001_20230107t005123_spec2_00130&dag_name=LEVEL_2B)
[jw01933-o001_20230107t005123_spec2_00117](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01933-o001_20230107t005123_spec2_00117_1673116047.414889&fileset_name=jw01933-o001_20230107t005123_spec2_00117&dag_name=LEVEL_2B)
[jw01933-o001_20230107t005123_spec2_00099](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01933-o001_20230107t005123_spec2_00099_1673115893.795801&fileset_name=jw01933-o001_20230107t005123_spec2_00099&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=623851#comment-623851):_

Performed a spot check using the latest B9.1 release candidate software for Cal and confirmed that jw01933-o001_20230107t005123_spec2_00144 now succeeds in level-2b processing. Previously, an error was caused by object 927, spectral order 2 only having a partial pixel on the detector in the y-axis direction:
```java
2023-01-07 18:34:22,029 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extracted for obj: 927 order: 2:
2023-01-07 18:34:22,029 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:982, xmax:2048), (ymin:0, ymax:0.22769361303964786) ```
In the most recent version of Cal, that partial pixel is correctly identified and extraction for that object is skipped, because we can only extract whole pixels.

So this is still targeted to be fixed once 9.1 is installed in Ops.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=629905#comment-629905):_

[Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) Do you want to keep this ticket open until you've had a chance to test and verify in Ops using B9.1.x?

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=630739#comment-630739):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Yes that sounds good, I'll report back once we have B9.1.x

**Comment by stscijgbot-jp** [comment]
_Comment by [Aiden Kovacs](https://jira.stsci.edu/secure/ViewProfile.jspa?name=akovacs) on [JIRA](https://jira.stsci.edu/browse/JP-2982?focusedCommentId=636927#comment-636927):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) Apologies for the late reply - we are no longer seeing this error since B9.1.2!
