### ISSUE TITLE
`check-dependencies` started failing with `no module named 'jwst'`

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/jwst#7383]
approximately 21 hours ago, the `check-dependencies` job started failing with the following error:
```
  File "/home/runner/work/jwst/jwst/.tox/check-dependencies/bin/verify_install_requires", line 7, in <module>
    import jwst
ModuleNotFoundError: No module named 'jwst'
```

### successful run: 
https://github.com/spacetelescope/jwst/actions/runs/3640001686/jobs/6144099116
```
Collecting tox
  Using cached tox-3.27.1-py2.py3-none-any.whl (86 kB)
Collecting filelock>=3.0.0
  Downloading filelock-3.8.2-py3-none-any.whl (10 kB)
Collecting packaging>=14
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting pluggy>=0.12.0
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py>=1.4.17
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting six>=1.14.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0
  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 96.2 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting distlib<1,>=0.3.6
  Using cached distlib-0.3.6-py2.py3-none-any.whl (468 kB)
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.6.0-py3-none-any.whl (14 kB)
Installing collected packages: distlib, six, pyparsing, py, pluggy, platformdirs, filelock, virtualenv, packaging, tox
Successfully installed distlib-0.3.6 filelock-3.8.2 packaging-21.3 platformdirs-2.6.0 pluggy-1.0.0 py-1.11.0 pyparsing-3.0.9 six-1.16.0 tox-3.27.1 virtualenv-20.17.1

check-dependencies create: /home/runner/work/jwst/jwst/.tox/check-dependencies
check-dependencies develop-inst: /home/runner/work/jwst/jwst
check-dependencies installed: asdf==2.14.2,asdf-astropy==0.3.0,asdf-coordinates-schemas==0.1.0,asdf-standard==1.0.3,asdf-transform-schemas==0.3.0,asdf-unit-schemas==0.1.0,asdf-wcs-schemas==0.1.1,astropy==5.1.1,attrs==22.1.0,BayesicFitting==3.0.1,certifi==2022.9.24,charset-normalizer==2.1.1,ci-watson==0.6.1,codecov==2.1.12,colorama==0.4.6,contourpy==1.0.6,coverage==6.5.0,crds==11.16.16,cycler==0.11.0,drizzle==1.13.6,filelock==3.8.2,fonttools==4.38.0,future==0.18.2,gwcs==0.18.2,idna==3.4,imageio==2.22.4,iniconfig==1.1.1,jmespath==1.0.1,jsonschema==4.17.3,-e git+https://github.com/spacetelescope/jwst@c021a433ee6184b7d5f96f4bf70f42cf3c0b6c9f#egg=jwst,kiwisolver==1.4.4,lxml==4.9.1,matplotlib==3.6.2,networkx==2.8.8,numpy==1.23.5,opencv-python==4.6.0.66,packaging==21.3,Parsley==1.3,photutils==1.5.0,Pillow==9.3.0,pluggy==1.0.0,poppy==1.0.3,psutil==5.9.4,pyerfa==2.0.0.1,pyparsing==3.0.9,pyrsistent==0.19.2,pytest==7.2.0,pytest-cov==4.0.0,pytest-doctestplus==0.12.1,pytest-openfiles==0.5.0,python-dateutil==2.8.2,PyWavelets==1.4.1,PyYAML==6.0,readchar==4.0.3,requests==2.28.1,requests-mock==1.10.0,ruff==0.0.166,scikit-image==0.19.3,scipy==1.9.3,semantic-version==2.10.0,six==1.16.0,spherical-geometry==1.2.23,stcal==1.2.2,stdatamodels==0.4.3,stpipe==0.4.2,stsci.image==2.3.5,stsci.imagestats==1.6.3,stsci.stimage==0.2.6,tifffile==2022.10.10,tweakwcs==0.8.0,urllib3==1.26.13,wiimatch==0.3.1
check-dependencies run-test-pre: PYTHONHASHSEED='1027269208'
check-dependencies run-test-pre: commands[0] | python -m pip install --upgrade pip
Requirement already satisfied: pip in ./.tox/check-dependencies/lib/python3.11/site-packages (22.3.1)
check-dependencies run-test: commands[0] | verify_install_requires
___________________________________ summary ____________________________________
  check-dependencies: commands succeeded
  congratulations :)
```
### failing run: 
https://github.com/spacetelescope/jwst/actions/runs/3643191676/jobs/6151151742
```
Collecting tox
  Downloading tox-4.0.0-py3-none-any.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 3.3 MB/s eta 0:00:00
Collecting cachetools>=5.2
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting chardet>=5.1
  Downloading chardet-5.1.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 7.7 MB/s eta 0:00:00
Collecting colorama>=0.4.6
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting filelock>=3.8.2
  Downloading filelock-3.8.2-py3-none-any.whl (10 kB)
Collecting packaging>=21.3
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 7.3 MB/s eta 0:00:00
Collecting platformdirs>=2.5.4
  Downloading platformdirs-2.6.0-py3-none-any.whl (14 kB)
Collecting pluggy>=1
  Downloading pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting pyproject-api>=1.2.1
  Downloading pyproject_api-1.2.1-py3-none-any.whl (11 kB)
Collecting virtualenv>=20.17.1
  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 25.7 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 43.6 MB/s eta 0:00:00
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 49.8 MB/s eta 0:00:00
Installing collected packages: distlib, pyparsing, pluggy, platformdirs, filelock, colorama, chardet, cachetools, virtualenv, packaging, pyproject-api, tox
Successfully installed cachetools-5.2.0 chardet-5.1.0 colorama-0.4.6 distlib-0.3.6 filelock-3.8.2 packaging-21.3 platformdirs-2.6.0 pluggy-1.0.0 pyparsing-3.0.9 pyproject-api-1.2.1 tox-4.0.0 virtualenv-20.17.1

.pkg: install_requires> python -I -m pip install oldest-supported-numpy 'setuptools>=42' 'setuptools_scm[toml]>=3.4' wheel
.pkg: _optional_hooks> python /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_editable> python /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_editable> python -I -m pip install setuptools_scm wheel
.pkg: get_requires_for_build_sdist> python /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: install_requires_for_build_sdist> python -I -m pip install setuptools_scm
.pkg: build_editable> python /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
check-dependencies: install_package_deps> python -I -m pip install 'BayesicFitting>=3.0.1' 'asdf-astropy>=0.2.2' 'asdf-transform-schemas>=0.3.0' 'asdf>=2.14.1' 'astropy>=5.1' 'ci-watson>=0.5.0' 'codecov>=1.6.0' 'colorama>=0.4.1' 'crds>=11.16.14' 'drizzle>=1.13.6' 'gwcs>=0.18.2' 'numpy>=1.20' opencv-python 'photutils>=1.4.0' 'poppy>=1.0.2' 'psutil>=5.7.2' 'pyparsing>=2.2.1' 'pytest-cov>=2.9.0' 'pytest-doctestplus>=0.10.0' 'pytest-openfiles>=0.5.0' 'pytest>=6.0.0' 'readchar>=3.0' 'requests-mock>=1.0' 'requests>=2.22' ruff 'scikit-image>=0.17.2' 'scipy>=1.6.0' 'spherical-geometry>=1.2.22' 'stcal<1.3,>=1.2.2' 'stdatamodels<1.0,>=0.4.3' 'stpipe<1.0,>=0.4.2' 'stsci.image>=2.3.5' 'stsci.imagestats>=1.6.3' 'tweakwcs>=0.8.0' 'wiimatch>=0.2.1'
check-dependencies: install_package> python -I -m pip install --force-reinstall --no-deps /home/runner/work/jwst/jwst/.tox/.pkg/dist/jwst-1.8.3.dev64+gf35a3bf0-0.editable-cp311-cp311-linux_x86_64.whl
check-dependencies: commands_pre[0] .> python -m pip install --upgrade pip
Requirement already satisfied: pip in ./.tox/check-dependencies/lib/python3.11/site-packages (22.3.1)
check-dependencies: commands[0] .> verify_install_requires
Traceback (most recent call last):
  File "/home/runner/work/jwst/jwst/.tox/check-dependencies/bin/verify_install_requires", line 7, in <module>
    import jwst
ModuleNotFoundError: No module named 'jwst'
check-dependencies: exit 1 (0.03 seconds) .> verify_install_requires pid=6089
.pkg: _exit> python /opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  check-dependencies: FAIL code 1 (687.73=setup[686.30]+cmd[1.40,0.03] seconds)
  evaluation failed :( (687.90 seconds)
```

**Comment by zacharyburnett** [comment]
it appears that a major difference is that `tox` updated to version `4.0`. I will test if pinning `tox` to `<4.0` solves the issue in the short term.
