### ISSUE TITLE
level_2b (spec2) failure for mir_mrs tso: "too many values to unpack (expected 2)" 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7870]
_Issue [JP-3359](https://jira.stsci.edu/browse/JP-3359) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

we received the following error while reprocessing program 1556 with b9.3.1
```java
2023-08-26 11:57:58,463 - CRDS - DEBUG - Final effective context is 'jwst_1118.pmap'
2023-08-26 11:57:58,463 - CRDS - DEBUG - Computing best references locally.
2023-08-26 11:57:58,464 - CRDS - DEBUG - Bestrefs header:
{'META.EXPOSURE.READPATT [READPATT]': 'FASTR1',
'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_MRS',
'META.INSTRUMENT.BAND [BAND]': 'SHORT',
'META.INSTRUMENT.CHANNEL [CHANNEL]': '12.0',
'META.INSTRUMENT.CORONAGRAPH [CORONMSK]': 'UNDEFINED',
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIFUSHORT',
'META.INSTRUMENT.FILTER [FILTER]': 'UNDEFINED',
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'OFF',
'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
'META.OBSERVATION.DATE [DATE-OBS]': '2023-02-25',
'META.OBSERVATION.TIME [TIME-OBS]': '13:19:45.850',
'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
'META.VISIT.TSOVISIT [TSOVISIT]': 'T',
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED',
'REFTYPE': 'UNDEFINED'}
2023-08-26 11:57:58,464 - stpipe.Spec2Pipeline.photom - INFO - Using photom reference file: /ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/miri/jwst_miri_photom_0096.fits
2023-08-26 11:57:58,464 - stpipe.Spec2Pipeline.photom - INFO - Using area reference file: N/A
2023-08-26 11:58:00,044 - stpipe.Spec2Pipeline.photom - INFO - Using instrument: MIRI
2023-08-26 11:58:00,044 - stpipe.Spec2Pipeline.photom - INFO - detector: MIRIFUSHORT
2023-08-26 11:58:00,044 - stpipe.Spec2Pipeline.photom - INFO - exp_type: MIR_MRS
2023-08-26 11:58:00,044 - stpipe.Spec2Pipeline.photom - INFO - band: SHORT
2023-08-26 11:58:00,494 - stpipe.Spec2Pipeline.photom - WARNING - Keyword CDP_LOW_QUAL does not correspond to an existing DQ mnemonic, so will be ignored
2023-08-26 11:58:00,578 - stpipe.Spec2Pipeline.photom - INFO - Applying MRS IFU time dependent correction.
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 122, in process
result = self.process_exposure_product(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 272, in process_exposure_product
calibrated = self._process_common(calibrated)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 526, in _process_common
calibrated = self.photom(calibrated)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/photom_step.py", line 70, in process
result = phot.apply_photom(phot_filename, area_filename)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/photom.py", line 1261, in apply_photom
self.calc_miri(ftab)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/photom.py", line 519, in calc_miri
correction = miri_mrs.time_correction(self.input, self.detector,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/miri_mrs.py", line 160, in time_correction
ysize, xsize = input.data.shape
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/bin/strun", line 26, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/step.py", line 186, in from_cmdline
return cmdline.step_from_cmdline(args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/cmdline.py", line 386, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 140, in process
raise RuntimeError('\n'.join(failures))
RuntimeError: Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 122, in process
result = self.process_exposure_product(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 272, in process_exposure_product
calibrated = self._process_common(calibrated)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 526, in _process_common
calibrated = self.photom(calibrated)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/photom_step.py", line 70, in process
result = phot.apply_photom(phot_filename, area_filename)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/photom.py", line 1261, in apply_photom
self.calc_miri(ftab)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/photom.py", line 519, in calc_miri
correction = miri_mrs.time_correction(self.input, self.detector,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/photom/miri_mrs.py", line 160, in time_correction
ysize, xsize = input.data.shape
ValueError: too many values to unpack (expected 2)```
it occurred during Spec2Pipeline.photom step, while applying MRS IFU time dependent correction. previous repro runs of same program did not give the error, so perhaps likely introduced by JP-3224?

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659361#comment-659361):_

I saw the same problem in the reference files regression test we ran after the build but thought I had the wrong test file. There seems to be an issue with TSO observations.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659366#comment-659366):_

Looks fairly simple; the time-dependent code assumes that the input array has two dimensions.  If TSO has three dimensions that would cause the fault.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659367#comment-659367):_

A more nuanced question is whether TSO wants to make a time-dependent correction, and if so to what time?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659373#comment-659373):_

An even more fundamental question is whether MIRI MRS exposures taken in TSO mode should even be going through the Spec2 pipeline to begin with. When TSO was allowed for the MRS template, I'm sure we implemented ASN rules that excluded those observations from level-2b processing, or at best only allowed very limited level-2b processing, because the IFU data are already 3D and the steps can't handle adding yet another dimension (time) to the data. Will need to check on this. Perhaps something accidentally got changed in the ASN rules that is now allowing spec2 ASN's to be created for MRS TSO exposures, but they really shouldn't be?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659375#comment-659375):_

OK, maybe I'm misremembering how we decided to handle MIRI MRS TSO. There's a pars-spec2pipeline ref file in place that simply skips many of the spec2 steps for MRS TSO exposures, rather than having an ASN rule that excludes processing all together. The photom step is NOT skipped by this pars ref file.

<https://jwst-crds.stsci.edu/browse/jwst_miri_pars-spec2pipeline_0002.asdf>

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659409#comment-659409):_

Seems there are two possible solutions:

1) Have a catch in the time correction that looks for data that isn't the expected 2d shape and modifies processing accordingly.

2) Turn off the time dependent correction for TSO mode data using the param ref file.

Both should be pretty simple, but probably need the TSO folks to weigh in on which is preferable.  I'll ping them.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659422#comment-659422):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw)  What param reference file are you talking about? Looks like there is no param reference file for time_dependent code. Correct me if I am wrong [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse), but looks like the only way to turn this off would be to turn off all the Photom step.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659423#comment-659423):_

There's a photom step param called `--mrs_time_correction` that can be set to False to turn off the MRS time-dependent correction. That can be done via a pars ref file.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659442#comment-659442):_

So it looks like the only way to fix this now would be to deliver a new par_reference file for TSO spec2 that turns this off. [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) mentions that the code expects a 2D array, so I assume that this is not in the reference file and that the fix in the pipeline cannot be done but in a patch.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659447#comment-659447):_

We have a MIRI MRS TSO regression test in our suite, but unfortunately the DATE-OBS in the input data file is old enough that an older photom ref file gets selected, which doesn't have the time-dependent corrections in it, so the step skips trying to apply them:
```java
2023-08-29 14:19:12,457 - stpipe.Spec2Pipeline.photom - INFO - Skipping MRS MIRI time correction. Extensions not found in the reference file.
2023-08-29 14:19:12,457 - stpipe.Spec2Pipeline.photom - INFO - Not applying MRS IFU time dependent correction.
2023-08-29 14:19:12,472 - stpipe.Spec2Pipeline.photom - INFO - Step photom done ```
So that's how this snuck through our B9.3.1 testing. We'll be updating that regtest right away!

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659449#comment-659449):_

[Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) Right, fixing it NOW should be possible with a param ref file to turn off the correction.  Fixing the code itself would be a patch.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=659466#comment-659466):_

[Misty Cracraft](https://jira.stsci.edu/secure/ViewProfile.jspa?name=cracraft) and [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw), could you please work in delivering an updated par files for turn this off for TSO? We will document this in the Known Issues.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660470#comment-660470):_

Updated spec2 par file turning the relevant correction off for TSO will be delivered via <https://jira.stsci.edu/browse/JWSTMIRI-343>

I've also submitted a pull request to fix the root code problem at #7869

When the fix is live in ops the par file can be modified to turn the correction on again.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660474#comment-660474):_

Also meant to add that I discussed with [Nestor Espinoza](https://jira.stsci.edu/secure/ViewProfile.jspa?name=nespinoza) ; sounds like turning off the time correction for TSO data is fine in the short term.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660598#comment-660598):_

Looks like the relevant par file fix is now live in CRDS OPS, so that should fix the processing of this program.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rosa Diaz](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rdiaz) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660604#comment-660604):_

Yes,  our regression test ran clean; which means it was fixed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660629#comment-660629):_

So shall we mark this ticket as done and ready to be tested in Ops (by updating Ops to use the latest CRDS context), or do we want to leave it open until any actual code updates are complete (assuming there need to be any)?  Given that the workaround implemented via the ref file update at least fixes the current errors seen in Ops, I would be in favor of closing this ticket and then opening another for any potential code updates that [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) may want to make.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660664#comment-660664):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) I've opened <https://jira.stsci.edu/browse/JP-3362> accordingly

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660665#comment-660665):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) Can you confirm, when possible, that this is now fixed in operations?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660765#comment-660765):_

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) i rescued the failed jobs after context 1122 went into ops, and they all went through successfully

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3359?focusedCommentId=660772#comment-660772):_

Great! Closing the ticket.
