### ISSUE TITLE
NRC_WFSS background subtraction error - index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7964]
_Issue [JP-3425](https://jira.stsci.edu/browse/JP-3425) was created on JIRA by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott):_

Using build 9.3.1, we are seeing reprocessing level 2b failures for NRC_WFSS files

[jw01187-o013_20230917t104234_spec2_00013](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01187-o013_20230917t104234_spec2_00013_1694982520.247024&fileset_name=jw01187-o013_20230917t104234_spec2_00013&dag_name=REPRO_LEVEL_2B)

and 

[jw01187-o024_20230917t104234_spec2_00013](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01187-o024_20230917t104234_spec2_00013_1694971656.211453&fileset_name=jw01187-o024_20230917t104234_spec2_00013&dag_name=REPRO_LEVEL_2B)

with trackback errors like :
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 122, in process
result = self.process_exposure_product(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 257, in process_exposure_product
calibrated = self.bkg_subtract(calibrated, members_by_type['background'])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/background/background_step.py", line 63, in process
result = background_sub.subtract_wfss_bkg(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/background/background_sub.py", line 192, in subtract_wfss_bkg
sci_mean = robust_mean(input_model.data[bkg_mask],
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/background/background_sub.py", line 312, in robust_mean
limits = np.percentile(cleaned_x, (lowlim, highlim))
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4283, in percentile
return _quantile_unchecked(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
return _ureduce(a,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3823, in _ureduce
r = func(a, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4721, in _quantile_ureduce_func
result = _quantile(arr,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4830, in _quantile
slices_having_nans = np.isnan(arr[-1, ...])
IndexError: index -1 is out of bounds for axis 0 with size 0
 
Reprocessing has been successful in the past.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3425?focusedCommentId=663394#comment-663394):_

Duplicated by JP-3426.
