### ISSUE TITLE
CrdsLookupError on Basic Pipeline Run

### ISSUE THREAD

**Issue by maxecharles** [spacetelescope/jwst#7970]
Hi there, I've been unable to run any pipeline without it throwing a CRDS error.
I followed the [Quickstart Guide](https://jwst-pipeline.readthedocs.io/en/latest/getting_started/quickstart.html) installation instructions (fresh conda environment, `pip install jwst`) and then tried to run the pipeline as in the [docs example](https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/running_pipeline_python.html#importing-and-running-pipelines-and-steps-in-python):

```python
# setting path and server url
import os
os.environ['CRDS_PATH'] = '/Users/mcha5804/JWST/crds_cache/'
os.environ['CRDS_SERVER_URL'] = 'https://jwst-crds.stsci.edu'

# defining directory to data
data_dir = "/Users/mcha5804/JWST/data/jw01021005001_02101_00001_nis/"

# Example: Running a Pipeline with Default Parameters and Reference Files
from jwst.pipeline import Detector1Pipeline
result = Detector1Pipeline.call(data_dir + 'jw01021005001_gs-track_2022162151202_uncal.fits')
```

I've manually navigated to the `CRDS_PATH` I provided and it _has_ managed to successfully create and populate the `~/crds_cache/` directory. However it is still throwing this error:

```
2023-09-25 14:41:11,473 - CRDS - ERROR -  Error determining best reference for 'pars-undersamplingcorrectionstep'  =   Unknown reference type 'pars-undersamplingcorrectionstep'
2023-09-25 14:41:11,475 - stpipe - INFO - PARS-DETECTOR1PIPELINE parameters found: /Users/mcha5804/JWST/crds_cache/references/jwst/fgs/jwst_fgs_pars-detector1pipeline_0001.asdf
2023-09-25 14:41:11,486 - stpipe.Detector1Pipeline - INFO - Detector1Pipeline instance created.
2023-09-25 14:41:11,487 - stpipe.Detector1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2023-09-25 14:41:11,487 - stpipe.Detector1Pipeline.dq_init - INFO - DQInitStep instance created.
2023-09-25 14:41:11,487 - stpipe.Detector1Pipeline.saturation - INFO - SaturationStep instance created.
2023-09-25 14:41:11,487 - stpipe.Detector1Pipeline.ipc - INFO - IPCStep instance created.
2023-09-25 14:41:11,488 - stpipe.Detector1Pipeline.superbias - INFO - SuperBiasStep instance created.
2023-09-25 14:41:11,488 - stpipe.Detector1Pipeline.refpix - INFO - RefPixStep instance created.
2023-09-25 14:41:11,488 - stpipe.Detector1Pipeline.rscd - INFO - RscdStep instance created.
2023-09-25 14:41:11,489 - stpipe.Detector1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2023-09-25 14:41:11,489 - stpipe.Detector1Pipeline.lastframe - INFO - LastFrameStep instance created.
2023-09-25 14:41:11,489 - stpipe.Detector1Pipeline.linearity - INFO - LinearityStep instance created.
2023-09-25 14:41:11,490 - stpipe.Detector1Pipeline.dark_current - INFO - DarkCurrentStep instance created.
2023-09-25 14:41:11,490 - stpipe.Detector1Pipeline.reset - INFO - ResetStep instance created.
2023-09-25 14:41:11,490 - stpipe.Detector1Pipeline.persistence - INFO - PersistenceStep instance created.
2023-09-25 14:41:11,491 - stpipe.Detector1Pipeline.jump - INFO - JumpStep instance created.
2023-09-25 14:41:11,491 - stpipe.Detector1Pipeline.undersampling_correction - INFO - UndersamplingCorrectionStep instance created.
2023-09-25 14:41:11,492 - stpipe.Detector1Pipeline.ramp_fit - INFO - RampFitStep instance created.
2023-09-25 14:41:11,492 - stpipe.Detector1Pipeline.gain_scale - INFO - GainScaleStep instance created.
2023-09-25 14:41:11,533 - stpipe.Detector1Pipeline - INFO - Step Detector1Pipeline running with args ('/Users/mcha5804/JWST/data/jw01021005001_02101_00001_nis/jw01021005001_gs-track_2022162151202_uncal.fits',).
2023-09-25 14:41:11,538 - stpipe.Detector1Pipeline - INFO - Step Detector1Pipeline parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_calibrated_ramp': False, 'steps': {'group_scale': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'dq_init': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'saturation': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'n_pix_grow_sat': 1}, 'ipc': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'superbias': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'refpix': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'odd_even_columns': True, 'use_side_ref_pixels': True, 'side_smoothing_length': 11, 'side_gain': 1.0, 'odd_even_rows': True, 'ovr_corr_mitigation_ftr': 1.8}, 'rscd': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'type': 'baseline'}, 'firstframe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'lastframe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'linearity': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'dark_current': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'dark_output': None}, 'reset': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'persistence': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'input_trapsfilled': '', 'flag_pers_cutoff': 40.0, 'save_persistence': False, 'save_trapsfilled': True}, 'jump': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'rejection_threshold': 4.0, 'three_group_rejection_threshold': 6.0, 'four_group_rejection_threshold': 5.0, 'maximum_cores': 'none', 'flag_4_neighbors': True, 'max_jump_to_flag_neighbors': 1000.0, 'min_jump_to_flag_neighbors': 10.0, 'after_jump_flag_dn1': 0.0, 'after_jump_flag_time1': 0.0, 'after_jump_flag_dn2': 0.0, 'after_jump_flag_time2': 0.0, 'min_sat_area': 1.0, 'min_jump_area': 5.0, 'expand_factor': 2.0, 'use_ellipses': False, 'sat_required_snowball': True, 'min_sat_radius_extend': 2.5, 'sat_expand': 2, 'expand_large_events': False, 'find_showers': False, 'edge_size': 25, 'extend_snr_threshold': 1.2, 'extend_min_area': 90, 'extend_inner_radius': 1.0, 'extend_outer_radius': 2.6, 'extend_ellipse_expand_ratio': 1.1, 'time_masked_after_shower': 15.0, 'max_extended_radius': 200, 'minimum_groups': 3, 'minimum_sigclip_groups': 100, 'only_use_ints': True}, 'undersampling_correction': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'signal_threshold': 30000.0}, 'ramp_fit': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'int_name': '', 'save_opt': False, 'opt_name': '', 'suppress_one_group': True, 'maximum_cores': 'none'}, 'gain_scale': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}}}
2023-09-25 14:41:11,585 - stpipe.Detector1Pipeline - INFO - Prefetching reference files for dataset: 'jw01021005001_gs-track_2022162151202_uncal.fits' reftypes = ['dark', 'gain', 'linearity', 'mask', 'persat', 'readnoise', 'refpix', 'reset', 'rscd', 'saturation', 'superbias', 'trapdensity', 'trappars']
2023-09-25 14:41:11,594 - CRDS - ERROR -  Error determining best reference for 'dark'  =    parameter='META.EXPOSURE.READPATT [READPATT]' value='TRACK' is not in ['FGS', 'FGS60', 'FGS8370', 'FGS840', 'FGSRAPID']
2023-09-25 14:41:11,594 - CRDS - ERROR -  Error determining best reference for 'readnoise'  =    parameter='META.EXPOSURE.READPATT [READPATT]' value='TRACK' is not in ['FGS', 'FGS60', 'FGS8370', 'FGS840', 'FGSRAPID']
Traceback (most recent call last):
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-31df4e3463e9>", line 1, in <module>
    runfile('/Users/mcha5804/Library/CloudStorage/OneDrive-TheUniversityofSydney(Students)/PyCharm/jwst/main.py', wdir='/Users/mcha5804/Library/CloudStorage/OneDrive-TheUniversityofSydney(Students)/PyCharm/jwst')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mcha5804/Library/CloudStorage/OneDrive-TheUniversityofSydney(Students)/PyCharm/jwst/main.py", line 12, in <module>
    result = Detector1Pipeline.call(data_dir + 'jw01021005001_gs-track_2022162151202_uncal.fits')
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/step.py", line 652, in call
    return instance.run(*args)
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/step.py", line 476, in run
    self.prefetch(*args)
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/step.py", line 589, in prefetch
    self._precache_references(args[0])
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/pipeline.py", line 266, in _precache_references
    self._precache_references_opened(model)
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/pipeline.py", line 287, in _precache_references_opened
    self._precache_references_impl(model_or_container)
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/pipeline.py", line 315, in _precache_references_impl
    crds_refs = crds_client.get_multiple_reference_paths(
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/crds_client.py", line 52, in get_multiple_reference_paths
    refpaths = _get_refpaths(parameters, tuple(reference_file_types), observatory)
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/stpipe/crds_client.py", line 65, in _get_refpaths
    bestrefs = crds.getreferences(
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/crds/core/heavy_client.py", line 127, in getreferences
    best_refs_paths = api.cache_references(
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/crds/client/api.py", line 848, in cache_references
    wanted = _get_cache_filelist_and_report_errors(bestrefs)
  File "/Users/mcha5804/miniconda3/envs/dLux/lib/python3.10/site-packages/crds/client/api.py", line 891, in _get_cache_filelist_and_report_errors
    raise last_error
crds.core.exceptions.CrdsLookupError: Error determining best reference for 'readnoise'  =    parameter='META.EXPOSURE.READPATT' value='TRACK' is not in ['FGS', 'FGS60', 'FGS8370', 'FGS840', 'FGSRAPID']
```

I also tried adding to my `bash_profile`:

```
export CRDS_PATH=/Users/mcha5804/JWST/crds_cache/
export CRDS_SERVER_URL=https://jwst-crds.stsci.edu
```
to no avail.

**Comment by hbushouse** [comment]
The errors:
```
Error determining best reference for 'dark'  =    parameter='META.EXPOSURE.READPATT [READPATT]' value='TRACK' is not in ['FGS', 'FGS60', 'FGS8370', 'FGS840', 'FGSRAPID']
Error determining best reference for 'readnoise'  =    parameter='META.EXPOSURE.READPATT [READPATT]' value='TRACK' is not in ['FGS', 'FGS60', 'FGS8370', 'FGS840', 'FGSRAPID']
```
are indicating that the READPATT (readout pattern name) keyword in the datasets you're trying to process are set to "TRACK", which is not a recognized readout pattern name. The valid readout pattern names are the ones listed at the end each message (FGS, FGS60, ...). What kind of observations are these and where did the files come from (e.g. directly downloaded from MAST?).

**Comment by hbushouse** [comment]
Whoops, should've looked more closely at the processing log messages. It looks like you're trying to process the dataset "jw01021005001_gs-track_2022162151202_uncal.fits". This is not a science exposure. As the "gs-track" field in the file name indicates, this is guider data from the FGS. As such, it cannot be processed using the regular science pipeline. If you really want to process guider data, you need to use the "calwebb_guider" pipeline module.

**Comment by maxecharles** [comment]
Ah! Thank you so much for your help @hbushouse.
