### ISSUE TITLE
NRC_WFSS background subtraction error: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8061]
_Issue [JP-3426](https://jira.stsci.edu/browse/JP-3426) was created on JIRA by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott):_

Using build 9.3.1, we saw some reprocessing level 2b errors for NRC_WFSS processing in the background subtraction step for 

[jw01187-o013_20230917t104234_spec2_00013](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01187-o013_20230917t104234_spec2_00013_1694982520.247024&fileset_name=jw01187-o013_20230917t104234_spec2_00013&dag_name=REPRO_LEVEL_2B)

 

and

 

[jw01187-o024_20230917t104234_spec2_00013](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01187-o024_20230917t104234_spec2_00013_1694971656.211453&fileset_name=jw01187-o024_20230917t104234_spec2_00013&dag_name=REPRO_LEVEL_2B)

 

 
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 122, in process
result = self.process_exposure_product(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 257, in process_exposure_product
calibrated = self.bkg_subtract(calibrated, members_by_type['background'])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/background/background_step.py", line 63, in process
result = background_sub.subtract_wfss_bkg(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/background/background_sub.py", line 192, in subtract_wfss_bkg
sci_mean = robust_mean(input_model.data[bkg_mask],
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/jwst/background/background_sub.py", line 312, in robust_mean
limits = np.percentile(cleaned_x, (lowlim, highlim))
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4283, in percentile
return _quantile_unchecked(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4555, in _quantile_unchecked
return _ureduce(a,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3823, in _ureduce
r = func(a, **kwargs)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4721, in _quantile_ureduce_func
result = _quantile(arr,
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.11.4.20230814-py3.9/lib/python3.9/site-packages/numpy/lib/function_base.py", line 4830, in _quantile
slices_having_nans = np.isnan(arr[-1, ...])
IndexError: index -1 is out of bounds for axis 0 with size 0
reprocessing in the past has been successful.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=670790#comment-670790):_

[Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) Do we know if this might've been fixed by any WFSS updates that were included in B10.0.x?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=671058#comment-671058):_

It looks related to JP-3234 but that should be present for this run. I can take a look.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=671141#comment-671141):_

The owlgui links above appear to be dead, but I was able to run all jw01187-o013 spec2 associations successfully. They were built from a pool generated in May 2023 - perhaps the newer pools generate different associations?

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=671197#comment-671197):_

Issue caused by complete coverage of frame with source bounding boxes, leaving no pixels from which to define a background region. This should be skipped, but the background subtraction code sees the reference pixel border as valid pixels, only causing an error once the mask is applied to the data array, where the reference pixels have NaN values. Will have a PR in with a fix shortly.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=671849#comment-671849):_

Fixed by #8070

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=742586#comment-742586):_

all l2b asns for 1187 have been dropped per DMSOPS-1045, so we can't test the fix for the datasets in this ticket, but repro of program 1076 with  b11.0.2 showed this same error in ops, so it appears this may still be an issue? see [jw01076-o124_20241013t063610_spec2_00001;](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01076-o124_20241013t063610_spec2_00001_1728831053.822951&fileset_name=jw01076-o124_20241013t063610_spec2_00001&dag_name=REPRO_LEVEL_2B) Directory Path: /ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01076-o124_20241013t063610_spec2_00001_1728831053.822951.

the alog.out is attached.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=744093#comment-744093):_

Prior fix needs an edit - oops!

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=745861#comment-745861):_

Second fix implemented in #8916

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=946710#comment-946710):_

also affected [jw05398-c1048_20241211t150815_spec2_00008](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw05398-c1048_20241211t150815_spec2_00008_1740237172.032553&fileset_name=jw05398-c1048_20241211t150815_spec2_00008&dag_name=LEVEL_2B)

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3426?focusedCommentId=949600#comment-949600):_

this issue is no longer seen with repro of 1076, 1571, and 5398 with b11.2.1. closing
