### ISSUE TITLE
error: pip install jwst

### ISSUE THREAD

**Issue by 3-kaku** [spacetelescope/jwst#8135]
I'm trying to install pip install jwst, but something wrong with to build a wheel.

Collecting jwst
  Using cached jwst-1.12.5.tar.gz (18.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting asdf<3,>=2.15.1 (from jwst)
  Using cached asdf-2.15.2-py3-none-any.whl.metadata (14 kB)
Collecting asdf-transform-schemas>=0.3.0 (from jwst)
  Using cached asdf_transform_schemas-0.4.0-py3-none-any.whl.metadata (4.1 kB)
Collecting astropy>=5.3 (from jwst)
  Using cached astropy-6.0.0-cp310-cp310-win_amd64.whl.metadata (10.0 kB)
Collecting BayesicFitting>=3.0.1 (from jwst)
  Using cached BayesicFitting-3.2.0-py3-none-any.whl.metadata (16 kB)
Collecting crds>=11.16.19 (from jwst)
  Downloading crds-11.17.14-py3-none-any.whl.metadata (9.6 kB)
Collecting drizzle<1.15.0,>=1.14.3 (from jwst)
  Using cached drizzle-1.14.3.tar.gz (103 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [49 lines of output]
      C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\config\expand.py:133: SetuptoolsWarning: File 'C:\\Users\\toshi\\AppData\\Local\\Temp\\pip-install-yj53ikl6\\drizzle_8c27ebf8b85347cda54088ac4756e281\\licenses' cannot be found
        return '\n'.join(
      running egg_info
      writing drizzle.egg-info\PKG-INFO
      writing dependency_links to drizzle.egg-info\dependency_links.txt
      writing requirements to drizzle.egg-info\requires.txt
      writing top-level names to drizzle.egg-info\top_level.txt
      reading manifest file 'drizzle.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\toshi\miniconda3\envs\jwst1\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\toshi\miniconda3\envs\jwst1\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\toshi\miniconda3\envs\jwst1\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 38, in <module>
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 596, in add_defaults
          self.read_manifest()
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\command\sdist.py", line 213, in read_manifest
          self.filelist.append(line)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 488, in append
          path = convert_path(item)
        File "C:\Users\toshi\AppData\Local\Temp\pip-build-env-20ctb3qx\overlay\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/home/runner/work/drizzle/drizzle/src/cdrizzleapi.c' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by braingram** [comment]
Thanks for sharing the build log failure.

What version of python are you using?

Looking at the log it appears to be failing due to attempting to (and failing) to build drizzle 1.14.3 from source.

It appears that drizzle 1.14.3 only has wheels for python 3.8 3.9 and 3.10 so if you are not on one of those versions would you try installing with python 3.10?

There is a drizzle [1.14.4](https://pypi.org/project/drizzle/1.14.4/) on pypi that has wheels for more versions (including 3.11 and 3.12 although 3.12 is not yet suppported by jwst). I'm not quite sure why that newer version was not selected so you might also try installing drizzle 1.14.4 first and then jwst.

**Comment by 3-kaku** [comment]
Thanks for getting back to me.

I tried to install drizzle1.14.4 as you suggested but it gave me an error saying it couldn't find the version.

BTW, my Python environment is 3.10.13.

**Comment by 3-kaku** [comment]
error log:
ERROR: Could not find a version that satisfies the requirement drizzle==1.14.4 (from versions: 1.11, 1.12, 1.13, 1.13.1, 1.13.3, 1.13.4, 1.13.5, 1.13.6, 1.13.7, 1.14.0, 1.14.1, 1.14.2, 1.14.3)
ERROR: No matching distribution found for drizzle==1.14.4

**Comment by braingram** [comment]
Thanks for the extra information. I failed to notice earlier the paths appear to be for a windows system.

jwst does not currently support windows (see [the mention of this in the readme](https://github.com/spacetelescope/jwst#jwst-calibration-pipeline)) which would explain the failure to install.

It also appears that drizzle (at the moment) does not support windows.

Would you take a look at the instructions for setting up an environment using windows subsystem for linux? https://stenv.readthedocs.io/en/latest/windows.html

**Comment by 3-kaku** [comment]
Thanks for the advice.

I'll give it a try.

**Comment by braingram** [comment]
Good luck. If you run into more issues please feel free to open an issue here or on the stenv repository (whichever seems more relevant).
