### ISSUE TITLE
level3 nis_image of jw01230-o009_20240210t011656_image3_00001 crashed with KeyError: 'ra'

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8286]
_Issue [JP-3541](https://jira.stsci.edu/browse/JP-3541) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

ops saw a new error during reprocessing of nis_image dataset [jw01230-o009_20240210t011656_image3_00001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01230-o009_20240210t011656_image3_00001_1707534171.411246&fileset_name=jw01230-o009_20240210t011656_image3_00001&dag_name=REPRO_LEVEL_3) (for l3 product jw01230-o009_t002_niriss_clearp-f480m-sub80) with b10.0, in the tweakreg step
```java
2024-02-17 00:34:17,588 - CRDS - DEBUG - Final effective context is 'jwst_1197.pmap'
2024-02-17 00:34:17,588 - CRDS - DEBUG - Computing best references locally.
2024-02-17 00:34:17,589 - CRDS - DEBUG - Bestrefs header:
{'META.EXPOSURE.READPATT [READPATT]': 'NISRAPID',
'META.EXPOSURE.TYPE [EXP_TYPE]': 'NIS_IMAGE',
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NIS',
'META.INSTRUMENT.FILTER [FILTER]': 'F480M',
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE',
'META.INSTRUMENT.NAME [INSTRUME]': 'NIRISS',
'META.INSTRUMENT.PUPIL [PUPIL]': 'CLEARP',
'META.OBSERVATION.DATE [DATE-OBS]': '2023-04-17',
'META.OBSERVATION.TIME [TIME-OBS]': '22:24:14.405',
'META.SUBARRAY.NAME [SUBARRAY]': 'SUB80',
'META.VISIT.CROWDED_FIELD [CROWDFLD]': 'F',
'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED',
'REFTYPE': 'UNDEFINED'}
2024-02-17 00:34:17,589 - CRDS - DEBUG - Reference type 'abvegaoffset' defined as 'jwst_niriss_abvegaoffset_0003.asdf'
2024-02-17 00:34:17,589 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_niriss_apcorr_0008.fits'
2024-02-17 00:34:17,589 - CRDS - DEBUG - Reference type 'drizpars' defined as 'jwst_niriss_drizpars_0002.fits'
2024-02-17 00:34:17,658 - stpipe.Image3Pipeline - INFO - Prefetch for ABVEGAOFFSET reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_abvegaoffset_0003.asdf'.
2024-02-17 00:34:17,659 - stpipe.Image3Pipeline - INFO - Prefetch for APCORR reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_apcorr_0008.fits'.
2024-02-17 00:34:17,660 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_drizpars_0002.fits'.
2024-02-17 00:34:17,661 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2024-02-17 00:34:17,870 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg running with args (<ModelContainer>,).
2024-02-17 00:34:17,872 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3', 'save_catalogs': False, 'use_custom_catalogs': False, 'catalog_format': 'ecsv', 'catfile': '', 'kernel_fwhm': 2.5, 'snr_threshold': 10, 'sharplo': 0.2, 'sharphi': 1.0, 'roundlo': -1.0, 'roundhi': 1.0, 'brightest': 100, 'peakmax': None, 'bkg_boxsize': 400, 'enforce_user_order': False, 'expand_refcat': False, 'minobj': 15, 'searchrad': 1.0, 'use2dhist': True, 'separation': 1.0, 'tolerance': 1.0, 'xoffset': 0.0, 'yoffset': 0.0, 'fitgeometry': 'shift', 'nclip': 3, 'sigma': 3.0, 'abs_refcat': 'GAIADR3', 'save_abs_catalog': False, 'abs_minobj': 15, 'abs_searchrad': 6.0, 'abs_use2dhist': True, 'abs_separation': 0.1, 'abs_tolerance': 0.7, 'abs_fitgeometry': 'rshift', 'abs_nclip': 3, 'abs_sigma': 3.0}
2024-02-17 00:34:17,878 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/photutils/background/background_2d.py:274: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically masked.
2024-02-17 00:34:17,879 - stpipe.Image3Pipeline.tweakreg - WARNING - warnings.warn('Input data contains invalid values (NaNs or '
2024-02-17 00:34:17,879 - stpipe.Image3Pipeline.tweakreg - WARNING -
2024-02-17 00:34:17,879 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/photutils/background/background_2d.py:274: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically masked.
2024-02-17 00:34:17,879 - stpipe.Image3Pipeline.tweakreg - WARNING - warnings.warn('Input data contains invalid values (NaNs or '
2024-02-17 00:34:17,879 - stpipe.Image3Pipeline.tweakreg - WARNING -
2024-02-17 00:34:17,880 - stpipe.Image3Pipeline.tweakreg - INFO - Background could not be estimated in meshes. Using the entire unmasked array for background estimation: bkg_boxsize=(80, 80).
2024-02-17 00:34:17,886 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 10 sources in jw01230009001_03103_00001_nis_cal.fits.
2024-02-17 00:34:17,894 - stpipe.Image3Pipeline.tweakreg - INFO -
2024-02-17 00:34:17,894 - stpipe.Image3Pipeline.tweakreg - INFO - Number of image groups to be aligned: 1.
2024-02-17 00:34:17,894 - stpipe.Image3Pipeline.tweakreg - INFO - Image groups:
2024-02-17 00:34:17,913 - stpipe.Image3Pipeline.tweakreg - INFO - * Images in GROUP 'jw01230009001_03103_00001_nis_cal':
2024-02-17 00:34:17,914 - stpipe.Image3Pipeline.tweakreg - INFO - jw01230009001_03103_00001_nis_cal
2024-02-17 00:34:17,914 - stpipe.Image3Pipeline.tweakreg - INFO -
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/bin/strun", line 26, in <module>
step = Step.from_cmdline(sys.argv[1:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 186, in from_cmdline
return cmdline.step_from_cmdline(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/stpipe/cmdline.py", line 386, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/jwst/pipeline/calwebb_image3.py", line 89, in process
input_models = self.tweakreg(input_models)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 478, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/jwst/tweakreg/tweakreg_step.py", line 392, in process
ref_cat = amutils.create_astrometric_catalog(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/jwst/tweakreg/astrometric_utils.py", line 98, in create_astrometric_catalog
ref_table = ref_dict[colnames]
~~~~~~~~^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/astropy/table/table.py", line 2064, in __getitem__
[self[x] for x in item], copy_indices=self._copy_indices
^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/astropy/table/table.py", line 2064, in <listcomp>
[self[x] for x in item], copy_indices=self._copy_indices
~~~~^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/astropy/table/table.py", line 2055, in __getitem__
return self.columns[item]
~~~~~~~~~~~~^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/astropy/table/table.py", line 264, in __getitem__
return OrderedDict.__getitem__(self, item)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ra'
2024048003418 INFO src=ssb_calibration_wrapper._strun_analyze_and_log_failure fsn=jw01230-o009_20240210t011656_image3_00001_asn msg="strun /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.12.5.20231019-py3.11/lib/python3.11/site-packages/jwst/pipeline/calwebb_image3.cfg FAILED (exit=1) on jw01230-o009_20240210t011656_image3_00001_asn.json."
2024048003418 ERROR src=ssb_calibration_wrapper.calibrate._strun._strun_analyze_and_log_failure fsn=jw01230-o009_20240210t011656_image3_00001_asn msg="strun exit status=1" ```
we successfully generate l3 products for this same dataset before and did not see such error in previous builds.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3541?focusedCommentId=688403#comment-688403):_

Fixed by #8334

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3541?focusedCommentId=688404#comment-688404):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) This will be included in our B10.2 delivery and can then be tested once 10.2 is installed in Ops.

**Comment by stscijgbot-jp** [comment]
_Comment by [Rachel Plesha](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rplesha) on [JIRA](https://jira.stsci.edu/browse/JP-3541?focusedCommentId=715660#comment-715660):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) I was wondering if this was tested/things looked ok now?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3541?focusedCommentId=715680#comment-715680):_

ah yes, thanks for the reminder. this program was reprocessed 2024-06-14 with b10.2.1 and the failed dataset went through just fine. i think this ticket can be closed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3541?focusedCommentId=715684#comment-715684):_

Fix confirmed working in B10.2 repro.
