### ISSUE TITLE
single-member niriss image3 crashed with "Number of output coordinates exceeded allocation (100)"

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8436]
_Issue [JP-3605](https://jira.stsci.edu/browse/JP-3605) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

ops saw reprocessing of the nis_image level3 dataset with b10.1.2 [jw01086-o002_20240409t155805_image3_00012](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01086-o002_20240409t155805_image3_00012_1712681483.313619&fileset_name=jw01086-o002_20240409t155805_image3_00012&dag_name=REPRO_LEVEL_3) (for products named `{}jw01086-o002_t001_niriss_clear-f200w{`}) crash during the tweakreg step
```java
2024-04-09 16:51:53,244 - CRDS - DEBUG - Final effective context is 'jwst_1225.pmap'
2024-04-09 16:51:53,244 - CRDS - DEBUG - Computing best references locally.
2024-04-09 16:51:53,246 - CRDS - DEBUG - Bestrefs header:
{'META.EXPOSURE.READPATT [READPATT]': 'NISRAPID',
'META.EXPOSURE.TYPE [EXP_TYPE]': 'NIS_IMAGE',
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NIS',
'META.INSTRUMENT.FILTER [FILTER]': 'CLEAR',
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE',
'META.INSTRUMENT.NAME [INSTRUME]': 'NIRISS',
'META.INSTRUMENT.PUPIL [PUPIL]': 'F200W',
'META.OBSERVATION.DATE [DATE-OBS]': '2022-05-01',
'META.OBSERVATION.TIME [TIME-OBS]': '10:08:47.008',
'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
'META.VISIT.CROWDED_FIELD [CROWDFLD]': 'T',
'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED',
'REFTYPE': 'UNDEFINED'}
2024-04-09 16:51:53,246 - CRDS - DEBUG - Reference type 'abvegaoffset' defined as 'jwst_niriss_abvegaoffset_0003.asdf'
2024-04-09 16:51:53,246 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_niriss_apcorr_0008.fits'
2024-04-09 16:51:53,247 - CRDS - DEBUG - Reference type 'drizpars' defined as 'jwst_niriss_drizpars_0002.fits'
2024-04-09 16:51:53,256 - stpipe.Image3Pipeline - INFO - Prefetch for ABVEGAOFFSET reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_abvegaoffset_0003.asdf'.
2024-04-09 16:51:53,258 - stpipe.Image3Pipeline - INFO - Prefetch for APCORR reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_apcorr_0008.fits'.
2024-04-09 16:51:53,260 - stpipe.Image3Pipeline - INFO - Prefetch for DRIZPARS reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_drizpars_0002.fits'.
2024-04-09 16:51:53,266 - stpipe.Image3Pipeline - INFO - Starting calwebb_image3 ...
2024-04-09 16:51:53,683 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg running with args (<ModelContainer>,).
2024-04-09 16:51:53,684 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/ifs/archive/ops/jwst/info/owlmgr/paths/sdp/asn_creation/cal/level3', 'save_catalogs': False, 'use_custom_catalogs': False, 'catalog_format': 'ecsv', 'catfile': '', 'kernel_fwhm': 2.0, 'snr_threshold': 10, 'sharplo': 0.2, 'sharphi': 1.0, 'roundlo': -1.0, 'roundhi': 1.0, 'brightest': 100, 'peakmax': None, 'bkg_boxsize': 400, 'enforce_user_order': False, 'expand_refcat': False, 'minobj': 15, 'searchrad': 1.0, 'use2dhist': True, 'separation': 1.0, 'tolerance': 1.0, 'xoffset': 0.0, 'yoffset': 0.0, 'fitgeometry': 'shift', 'nclip': 3, 'sigma': 3.0, 'abs_refcat': 'GAIADR3', 'save_abs_catalog': False, 'abs_minobj': 15, 'abs_searchrad': 6.0, 'abs_use2dhist': True, 'abs_separation': 0.1, 'abs_tolerance': 0.7, 'abs_fitgeometry': 'rshift', 'abs_nclip': 3, 'abs_sigma': 3.0}
2024-04-09 16:51:53,736 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/photutils/background/background_2d.py:273: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically masked.
2024-04-09 16:51:53,737 - stpipe.Image3Pipeline.tweakreg - WARNING - warnings.warn('Input data contains invalid values (NaNs or '
2024-04-09 16:51:53,737 - stpipe.Image3Pipeline.tweakreg - WARNING -
2024-04-09 16:51:54,097 - stpipe.Image3Pipeline.tweakreg - WARNING - /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/photutils/background/background_2d.py:273: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically masked.
2024-04-09 16:51:54,097 - stpipe.Image3Pipeline.tweakreg - WARNING - warnings.warn('Input data contains invalid values (NaNs or '
2024-04-09 16:51:54,097 - stpipe.Image3Pipeline.tweakreg - WARNING -
2024-04-09 16:51:54,466 - stpipe.Image3Pipeline.tweakreg - INFO - Background could not be estimated in meshes. Using the entire unmasked array for background estimation: bkg_boxsize=(2048, 2048).
2024-04-09 16:51:56,120 - stpipe.Image3Pipeline.tweakreg - INFO - Detected 100 sources in jw01086002001_04101_00001_nis_cal.fits.
2024-04-09 16:51:56,130 - stpipe.Image3Pipeline.tweakreg - INFO -
2024-04-09 16:51:56,131 - stpipe.Image3Pipeline.tweakreg - INFO - Number of image groups to be aligned: 1.
2024-04-09 16:51:56,131 - stpipe.Image3Pipeline.tweakreg - INFO - Image groups:
2024-04-09 16:51:56,153 - stpipe.Image3Pipeline.tweakreg - INFO - * Images in GROUP 'jw01086002001_04101_00001_nis_cal':
2024-04-09 16:51:56,153 - stpipe.Image3Pipeline.tweakreg - INFO - jw01086002001_04101_00001_nis_cal
2024-04-09 16:51:56,153 - stpipe.Image3Pipeline.tweakreg - INFO -
2024-04-09 16:52:03,034 - stpipe.Image3Pipeline.tweakreg - INFO -
2024-04-09 16:52:03,034 - stpipe.Image3Pipeline.tweakreg - INFO - ***** tweakwcs.imalign.align_wcs() started on 2024-04-09 16:52:03.034419
2024-04-09 16:52:03,034 - stpipe.Image3Pipeline.tweakreg - INFO - Version 0.8.5
2024-04-09 16:52:03,034 - stpipe.Image3Pipeline.tweakreg - INFO -
2024-04-09 16:52:03,119 - stpipe.Image3Pipeline.tweakreg - INFO - Aligning image catalog 'GROUP ID: 987654' to the reference catalog.
2024-04-09 16:52:03,298 - stpipe.Image3Pipeline.tweakreg - INFO - Matching sources from 'jw01086002001_04101_00001_nis_cal' catalog with sources from the reference 'Unnamed' catalog.
2024-04-09 16:52:03,298 - stpipe.Image3Pipeline.tweakreg - INFO - Computing initial guess for X and Y shifts...
2024-04-09 16:52:03,303 - stpipe.Image3Pipeline.tweakreg - INFO - Found initial X and Y shifts of -0.2281, 0.02888 (arcsec) with significance of 90.04 and 99 matches.
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/stpipe/cli/strun.py", line 24, in main
Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 187, in from_cmdline
return cmdline.step_from_cmdline(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/stpipe/cmdline.py", line 392, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/jwst/pipeline/calwebb_image3.py", line 89, in process
input_models = self.tweakreg(input_models)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/jwst/tweakreg/tweakreg_step.py", line 442, in process
align_wcs(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/tweakwcs/imalign.py", line 683, in align_wcs
current_wcat.align_to_ref(
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/tweakwcs/wcsimage.py", line 1348, in align_to_ref
nmatches, mref_idx, minput_idx = self.match2ref(
^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/tweakwcs/wcsimage.py", line 965, in match2ref
mref_idx, minput_idx = match(
^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/tweakwcs/matchutils.py", line 268, in __call__
matches = xyxymatch(
^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/stsci/stimage/__init__.py", line 236, in xyxymatch
return _stimage.xyxymatch(
^^^^^^^^^^^^^^^^^^^
RuntimeError: Number of output coordinates exceeded allocation (100)
2024100165204 INFO src=ssb_calibration_wrapper._strun_analyze_and_log_failure fsn=jw01086-o002_20240409t155805_image3_00012_asn msg="strun /dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.13.3.20240108-py3.11/lib/python3.11/site-packages/jwst/pipeline/calwebb_image3.cfg FAILED (exit=1) on jw01086-o002_20240409t155805_image3_00012_asn.json."
2024100165204 ERROR src=ssb_calibration_wrapper.calibrate._strun._strun_analyze_and_log_failure fsn=jw01086-o002_20240409t155805_image3_00012_asn msg="strun exit status=1" ```
there are other datasets with the same failure in DMSOPS-1089. they all appear to fail because these image3 associations consist of only a single input member each, and the tweakreg step crashed trying to do alignment with only one exposure. the problem seems to have been introduced in b10.0, since in reprocessing prior to b10.0, tweakreg was correctly skipped. for example, reprocessing of same dataset on 2023-10-24 with b9.3.1 showed
```
2023-10-24 03:01:49,089 - stpipe.Image3Pipeline.tweakreg - WARNING - At least two exposures are required for image alignment.
2023-10-24 03:01:49,089 - stpipe.Image3Pipeline.tweakreg - WARNING - Nothing to do. Skipping 'TweakRegStep'...
2023-10-24 03:01:49,092 - stpipe.Image3Pipeline.tweakreg - INFO - Step tweakreg done ```
and the pipeline exited "successfully" without throwing an error.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=696284#comment-696284):_

This issue basically is a duplicate of <https://jira.stsci.edu/browse/JP-2569> at least in the reasons for the failure. I don't know how to share a particular answer on a JIRA issue, so I "pinned" my answer there. For convenience, I will cite some passages from the linked JIRA issue:

[Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) wrote:

??... these errors occur due to a single source from the reference catalog being matched to multiple sources in the input image. This is not a bug. The xyxymatch algorithm has a parameter 'tolerance' which allows it to match sources when they are a little bit off from their expected positions, i.e., due to distortions or incorrect pointing recorded in the WCS. Without any tolerance most likely no sources would be matched in practical situations. Increasing this tolerance allows one to account for possible registration errors.??

??One obvious solution is to decrease 'tolerance' value. Based on my previous paragraph one could set tolerance=1 pixel. However, in practice there will be rotational errors and differential effects due to distortions. So tolerance must be set higher. Current default is 1 arcsecond. That would be equivalent to 10 pixels for MIRI and up to 30 for NIRCAM. This seem to be quite high. The tolerance should be set as low as possible while allowing for expected (differential effects of the) distortion and (uncorrected by 2dhist algorithm) pointing errors.??

??I updated default parameters in #6809 but this will likely not have any effect unless the step's parameters are changed in the reference files.??

[Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) wrote:

??Mihai Cara you're correct about the (f)utility of changing the param defaults in the step itself, when some instruments have pars-tweakregstep parameter reference files in place in CRDS. Any changes in the step defaults will be overridden by values in the reference files. For this particular example, the new defaults are: searchrad=2.0 arcsec, separation=1.0 arcsec, and tolerance=0.7 arcsec, while the values coming from the pars ref file are still 1.0, 0.5, and 1.0, respectively.??
??So to implement any real change would require updating and redelivering the pars-tweakregstep ref files (which for most instruments is a lot of ref files, because there's one per filter). The work of implementing better default values in the pars ref files can be done as part of JP-2562. Team members making those updates can perhaps use the changes in #6809 as a guide for their ref file updates.??

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=696346#comment-696346):_

After further analysis with the help of [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) , the reference parameter file for this instrument turned absolute alignment ON but it does not specify abs_tolerance and abs_separation for this alignment leaving it to default values in the step. Unfortunately these defaults are left over from the hardcoded values as written by Warren. I do not know the reason why abs_separation  was set to 1/10 to 'separation' (used for relative alignment) but this set of parameter defaults is not good and should be modified.

I can either increase abs_separation to 1 or decrease abs_tolerance to 0.07. Please advise on what is a preferred value.

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=696433#comment-696433):_

A fix was proposed in #8445

**Comment by stscijgbot-jp** [comment]
_Comment by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=696496#comment-696496):_

Where can I find the data to test my solution?

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=697122#comment-697122):_

data, which is public, can be found in ████████████████████████████

**Comment by stscijgbot-jp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=697390#comment-697390):_

Fixed by #8445

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=697400#comment-697400):_

[Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) The fix for this will be included in B11.0 and hence can be tested in Ops once that build has been installed there (sometime in Aug 2024?).

**Comment by stscijgbot-jp** [comment]
_Comment by [Richard Spencer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rspencer) on [JIRA](https://jira.stsci.edu/browse/JP-3605?focusedCommentId=709662#comment-709662):_

Successfully processed **jw01086002001_04101_00001_nis** under B11.0 on D-2 using cal 

1.15.1 and jwst_1255.pmap:

/ifs/archive/test/jwst/store/rspencer/tests/NIRISS001/dtest2/JWSTDP-2024.2.0-52~dbc52a8d/2024-07-20-185635/sdp/asn_creation/cal/level3/{*}jw01086002001_04101_00001_nis_cal.fits{*}

/ifs/archive/test/jwst/store/rspencer/tests/NIRISS001/dtest2/JWSTDP-2024.2.0-52~dbc52a8d/2024-07-20-185635/sdp/asn_creation/cal/level2/{*}jw01086002001_04101_00001_nis_cal.fits{*}

/ifs/archive/test/jwst/store/rspencer/tests/NIRISS001/dtest2/JWSTDP-2024.2.0-52~dbc52a8d/2024-07-20-185635/sdp/archive/level2b/{*}jw01086002001_04101_00001_nis_cal.fits{*}
