### ISSUE TITLE
Spec3 step mrs_imatch crashing 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8538]
_Issue [JP-3649](https://jira.stsci.edu/browse/JP-3649) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

The mrs_imatch step is skipped by default for data with USEAFTER 2022-05-01. I used the test set that is currently in artifactory for regression tests for MIRI MRS. When it runs it crashes with the following traceback:

Traceback (most recent call last):
  File "/Users/pena/Documents/SCSB/analysis_tools/analysis_tools/src/run_st_pipes.py", line 713, in run_st_pipes
    run_spec3(asn_json, outdir, save_stps_lst=save_stps_lst,
  File "/Users/pena/Documents/SCSB/analysis_tools/analysis_tools/src/run_st_pipes.py", line 418, in run_spec3
    spec3.call(asn_json, output_dir=output_dir, steps=parameter_dict, save_results=True)
  File "/Users/pena/Documents/SCSB/stpipe/stpipe/src/stpipe/step.py", line 686, in call
    return instance.run(*args)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/pena/Documents/SCSB/stpipe/stpipe/src/stpipe/step.py", line 509, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/pena/Documents/SCSB/jwst/jwst/jwst/pipeline/calwebb_spec3.py", line 221, in process
    result = self.mrs_imatch(result)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pena/Documents/SCSB/stpipe/stpipe/src/stpipe/step.py", line 509, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/pena/Documents/SCSB/jwst/jwst/jwst/mrs_imatch/mrs_imatch_step.py", line 85, in process
    _match_models(single_ch[c], channel=str(c), degree=degree)
  File "/Users/pena/Documents/SCSB/jwst/jwst/jwst/mrs_imatch/mrs_imatch_step.py", line 266, in _match_models
    cube_models = cbs.process(models)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/pena/Documents/SCSB/jwst/jwst/jwst/cube_build/cube_build_step.py", line 369, in process
    cube_container = thiscube.build_ifucube_single()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pena/Documents/SCSB/jwst/jwst/jwst/cube_build/ifu_cube.py", line 827, in build_ifucube_single
    coord1, coord2, corner_coord, wave, dwave, flux, err, slice_no, \
ValueError: too many values to unpack (expected 13)
None

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=703221#comment-703221):_

I think it's useful to know that this step is now crashing, but fixing that isn't a priority at the moment as the step is now quite outdated and not recommended for any users.  Setting to 'On Hold'.

**Comment by stscijgbot-jp** [comment]
_Comment by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=708015#comment-708015):_

Just for reference, here is a Help Desk ticket that reports this bug as well: <https://stsci.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Df3c557dd831642545d629da6feaad3e6%26sysparm_domain%3Dnull%26sysparm_domain_scope%3Dnull%26sysparm_view%3DJWST%26sysparm_view_forced%3Dtrue>

**Comment by stscijgbot-jp** [comment]
_Comment by [Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=715237#comment-715237):_

[David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) 

I fixed cube_build so that when mrs_imatch is called there is not an error The mrs_imatch step uses the 'single' type IFU cubes. As updates have been made to normal IFU cube building the single type got forgotten about. I do not know of a cases where these single type cubes are used in the pipeline. 
I have added a deprecation warning to mrs_imatch. I can set the step to skip never allow it to be run. 
But I am not sure that is what I should do.

This became an issue when a user used the .run method rather than .call for calwebb_spec3 - so mrs_imatch was called. 
Should I always skip mrs_imatch or just use the deprecation warning ?

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=715241#comment-715241):_

[Jane Morrison](https://jira.stsci.edu/secure/ViewProfile.jspa?name=morrison) Let's leave it as a deprecation warning for now.  I'd rather we look back at this when possible and remove the step than having a step in the pipeline that's impossible to run.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=715247#comment-715247):_

I think it's probably still a good idea to default to skip = True in the spec for the step, so that it doesn't run by default when a user calls it via .run.  They will still be able to run it if they manually set skip = False.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=715321#comment-715321):_

Agreed.

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=716452#comment-716452):_

Fixed by #8728

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3649?focusedCommentId=719037#comment-719037):_

Tested and performing as expected: step no longer crashes, but can be made to run if manually setting skip=False.  If so, it prints a warning about deprecation.  Closing.
