### ISSUE TITLE
calwebb_tso3 failures for SOSS data in FULL subarray

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8581]
_Issue [JP-3665](https://jira.stsci.edu/browse/JP-3665) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

Operations recently had some more NIRISS SOSS full-frame exposures cause errors in processing, but this time the failure is in the TSO3 pipeline, as opposed to Spec2. See <https://jira.stsci.edu/browse/JSDP-2890> The problem is no doubt related to [JP-3662](https://jira.stsci.edu/browse/JP-3662) because the data are again full-frame readouts, but this time they were at least taken in TSO mode (TSOVISIT=True). But because the Spec2 pipeline is not creating extracted 1-D spectra, the inputs to the Tso3 pipeline again don't contain a "spec" attribute (it's still an image, instead of a spectrum).The logs have the following info:
```java
jw02113002001_02101_00001-seg001_nis_calints.fits {'META.EXPOSURE.READPATT [READPATT]': 'NISRAPID', 'META.EXPOSURE.TYPE [EXP_TYPE]': 'NIS_SOSS', 'META.INSTRUMENT.DETECTOR [DETECTOR]': 'NIS', 'META.INSTRUMENT.FILTER [FILTER]': 'CLEAR', 'META.INSTRUMENT.LAMP_STATE [LAMP]': 'NONE', 'META.INSTRUMENT.NAME [INSTRUME]': 'NIRISS', 'META.INSTRUMENT.PUPIL [PUPIL]': 'GR700XD', 'META.OBSERVATION.DATE [DATE-OBS]': '2023-09-28', 'META.OBSERVATION.TIME [TIME-OBS]': '17:17:07.854', 'META.SUBARRAY.NAME [SUBARRAY]': 'FULL', 'META.VISIT.CROWDED_FIELD [CROWDFLD]': 'F', 'META.VISIT.TSOVISIT [TSOVISIT]': 'T', 'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_FIXED', 2024-06-19 11:45:23,281 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d running with args (<CubeModel(10, 2048, 2048) from jw02113002001_02101_00001-seg001_nis_calints.fits>,). 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - INFO - Input is a NIRISS SOSS observation, the specialized SOSS extraction (ATOCA) will be used. 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - INFO - Exposure is through the GR700XD + CLEAR (science). 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - ERROR - The SOSS extraction is implemented for the SUBSTRIP256and SUBSTRIP96 subarrays only. Subarray is currently FULL. 2024-06-19 11:45:23,290 - stpipe.Tso3Pipeline.extract_1d - ERROR - Extract1dStep will be skipped. 2024-06-19 11:45:23,291 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d done 2024-06-19 11:45:23,438 - stpipe.Tso3Pipeline.photom - INFO - Step photom running with args (<CubeModel(10, 2048, 2048) from jw02113002001_02101_00001-seg001_nis_calints.fits>,). 2024-06-19 11:45:23,475 - stpipe.Tso3Pipeline.photom - INFO - Using photom reference file: /ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/niriss/jwst_niriss_photom_0045.fits 2024-06-19 11:45:23,475 - stpipe.Tso3Pipeline.photom - INFO - Using area reference file: N/A 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - Using instrument: NIRISS 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - detector: NIS 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - exp_type: NIS_SOSS 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - filter: CLEAR 2024-06-19 11:45:24,223 - stpipe.Tso3Pipeline.photom - INFO - pupil: GR700XD 2024-06-19 11:45:24,247 - stpipe.Tso3Pipeline.photom - ERROR - Unexpected data model type CubeModel for NIRISS. Photom will be skipped. 2024-06-19 11:45:25,161 - CRDS - DEBUG - Using reference file selection rules 'jwst_1241.pmap' defined by cache. 2024-06-19 11:45:25,161 - stpipe.Tso3Pipeline.photom - INFO - Step photom done Traceback (most recent call last): File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stdatamodels/properties.py", line 350, in __getattr__ val = self._instance[attr] ~~~~~~~~~~~~~~^^^^^^ KeyError: 'spec' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/cli/strun.py", line 24, in main Step.from_cmdline(sys.argv[1:]) File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 191, in from_cmdline return cmdline.step_from_cmdline(args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/cmdline.py", line 394, in step_from_cmdline step.run(*positional) File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stpipe/step.py", line 509, in run step_result = self.process(*args) ^^^^^^^^^^^^^^^^^^^ File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/jwst/pipeline/calwebb_tso3.py", line 182, in process x1d_result.spec.extend(result.spec) ^^^^^^^^^^^ File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.14.0.20240401-py3.11/lib/python3.11/site-packages/stdatamodels/properties.py", line 353, in __getattr__ raise AttributeError("No attribute '{0}'".format(attr)) AttributeError: No attribute 'spec'```
 
So in this case the photom step is at least catching the problem and skipping, but then when it returns to the Tso3 pipeline, it barfs because the returned datamodel is not the right type or contains the right contents.
 
In terms of how to handle it, it's possible this should be caught already in ASN rules, so that we don't even build a tso3 asn file for these cases (and hence avoid the processing error), but the crfints files could at least perhaps be of some use. It will of course still cause some confusion somewhere, because the x1d/x1dints files don't actually contain 1-D spectra (I think right now they're getting filled with 2-D or 3-D image data - this should be checked).

**Comment by stscijgbot-jp** [comment]
_Comment by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter) on [JIRA](https://jira.stsci.edu/browse/JP-3665?focusedCommentId=705415#comment-705415):_

Fixed by #8583

**Comment by stscijgbot-jp** [comment]
_Comment by [Joseph Filippazzo](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jfilippazzo) on [JIRA](https://jira.stsci.edu/browse/JP-3665?focusedCommentId=710269#comment-710269):_

Tested this using the TSO dataset 'jw02113004001_02101_00001-seg001_nis_uncal.fits' and ASN file `jw02113-o004_20240715t130253_tso-spec2_00001_asn.json`.

DETECTOR1 pipeline ran as expected without error.

SPEC2 failed gracefully as expected with the error "2024-07-24 11:20:06,027 - stpipe.Spec2Pipeline.extract_1d - ERROR - The SOSS extraction is implemented for the SUBSTRIP256and SUBSTRIP96 subarrays only. Subarray is currently FULL.".

TSO3 failed gracefully as expected with:

```

2024-07-24 11:26:48,350 - stpipe.Tso3Pipeline.extract_1d - ERROR - The SOSS extraction is implemented for the SUBSTRIP256and SUBSTRIP96 subarrays only. Subarray is currently FULL.
2024-07-24 11:26:48,350 - stpipe.Tso3Pipeline.extract_1d - ERROR - Extract1dStep will be skipped.
2024-07-24 11:26:48,350 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d done
2024-07-24 11:26:48,353 - stpipe.Tso3Pipeline - WARNING - extract_1d step could not be completed for any integrations
2024-07-24 11:26:48,353 - stpipe.Tso3Pipeline - WARNING - x1dints products will not be created.
2024-07-24 11:26:48,353 - stpipe.Tso3Pipeline - WARNING - Could not create a photometric catalog; all results are null
2024-07-24 11:26:48,354 - stpipe.Tso3Pipeline - INFO - Step Tso3Pipeline done

```

This seems good to go. Thanks!

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3665?focusedCommentId=980333#comment-980333):_

This fix appears to have been broken in 12.0.1, error report from OPS for jw02113-o004: <https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/reproman_jw02113-o004_20250910t061917_tso3_00001_1757488670.615771&fileset_name=jw02113-o004_20250910t061917_tso3_00001&dag_name=REPRO_LEVEL_3>


```
In b12.0:
2025-09-10 07:21:23,373 - stpipe.Tso3Pipeline.extract_1d - ERROR - The SOSS extraction is implemented for the SUBSTRIP256 and SUBSTRIP96 subarrays only. Subarray is currently FULL.
2025-09-10 07:21:23,374 - stpipe.Tso3Pipeline.extract_1d - ERROR - Extract1dStep will be skipped.
2025-09-10 07:21:23,412 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d done
2025-09-10 07:21:23,414 - stpipe.Tso3Pipeline - INFO - Performing white-light photometry ...
2025-09-10 07:21:23,474 - stpipe.Tso3Pipeline.white_light - INFO - Step white_light running with args (<TSOMultiSpecModel from jw02113004001_02101_00001-seg001_nis_calints.fits>,).
Traceback (most recent call last):
<crash!>

previously, in b11.3:
2025-06-19 17:26:39,144 - stpipe.Tso3Pipeline.extract_1d - INFO - Step extract_1d done
2025-06-19 17:26:39,147 - stpipe.Tso3Pipeline - WARNING - extract_1d step could not be completed for any integrations
2025-06-19 17:26:39,148 - stpipe.Tso3Pipeline - WARNING - x1dints products will not be created.
2025-06-19 17:26:39,148 - stpipe.Tso3Pipeline - WARNING - Could not create a photometric catalog; all results are null
2025-06-19 17:26:39,154 - stpipe.Tso3Pipeline - INFO - Step Tso3Pipeline done
2025-06-19 17:26:39,154 - stpipe - INFO - Results used jwst version: 1.18.0
```

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3665?focusedCommentId=981496#comment-981496):_

Fixed by #9821

Also added regression tests for NIRISS SOSS TSO full frame data, so hopefully this won't reappear.

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3665?focusedCommentId=981808#comment-981808):_

Assigning to [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) to confirm whether this is working again in ops once 12.1 is installed.

**Comment by stscijirahub** [comment]
_This issue is tracked on JIRA as [JP-3665](https://jira.stsci.edu/browse/JP-3665)._

**Comment by stscijirahub** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3665?focusedCommentId=998196#comment-998196):_

fix confirmed, see DMSOPS-1615
