### ISSUE TITLE
resample error in NIRCam processing of Image3

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8991]
_Issue [JP-3807](https://jira.stsci.edu/browse/JP-3807) was created on JIRA by [Maria Pena-Guerrero](https://jira.stsci.edu/secure/ViewProfile.jspa?name=pena):_

Help Desk ticket [INC0204970|[https://stsci.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Da5e124e3c3495610861c5763e401312e%26sysparm_record_list%3Dcaller_id.name%3E%3DKevin%2BLuhman%5Ecompany%3D%5EORwatch_listCONTAINSa89f418ddb8f620042685434ce961990%5EORcompany%3Dc3478b5edb013e0042685434ce961951%5EORu_additional_help_desksCONTAINSc3478b5edb013e0042685434ce961951%5EORcaller_id%3Da89f418ddb8f620042685434ce961990%5EORopened_by%3Da89f418ddb8f620042685434ce961990%5EORDERBYcaller_id%26sysparm_record_row%3D26%26sysparm_record_rows%3D2763%26sysparm_record_target%3Dincident%26sysparm_view%3DJWST%26sysparm_view_forced%3Dtrue]] shows a crash while processing data for PID 4866.

Input is: F182M _cal.fits images from program 4866

User used the following command:
```java
strun calwebb_image3 tw1.json --steps.tweakreg.skip=True --steps.outlier_detection.skip=True --steps.skymatch.skip=True --logcfg=../test.cfg --steps.resample.in_memory=False```
The traceback is as follows:
```java
ERROR RUNNING STEP 'Image3Pipeline':
    setting an array element with a sequence. The requested array has
    an inhomogeneous shape after 1 dimensions. The detected shape was
    (2,) + inhomogeneous part.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/stpipe/cli/strun.py", line 24, in main
    Step.from_cmdline(sys.argv[1:])
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/stpipe/step.py", line 191, in from_cmdline
    return cmdline.step_from_cmdline(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/stpipe/cmdline.py", line 395, in step_from_cmdline
    step.run(*positional)
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/jwst/stpipe/core.py", line 100, in run
    result = super().run(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/stpipe/step.py", line 524, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/jwst/pipeline/calwebb_image3.py", line 101, in process
    result = self.resample(input_models)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/stpipe/step.py", line 524, in run
    step_result = self.process(*args)
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/jwst/resample/resample_step.py", line 103, in process
    result = resamp.do_drizzle(input_models)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/jwst/resample/resample.py", line 202, in do_drizzle
    return self.resample_many_to_one(input_models)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/jwst/resample/resample.py", line 425, in resample_many_to_one
    self.resample_variance_arrays(output_model, input_models)
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/jwst/resample/resample.py", line 488, in resample_variance_arrays
    weighted_rn_var[mask] = np.nansum(
                            ^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/numpy/lib/nanfunctions.py", line 722, in nansum
    a, mask = _replace_nan(a, 0)
              ^^^^^^^^^^^^^^^^^^
  File "/Users/kll207/anaconda3/envs/jwst/lib/python3.11/site-packages/numpy/lib/nanfunctions.py", line 96, in _replace_nan
    a = np.asanyarray(a)
        ^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part. ```

**Comment by stscijgbot-jp** [comment]
_Comment by [Melanie Clarke](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mclarke) on [JIRA](https://jira.stsci.edu/browse/JP-3807?focusedCommentId=784530#comment-784530):_

Set to "on hold" for now - in initial testing, we weren't able to reproduce the error with the current pipeline.  We're looking for more information from the user.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3807?focusedCommentId=951332#comment-951332):_

User issue resolved by setting image3 processing to in_memory=False.
