### ISSUE TITLE
spec3 crash at assign_mtwcs step for moving targets affecting mir and nrs 

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#9013]
_Issue [JP-3821](https://jira.stsci.edu/browse/JP-3821) was created on JIRA by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran):_

during reprocessing with b11.1.1 ops observed the following spec3 crashes (so far) for the various instrument/modes, as noted:
|[jw01253-c1005_20241214t022934_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01253-c1005_20241214t022934_spec3_00001_1734158092.307373&fileset_name=jw01253-c1005_20241214t022934_spec3_00001&dag_name=REPRO_LEVEL_3)|NRS_IFU|
|[jw01897-c1002_20241214t003404_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01897-c1002_20241214t003404_spec3_00001_1734147713.827061&fileset_name=jw01897-c1002_20241214t003404_spec3_00001&dag_name=REPRO_LEVEL_3)|NRS_IFU|
|[jw01897-c1003_20241214t003404_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01897-c1003_20241214t003404_spec3_00001_1734147756.302529&fileset_name=jw01897-c1003_20241214t003404_spec3_00001&dag_name=REPRO_LEVEL_3)|MIR_MRS|
|[jw01273-o009_20241213t234718_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01273-o009_20241213t234718_spec3_00001_1734146020.574476&fileset_name=jw01273-o009_20241213t234718_spec3_00001&dag_name=REPRO_LEVEL_3)|MIR_LRS-FIXEDSLIT|
|[jw01273-o001_20241213t234718_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01273-o001_20241213t234718_spec3_00001_1734145932.231009&fileset_name=jw01273-o001_20241213t234718_spec3_00001&dag_name=REPRO_LEVEL_3)|MIR_LRS-FIXEDSLIT|
|[jw01273-c1000_20241213t234718_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01273-c1000_20241213t234718_spec3_00001_1734145997.816213&fileset_name=jw01273-c1000_20241213t234718_spec3_00001&dag_name=LEVEL_3)|MIR_LRS-FIXEDSLIT|
|[jw04198-c1001_20241213t195942_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw04198-c1001_20241213t195942_spec3_00001_1734131350.485040&fileset_name=jw04198-c1001_20241213t195942_spec3_00001&dag_name=REPRO_LEVEL_3)|NRS_IFU|
|[jw04198-c1003_20241213t195942_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw04198-c1003_20241213t195942_spec3_00001_1734131309.703951&fileset_name=jw04198-c1003_20241213t195942_spec3_00001&dag_name=REPRO_LEVEL_3)|NRS_IFU|
|[jw04198-c1002_20241213t195942_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw04198-c1002_20241213t195942_spec3_00001_1734131187.963080&fileset_name=jw04198-c1002_20241213t195942_spec3_00001&dag_name=LEVEL_3)|NRS_IFU|
|[jw01449-o003_20241212t224157_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01449-o003_20241212t224157_spec3_00001_1734050062.804058&fileset_name=jw01449-o003_20241212t224157_spec3_00001&dag_name=REPRO_LEVEL_3)|MIR_LRS-FIXEDSLIT|
|[jw01254-o001_20241213t050938_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01254-o001_20241213t050938_spec3_00001_1734073681.261212&fileset_name=jw01254-o001_20241213t050938_spec3_00001&dag_name=REPRO_LEVEL_3)|MIR_LRS-FIXEDSLIT|
|[jw04078-c1001_20241213t044643_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw04078-c1001_20241213t044643_spec3_00001_1734072305.717385&fileset_name=jw04078-c1001_20241213t044643_spec3_00001&dag_name=LEVEL_3)|MIR_MRS|
|[jw01444-o003_20241213t020302_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01444-o003_20241213t020302_spec3_00001_1734065981.025083&fileset_name=jw01444-o003_20241213t020302_spec3_00001&dag_name=REPRO_LEVEL_3)|NRS_MSASPEC|
|[jw04565-c1001_20241213t053559_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw04565-c1001_20241213t053559_spec3_00001_1734091091.201296&fileset_name=jw04565-c1001_20241213t053559_spec3_00001&dag_name=REPRO_LEVEL_3)|MIR_MRS|

the crashes occur at the assign_mtwcs step with error message similar to the following example
```java
{'META.EXPOSURE.NGROUPS [NGROUPS]': '88.0',
'META.EXPOSURE.READPATT [READPATT]': 'FASTR1',
'META.EXPOSURE.TYPE [EXP_TYPE]': 'MIR_LRS-FIXEDSLIT',
'META.INSTRUMENT.BAND [BAND]': 'UNDEFINED',
'META.INSTRUMENT.CHANNEL [CHANNEL]': 'UNDEFINED',
'META.INSTRUMENT.CORONAGRAPH [CORONMSK]': 'UNDEFINED',
'META.INSTRUMENT.DETECTOR [DETECTOR]': 'MIRIMAGE',
'META.INSTRUMENT.FILTER [FILTER]': 'P750L',
'META.INSTRUMENT.LAMP_STATE [LAMP]': 'OFF',
'META.INSTRUMENT.NAME [INSTRUME]': 'MIRI',
'META.OBSERVATION.DATE [DATE-OBS]': '2023-03-12',
'META.OBSERVATION.TIME [TIME-OBS]': '12:22:15.458',
'META.SUBARRAY.NAME [SUBARRAY]': 'FULL',
'META.VISIT.TSOVISIT [TSOVISIT]': 'F',
'META.VISIT.TYPE [VISITYPE]': 'PRIME_TARGETED_MOVING',
'REFTYPE': 'UNDEFINED'}
2024-12-14 03:20:51,767 - CRDS - DEBUG - Reference type 'apcorr' defined as 'jwst_miri_apcorr_0013.fits'
2024-12-14 03:20:51,767 - CRDS - DEBUG - Reference type 'extract1d' defined as 'jwst_miri_extract1d_0006.json'
2024-12-14 03:20:51,768 - CRDS - DEBUG - Reference type 'photom' defined as 'jwst_miri_photom_0216.fits'
2024-12-14 03:20:51,777 - stpipe.Spec3Pipeline - INFO - Prefetch for APCORR reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/miri/jwst_miri_apcorr_0013.fits'.
2024-12-14 03:20:51,782 - stpipe.Spec3Pipeline - INFO - Prefetch for AREA reference file is 'N/A'.
2024-12-14 03:20:51,783 - stpipe.Spec3Pipeline - INFO - Prefetch for CUBEPAR reference file is 'N/A'.
2024-12-14 03:20:51,783 - stpipe.Spec3Pipeline - INFO - Prefetch for EXTRACT1D reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/miri/jwst_miri_extract1d_0006.json'.
2024-12-14 03:20:51,791 - stpipe.Spec3Pipeline - INFO - Prefetch for MRSPTCORR reference file is 'N/A'.
2024-12-14 03:20:51,792 - stpipe.Spec3Pipeline - INFO - Prefetch for PASTASOSS reference file is 'N/A'.
2024-12-14 03:20:51,792 - stpipe.Spec3Pipeline - INFO - Prefetch for PHOTOM reference file is '/ifs/archive/ops/jwst/ref/tmp_crds/crds/cache/references/jwst/miri/jwst_miri_photom_0216.fits'.
2024-12-14 03:20:51,799 - stpipe.Spec3Pipeline - INFO - Prefetch for SPECKERNEL reference file is 'N/A'.
2024-12-14 03:20:51,799 - stpipe.Spec3Pipeline - INFO - Prefetch for SPECPROFILE reference file is 'N/A'.
2024-12-14 03:20:51,801 - stpipe.Spec3Pipeline - INFO - Starting calwebb_spec3 ...
2024-12-14 03:20:52,748 - stpipe.Spec3Pipeline - INFO - Assigning WCS to a Moving Target exposure.
2024-12-14 03:20:52,929 - stpipe.Spec3Pipeline.assign_mtwcs - INFO - Step assign_mtwcs running with args (<ModelContainer>,).
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stdatamodels/properties.py", line 306, in __getattr__
val = self._instance[attr]
~~~~~~~~~~~~~~^^^^^^
KeyError: 'wcsinfo'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stpipe/cli/strun.py", line 24, in main
Step.from_cmdline(sys.argv[1:])
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stpipe/step.py", line 191, in from_cmdline
return cmdline.step_from_cmdline(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stpipe/cmdline.py", line 395, in step_from_cmdline
step.run(*positional)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/jwst/stpipe/core.py", line 100, in run
result = super().run(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stpipe/step.py", line 524, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/jwst/pipeline/calwebb_spec3.py", line 143, in process
self.assign_mtwcs(input_models)
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stpipe/step.py", line 524, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/jwst/assign_mtwcs/assign_mtwcs_step.py", line 43, in process
result = assign_moving_target_wcs(input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/jwst/assign_mtwcs/moving_target_wcs.py", line 40, in assign_moving_target_wcs
mt_ra[i] = model.meta.wcsinfo.mt_ra
^^^^^^^^^^^^^^^^^^
File "/dms/local/jwst/pipeline/pkgs/miniconda3/envs/jwstdp-1.16.1.20241119-py3.12/lib/python3.12/site-packages/stdatamodels/properties.py", line 309, in __getattr__
raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'wcsinfo' ```

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3821?focusedCommentId=760939#comment-760939):_

one of the observations affected (1444:3) had a problem that seemed to be similar (JP-3798), but it is unclear if all the other cases had the same root cause.

**Comment by stscijgbot-jp** [comment]
_Comment by [Tyler Pauly](https://jira.stsci.edu/secure/ViewProfile.jspa?name=tpauly) on [JIRA](https://jira.stsci.edu/browse/JP-3821?focusedCommentId=760955#comment-760955):_

It appears as though the root cause was fixed as part of this PR: #8918

The exptype of association members was being incorrectly sourced - the error seen during processing is the result of attempting to modify the wcsinfo attribute of background members of the association with filetype x1d, which has no wcsinfo. It's unclear to me why this wasn't caught earlier, and why it wasn't prioritized for inclusion in our patch. I'll review our test coverage for moving target data, ensuring we include tests of an association that includes background members. This will likely need to be added to the Known Issues page for B11.1(.1). Users encountering this issue should be able to successfully (re)process with jwst/main, or our 11.2 release which should be released at the end of this week.

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-3821?focusedCommentId=780817#comment-780817):_

also [jw01658-o002_20241223t133443_spec3_00001](https://pl9jwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw01658-o002_20241223t133443_spec3_00001_1734973475.270013&fileset_name=jw01658-o002_20241223t133443_spec3_00001&dag_name=REPRO_LEVEL_3)

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3821?focusedCommentId=930070#comment-930070):_

Since it sounds like the root cause of this problem has already been fixed, I'm going to set this ticket to RTT for when ops receives 11.2.  Documentation of this issue has been added to JDox for build 11.1.

**Comment by stscijgbot-jp** [comment]
_Comment by [John Scott](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jscott) on [JIRA](https://jira.stsci.edu/browse/JP-3821?focusedCommentId=946657#comment-946657):_

Also [jw06116-c1009_20241212t233733_spec3_00001](https://pljwdmsweb.stsci.edu/owlgui/logs/directory_view?directory_path=/ifs/archive/ops/jwst/info/owl/logs/owlmgr_jw06116-c1009_20241212t233733_spec3_00001_1740449736.493889&fileset_name=jw06116-c1009_20241212t233733_spec3_00001&dag_name=LEVEL_3)

**Comment by stscijgbot-jp** [comment]
_Comment by [Hien Tran](https://jira.stsci.edu/secure/ViewProfile.jspa?name=htran) on [JIRA](https://jira.stsci.edu/browse/JP-3821?focusedCommentId=948431#comment-948431):_

all affected data have been reprocessed with b11.2.1 2025mar05 and this issue was no longer encountered. see DMSOPS-1419, closing.
